### ISSUE TITLE
Multicontainer docker support on Beanstalk

### ISSUE THREAD

**Issue by philippeluickx** [pydanny/cookiecutter-django#1004]
It seems to me that the best of both worlds (docker and EBS) should be possible: https://aws.amazon.com/about-aws/whats-new/2015/03/aws-elastic-beanstalk-supports-multi-container-docker-environments/

I'm looking into this setup, but if anyone has any suggestions it'd be awesome to hear!

**Comment by statwonk** [comment]
@philippeluickx I'm pretty in this type of setup and a willing test user. :) Let me know how I can help. I'm happy to do research if you can think of a checklist.

**Comment by pydanny** [comment]
I'm definitely interested in this effort, but as I'm not a Docker expert, the most I can do is review pull requests.

**Comment by philippeluickx** [comment]
@pydanny Thanks for the thumbs up!
@statwonk I got a basic setup running, still interested?


I'm actually making progress with this, got a first very basic setup running.
However, there are some practical challenges. E.g. one is that with multicontainer Beanstalk, you pull docker images from repositories, you can not build and push a container yourself.
So this setup would work, but there would be quite some docs and instructions on how to get it running.

Still trying to learn how to get a full project up, once I have that running I'll fork and share what I've got!

**Comment by pydanny** [comment]
I'm excited by this! For the HTTP Server are you using Nginx or Caddy? I'm asking because websocket/asgi support would mean channels on ELB! Yeah!

**Comment by philippeluickx** [comment]
Using plain old nginx. But it's docker, so should be easy to swap?

**Comment by pydanny** [comment]
Nginx is fine with me. I know @jayfk prefers Caddy, but as long as we get this for ELB, I'm not picky. 😄

**Comment by philippeluickx** [comment]
https://github.com/philippeluickx/cookiecutter-django/tree/d/ebs

Started a new fork (and d/ebs branch) to share what I've got so far. I started out by removing a lot of functionality (e.g. Celery support) to get just to basics running. So far a simple implementation works for my project that started from a basic cookiecutter, trying to copy the changes to the core project.

I'd love to get feedback on this. Wouldn't make sense to continue adding functionality and logic if the starting point goes in the wrong direction.

By the way, if there is any better way to test, I'd love to hear about it. For now, I always do a git push for the smallest change to debug, not really best practice I fear.

Finally, I couldn't test it myself because of an issue https://github.com/pydanny/cookiecutter-django/issues/1150 .

**Comment by matt7277** [comment]
Hey @philippeluickx  thanks for the work! I also want to get this working on Elasticbeanstalk but i was approaching it from the Python EBS platform and not the multi-container docker route. I'll give your fork a try and will provide feedback if I can

**Comment by philippeluickx** [comment]
@matt7277 Sounds good!
It's really really WIP, but drop me a message when you get stuck somewhere.
I am keeping some docs as well, make sure to check that out.

**Comment by philippeluickx** [comment]
@pydanny @matt7277 Found some time and got the multicontainer setup to work. Please check out https://github.com/philippeluickx/cookiecutter-django/tree/d/ebs2 . Added a file in docs, so be sure to read that.

I would need people testing this more in depth, what's the best approach?

**Comment by browniebroke** [comment]
Stumbled upon this issue today. Just a heads up that [the EBS support has been removed](https://github.com/pydanny/cookiecutter-django/commit/793a46ba45229cf26c67d760c4b1df767a9e0f12) recently.

**Comment by philippeluickx** [comment]
Yes, I'll be putting up a fork for this and rebase regularly. Thanks for the heads up!
