### ISSUE TITLE
Cant connect to site on production (times out)

### ISSUE THREAD

**Issue by hgonzalez94** [pydanny/cookiecutter-django#1005]
```
use_whitenoise [y]: n
use_celery [n]: y
use_mailhog [n]: n
use_sentry_for_error_reporting [y]: y
use_opbeat [n]: y
use_pycharm [n]: y
windows [n]: n
use_python3 [y]: y
use_docker [y]: y
use_heroku [y]: n
use_compressor [n]: y
Select postgresql_version:
1 - 9.5
2 - 9.4
3 - 9.3
4 - 9.2
Choose from 1, 2, 3, 4 [1]: 1
Select js_task_runner:
1 - Gulp
2 - Grunt
3 - Webpack
4 - None
Choose from 1, 2, 3, 4 [1]: 4
use_lets_encrypt [n]: y
Select open_source_license:
1 - MIT
2 - BSD
3 - GPLv3
4 - Apache Software License 2.0
5 - Not open source
Choose from 1, 2, 3, 4, 5 [1]: 1
```

After building my docker project with production settings, I'm unable to access my site. It times out on google chrome saying its taking too long to access. I see my attempts at accessing in my logs but I can't load the admin site or root directory. Any suggestions or anything I might have missed?

**Comment by Afrowave** [comment]
Hey Hugo,

You will find a file called env.example where you are to set up variables for the production server.
Specifically did you set up the ```DJANGO_ALLOWED_HOSTS``` so that you can have access to your server?

**Comment by hgonzalez94** [comment]
@Afrowave my DJANGO_ALLOWED_HOSTS is set to what the cookiecutter set it to, my domain name in the format of DJANGO_ALLOWED_HOSTS=.domainname

**Comment by Afrowave** [comment]
Add the IP address of the server and test it and see.

And did you connect to the server using ```eval $(docker-machine env <server_name>```?

**Comment by hgonzalez94** [comment]
Sorry, I forgot to open my ssl port on the instance. My bad, I love you guys, thank you for this beautiful cookiecutter, you guys are the best. 1luv
