### ISSUE TITLE
jinja2

### ISSUE THREAD

**Issue by silver0346** [pydanny/cookiecutter-django#1009]
Hi,

I try to use your template with some changes: I try to use my own base.html and other default templates. Since your template uses jinja2 it is not possible to use this. Jinja stops at templates like {% comment %}. Can you fix this? I try to use standard django template language?

**Comment by luzfcb** [comment]
@silver0346 Cookiecutter uses Jinja2 to render the files

If you want to keep the the Django template tags or Jinja2 tags in the generated file, you need to escape the tags so they are not processed. Put the tags between `{% raw %} {% endraw %}`

See: http://jinja.pocoo.org/docs/2.9/templates/#escaping

```
{% raw %}

       This will not be processed by cookiecutter
       {% comment %}
              FooBar
       {% endcomment %}

{% endraw %}


```
