### ISSUE TITLE
django_extensions app is imported in local settings only

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1016]
I noticed the `django_extensions` app is being imported in local configuration only; provided I want to use its [`TimeStampedModel`](https://github.com/django-extensions/django-extensions/blob/master/django_extensions/db/models.py#L14) to build my models upon, shouldn't the app be present in production configuration as well i.e installed in `common.py`?

**Comment by luzfcb** [comment]
@webyneter django-extensions is only used in development for security reasons. See: https://github.com/pydanny/cookiecutter-django/issues/417#issuecomment-158452987

said that, django-model-utils provide a very similar `TimeStampedModel` model class https://github.com/carljm/django-model-utils/blob/master/model_utils/models.py#L31-L41

and other usefull features

**Comment by webyneter** [comment]
@luzfcb, thanks for the exhaustive reply!
