### ISSUE TITLE
UserDetailView fails on mixed-case usernames

### ISSUE THREAD

**Issue by jandrewstre** [pydanny/cookiecutter-django#1020]
UserDetailView fails to find the user based on slug if the username is not stored in lowercase, which is likely to be the case given that django-allauth preserves case when storing usernames by default.

**Comment by pydanny** [comment]
I encountered something like this not too long ago. Let's see if we can write a test for it, shall we?

**Comment by browniebroke** [comment]
We couldn't reproduce in #2234 so I'm closing this.
