### ISSUE TITLE
Gulp With Docker

### ISSUE THREAD

**Issue by jamesaud** [pydanny/cookiecutter-django#1028]
With Cookiecutter Gulp doesn't currently support docker out of the box... It would be reaalllly nice to have Gulp work out of the box with docker. 

I'm sure I'm not the first person interested in this feature. If anyone is interested, with CookieCutter Django I've got Gulp running as it's own docker container with live browser reload working!

My project is standard cookiecutter. Here's the file modifications to get this to work:

dev.yml specifies gulp as it's own service: https://github.com/jamesaud/ReuseRat/blob/feature/shopify/dev.yml#L35-L47

gulpfile.js the proxy is set to the django container:
https://github.com/jamesaud/ReuseRat/blob/feature/shopify/gulpfile.js#L90

the dockerfile and build for docker-compose is here (and a little bit hacky. If anyone could help with the entrypoint.sh file, it would be nice):
https://github.com/jamesaud/ReuseRat/tree/feature/shopify/compose/gulp

Thoughts on this?

**Comment by webyneter** [comment]
@jamesaud, your repo is unavailable...

**Comment by jamesaud** [comment]
Apologies, I've removed it for security purposed on my project. I'll post it back up when i fix the security issues and tag you in this post when I do.
