### ISSUE TITLE
PyCharm + Docker for Mac

### ISSUE THREAD

**Issue by CharlesBergmeier** [pydanny/cookiecutter-django#1033]
Want to start by saying thanks for the amazing ongoing work on this project - been a fan for a while!

So, I've pulled a very recent build of `cookiecutter-django` and tried to get it to play nice with `Docker for Mac` and `PyCharm`.  Here's a few current issues:

1. The docs suggest that configuring the `Docker` build configuration in PyCharm should be possible by specifying an `API URL` of `unix:///var/run/docker.sock`, but that doesn't currently work with `Docker for Mac`.  One alternative would be to skip the advantages of `Docker for Mac` by instead configuring the setup for `docker-machine` instead, but that's less ideal.  Instead, there is a way to get `Docker for Mac` to talk to PyCharm, although it looks a bit hacky:
**FIX:**
   1. Install socat `brew install socat`
   2. Run `socat TCP-LISTEN:8099,reuseaddr,fork,bind=localhost UNIX-CONNECT:/var/run/docker.sock`
   3. Configure the PyCharm docker API URL config to point to `tcp://localhost:8099`

2. The next problem I ran into was with the `entrypoint.sh` script on the django Dockerfile.  For some reason, when you try to run the included PyCharm run configuration for django, it immediately fails, due to looking for a non-existent local build of postgres.  Digging a bit, I realized that all the environment configuration from `entrypoint.sh` is not actually being run when using the run configuration in PyCharm.  By setting those values manually in the run configuration setup, it starts to work.
**FIX:**
    1. Open up the django run configurations in PyCharm
    2. Edit the `Environment variables` section
    3. Specify the following values manually in that configuration:
        1. POSTGRES_USER=postgres
        2. DJANGO_SETTINGS_MODULE=config.settings.local
        3. PYTHONUNBUFFERED=1
        4. DATABASE_URL=postgres://{{your_project_name_here}}:@postgres:5432/{{your_project_name_here}}
        5. CELERY_BROKER_URL=redis://redis:6379/0
        6. REDIS_URL=redis://redis:6379

3. This gets you most of the way, allowing you to run the project via PyCharm.  Unfortunately, I couldn't get PyCharm's debugger to play nice with the run configurations, as it hangs indefinitely waiting for a connection.  I think it's because the debugger is opened on a random (and unpredictable) port, making it difficult to know in advance which port to expose.  Best thing I could figure out for getting debugging support working is to manually run the project via a `docker-compose` command in terminal, and setting breakpoints with `ipdb`.  It would be great to figure out how to get PyCharm's debugger supported with this project, when using `Docker for Mac`
**FIX:** UNKNOWN

I think the first two issues are partially solved by my suggestions above, though better approaches are certainly welcome.  And if the fixes documented above are the best we have, maybe they should be documented in the project?  I am at a loss for figuring out how to fix the third issue though.

Thanks!

**Comment by CharlesBergmeier** [comment]
Looks like the 3rd issue may get addressed by an upcoming change in PyCharm:
https://youtrack.jetbrains.com/issue/PY-21177

**Comment by luzfcb** [comment]
please, check new Pycharm EAP version: 

https://twitter.com/pycharm/status/831056344115470336

**Comment by CharlesBergmeier** [comment]
@luzfcb Tried out the latest EAP build: `2017.1 EAP 8 (build 171.3566.25)` (released 2/22/2017).

Confirmed that PyCharm has addressed all the major concerns previously raised:
1. Using `unix:///var/run/docker.sock` works as expected
2. Entrypoint script is now respected while executing run configs
3. Debugging works as expected - setting breakpoints in the IDE results in them being caught appropriately

Pycharm 2017.1 is set to launch in March :)

I'll close this issue -thanks!
