### ISSUE TITLE
Warning: Debugger speedups using cython not found

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1034]
Whenever I start debugging, the following warning gets fired:

`warning: Debugger speedups using cython not found. Run '"/usr/local/bin/python" "/opt/.pycharm_helpers/pydev/setup_cython.py" build_ext --inplace' to build.`

I've found the issue to be addressed in

* https://blog.jetbrains.com/pycharm/2016/02/faster-debugger-in-pycharm-5-1,
* https://youtrack.jetbrains.com/issue/PY-18913,
* http://bryan7.tistory.com/838,

yet none worked out for me.

I'm well aware that it has nothing to with cookiecutter-django itself and rather the PyCharm version I'm using (EAP 2017.1), but I still hope I'm not the only one to stumble upon that and would appreciate any help.

**Comment by pydanny** [comment]
Ping @pauleveritt

**Comment by pauleveritt** [comment]
@webyneter That message in the console is intended to provide a clickable link on some part of the text. Clicking it makes PyCharm go off and do everything it needs to do, for that version of Python.

The backstory: we ship the Cython binaries for Windows, but not for macOS nor Linux.

**Comment by webyneter** [comment]
@pauleveritt, the problem was that whenever I click the message text, PyCharm burst with a "Compile Cython Extension Error: ... No such file or directory".

**Comment by pauleveritt** [comment]
Possibly this is the issue? https://youtrack.jetbrains.com/issue/PY-20367 <https://youtrack.jetbrains.com/issue/PY-20367>

Meaning, do you have the python3-dev apt package installed?

—Paul

**Comment by webyneter** [comment]
@pauleveritt, yep, just checked it out: `python3-dev is already the newest version (3.5.1-4).`

My system info is `Linux webyneter-pc 4.8.0-37-generic #39-Ubuntu SMP Thu Jan 26 02:27:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by pauleveritt** [comment]
@webyneter Is this something new for 2017.1 EAP? Have you used PyCharm in the past, and with the debugger speedups? (My guess is no.)

**Comment by webyneter** [comment]
@pauleveritt, no I didn't (in fact I moved from Windows to Linux so to enable PyCharm's Linux- and Mac-only docker-compose support :)

**Comment by pauleveritt** [comment]
We could hijack that ticket and add your info to it, but that doesn’t really fit with the ticket.

I can make a new ticket for you, but I suspect Liza will want to have a dialog with you about it. Do you mind making a YouTrack account there and creating the ticket? Once you do, send me the URL and I’ll give her a nudge in Slack.

**Comment by webyneter** [comment]
@pauleveritt, yes, I will with great pleasure. Thank you for immediate assistance!

**Comment by webyneter** [comment]
@pauleveritt, https://youtrack.jetbrains.com/issue/PY-22681

**Comment by pauleveritt** [comment]
Thanks, that was fast, good job. I’ll comment on that ticket. I suggest closing this one in the cookiecutter repo.

—Paul

**Comment by pauleveritt** [comment]
Just to be clear, are you getting this when working on a Docker-based interpreter?

—Paul

**Comment by webyneter** [comment]
@pauleveritt, yes. 

`docker version`:

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

`docker-compose version`:
```
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

`docker-machine version`:
```
docker-machine version 0.8.2, build e18a919
```

**Comment by pauleveritt** [comment]
Can you add that to the ticket info?

—Paul

**Comment by webyneter** [comment]
@pauleveritt, yes, on my way.

**Comment by nicholishen** [comment]
I fixed this issue on windows by closing pycharm and then running it as administrator and then clicking the link.

**Comment by robevans** [comment]
I tried running as administrator and clicking the link, but I got an error window pop up:

Compile Cython Extensions Error
Non-zero exit code (1):
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2

**Comment by arcanefoam** [comment]
Running the command form the terminal (cmd in windows) gives a bit more insight about the error (at least in my case):

```
...
...\python_env\include\pyconfig.h(222): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
```
Based on [this](https://stackoverflow.com/a/42624713/3837873) answer, adding the windows 8.1 / 10 SDK fixed the problem.
