### ISSUE TITLE
Bug:  config/settings/common.py - READ_DOT_ENV_FILE

### ISSUE THREAD

**Issue by kaaheap** [pydanny/cookiecutter-django#1039]
The line:

`READ_DOT_ENV_FILE = env('DJANGO_READ_DOT_ENV_FILE', default=False)`

should be changed to:

`READ_DOT_ENV_FILE = env.bool('DJANGO_READ_DOT_ENV_FILE', default=False)`

**Comment by luzfcb** [comment]
@kaaheap Thanks for the report. 
Fixed in https://github.com/pydanny/cookiecutter-django/commit/a0efe839017483cc55ffaa03413289f491abf1e2
