### ISSUE TITLE
Bootstrap CDN source incomplete/wrong?

### ISSUE THREAD

**Issue by kaaheap** [pydanny/cookiecutter-django#1046]
When trying to use Bootstrap 4 text-right or float-right style classes, they are not getting applied to the element.  In the browser debugger, these alignment directives were not applied to the element.

I downloaded the Bootstrap min file used in cookiecutter-django (https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css).  When I opened the file and searched for text-right and float-right, they do not exist.

**Comment by kaaheap** [comment]
I just checked the bootstrap CDN.   Version 4.0.0-alpha.4 does not have the class styles, the current version 4.0.0-alpha.6 does.

**Comment by polinom** [comment]
Yeah, we run in to the same problem recently. Tried to change version of the bootstrap to alpha 6 and it broke.

**Comment by pydanny** [comment]
Apologies, we're behind with integration with the latest bootstrap. We're open to pull requests to fix this issue.

**Comment by pydanny** [comment]
I just bumped the resources to Bootstrap 4.0.0-alpha.6. I'll work on this daily to stamp out issues. If someone wants to submit a PR that completes all the work, that would be appreciated! 😄
