### ISSUE TITLE
Add Google Cloud Storage Option in addition to current AWS S3 options

### ISSUE THREAD

**Issue by ndanielsen** [pydanny/cookiecutter-django#1053]
I'm a big fan of this cookie cutter and find myself using it frequently for green field projects. 

Wondering if anyone would be interested in a pull-request to add Google compute cloud storage support for static and media files?

While AWS S3 is widely used, I find myself using the google ecosystem a bit more with the dockerized django cookie cutter.

One note is that these production dependencies would need to be updated boto==2.46.1 and django-storages==1.5.2

If this is a desirable addition, I can put together the PR and update the documentation etc.

**Comment by burhan** [comment]
I don't see how this could hurt. If you put together a PR, I can have a look at it.

**Comment by sfdye** [comment]
I believe so, PR welcome

**Comment by burhan** [comment]
We always welcome PR that offer additional options. I'll keep an eye out for the PR.

**Comment by browniebroke** [comment]
An article explaining what changes are required:
https://ahhda.github.io/cloud/gce/django/2019/03/12/using-django-cookiecutter-cloud-storage.html

**Comment by ahhda** [comment]
Started a PR for this at #2012
