### ISSUE TITLE
Create a non root user for running nginx

### ISSUE THREAD

**Issue by D3f0** [pydanny/cookiecutter-django#1056]
Although Docker is a isolated environment it's a good practice to avoid being root when it's not necessary.
It would be nice to add a `useradd` command and a `USER` directive in the Django dockerfile.

**Comment by jayfk** [comment]
Django: https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/django/Dockerfile#L12-L13
Nginx: https://github.com/nginxinc/docker-nginx/issues/27
