### ISSUE TITLE
Users app provided in the app cannot migrate

### ISSUE THREAD

**Issue by Rajesh-Yogeshwar** [pydanny/cookiecutter-django#1057]
I am using this current repo with docker for my Django project. The build runs fine but when I issue **docker-compose up**, the migration fails with following stacktrace

>  Traceback (most recent call last):
>   File "manage.py", line 23, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
>     output = self.handle(*args, **options)
>   File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 86, in handle
>     executor.loader.check_consistent_history(connection)
>   File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 292, in check_consistent_history
>     connection.alias,
> django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency users.0001_initial on database 'default'.

I am not understanding what is going wrong with it. Is there any other step involved in getting the application up and ready?

**Comment by Rajesh-Yogeshwar** [comment]
It was my mistake that to report this as an issue. But given that it was my first time trying this repository with docker there were lot many things I was not able to figure out. One among them was "what was happening with my db?" when I was removing containers and images. I found it hard way that despite deleting the images the DB persisted. It was my inexperience that led to this stupidity.

As far as issue, because of the above mentioned thing, I tried the whole setup as described on the landing page of the repo yesterday, so a DB was created yesterday and had successful migrations. I decided to remove all images and containers to retry everything. Now in this case the DB persisted and when migrations were being applied the above migration exception popped up.

Probably, for some one who is just trying to give cookiecutter django with docker a go, this might be helpful.

**Comment by jayfk** [comment]
> Probably, for some one who is just trying to give cookiecutter django with docker a go, this might be helpful.

It is, thanks! 

I'm currently working on a full doc rewrite. If you want to help out, take a look here: https://github.com/pydanny/cookiecutter-django/pull/1051

Your input is probably something for the FAQ/Troubeshooting section.

**Comment by Rajesh-Yogeshwar** [comment]
@jayfk I will. Sure.
