### ISSUE TITLE
Database Disconnecting when using dev.yml compose file?

### ISSUE THREAD

**Issue by Jaredn** [pydanny/cookiecutter-django#1076]
I apologize if this isn't the best way to ask a question, but I've been scouring the internet trying to find a solution.  I know you guys are Django superstars, so I'm hoping you've seen this before.

I've set up coockiecutter-django as best I can, using both the example Postgres Image as a backend and Mysql as a backend.  BOTH got the same error when using their respective docker images (postgres:latest and mysql:latest).

The basics are:
I run docker-compose -f dev.yml up
Mysql / Postgres container comes up, says ready to accept connections
Script in Django entrypoint.sh runs and verifies the DB is up
Django container continues and runs start-dev.yml
start-dev.yml runs a migration (and succeeds - all migrations pass)
start-dev.yml starts django with manage.py runserver_plus

At this point I see:
django_1  | Django version 1.9.8, using settings 'nomad.settings.test'
django_1  | Development server is running at http://0.0.0.0:8000/
django_1  | Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
django_1  | Quit the server with CONTROL-C.
django_1  |  * Debugger is active!
django_1  |  * Debugger pin code: xxx-xxx-xxx
django_1  |  * Debugger is active!
django_1  |  * Debugger pin code: xxx-xxx-xxx

SWEET!  So we're good to go.  Now I go to a browser and try http://127.0.0.1:8000 and on the browser I see "Bad Request (400)".
In Docker-Compose logs I see this:

django_1  | 172.20.0.1 - - [14/Mar/2017 00:21:39] "GET / HTTP/1.1" 400 -
mysql_1   | 2017-03-14T00:21:39.016733Z 9 [Note] Aborted connection 9 to db: 'nomad' user: 'nomad' host: '172.20.0.3' (Got an error reading communication packets)
nomad_django_1 exited with code 247

And that's the end of it!  I've seen tons of posts related to wait_times and packet sizes and all sorts of other 'try this' magic.  I'm hoping, though, that you guys have seen this before and know how to resolve it.

I'm running this whole thing on a mac, with docker version:
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true

The Postgres version does essentially the same thing, crashes with a Bad Request (400) when I go to the browser.  This leads me to believe that it's actually someone on the Django side of things, and not necessarily a database issue, but I'm having trouble getting any sort of meaningful logs of what the issue could be.  Thoughts?

**Comment by Jaredn** [comment]
Ok so I apologize for this long post, but by the powers that be I managed to figure this out.  I'm still not 100% sure what was causing this, but I noticed in the writeup here that I was hitting the 'test' settings file, and I was expecting to hit the 'local' settings file.  Once I updated my environment variable to hit local I was able to keep the connection open consistently.

**Comment by pydanny** [comment]
Can this issue be closed then?

**Comment by Jaredn** [comment]
Yeah =)  Thanks
