### ISSUE TITLE
[bug] Environment variables from entrypoint.sh ain't exported

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1085]
Environment variables from `./compose/django/entrypoint.sh` ain't exported.

To reproduce, run
```bash
docker-compose -f dev.yml build
docker-compose -f dev.yml up -d
docker-compose -f dev.yml exec django env 
```
The last command's output contains no `REDIS_URL`, `DATABASE_URL`, or `CELERY_BROKER_URL` variables declared in [the entrypoint](https://github.com/pydanny/cookiecutter-django/blob/f3ea2570ab6cfc981dca1b6a8f49852c91cbe2d7/%7B%7Bcookiecutter.project_slug%7D%7D/compose/django/entrypoint.sh).

**Comment by webyneter** [comment]
It's weird, but now I've noticed they are indeed being exported... Have no idea what it was all about, but I guess the issue can be closed.

**Comment by underchemist** [comment]
I'm not seeing this behavior, I pinged you on another thread but I see different behavior when using `docker-compose -f local.yml run` vs `docker-compose -f local.yml exec`
