### ISSUE TITLE
PyCharm integration.

### ISSUE THREAD

**Issue by thisfieldmustbefilled** [pydanny/cookiecutter-django#1093]
Hi! Thanks for authors and contributors for nice work.

I am using PyCharm IDE and having troubles with some stuff:
1) When I am starting project out of the box (with PyCharm support), I can work directly with manage.py script in terminal. But when it comes to Tools>Run manage.py Task in PyCharm, I get this:
`Requested setting LOGGING_CONFIG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.`
Of course, I have my .env file and I also have DJANGO_SETTINGS_MODULE=config.settings.production in it.
Changing `READ_DOT_ENV_FILE = env.bool('DJANGO_READ_DOT_ENV_FILE', default=False)` to default=True in base.py settings gives nothing. So django-environ does not seem to work.
2) I have much of Docker-specific tasks inside my .idea project, while I asked for no Docker support at all when setting up my cookiecutter. Meanwhile, there is even no task for simple running the standard debug server with runserver. And I also had to add Django support for project manually in IDE. I have no idea if this is bug or feature.

I really like that clear and solid structure of this cookiecutter, but I am now finding this difficult to understand how to start working right way.
Could you please explain that moments or add more transparent documentation on them?

**Comment by luzfcb** [comment]
@thisfieldmustbefilled inside the generated project, 
on `/docs/pycharm/configuration.rst`, did you follow the instructions? ( you can also see the rendered version here: [configuration.rst](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/docs/pycharm/configuration.rst))


Additionally, please, go to `File -> Settings -> Languages & Frameworks -> Django`,  and capture and send a printscreen.

by reference, the support for pycharm was included in in https://github.com/pydanny/cookiecutter-django/pull/507


about the documentation: There is an initial work of restructuring the documentation https://github.com/pydanny/cookiecutter-django/pull/1051 .

any improvement in documentation is welcome.

**Comment by thisfieldmustbefilled** [comment]
@luzfcb thanks for your answer.
Poor me! I just kept "Settings" option out of sight in Django tab, what a shame. Now fetching manage.py command works just fine. https://i.imgur.com/uCEDQn0.png .
And I seem to got clear about envvars. So the idea seems to be I should set the only READ_DOT_ENV_FILE=True in environment not in file and all other goes inside .env file.
Docker run configurations in general do not disturb, even not needed, but it definitely should be a configuration for native runserver, I believe, even if this is really easy to do yourself.

_Keep that project goin!_
