### ISSUE TITLE
Switch to current runtime version in runtime.txt

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1094]
On the one hand, the `django` image is created `FROM python:3.5`, resolving to `3.5.3` [as of now](https://hub.docker.com/_/python/). On the other hand, we use `python-3.5.1` in `./runtime.txt` -- there seems to be a mismatch.

Provided my suggestion is valid, I can to provide a PR upgrading `./runtime.txt` to  `python-3.5.3`.

**Comment by pydanny** [comment]
Yes please.

**Comment by webyneter** [comment]
@pydanny, [done](https://github.com/pydanny/cookiecutter-django/pull/1112).
