### ISSUE TITLE
[question] Wasn't the 'Verified bug on Python 3.5.1' mentioned in base.txt fixed already?

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1095]
In the very beginning of `./requirements/base.txt`, a `# Verified bug on Python 3.5.1` comment is left. Firstly, the status of [the issue](https://bitbucket.org/pypa/wheel/issues/146/wheel-building-fails-on-cpython-350b3) is officially resolved. Secondly, even if it was closed by a mistake, the latest comment suggests a workaround:
```
Sorin Sbarnea
I was able to bypass this error by adding pip>8.1.0 in addition to wheel>0.25.0.
```
Shouldn't we try this out and see if it works?

**Comment by pydanny** [comment]
Try it and if it works, submit a pull request.
