### ISSUE TITLE
Provide option to use MySQL instead of PostgreSQL

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#111]
While I really prefer PostgreSQL, a lot of people use MySQL. With cookiecutter, we could pass in a new cookiecutter.json prompt:

{
"Database Engine (PostgreSQL or MySQL)": "PostgreSQL"
}

Then, in the settings template, we could use this variable for a Jinja2 conditional which would either set things up for PostgreSQL or MySQL.

**Comment by ad-m** [comment]
Asking about database_url mean storing password in repo (mostly). It is important to add property requirements too.

**Comment by ad-m** [comment]
[ ] providing mysql require requirements.txt update

**Comment by pydanny** [comment]
Upon reflection this is an option I think cookiecutter-django shouldn't support. If someone wants to create a fork that mirrors cookiecutter-django except for the use of MySQL, we'll link to it from the top README.rst file.

**Comment by dmarcelino** [comment]
Hi @pydanny, I've been reading about cookiecutter-django and it looks like a great way to make Django production ready but my current hosting tier only allows MySQL. After stumbling on this issue I'm wondering is Postgres a hard requirement for cookiecutter-django, as in it won't work without it, or does it mean that cookiecutter-django's DB related features won't work? Thanks

**Comment by ad-m** [comment]
@dmarcelino , there is only requirements and ```DATABASE_URL``` changes. I start project with cookiecutter-django and replace all postgresql-related requirements to mysql.

**Comment by dmarcelino** [comment]
I see, thanks @ad-m!

**Comment by rwillmer** [comment]
Hi @pydanny I'm about to create a fork of the foundation fork with mysql support; do you want to reconsider your choice not to provide this inside cookiecutter itself? having more forks than we need just to provide a deployment choice seems overkill to me.

p.s. thanks for the cookiecutter project, it's really useful

**Comment by luzfcb** [comment]
@rwillmer After so many years that this issue was opened, i think that the main reason not to add MySQL and any other database, at least to me, is because we do not want to add more unpaid workload to maintain this project.

**Comment by ad-m** [comment]
@rwillmer , tell me about fork with MySQL support. I would like use them.

**Comment by pydanny** [comment]
@rwillmer, much as MySQL support would be awesome, @luzfcb is correct in that it adds too much to our support load. 

As always, if you can convince your organization to come into an agreement with us to provide ongoing paid support in Cookiecutter Django for MySQL (or Foundation), then we're willing to add it in.

**Comment by rwillmer** [comment]
I totally understand, @pydanny. I'll just do it for myself, and make the fork available if anyone wants it. Thanks again for Cookiecutter Django, it's terrific.

**Comment by RohitShende** [comment]
> I totally understand, @pydanny. I'll just do it for myself, and make the fork available if anyone wants it. Thanks again for Cookiecutter Django, it's terrific.

Have you created the fork with mysql support ? Please provide the link

**Comment by davydany** [comment]
@rwillmer Could you provide the link?

**Comment by browniebroke** [comment]
A link to a MySQL fork has been added to the readme in #3544
