### ISSUE TITLE
Why use  ./compose/django/entrypoint.sh for postgres-related set ups? 

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1114]
As of now, `./compose/django/entrypoint.sh` contains both `django` and `postgres` services-related code  (specifically, `REDIS_URL` with `CELERY_BROKER_URL` and the rest, respectively).

From `postgres:9.6` [docker-entrypoint.sh](https://github.com/docker-library/postgres/blob/3d4e5e9f64124b72aa80f80e2635aff0545988c6/9.6/docker-entrypoint.sh#L126), it's clear that a custom `entrypoint.sh` can be placed in `/docker-entrypoint-initdb.d/` to be called later on.

I wonder, why don't we move `postgres`-related code from `./compose/django/entrypoint.sh` to `./compose/postgres/entrypoint.sh` and modify the respecitve Dockerfiles accordingly? 

For instance, `POSTGRES_USER`, `POSTGRES_PASSWORD`, and `POSTGRES_DB` can go in, say, `dev.env` file (I've elaborated on that [earlier before](https://github.com/pydanny/cookiecutter-django/pull/1087)) with reasonable defaults (e.g. `{{ cookiecutter.project_slug }}`), exported to `postgres` environment in `dev.yml` via `env_file` directive, and utilized from `./compose/postgres/entrypoint.sh`.

**Comment by TidyData** [comment]
@webyneter, my review of the entrypoint.sh is that it forces the django container to wait for the postgres database to be available.  With docker compose, the service sometimes takes a little while to startup and the django container may error out believing the server to be unavailable, when it just needed a little more coffee and time to start up.
