### ISSUE TITLE
CELERY_BROKER_URL naming mismatch

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1116]
As of now, we `export CELERY_BROKER_URL` in `./compose/django/entrypoint.sh`, yet in `./config/settings/base.py` we utilize the unprefixed `BROKER_URL`.

Is this a mismatch?

Moreover, it's clear from [Celery migration docs](http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#lowercase-setting-names) that prefixing celery settings with `CELERY_` is recommended since 4.0, so I guess we should upgrade our settings, also renaming `BROKER_URL` to `CELERY_BROKER_URL`. I can provide a PR.

**Comment by webyneter** [comment]
I noticed `BROKER_URL` is populated from `CELERY_BROKER_URL` in Celery [Dockerfile](https://github.com/docker-library/celery/blob/96de4372507fc4eb147f43b8c4f207da3d95bcd1/4.0/Dockerfile) to be further written to `celeryconfig.py`.

**Comment by pydanny** [comment]
It's probably a mismatch. Submit the PR!

**Comment by webyneter** [comment]
@pydanny, on my way.
