### ISSUE TITLE
Incomplete auth system urls

### ISSUE THREAD

**Issue by chrickso** [pydanny/cookiecutter-django#1123]
in the base.html template, there is this code:

```
{% if request.user.is_authenticated %}
  <li class="nav-item">
  <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
  </li>
  <li class="nav-item">
  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
  </li>
{% else %}
  <li class="nav-item">
  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
  </li>
  <li class="nav-item">
  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
  </li>
{% endif %}
```
but 'account_signup', 'account_login', and 'account_logout' are not named url's defined in any urls.py in the project. is this intentional and the user is expected to provide these routes/functions themselves? seems like there should at least be placeholders for them.

**Comment by webyneter** [comment]
@chrickso , ain't those are provided by `django-allaith`?

**Comment by webyneter** [comment]
@chrickso , see `allauth/account/urls.py`

**Comment by chrickso** [comment]
@webyneter thanks.

**Comment by pydanny** [comment]
Excellent question @chrickso. Added a383fa23788e976a6d9f30a2425cb33394042ce6 to clarify things.

Thanks @webyneter for the answer. 😄

**Comment by webyneter** [comment]
@pydanny, always welcome :)
