### ISSUE TITLE
Crispy forms are confusing, difficult to customize, and there is no direction as to were the form code resides.

### ISSUE THREAD

**Issue by chrickso** [pydanny/cookiecutter-django#1124]
Assume I want my login/signup form to function/look different in any way from the default, where do I even go to see how the forms are being generated? The template just gets passed a form var and I put {{ form|crispy }} in the template and everything gets auto-generated. This is great if i'm 100% happy with it's look/function but what if i don't want the pop-up bubbles that say 'Please fill in this field.'? allauth docs don't say. crispy form docs don't say. cookiecutter-django don't say. any direction on where to go to customize the forms would be nice.

**Comment by webyneter** [comment]
@chrickso , take a look at the projects `templates/bootstrap4` dir: there you can find `Layout` class derivatives' templates (`layout` subdir), fields templates (`fields` subdir), and so on and so forth.

**Comment by webyneter** [comment]
@chrickso , I do agree we somewhat miss on `crispy-forms` integration docs, and it took me quite some time to grasp the overall concept.

**Comment by luzfcb** [comment]
Good links about crispy-forms: 
http://www.merixstudio.com/blog/django-crispy-forms-what-are-they-about/

https://ana-balica.github.io/2014/11/04/the-tale-of-dry-with-django-crispy-forms/
https://ana-balica.github.io/2015/03/18/the-tale-of-dry-with-django-crispy-forms-part-2/

**Comment by pydanny** [comment]
> Crispy forms are confusing, difficult to customize, and there is no direction as to where the form code resides

@chrickso, everyone who works on Cookiecutter Django is a volunteer. None of us get paid for it. We work on it in our free time. It is not our responsibility of Cookiecutter Django to document how django-crispy-forms works. Or for that matter, how allauth or other third-party projects work. That we do so or answer questions on any topic is a courtesy to our users. 

Therefore, please tone down the language. Or at least use emoji to lighten your requests. Again, we're unpaid volunteers.

Speaking of volunteering, as you figure out how to customize things to your liking, consider submitting pull requests to improve the documentation. Your insights as a new user are invaluable.

**Comment by chrickso** [comment]
apologies for the wrong tone coming across. i appreciate the effort put in by everyone. just needed to vent some of the frustration i was having trying to wrap my head around how some of this stuff works. thanks for all you do!

**Comment by pydanny** [comment]
@chrickso Thanks for understanding. Glad to have you around! 😄
