### ISSUE TITLE
Support Python 3 Only

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#1129]
At the start of next year (2018) Django 2.0 will be released and Python 2.7 support will be a thing of the past. I want to begin the move sooner, rather than later, to a Python 3-only project.

TODO list:

* [x] Tag the last version of this project supporting 2.7
* [x] Remove all file encodings (`# -*- coding: utf-8 -*-`)
* [x] Remove Cookiecutter logic branches that support Python 2.7 (i.e use_python3 == 'N' )
* [x] Remove any references to the `six` library
* [x] Remove all `__future__` code 

As for which Python 3 version we support, for now, we'll stick with Python 3.5. Once a few lingering issues are resolved though, I want to move us up to Python 3.6.

**Comment by jayfk** [comment]
I applaud this. Do you have any particular Python 3.6 issues in mind?

**Comment by pydanny** [comment]
Yup. On my machine, at least, Python 3.6 blows up on the current version of Cookiecutter Django. Once that stops happening, we'll go to Python 3.6 (and those lovely, lovely f-strings).

**Comment by webyneter** [comment]
I suggest that we create a separate branch, say, python-36, off of master to allow for everybody to contribute.

**Comment by webyneter** [comment]
@pydanny, it's also worth mentioning that JetBrains claims their enhanced PyCharm 2017.1 debugger to be whopping [**"forty times faster for Python 3.6 projects"**](https://blog.jetbrains.com/pycharm/2017/03/pycharm-2017-1/)!

**Comment by pydanny** [comment]
@jayfk Actually... the other reason why I don't want to go to Python 3.6 is because AWS ELB is on Python 3.4 and that's our preferred target environment right now. 😿 

@webyneter, PyCharm doesn't work so well for those of us running computers purchased in 2011. Why else do you think I never comment on PyCharm PRs? 😉

**Comment by webyneter** [comment]
@pydanny, oh, I see now; what kind of trouble that might be with hardware/... preventing PyCharm from working on 'oldish' machines?

**Comment by pydanny** [comment]
@webyneter That would be memory and harddrive space. 😜

**Comment by pydanny** [comment]
@jayfk I want to do this before we get Django 1.11 working. For no other reason that it's a LTS version and I don't want to have to support Python 2.7 for several years while people work off old commits of this project. Therefore, I'm commencing on this RIGHT NOW.  😀

**Comment by pydanny** [comment]
Tagged the last Python 2.7-compatible code: https://github.com/pydanny/cookiecutter-django/releases/tag/1.10.7

**Comment by pydanny** [comment]
We should also have a pre hook that checks the python version.

**Comment by pydanny** [comment]
Closing this as done!
