### ISSUE TITLE
Switch to Caddy on Docker

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#1132]
Caddy is so much easier to set up using let's encrypt than nginx. A perfect fit for Cookiecutter Django.

**Comment by webyneter** [comment]
@jayfk, I've heard "rumours" (yeah, sort of "some people say"-stuff) that Caddy is not yet ready for wide real-world adoptioin, or I am wrong?

**Comment by jayfk** [comment]
I've been using Caddy for a lot of smaller and mid-sized sites and I'm really happy with it. Djangopackages.org runs Caddy for ~6 months, no problems.

I wouldn't use it for very large sites, but the only reason is that nginx Plus offers some great enterprise features.

**Comment by webyneter** [comment]
@jayfk, what do you think about introducing a separate 'nginx-master' branch off of `master` for dedicated nginx support while migrating the mainline to Caddy to further cherrypick Caddy-unrelated `master` commits to `nginx-master` so keeping both options?

**Comment by webyneter** [comment]
@jayfk, even better: We could introduce these two mutually-exclusive cookiecutter-django template options, and stick with one branch.

**Comment by jayfk** [comment]
I'm -1 on that. Supporting multiple servers is a huge pain in the long run. Either Caddy or nginx.

I'm in huge favor of Caddy. It's simple, has a great config file format, supports Lets Encrypt with secure defaults out of the box and it's super easy to add basic load balancing capabilities. A prereq for #1133. 

@pydanny @audreyr @luzfcb @burhan @theskumar @webyneter  and everyone interested. Can I get a vote on that? 👍 for caddy, 👎 against it.

**Comment by webyneter** [comment]
@jayfk , I trust your experience wholeheartedly on this :smile:.

**Comment by webyneter** [comment]
@jayfk, how is this going? Can I be of any help?

**Comment by bdrhoa** [comment]
Just for reference, I don't think caddy works on AWS when using and AWS Cert and load balancer. Here's a related article. https://msaizar.com/blog/cookiecutter-django-nginx-route-53-and-elb/
