### ISSUE TITLE
argon2 issue

### ISSUE THREAD

**Issue by killown** [pydanny/cookiecutter-django#1138]
data = argon2.low_level.hash_secret(
AttributeError: module 'argon2' has no attribute 'low_level'

**Comment by webyneter** [comment]
@killown, please, describe the circumstances for reproducibility.

**Comment by killown** [comment]
.low_level.hash_secret is new from 1.16 and I was trying with Installed /usr/lib/python3.6/site-packages/argon2-0.1.10-py3.6-linux-x86_64.egg pip install argon2 will install 1.10 as default

**Comment by webyneter** [comment]
@killown, what exactly were the steps led to the issue: Did you create a `virtualenv`, or did you use Docker; are you trying to access `argon2` from standalone python script, or have you initialized the project with `cookiecutter-django`?..

**Comment by killown** [comment]
solved installing argon2_cffi

**Comment by pydanny** [comment]
@killown Should we make https://pypi.python.org/pypi/argon2_cffi a dependency then?

**Comment by webyneter** [comment]
@pydanny, we've got one (`argon2-cffi==16.3.0`) already in `base.txt`, which is strange...

**Comment by killown** [comment]
sorry, I was manually installing without base.xt

**Comment by webyneter** [comment]
@killown, well, then, I guess, the issue can be closed. :smile:

**Comment by killown** [comment]
thank you

**Comment by panu2306** [comment]
module 'argon2' has no attribute 'low_level'

**Comment by rahulreddyv** [comment]
I am using docker-compose. Yet I am getting error.
