### ISSUE TITLE
Selecting Celery yields an error when you try to run manage.py

### ISSUE THREAD

**Issue by acidjunk** [pydanny/cookiecutter-django#1139]
I think it has something to do with the recent upgrade to Celery 4:

```
(myproject) Renes-MacBook-Pro:myproject acidjunk$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/acidjunk/.virtualenvs/myproject/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/acidjunk/.virtualenvs/myproject/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/Users/acidjunk/.virtualenvs/myproject/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/acidjunk/.virtualenvs/myproject/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/acidjunk/.virtualenvs/myproject/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/acidjunk/GIT/odoo2magento/myproject/taskapp/celery.py", line 3, in <module>
    from celery import Celery
ImportError: cannot import name Celery
```

**Comment by luzfcb** [comment]
what is the output of:

```bash
pip freeze
```

**Comment by webyneter** [comment]
@acidjunk, make sure you've installed all dependencies.

**Comment by webyneter** [comment]
@luzfcb, you first :)

**Comment by jayfk** [comment]
Why is celery on 4 even? There's still a pending PR with a discussion: https://github.com/pydanny/cookiecutter-django/pull/945

**Comment by acidjunk** [comment]
alabaster==0.7.10
amqp==2.1.4
appdirs==1.4.3
appnope==0.1.0
argon2-cffi==16.3.0
awesome-slugify==1.6.5
Babel==2.4.0
backports.shutil-get-terminal-size==1.0.0
billiard==3.5.0.2
celery==4.0.2
cffi==1.10.0
coverage==4.3.4
decorator==4.0.11
Django==1.10.7
django-allauth==0.31.0
django-braces==1.11.0
django-coverage-plugin==1.5.0
django-crispy-forms==1.6.1
django-debug-toolbar==1.7
django-environ==0.4.3
django-extensions==1.7.8
django-model-utils==3.0.0
django-redis==4.7.0
django-test-plus==1.0.17
docutils==0.13.1
enum34==1.1.6
factory-boy==2.8.1
Faker==0.7.11
imagesize==0.7.1
ipaddress==1.0.18
ipdb==0.10.2
ipython==5.3.0
ipython-genutils==0.2.0
Jinja2==2.9.6
kombu==4.0.2
MarkupSafe==1.0
oauthlib==2.0.2
olefile==0.44
packaging==16.8
pathlib2==2.2.1
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.1.0
prompt-toolkit==1.0.14
psycopg2==2.7.1
ptyprocess==0.5.1
py==1.4.33
pycparser==2.17
Pygments==2.2.0
pyparsing==2.2.0
pytest==3.0.7
pytest-django==3.1.2
pytest-sugar==0.8.0
python-dateutil==2.6.0
python-openid==2.2.5
pytz==2017.2
redis==2.10.5
regex==2017.4.23
requests==2.13.0
requests-oauthlib==0.8.0
scandir==1.5
simplegeneric==0.8.1
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.5.5
sqlparse==0.2.3
termcolor==1.1.0
traitlets==4.3.2
Unidecode==0.4.20
vine==1.1.3
wcwidth==0.1.7
Werkzeug==0.12.1

**Comment by webyneter** [comment]
@acidjunk , @jayfk is right: You've got celery==4 which we don't officially support yet.

**Comment by acidjunk** [comment]
Just selected [y] when it asked do you want celery ;)

**Comment by webyneter** [comment]
@acidjunk , are you using the latest master branch of `cookiecutter-django`?

**Comment by acidjunk** [comment]
yup.

**Comment by webyneter** [comment]
@acidjunk , true, we've got Celery 4 in `./requirements/base.txt' as of now

**Comment by acidjunk** [comment]
'll Try with Celery 3.1.25.

**Comment by webyneter** [comment]
@acidjunk , if the issue re-occurs, feel free to reopen the issue.

**Comment by acidjunk** [comment]
Damn, you're fast :)
Thanks. Hate to be the messenger but I think the issue was already in there (with 3.1.24 I've the same error)

**Comment by pydanny** [comment]
@acidjunk Which version of Python are you on? FWIW, Cookiecutter Django only supports Python 3.

**Comment by acidjunk** [comment]
It was indeed related to Python2. 
With 3 it works. Tested with Celery 3.1.24 and with Celery4.

Thanks for your support and keep up the good work.
