### ISSUE TITLE
celerybeat-schedule gets nuked on Docker

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#1146]
The `celerybeat-schedule` file created by celerybeat isn't mounted and will be nuked on container rebuilds/restarts.

**Comment by geekodour** [comment]
isn't the `celerybeat-schedule` file created by celery on running of the celery process? that way it should not be a problem anyways. how can this be fixed?

**Comment by jayfk** [comment]
> isn't the celerybeat-schedule file created by celery on running of the celery process?

yep, but it's meant to be a persistent file. Celery creates it once and then uses it across restarts to determine which scheduled tasks have been run.

**Comment by robrivas** [comment]
This bug is happening to me also, I copied the log on a gist. 
https://gist.github.com/robrivas/a3c4b6b9b723ffae5619bfbc9fa2d7a9

**Comment by browniebroke** [comment]
The template now uses django-celery-beat as scheduler out of the box in #2084, which should avoid this from happening. Closing this.
