### ISSUE TITLE
Celery on RHEL7

### ISSUE THREAD

**Issue by genomics-geek** [pydanny/cookiecutter-django#1172]
I am developing a django project locally on Mac OSX using Python3.5.  When I run `celery worker -A proj.taskapp` locally it works just fine.  However, when I deployed this project to a RHEL7 server using Python3.5 and run the same command I get the error:

```python
  File "/webapps/nexus/pyvenv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ImportError: No module named 'config.settings'; 'config' is not a package
```

Seems to be specific to RHEL7 and celery.  All other django processes work just fine.  I have tried python manage.py runserver on the RHEL7 server and I don't get any errors.  I am not sure why this would be an issue with celery...

**Comment by pydanny** [comment]
Cookiecutter Django does not support RHEL7. Can you move to Ubuntu, which is supported?

**Comment by genomics-geek** [comment]
Ahh that is what I figured.  Unfortunately, I work at Children's Hospital of Philadelphia and the servers are all RHEL7.... Everything else seems to work fine, its just celery.  However, if I change `config` to `django_config` (or anything else) it works fine.  The only explanation I have is that RHEL7 Python3 handles imports differently, because it works fine on Mac OSX.

**Comment by pydanny** [comment]
For what it's worth, we would love to support RHEL. Unfortunately, none of the maintainers knows RHEL and Redhat isn't interested in sponsoring the project. 😢

**Comment by genomics-geek** [comment]
That stinks, this is such a great project!  I bought two scoops of django 1.8 and now buying 1.11 for our team :).

For what it's worth, this cookiecutter has worked perfectly on RHEL7 until I needed to start using Celery.  I am not convinced that it is the cookiecutter, but the way python3 was installed on the server...

**Comment by mjj55409** [comment]
So why not run things in Docker containers?

**Comment by genomics-geek** [comment]
Good point @mjj55409.  I was just more curious than anything why this would be handled differently on different OS.
