### ISSUE TITLE
Can't make backups with default Postgres user with Docker.

### ISSUE THREAD

**Issue by mekhami** [pydanny/cookiecutter-django#1188]
This bit of information is missing from the documentation, so I have a few questions.

1. Does the production docker set up a separate postgres user to make backups with? Or is the only user configured the default 'postgres' user?
2. If the only user is `postgres`, will there be unexpected side effects for adding another user and changing the .env to use that user instead of the default user?
3. If there is another configured user, what's that user's name? Should the process for getting that username and putting it into the .env file be documented?

I assume the user is expected to create the user and give them all the permissions on the relevant database, but since this isn't documented anywhere I wanted to bring it up as a possible missing documentation request.

**Comment by mjj55409** [comment]
The backup script uses $POSTGRES_USER and $POSTGRES_PASSWORD, both of which should be set in your .env file. The postgres container should also use the .env file; it will then create the user/permissions/database. No other users and/or permissions need to be created.

**Comment by mekhami** [comment]
Right but what I'm saying is the value in my .env file is 'postgres'. Should it be something else?

**Comment by mjj55409** [comment]
It can be whatever you want. I have set to another user. My point is that whatever you have in POSTGRES_USER will be created by the postgres container when built.

**Comment by mekhami** [comment]
Ah, I see, so this should be specified in the .env file before building your postgres image.

So, followup question, can I change that value now and rebuild it? It should maintain it's data because of the attached data volumes, yes? Or is it wiser to just manually create a new postgres user in the postgres container?

**Comment by jayfk** [comment]
The default user is set to `postgresuser`. Using `postgres` as username will cause problems if you ever need to restore your database. Using the backup and restore commands will warn you about that: https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/postgres/backup.sh#L9




> So, followup question, can I change that value now and rebuild it? It should maintain it's data because of the attached data volumes, yes? Or is it wiser to just manually create a new postgres user in the postgres container?

You'll probably run into problems with this. Upon first start, the postgres container creates the user and initialises the database based on that. 

If you want to change your username, use `ALTER USER` on the running database, shut it down, change the username in your `.env` file, rebuild and then restart.

**Comment by mekhami** [comment]
Thank you for the quick responses. One last question, how do I access the psql command line or something so that I can issue the ALTER USER command  inside the docker container? when i try to `docker-compose run --rm postgres psql` it complains, so I assume I'm being naive about that.

**Comment by jayfk** [comment]
Make sure the database is running and then run, from the top of my head:

```
docker-compose run postgres bash
export PGPASSWORD=$POSTGRES_PASSWORD
psql -h postgres --username=username
```

**Comment by mjj55409** [comment]
Note that you do not need to use psql on the container. If the container is up, you can use any postgresql client. I use either the Database connector in Pycharm or pgAdmin4 (I'm using a Mac).

**Comment by mekhami** [comment]
Thanks everyone for the fast responses. I should have enough here to solve my problem. My only recommendation is that we add some information to the documentation (especially about setting the postgres .env before building. That's something I didn't think to do automatically.)

Thanks!

**Comment by pydanny** [comment]
> My only recommendation is that we add some information to the documentation (especially about setting the postgres .env before building.

@mekhami, since you have immediate experience with this issue, would you mind submitting a pull request for this item?

**Comment by mekhami** [comment]
I'd be happy to, let me think about where to put it and i'll have something for you shortly.
