### ISSUE TITLE
storages with S3 doesn't work without DEFAULT_FILE_STORAGE setting

### ISSUE THREAD

**Issue by AuxProc** [pydanny/cookiecutter-django#1192]
Every time I deploy a new app to Heroku, I always forget how much trouble I have getting S3 to work correctly using the default settings from cookiecutter.  Unless I just missed something in the docs, production settings seem to be missing the DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage' setting.  I have not been able to get storages to work with S3 without it.  

Is there a reason this isn't in the production settings file by default?

**Comment by browniebroke** [comment]
I think this relates to #869: `DEFAULT_FILE_STORAGE` is specified if you answer 'n' to using Whitenoise.
Answering 'y' should still set `DEFAULT_FILE_STORAGE` for media files, which is not the case currently. The fix should be added [here](https://github.com/pydanny/cookiecutter-django/blob/6aced9ba73ad09edd7ce3612aff39a4b0aff3447/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/production.py#L130-L132).
