### ISSUE TITLE
how to track changes in the project boilerplate generated by cookiecutter-django

### ISSUE THREAD

**Issue by highpost** [pydanny/cookiecutter-django#1194]
What is the recommended procedure for tracking changes in the project boilerplate generated by cookiecutter-django? Let's say on Feb 1 I create a project based on cookiecutter-django and then I check back a few months later. How do I integrate the subsequent changes? So far, I've been keeping a clean version of the generated project and reviewing diffs. Is there a well-defined set of guidelines for where I can make changes for my app and what I should leave alone?

**Comment by webyneter** [comment]
@highpost, see #1047.

**Comment by highpost** [comment]
Thanks.
