### ISSUE TITLE
Upgrade docker and docker-compose deployed by Travis

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1199]
What do you think of upgrading 

* `docker` deployed during CI to the latest [`v17.05.0-ce`](https://github.com/moby/moby/releases/tag/v17.05.0-ce) release?
* `docker-compose` deployed during CI to the latest [`1.14.0`](https://github.com/docker/compose/releases/tag/1.14.0) release?

By the way, I have already implemented it (and rolled back when realized that wasn't the problem back then) while working on #1128.

**Comment by webyneter** [comment]
On hold unless #1258 is resolved (and this one will most definitely be closed thereafter).

**Comment by browniebroke** [comment]
Out of curiosity, does anyone remembers why PR #497 started using a custom docker version rather than [using the one from Travis](https://docs.travis-ci.com/user/docker/)?

**Comment by jayfk** [comment]
Docker 1.10 wasn't available on Travis during that time.

**Comment by browniebroke** [comment]
It looks like [the documentation](https://cookiecutter-django.readthedocs.io/en/latest/deployment-with-docker.html#prerequisites) is out of sync with the version we test against.
