### ISSUE TITLE
'STATIC_URL' value is not set properly

### ISSUE THREAD

**Issue by burhan** [pydanny/cookiecutter-django#121]
The issue is at this line:

    STATIC_URL = 'https://s3.amazonaws.com/%s/' % AWS_STORAGE_BUCKET_NAME

The [`__repr__` method for ``values.Value``](https://github.com/jezdez/django-configurations/blob/master/configurations/values.py#L42) will return a string not suitable to be inserted into a URL: `<Value Default: None>`

It will replace `None` with whatever it could resolve from the environment.  The problem is now the URL becomes:

    https://s3.amazonaws.com/%lt;Value%20Default:%20foo&gt;/

I have a fix - its more of a hack really at [this commit](https://github.com/burhan/cookiecutter-django/commit/c8ee217dd72ec29ccea4f683d83ca7438247461c) that will resolve the issue.

[This commit](https://github.com/burhan/cookiecutter-django/commit/4bf90c08ee07007a4d053c2a19499e1516777ba7) just updates the above to reflect the environment variable as per the documentation.

**Comment by philippeluickx** [comment]
+1
I am having this issue when using https://github.com/Yaco-Sistemas/django-inplaceedit
> {% inplace_static %}

**Comment by theskumar** [comment]
This should be fixed with us replacing django-configuration with django-environ now.
