### ISSUE TITLE
Rename dev.yml to local.yml

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1226]
That would match up with `local.py` and `local.txt`. 

@pydanny, @jayfk, @luzfcb what do you think?

**Comment by jayfk** [comment]
Yep 👍 .

**Comment by amcorreia** [comment]
This means, to run unittest when using Docker, I need create a new compose file, to use config/settings/test.py ?

**Comment by webyneter** [comment]
@amcorreia no, you don't, test-specific settings will be made available to the running container through `pytest.ini` once you `docker-compose -f dev.yml run --rm django pytest .`

**Comment by webyneter** [comment]
@amcorreia all the related PR will do is just rename the files mentioned.
