### ISSUE TITLE
Question on postgres data persistence

### ISSUE THREAD

**Issue by hgonzalez94** [pydanny/cookiecutter-django#1231]
Hey, I had a question about this docker image. I'm pretty new to docker containers but I was hoping to understand why my postgres data persists between my restart operations.

Essentially whenever I want to restart my server, I run the following commands:

'docker stop $(docker ps -a -q)'
'docker rm $(docker ps -a --filter=status=exited --filter=status=created -q)'
'docker rmi $(docker images -a -q)'

Then I build it up again like this:

'docker-compose build'
'docker-compose up'

1) Is this a proper way of restarting the server?
2) Whenever I do this, I notice that my postgres data persists. Why is this? I never updated the data volume. Does the postgres docker image inherently store the data elsewhere? Does this have to do with docker data volumes?

@webyneter do you or anyone have any advice / answers on this? Any help understanding this would be greatly appreciated.

**Comment by webyneter** [comment]
@hgonzalez94 
1. You don't need to remove/rebuild your service images every time you want the server to restart — unless there's a new *version* (major/minor/patch) of the service to use, restarting service containers based on the same images should suffice: `docker-compose restart`. Or, if you want to restart the entire host, just `docker-compose stop`, restart, and then `docker-compose start` (or `docker-compose rm -s`, restart, `docker-compose up`).
2. If you take a look at `./compose/postgres/Dockerfile`, you'll see that we opt out to store no data in the image whatsoever — it all goes into either `postgres_data*` or `postgres_backup*` volumes defined in any of the `./*.yml` files; therefore, the data persists across an arbitrary number of run cycles unless you specifically remove/prune the associated volumes; all in all, volumes are nothing but paths mappings from aliases declared to host file system paths specified, so the dirs persist unless removed from the host.

**Comment by webyneter** [comment]
@hgonzalez94 has the issue been clarified?

**Comment by hgonzalez94** [comment]
Yea, thank you for the explanation!
