### ISSUE TITLE
run coverage with docker

### ISSUE THREAD

**Issue by narnikgamarnikus** [pydanny/cookiecutter-django#1238]
Hello!

I just recently started using cookiecutter and I do not understand how to run coverage?
I created the application, and run the tests like this: `docker-compose -f dev.yml run django py.test`

But how do I start the coverage ?

Thanks!

**Comment by webyneter** [comment]
@narnikgamarnikus try
```shell
docker-compose -f local.yml run --rm django coverage run --source . -m py.test
docker-compose -f local.yml run --rm django coverage report
docker-compose -f local.yml run --rm django coverage html
```

**Comment by narnikgamarnikus** [comment]
@webyneter , how i can run `open htmlcov/index.html`, and how i can add coverage badge to my README.rst ? 
I am sure that here it should be provided.

**Comment by Afrowave** [comment]
@narnikgamarnikus type it directly on to the terminal so long as you are in the project folder.
``` open htmlcov/index.html ```

**Comment by webyneter** [comment]
@narnikgamarnikus,
> how i can add coverage badge to my README.rst?
Take a look at my recent project, https://github.com/webyneter/python-humble-utils I've integrated with `codecov`.

**Comment by webyneter** [comment]
@narnikgamarnikus, to integrate with `codecov`,
1. you should first [sign up](https://codecov.io/);
1. then, follow the instructions they provide;
1. finally, find the badge at one of the `codecov`'s pages related to your account: As far as I can remember, they do provide the one for inclusion into `*.rst` files.

**Comment by webyneter** [comment]
@narnikgamarnikus can I close this one?

**Comment by narnikgamarnikus** [comment]
@webyneter , yes. 
Thanks you!
