### ISSUE TITLE
why apache with elasticbean?

### ISSUE THREAD

**Issue by kodeine** [pydanny/cookiecutter-django#1240]
as the title says, why apache was chosen for elasticbean and not nginx. also does it support certbot?

**Comment by pydanny** [comment]
Apache is required because that's the option Amazon gives you: http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-container.html

Instead of certbot, for Elastic Beanstalk, you have to use the AWS alternative.

**Comment by kodeine** [comment]
@pydanny you mean EC2 if i want to use certbot etc?

**Comment by pydanny** [comment]
@kodeine, i don't use certbot myself anymore. So if you want answers to your questions on certbot, you'll need to ask someone else.

**Comment by pydanny** [comment]
And the reason why I don't use certbot anymore is because I use the AWS alternative because that works so easily with EB AND lambda

**Comment by kodeine** [comment]
oh wow, i didnt know about the AWS certs, this is awesome!

**Comment by kodeine** [comment]
@pydanny  can you please share what config you use for using AWS ssl certifications on cookie cutter?

**Comment by pydanny** [comment]
We're converting our last app from AWS EB to to AWS Lambda. When that's done I'll update Cookiecutter Django.

**Comment by kodeine** [comment]
wonderful :+1:
