### ISSUE TITLE
Bootstrap 4 custom templates still required?

### ISSUE THREAD

**Issue by yunti** [pydanny/cookiecutter-django#1243]
With bootstrap 4 about to go to beta imminently.. it seems a good point to check whether some earlier workaround fixes for the earlier alpha stages are still required..

the custom bootstrap templates look to have been fixed upstream in django crispy forms.
Can these now be removed?

The css fix for the navbar, is this now also redundant?

**Comment by webyneter** [comment]
@yunti we welcome contribution efforts of all sorts to help us keep the project up-to-date with the modern ecosystem. If you feel the capacity to implement the proposed changes feel free to send a PR. It will be reviewed by the Core team once we have time.

**Comment by zoidbergwill** [comment]
Let me know if I can help getting any changes upstream into django-crispy-forms too.
