### ISSUE TITLE
Rename Dockerfile-dev to local.Dockerfile

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1256]
That would promote consistency further (for instance, see #1226).

**Comment by webyneter** [comment]
@pydanny @jayfk what do you think?

**Comment by pydanny** [comment]
FWIW, I haven't touched Docker in many months. Everything we run is on AWS Lambda with one exception, which isn't on Docker. So my ability to judge things is probably not that good. ;)

**Comment by sfdye** [comment]
Dockerfile should not have extension by convention I think.

At least it could be renamed to `Dockerfile-local` for consistency.

**Comment by webyneter** [comment]
@sfdye, you're right, it'd better be `Dockerfile-local`.
