### ISSUE TITLE
custom_bootstrap_compilation not documented

### ISSUE THREAD

**Issue by vladcalin** [pydanny/cookiecutter-django#1265]
I get prompted ``custom_bootstrap_compilation [n]: `` but I cannot find into the options documentation (http://cookiecutter-django.readthedocs.io/en/latest/project-generation-options.html) what features this enables.

**Comment by webyneter** [comment]
@vladcalin thanks for pointing this out: For historical reference on the issue, see #1181. As far as the docs are concerned, you're right, we don't have this feature documented -- I will address this in a new issue.

**Comment by webyneter** [comment]
@bwarren2 thank you, I've left a note in the PR.

**Comment by bwarren2** [comment]
I don't see a note :( .  (I have been getting a lot of Github instability this morning, so it might have dropped?)

**Comment by webyneter** [comment]
@bwarren2 a review note :)
