### ISSUE TITLE
Document custom_bootstrap_compilation project generation option

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1266]
As of now, we don't have any documentation for `custom_bootstrap_compilation` project generation option (first introduced in #1181). 

This issue was exposed in #1265 (thanks, @vladcalin). 

Things to cover:
* (_debatable_) a separate documentation section (say, 'Custom Bootstrap Compilation with Grunt') extending further on the feature summary from `README.rst` (but only if there's anything to elaborate on besides the info already provided);
* brief option description at the end of the [Project Generation Options](https://cookiecutter-django.readthedocs.io/en/latest/project-generation-options.html) page.

@bwarren2 mind delivering on this one? :)

**Comment by chriswedgwood** [comment]
Hi I've been trying to work with this option and I have been struggling a bit. If I choose it , in the project.sass there are a bunch of imports e.g. 

@import "type"; (this doesn't resolve)

Not @import "../bower_components/bootstrap-sass/assets/stylesheets/bootstrap.scss";

Im new to package managers but the questions that have come up for me in my attempts to get a workflow going with this are:

1)Is there a configuration option that lets the sass file know where to retrieve these assets in the bower path without having to write the full path?
2)Am I supposed to copy all the scss files into my sass folder?
3)Does it matter where the bower folder goes?
4)Can npm be used?

I would be happy to create further documentation for this 'Custom Bootstrap Compilation with Grunt' once Ive got my head around how its supposed to all tie together:)

**Comment by bwarren2** [comment]
Hey  Chris!

The bower_components folder belongs in the project root.  You need to `bower install` per the generated README block and `npm install` per the usual instructions.   As for the rest of it: you can change the import directives to point wherever you want.

I uploaded a video as a guide: https://vimeo.com/228722164 .

**Comment by chriswedgwood** [comment]
Thanks Ben that's a really useful video :)
