### ISSUE TITLE
Custom user model still contains first_name and last_name

### ISSUE THREAD

**Issue by federicobond** [pydanny/cookiecutter-django#1268]
The custom user model provided by this template has a `name` field which works better with name patterns around the globe, but still inherits `first_name` and `last_name` from AbstractUser.

Is this intended behavior? If that's the case, it would be appropiate to document it.

**Comment by jambonrose** [comment]
Would people be interested in integrating [`django-improved-user`](https://github.com/jambonsw/django-improved-user/)?

Full disclosure: I am one of the original authors.

I understand not wishing to add yet another dependency, but we also built it specifically to deal with this problem.

Note that it uses an email as an identifier, not a username, which [comes with its own issues](https://django-improved-user.readthedocs.io/en/latest/email_warning.html). That said, it would also be easy to leverage the mix-in classes to remove Django's names and use more international friendly short name, full name on a model with a Username.

Given the potential conflict of interest, I'll leave it at that. However, I'm happy to answer questions or create a PR if people want this.
