### ISSUE TITLE
Elastic Beanstalk deployment fails due to missing packages

### ISSUE THREAD

**Issue by shultz** [pydanny/cookiecutter-django#1270]
Steps to re-create:
Create new cookiecutter-django project with use_elasticbeanstalk_experimental enabled. Follow steps in `deployment-with-elastic-beanstalk.rst`

Deployment will fail and logs hint that there was an error with pip installing requirements, log into ec2 instance to reproduce the error:
```sh
[ec2-user@ip-172-31-11-149 ~]$ source /opt/python/run/venv/bin/activate
(venv)[ec2-user@ip-172-31-11-149 ~]$ cd /opt/python/ondeck/app/
(venv)[ec2-user@ip-172-31-11-149 app]$ pip install -r requirements.txt
...
No package 'libffi' found
...
Failed building wheel for argon2-cffi
...
Command "/opt/python/run/venv/bin/python3.4 -c "import setuptools, tokenize;__file__='/tmp/pip-build-6y5hb9qx/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-r7iy510t-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/python/run/venv/include/site/python3.4/cffi" failed with error code 1 in /tmp/pip-build-6y5hb9qx/cffi
```

I am guessing the libffi packages became a OS dependency when argon2-cffi was added to the base requirements file in f3ea2570ab6cfc981dca1b6a8f49852c91cbe2d7.

I have found that adding `libffi` and `libffi-devel` to `.ebextensions/10_packages.config` resolves this issue.

Also, in order to get elastic beanstalk to find the wsgi file, the quotes around `config/wsgi.py` in `40_python.config` need to be removed.

I will put together a PR for this, just wanted to check if there was any feedback or if anyone else was having this issue?

**Comment by pydanny** [comment]
When you have the opportunity, please submit a pull request. :-)

**Comment by shultz** [comment]
I have submitted #1277
