### ISSUE TITLE
How to set email as username?

### ISSUE THREAD

**Issue by evilplanet** [pydanny/cookiecutter-django#1280]
I've just set up a latest version of Cookiecutter project. What changes should I make to use email address as username?

**Comment by pydanny** [comment]
You'll need to adjust your allauth settings per http://django-allauth.readthedocs.io/en/latest/configuration.html?highlight=settings#configuration

**Comment by evilplanet** [comment]
@pydanny Just found it. Thank you!! I was going to past that link here, too! :)

**Comment by gotexis** [comment]
as of 2019 shouldn't this be the default behavior somehow?

**Comment by schlich** [comment]
agreed @gotexis

**Comment by theptrk** [comment]
You need to remember to update the email message or it will look confusing.
