### ISSUE TITLE
Deploy with virtualenv only

### ISSUE THREAD

**Issue by arcanewater** [pydanny/cookiecutter-django#1281]
Is there any option to deploy manually with just virtualenv instead of docker, heroku etc...? Because i tried but it always wants to install develop libs (debug toolbar etc) when i run the application. Is there a way to skip this that it wont require in production dev libs?

**Comment by jayfk** [comment]
Yup.

You'd install your dependencies with `pip install -r requirements/production.txt` and then run gunicorn pointing to your production settings with `/usr/local/bin/gunicorn config.wsgi -w 4 -b 0.0.0.0:5000 --chdir=/app`.

**Comment by arcanewater** [comment]
Okay i get the point to run it, but what about migrations etc? Because i get problems when i try to run migrate it already requires debug toolbar etc.

**Comment by pydanny** [comment]
@arcanewater We don't provide those answers here because the only platforms we currently support are Docker and Heroku. If you want answers to your questions outside of those things, you will need to:

* Purchase paid support at support@cookiecutter.io
* Ask somewhere else.
