### ISSUE TITLE
Pro Support

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#1283]
I've discussed this with @pydanny yesterday, time to make it official!

Cookiecutter Django now has *professional* paid support available at `support@cookiecutter.io`. This includes project setup, general Django questions, best practises, bugfixing, code reviews, updating old projects etc.

This is an experiment for a limited time. If there are enough support requests coming in, there's a good chance to extend it.

I've updated the readme and added an issue template in https://github.com/pydanny/cookiecutter-django/commit/e4d94b52d5aa0007e8def914d69b300249525765

Any thoughts or questions?

**Comment by Afrowave** [comment]
Nice!

I really hope this works. @pydanny and the rest of the contributors should be able to make some money from all the hard work.

**Comment by pydanny** [comment]
Some ideas to promote this:

* [ ] Add a "commercial support available" footer to the documentation
* [ ] Change the contributor's file to include "commercial support available"

**Comment by willyhakim** [comment]
I'm glad y'all are taking this direction. I would suggest to also add "commercial support for enterprises" . Companies love to buy "10 -20 hours a month" to get help with all of the above.

**Comment by weelng** [comment]
Definitely supporting this initiative. Going forward, I probably need guidance on how to actually use this tool to create Django microservices which I'm currently left dangling.

**Comment by zenahirsch** [comment]
It looks like my emails to support@cookiecutter.io are being bounced back—is this service no longer available?

**Comment by jayfk** [comment]
Argh, it looks like the DNS has changed about a week ago! Thanks for letting me know.

The main problem with the Pro support is/was that nobody is using it :). There were a couple support requests but none of them ended in a successful monetary transaction.

**Comment by zenahirsch** [comment]
@jayfk Well, if there's still some way to get access to paid support, I'd be interested (and willing to pay!)

**Comment by jayfk** [comment]
📫

**Comment by pydanny** [comment]
ping @jayfk

**Comment by jayfk** [comment]
Yeah, this didn't really work out. I'm going to remove all references to the pro support email address.
