### ISSUE TITLE
Remove dependency on Pillow?

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#1286]
We no longer ship Cookiecutter Django with a thumbnail plugin.

What is Pillow currently used for?

**Comment by pydanny** [comment]
I think I kept it in there to encourage people to use Pillow instead of PIL.

**Comment by jayfk** [comment]
👍🏼

**Comment by luzfcb** [comment]
Keeping Pillow makes life easier for our users.
Pillow have a lot of OS dependencies, and it was very "hard" for me to find them (a few years ago). 
This is what originated https://github.com/pydanny/cookiecutter-django/issues/34#issuecomment-65794902
