### ISSUE TITLE
Use Unix, not Windows environment variable format in Caddyfile

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1310]
From [Caddy docs](https://caddyserver.com/tutorial/caddyfile):

>Use of environment variables is allowed in addresses and arguments. They must be enclosed in curly braces, and you can use **either Unix or Windows** variable formats:

> ```Caddyfile
> localhost:{$PORT}
> root {%SITE_ROOT%}
> ```

What do you think, @jayfk?

**Comment by jayfk** [comment]
I really don't care :)
