### ISSUE TITLE
requirements/base.txt: pytz

### ISSUE THREAD

**Issue by berndca** [pydanny/cookiecutter-django#133]
I got a DataError exception (Django 1.7, Python 2.7)

    time zone "Pacific Standard Time" not recognized

in 

    h:\development\regxact\regxact_api_venv\lib\site-packages\django\db\backends\utils.py in execute, line 65

probably triggered by a last_modified field

    last_modified = models.DateTimeField(auto_now=True, db_index=True)

This problem was resolved by installing pytz (2017.7). Perhaps you might consider adding pytz to requirements.

Thanks, Bernd

**Comment by theskumar** [comment]
It seems `pytz` is added to `requirements/base.txt` https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/requirements/base.txt#L36 

Closing this issue. @berndca thanks a lot for reporting this. Re-open if you feel anything extra need to be done. :+1:
