### ISSUE TITLE
Python 3.4 and python-memcached

### ISSUE THREAD

**Issue by jrumbut** [pydanny/cookiecutter-django#135]
The python-memcached library isn't compatible with Python 3.4, and it's uncertain when 3.4 compatibility will be finished (see linsomniac/python-memcached#54).

The main release of pylibmc suffers from a similar issue.

It would be nice to update the documentation with this information, or perhaps comment out the entries. Let me know if you'd like a pull request for this!

Regardless, this project (and your book, I have the Django 1.5 edition) have been immensely helpful. Thank you!

**Comment by theskumar** [comment]
This can be associated as part of this issue: https://github.com/pydanny/cookiecutter-django/issues/186

**Comment by theskumar** [comment]
@jrumbut how about replacing memcached with redis cache?

**Comment by pydanny** [comment]
I'm game for replacing memcached with redis. Simplifies deployment a little bit. If someone really wants memcached, they can add it in themselves.

**Comment by theskumar** [comment]
Closing this now. Opened a new issue at https://github.com/pydanny/cookiecutter-django/issues/221 for using Redis as cache backend.
