### ISSUE TITLE
Cookiecutter-django error when run on Windows 10

### ISSUE THREAD

**Issue by BadgerMann** [pydanny/cookiecutter-django#1351]
* **I'm submitting a ... **
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
After answering all the installation questions the installation fails with the following errors:
```
Traceback (most recent call last):
  File "C:\Users\holldav\AppData\Local\Temp\tmpdny9uw4a.py", line 269, in <module>
    remove_elasticbeanstalk()
  File "C:\Users\holldav\AppData\Local\Temp\tmpdny9uw4a.py", line 193, in remove_elasticbeanstalk
    PROJECT_DIRECTORY, filename
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\holldav\\Dropbox\\UbuntuDjangoProjects\\CiCSVDev\\CiCSVDev\\cicsv\\requirements.txt'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
This is a transcript of the questions and answers that produced the error above:

```
(CiCSV) C:\Users\holldav\Dropbox\UbuntuDjangoProjects\CiCSVDev\CiCSVDev>cookiecutter https://github.com/pydanny/cookiecutter-django
project_name [Project Name]: CiCSV
project_slug [cicsv]:
author_name [Daniel Roy Greenfeld]: David Hollingworth
email [you@example.com]: me@myaddress.com
description [A short description of the project.]: Computer Systems Validation made easy.
domain_name [example.com]: mydomain.com
version [0.1.0]: 0.0.1
timezone [UTC]: GMT
use_whitenoise [y]:
use_celery [n]:
use_mailhog [n]: y
use_sentry_for_error_reporting [y]:
use_opbeat [n]:
use_pycharm [n]:
windows [n]: y
use_docker [n]:
use_heroku [n]:
use_elasticbeanstalk_experimental [n]:
use_compressor [n]:
Select postgresql_version:
1 - 9.6
2 - 9.5
3 - 9.4
4 - 9.3
5 - 9.2
Choose from 1, 2, 3, 4, 5 [1]:
Select js_task_runner:
1 - Gulp
2 - Grunt
3 - None
Choose from 1, 2, 3 [1]: 3
custom_bootstrap_compilation [n]:
Select open_source_license:
1 - MIT
2 - BSD
3 - GPLv3
4 - Apache Software License 2.0
5 - Not open source
Choose from 1, 2, 3, 4, 5 [1]: 5
```

* **What is the expected behavior?**
The installation should complete with no errors

* **What is the motivation / use case for changing the behavior?**
N/A

* **Please tell us about your environment:**
Windows 10 Pro 64 bit
Python 3.6
Virtualenv & Virtualenvwrapper-win
Django 1.11

* **Other information** 
None

**Comment by BadgerMann** [comment]
On a number of subsequent attempts this worked fine. I'm closing this issue as I couldn't reproduce it.

**Comment by Vaibhav** [comment]
run your terminal/powershell as administrator

**Comment by sdsaati** [comment]
I have the same issue. I'm running it on the administrator terminal on Windows 11. Have you found a solution for this?
