### ISSUE TITLE
Migrate to Bootstrap 4. 

### ISSUE THREAD

**Issue by zfrenchee** [pydanny/cookiecutter-django#1355]
I believe this repo currently depends on [bootstrap 4 alpha](https://v4-alpha.getbootstrap.com/). Bootstrap 4 is now released at [getbootstrap.com](https://getbootstrap.com/). 

Among other differences, bootstrap 4 reintroduced offsets (where the alpha had removed them I think) which is impacting how the allauth forms look. 

It would be nice to see this repo updated from the alpha version to the released Bootstrap 4.

**Comment by zfrenchee** [comment]
Actually I might have that backwards -- allauth might be stuck in the past but cookiecutter is up to date...

**Comment by pydanny** [comment]
I too would like to see this repo updated. We're open to pull requests. 😀

**Comment by mjhea0** [comment]
@pydanny This is a great one for [hacktoberfest](https://hacktoberfest.digitalocean.com/)... want to add the label?

**Comment by sfdye** [comment]
@zfrenchee  I think it's still in beta and this repo is up-to-date for that by #1319.

**Comment by zfrenchee** [comment]
@pydanny @mjhea0 @sfdye 
This repo is up to date, allauth is behind. However, Bootstrab 4 Beta 2 (to be released soon) [adds back offsets](https://github.com/twbs/bootstrap/issues/23278) solving the original problem. 

All things considered, since bootstrap 4 is in pretty rapid flux, it's just important to make sure everyone's consistent with the most up to date version. But I now believe this project is (for now) and so it makes sense to close this issue.
