### ISSUE TITLE
Drop Caddy - only free for personal use

### ISSUE THREAD

**Issue by philippeluickx** [pydanny/cookiecutter-django#1356]
* **I'm submitting a ... **
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Feature (or rollback)

* **What is the current behavior?**
Currently the default reverse proxy is Caddy (recently switched from nginx - for good reasons).

* **What is the motivation / use case for changing the behavior?**
Caddy changed licensing and is now paid for commercial usage.
https://caddyserver.com/products/licenses
Should we get back to nginx? What is the policy on using SW with this type of license?

**Comment by webyneter** [comment]
@philippeluickx, #1282.

**Comment by philippeluickx** [comment]
Couldn't find it in the issues, didn't check the PRs... thanks for the pointer, closing here.
