### ISSUE TITLE
Adding database credentials

### ISSUE THREAD

**Issue by berndca** [pydanny/cookiecutter-django#136]
When I ran ./manage migrate for the first time I got 

    django.db.utils.OperationalError: fe_sendauth: no password supplied

I'm proposing to add credentials to the database URL replacing:

    DATABASES = values.DatabaseURLValue('postgres://localhost/{{cookiecutter.repo_name}}')		

with 

    DATABASES = values.DatabaseURLValue('postgres://localhost/django:blank@{{cookiecutter.repo_name}}')	

In addition I would add a security check to make sure that an error is flagged if the production database password is 'blank'. I have opened a pull request #139.

**Comment by theskumar** [comment]
Appropriate documentation has been added and we feel that is enough to address this.
