### ISSUE TITLE
Wouldn't install ipdb==0.10.3 on Mac. Used 0.10.2

### ISSUE THREAD

**Issue by pekasus** [pydanny/cookiecutter-django#1361]
**Note: for support questions, please use the `cookiecutter-django` tag on stackoverflow**. This repository's issues are reserved for feature requests and bug reports. If you need quick professional paid support for your project, contact support@cookiecutter.io.

* **I'm submitting a ... **
  - [x ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
Wouldn't install ipdb==0.10.3. Kept getting the following error:
Command python setup.py egg_info failed with error code 1 in .../project/environment/build/ipdb

And:
error in ipdb setup command: Invalid environment marker: python_version >= "3.3"

I changed the requirements file to include version 0.10.2 and it installed.
* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by pydanny** [comment]
Did you file a corresponding issue with ipdb?

**Comment by pydanny** [comment]
Also, thanks for the report 😃

**Comment by pydanny** [comment]
This is an IPDB issue and not a Cookiecutter Django problem. Please open your issue with that project.
