### ISSUE TITLE
Startup procedure appears broken with a missing module: functools_lru_cache

### ISSUE THREAD

**Issue by statwonk** [pydanny/cookiecutter-django#1396]
* __I'm submitting a ...__
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Report a bug.

* **What is the current behavior?**

When following [the steps described here](https://github.com/pydanny/cookiecutter-django#usage), I receive the following error (using both Python3.5 and Python3.6),

```
$ cookiecutter https://github.com/pydanny/cookiecutter-django
You've downloaded /Users/statwonk/.cookiecutters/cookiecutter-django before. Is it okay to delete and re-download it? [yes]: yes
Unable to load extension: No module named functools_lru_cache
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

```
$ virtualenv --python=python3.6 venv
$ source venv/bin/activate
$ pip install "cookiecutter>=1.4.0"
$ cookiecutter https://github.com/pydanny/cookiecutter-django
```
* **What is the expected behavior?**

A sequence that asks for the set of Cookiecutter options I'd like to select. Instead I see,

```
$ cookiecutter https://github.com/pydanny/cookiecutter-django
You've downloaded /Users/statwonk/.cookiecutters/cookiecutter-django before. Is it okay to delete and re-download it? [yes]: yes
Unable to load extension: No module named functools_lru_cache
```
and the process ends.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

Mac OS X, `brew` installed.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by pydanny** [comment]
I suspect this is a Cookiecutter issue, not related to Cookiecutter Django. Some questions:

1. How did you install Cookiecutter?
2. Do you get the same error when you run Cookiecutter against another template?

**Comment by statwonk** [comment]
Ah! I installed Cookiecutter with `pip install "cookiecutter>=1.4.0"` _after_ activating the python3.5 and/or python3.6 virtualenv.

It looks like your theory is right as I see the same issue with `cookiecutter-flask`,

```
$ cookiecutter https://github.com/pydanny/cookiecutter-flask
Unable to load extension: No module named functools_lru_cache
```

**Comment by pydanny** [comment]
In your virtualenv, try: `pip install -U cookiecutter`

**Comment by jayfk** [comment]
Cookiecutter comes with a `--version` flag which also tells you where it is installed.

```
cookiecutter --version
```

**Comment by Afrowave** [comment]
I found out this the hard way as well. I use "[pyenv](https://github.com/pyenv/pyenv)" now.

**Comment by jayfk** [comment]
The `pip` command is probably linked to Python 2.7. Try `pip3` instead.

**Comment by statwonk** [comment]
Thank you all!

**Comment by statwonk** [comment]
For others that may find this. I hit this again and outside of the `virutualenv` (deactivated), I had to, `pip uninstall cookiecutter` to remote the 2.7 version.
