### ISSUE TITLE
I can't get cookiecutter to install properly on Ubuntu 16.04

### ISSUE THREAD

**Issue by Wcollard** [pydanny/cookiecutter-django#1415]
**Note: for support questions, please use the `cookiecutter-django` tag on stackoverflow**. This repository's issues are reserved for feature requests and bug reports. If you need quick professional paid support for your project, contact support@cookiecutter.io.

* **I'm submitting a ... **
  - [ ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Wcollard** [comment]
There seems to be a bug when installing cookiecutter on Ubuntu 16.04.  Maybe it is defaulting to python 2.7

**Comment by pydanny** [comment]
How exactly are you trying to install cookiecutter? Pip or something else?

**Comment by pydanny** [comment]
From the description, this is a Cookiecutter problem, and has nothing to do with Cookiecutter Django. Please open your ticket there.
