### ISSUE TITLE
Update project generated by old version of cookiecutter-django

### ISSUE THREAD

**Issue by glxiong** [pydanny/cookiecutter-django#1437]
**Note: for support questions, please use the `cookiecutter-django` tag on stackoverflow**. This repository's issues are reserved for feature requests and bug reports. If you need quick professional paid support for your project, contact support@cookiecutter.io.

* **I'm submitting a ... **
  - [ ] bug report
  - [X] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

request feature

* **What is the current behavior?**

Not sure whether I can update the project I generated using old version of cookiecutter-django to the latest cookiecutter-django

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

* **What is the expected behavior?**

I should be able to update to old project to latest cookiecutter-django.

* **What is the motivation / use case for changing the behavior?**

Always keeps up to date for old projects generated by old cookiecutter-django.

* **Please tell us about your environment:**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by pydanny** [comment]
Without significant funding (which is currently around $0), this is outside the scope of Cookiecutter Django. If you, @glxiong  are able to procure us funding for at least maintainer to go full time on this project, then we can reopen this issue.
