### ISSUE TITLE
Cookiecutter Django Docker Build Failing

### ISSUE THREAD

**Issue by joshmello** [pydanny/cookiecutter-django#1449]
* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug
Sorry if this isn't a bug but not sure what else it could be since I figured it should be building correctly.

* **What is the current behavior?**
Cookiecutter Django Docker build failing local and prod

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
When running docker-compose -f local.yml build or even the prod one I get an error. I tried everything and does not get past this part. StackTrace below.

* **What is the expected behavior?**
Build correctly

* **Please tell us about your environment:**
GitHub master of cookiecutter-django current build
Mac

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
[StackOverflow](https://stackoverflow.com/questions/48251274/cookiecutter-django-docker-build-failing)

**Comment by webyneter** [comment]
@joshmello please, fix your link url value.

**Comment by joshmello** [comment]
@webyneter Yes I already did sorry

**Comment by webyneter** [comment]
@joshmello what your initialization options exactly were?

**Comment by joshmello** [comment]
@webyneter I am assuming you mean this if . not please let me know what else you need.

- use_whitenoise [y]: n
-   use_celery [n]: n
-   use_mailhog [n]: n
-   use_sentry_for_error_reporting [y]: y
- use_opbeat [n]: y
- use_pycharm [n]: y
- windows [n]: n
- use_docker [y]: y
- use_heroku [n]: n
- use_compressor [n]: n
- Select postgresql_version: 1 - 10
- Choose from 1, 2, 3, 4 [1]: 1
- Select js_task_runner: None
- Select open_source_license:  Not open source
- use_elasticbeanstalk_experimental: n

**Comment by webyneter** [comment]
@joshmello yep.

**Comment by jayfk** [comment]
pip is trying to install something it can‘t read. Please check your requirement files for encoding issues.

**Comment by webyneter** [comment]
@joshmello had no problem reproducing it and successfully building on my Ubuntu...

**Comment by webyneter** [comment]
@joshmello what are your `docker version` and `docker-compose version`?

**Comment by joshmello** [comment]
Docker: `Docker version 17.12.0-ce, build c97c6d6`
Docker-Compose: `docker-compose-1.18.0 `

**Comment by joshmello** [comment]
@webyneter I reinstalled Docker from the docker site and redid the project with the same options and getting the same error. I will just close this issue and go a different route thanks for the quick response.
