### ISSUE TITLE
Use AWS roles instead of AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY

### ISSUE THREAD

**Issue by sfdye** [pydanny/cookiecutter-django#1453]
If the server is compromised, the attacker can easily get `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` from the environment,  with which they can do anything. 

In stead, the AWS best practice is to create an IAM [role](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html) and attach the IAM to the instance that requires the specific permissions, like for example in the default `cookiecutter-django` setup, it's the `S3FullPermission` for writing the static files.

Then we can safely remove the following:

env.example: 
https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/env.example?#L18:L19

production.py:
https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/env.example?#L18:L19

**Comment by pydanny** [comment]
I agree.

**Comment by sfdye** [comment]
Cool, I can make a PR for your to review. Basically remove these lines and update the docs with an additional step to provision an IAM role when deploying to production on aws.

________________________________

**Comment by sfdye** [comment]
Okay I will work on this and submit my PR today.

**Comment by jayfk** [comment]
This will only work on AWS, though. We are currently supporting a wide range of different deployments.

Creating an IAM role and giving it only prrmissions for s3 is the better approach in this regard.

**Comment by browniebroke** [comment]
Apologies if I'm misunderstood what you mean, but reading again, I'm not sure it's going to work. Have you used it in a project? I _think_ (but happy to be proven wrong) [the underlying library](http://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#settings) requires these 2 settings to be defined, they are not listed as optional.

Sure, if you use the key and secret from your root account, that's is bad practice. However, what I've done in the past, is to create an IAM role used only by a deploy user, with restricted access to S3. Then I created a Key and Secret for that user, and that's what I'm using in my project.

You can go one step further and only grant access to the specific bucket(s) to that user, as outlined in [this tutorial](https://www.caktusgroup.com/blog/2014/11/10/Using-Amazon-S3-to-store-your-Django-sites-static-and-media-files/).

**Comment by sfdye** [comment]
@browniebroke Yes, I have used it in one of my production projects. 

Happy to provide some background, according boto3 doc [here](http://boto3.readthedocs.io/en/latest/guide/configuration.html#iam-role), if no credentials are provided, boto3 will search for IAM role attached to the EC2 instance automatically.

> Sure, if you use the key and secret from your root account, that's is bad practice. However, what I've done in the past, is to create an IAM role used only by a deploy user, with restricted access to S3. Then I created a Key and Secret for that user, and that's what I'm using in my project.

I guess this really comes down to the question of IAM user V.S. IAM role. Here is an excerpt from the AWS [FAQ]:(https://aws.amazon.com/iam/faqs/)

> Q: What is the difference between an IAM role and an IAM user? 
An IAM user has permanent long-term credentials and is used to directly interact with AWS services. An IAM role does not have any credentials and cannot make direct requests to AWS services. IAM roles are meant to be assumed by authorized entities, such as IAM users, applications, or an AWS service such as EC2.

So I think if we don't want to give long-term credentials and just granting access to certain AWS service (like S3), IAM role is more suitable for this job. What do you think?

**Comment by browniebroke** [comment]
I've been meaning to review the pull request for this, but I'm wondering if I know enough about the supported range of deployments. In theory, a Docker container isn't restricted to be deployed AWS, it could get deployed in [a number of platforms](https://docs.docker.com/machine/drivers/). 

I'm not familiar enough with the project to know what Docker platform is supported, but if there is anything else than AWS, I'd say the environment variables should stay in the env.example file.

Thoughts on this? Am I missing anything?

**Comment by sfdye** [comment]
@browniebroke you are absolutely right, even docker deployment isn't limited to AWS only. I think the best approach would probably be to include a note for AWS deployment and keep the environment variables in the `env.example` as they are.
