### ISSUE TITLE
about pienv and virtualenv

### ISSUE THREAD

**Issue by fantasyhh** [pydanny/cookiecutter-django#1462]
when using  virtualenv: 
project_name [Project Name]: icecreamratings_project
project_slug [icecreamratings_project]: icecreamratings
then, project dir  : icecreamratings/ ...

when using  pipenv: 
project_name [Project Name]: icecreamratings_project
project_slug [icecreamratings_project]: icecreamratings
then, project dir  : icecreamrating_projects/ ...

**Comment by webyneter** [comment]
Would you mind elaborating a bit further?
