### ISSUE TITLE
f-string

### ISSUE THREAD

**Issue by sfdye** [pydanny/cookiecutter-django#1484]
Since it's Python 3.6 or go home now, shall we change all the `.format()` to f-string? For better readability and performance.

@pydanny @webyneter @jayfk what do you think?

**Comment by webyneter** [comment]
@sfdye provided you have time and effort to spare, it's welcome! ;)

**Comment by sfdye** [comment]
@webyneter I will be happy to do that, when I get a chance.

**Comment by browniebroke** [comment]
We are still using Python 3.5 in a few places, but that should not be the case once #1482 is merged, which should be this week.

**Comment by sfdye** [comment]
Cool, I will wait until #1482 is merged.

**Comment by browniebroke** [comment]
Update: this is no longer blocked, thanks to #1418

**Comment by sfdye** [comment]
Nice! I will do it tonight.
