### ISSUE TITLE
Drop support for PostgreSQL 9.2

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1493]
PostgreSQL 9.2 EOL date [has come on Sep, 2017](https://www.postgresql.org/support/versioning/).

**Comment by browniebroke** [comment]
It looks like this option is used in a single place, to choose [the base Docker image](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/postgres/Dockerfile) for the DB. 

I'm going to go one step further and ask if it actually makes sense to keep this customisation question? Given that cookiecutter-django is used to jumpstart new projects, is there a use case to start with something else than the latest DB version?

**Comment by webyneter** [comment]
@browniebroke that's a good question, indeed, @pydanny, @jayfk, what do you think?

**Comment by webyneter** [comment]
@browniebroke to my mind, it's better to give our users a choice. I suspect, numerous people will still be using 9.6 in the months to come.
