### ISSUE TITLE
Opbeat sunset

### ISSUE THREAD

**Issue by browniebroke** [pydanny/cookiecutter-django#1516]
Opbeat is joining Elastic and they are planning to sunset the service May 24, 2018. The new service will be called Elastic APM, and has [entered into GA phase](https://www.elastic.co/blog/elastic-apm-ga-released) recently. Might be time to drop this option from this cookiecutter?

(x-refs #559 #449)

**Comment by sfdye** [comment]
PR submitted, help me check? @browniebroke
