### ISSUE TITLE
Migrate from old url regex urls to new path urls

### ISSUE THREAD

**Issue by vCra** [pydanny/cookiecutter-django#1519]
**Note: for support questions, please use the `cookiecutter-django` tag on stackoverflow**. This repository's issues are reserved for feature requests and bug reports. If you need quick professional paid support for your project, contact support@cookiecutter.io.

* **I'm submitting a ... **
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Django versions pre 2 used django.conf.urls.url() instances within a projects urlpatterns. The "preferred" way of doing this is to use django.urls.path(), which does not require the use of regex. For any paths which require the use of regex, we can use django.urls.re_path(). 

* **What is the current behavior?**

The old django.conf.urls.url() still works, but is mapped to django.urls.re_path(), without any warning as it is not yet been marked for depreciation

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

* **What is the expected behavior?**

The new system should use django.urls.path(), or django.urls.re_path() when regex is required

* **What is the motivation / use case for changing the behavior?**

The new path syntax is cleaner, simpler and more readable than the previous regex version. 

* **Please tell us about your environment:**

cookiecutter-django with django2

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

https://docs.djangoproject.com/en/2.0/releases/2.0/#simplified-url-routing-syntax
https://docs.djangoproject.com/en/2.0/ref/urls/

**Comment by saschalalala** [comment]
Is anyone working on this? I could do this in the next week and provide a pull request, I think.

**Comment by webyneter** [comment]
@saschalalala that'd be of great value to everyone if you could!

**Comment by saschalalala** [comment]
Before starting to work on it, just to be clear: Cookiecutter is Django 2.0+-only, right? So there is no need to somehow provide backwards compatibility?

**Comment by webyneter** [comment]
@saschalalala, yes, that's right: Python 3.6, Django 2.0.

**Comment by webyneter** [comment]
Any news on this one, @saschalalala ?

**Comment by saschalalala** [comment]
@webyneter Just created a pull request. Sorry, I totally forgot this one m(
