### ISSUE TITLE
500 internal server error on heroku, fresh deploy

### ISSUE THREAD

**Issue by AntoineGagnon** [pydanny/cookiecutter-django#1527]
**Note: for support questions, please use the `cookiecutter-django` tag on stackoverflow**. This repository's issues are reserved for feature requests and bug reports. If you need quick professional paid support for your project, contact support@cookiecutter.io.

* **I'm submitting a**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
My app works in my local environment, but when I deploy to heroku and try to access any page, this is the error I get in sentry:

``` 
 ValueError
 
 Missing staticfiles manifest entry for 'css/project.min.css'
 
     compressor/templatetags/compress.py in get_original_content at line 123
 
 compressor/templatetags/compress.py in get_compressor at line 39
 compressor/templatetags/compress.py in render_compressed at line 98
 compressor/templatetags/compress.py in render at line 131
 Called from: django/template/base.py in render_annotated
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
I just deployed a fresh install to heroku following the docs.

* **Please tell us about your environment:**
I'm using Whitenoise, everything is working fine in local dev.

**Comment by browniebroke** [comment]
Thanks for the bug report. Could you please tell what options were selected for use_compressor, js_task_runner, and custom_bootstrap_compilation?

**Comment by AntoineGagnon** [comment]
Sure !
use_compressor was set to Yes
js_task_runner was set to Gulp
custom_bootstrap_compilation was set to No

**Comment by browniebroke** [comment]
Ok, found some time to look into this. I can reproduce, and I've confirmed my suspicions that it's related to #1429. The fix is to replace `{% static 'css/project.min.css' %}` by `{% static 'css/project.css' %}` in `base.html` (remove the `min` bit in the name).

This seems to be a case I didn't cater for in that PR: compressor + Gulp.

**Comment by AntoineGagnon** [comment]
Everything works great now, thanks for fixing it !

**Comment by mjstenbe** [comment]
Tried to deploy node-js-demo-app to Heroku from https://github.com/mjstenbe/HerokuDemo.
The app is cloned from heroku sample app repo.
After deploy I get Internal server error?

**Comment by luzfcb** [comment]
@mjstenbe your problem is not related to cookiecutter-django, django, or python. so here is not the best place for you to get help.

**Comment by Mihks** [comment]
j'ai une erreur 500 erreur de serveur interne lorsque j'utilise des requetes ajax dans mon app hebergé sur heroku

**Comment by browniebroke** [comment]
@Mihks ce projet est maintenu par des volontaires non rémunéré et n'est pas affilié à Heroku. Qui plus est, il n'est pas écrit en PHP. 

Veuillez choisir un endroit plus adéquat pour trouver de l'aide.

Merci

**Comment by Mihks** [comment]
sorry, je cherche un peu partout depuis des jours donc quand j'ai vu cette discussion je me suis dit que je pourrai avoir la solution, chui désespéré !Encore désolé
