### ISSUE TITLE
psycopg2 is moved to psycopg-binary

### ISSUE THREAD

**Issue by elcolie** [pydanny/cookiecutter-django#1530]
`pip install -r local.txt`
```
Downloading psycopg2-2.7.4.tar.gz (425kB)
    100% |████████████████████████████████| 430kB 1.0MB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found


    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/h5/lj3c5_050j3_yjd77zqxcn7r0000gp/T/pip-build-vah0b9cd/psycopg2/
```

**Comment by luzfcb** [comment]
@elcolie please, install the OS package `libpq-dev` and try again install psycopg2

```
sudo apt-get install libpq-dev
```

or

```
cd utility/
sudo ./install_os_dependencies.sh
```

**Comment by sfdye** [comment]
Are you using the latest cookiecutter-django? It should be fixed in #1503.

**Comment by elcolie** [comment]
@luzfcb Hi. Thank you for your fast reply. I am using OSX 10.13.3

@sfdye Hi. I think that fix break package
I can't use `psycopg2==2.7.4 --no-binary psycopg2`
But I use `psycopg2==2.7.4`

Refer to this. It does not need any extra argument
http://initd.org/psycopg/docs/install.html

I am new to this. Please correct me if I am wrong.
I heard that `--no-binary` is better than `binary` in terms of forward compatibility. But I can not use it. I need to leave it blank

**Comment by elcolie** [comment]
@sfdye I use `2.0.2`

**Comment by elcolie** [comment]
Never mind this issue is very easy to fixed. I just follow the  the official docs by drop `--no-binary psycopg2` and I am good to go.

Thank you @luzfcb @sfdye 

**official docs:**
http://initd.org/psycopg/docs/install.html

**Comment by browniebroke** [comment]
To avoid this kind of extra complications, should we use `psycopg2-binary==2.7.4` when not using Docker?

**Comment by jayfk** [comment]
Yeah, that's probably a good idea. We could also update the docs and make `pg_config` a prerequisite on all platforms.

**Comment by browniebroke** [comment]
Reopening this to improve the current situation.

**Comment by Arti3DPlayer** [comment]
Same issue with cookiecutter==1.6.0 on mac os

**Comment by sfdye** [comment]
@Arti3DPlayer what version of cookiecutter-django are you using? The master branch should have the fix already.

**Comment by Arti3DPlayer** [comment]
@scast I installed from documentation `pip install "cookiecutter>=1.4.0"`, so I have: cookiecutter==1.6.0

**Comment by sfdye** [comment]
@Arti3DPlayer I mean `cookiecutter-django` version. How did you initialize your project?

**Comment by Arti3DPlayer** [comment]
@sfdye I used command from here: https://github.com/pydanny/cookiecutter-django#usage

**Comment by KrunchMuffin** [comment]
I just got this error as well. Using Docker. Pycharm. Windows 10
