### ISSUE TITLE
What's ACCOUNT_ALLOW_REGISTRATION for? 

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1543]
Couldn't find any signs of `ACCOUNT_ALLOW_REGISTRATION` in `django-allauth` docs (not even the repo history)...

**Comment by luzfcb** [comment]
@webyneter https://github.com/pydanny/cookiecutter-django/pull/432

**Comment by luzfcb** [comment]
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/adapter.py#L169-L176

**Comment by webyneter** [comment]
@luzfcb thanks, indeed.
