### ISSUE TITLE
Consider renaming local.yml to docker-compose.yml 

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#1552]
Based on an internal discussion, consider renaming `local.yml` to `docker-compose.yml`.

**Pro**
- Easier for new users. `docker-compose up` simply works, no need to set the file explicitly
- Easier on the hand, Docker commands are shorter
- Internal consistency. Running the Django CLI with vanilla Python starts the project with the local settings. 

**Con**
- Explicit is better than implicit. Running a `docker-compose` command on a production machine starts starts the dev configuration.

**Comment by Afrowave** [comment]
I actually like the fact that you must specify which file you want to use, explicitly.

**Comment by webyneter** [comment]
@jayfk I'm -1 on this, you know that :)

**Comment by pydanny** [comment]
> Explicit is better than implicit. **Running a docker-compose command on a production machine starts starts the dev configuration**.

That beginners might run dev in production is scary. Especially if it's the default and we implemented it. To me, this is an unnacceptable security risk. Someone's going to make this mistake and we are going to be (arguably rightfully so) blamed for it.

**Comment by browniebroke** [comment]
I am -1 on this too, for the "Explicit is better than implicit".

For a non-beginner but unfamiliar with cookiecutter-django, it might not be obvious what `docker-compose.yml` is for. 

One would have to look around and see that there is a production file, and deduct it's the local file. Requires a mental effort whereas the `local.yml` is easy to detect and remember.

**Comment by sfdye** [comment]
+1 for explicit
