### ISSUE TITLE
Uninstall gevent

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1555]
We don't use it anywhere.

**Comment by jayfk** [comment]
gunicorn

**Comment by webyneter** [comment]
To the best of my knowledge, we don't have gunicorn's [`-k gevent` or `--worker-class gevent`](http://docs.gunicorn.org/en/stable/settings.html#worker-class) set anywhere...

**Comment by jayfk** [comment]
It could be that this was a hard requirement on Heroku some time ago?

**Comment by webyneter** [comment]
@jayfk sure, I'll double check that.

**Comment by webyneter** [comment]
@jayfk on one of the recent projects of mine we removed `gevent` and the setup's been rolling in production without any apparent glitches.

**Comment by pydanny** [comment]
Yes, back in the day Heroku tutorials mentioned it, but that was many years ago.
