### ISSUE TITLE
Docker database restore not working

### ISSUE THREAD

**Issue by afgane** [pydanny/cookiecutter-django#1558]
**Note: for support questions, please use the `cookiecutter-django` tag on stackoverflow**. This repository's issues are reserved for feature requests and bug reports. If you need quick professional paid support for your project, contact support@cookiecutter.io.

* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
```
$ docker-compose -f local.yml run postgres restore backup_2018_03_08T03_34_00.sql.gz
beginning restore from backup_2018_03_08T03_34_00.sql.gz
-------------------------
deleting old database obygSDFWXMfXVZxu
dropdb: could not connect to database template1: could not translate host name "postgres" to address: Name or service not known
database obygSDFWXMfXVZxu does not exist, continue
creating new database obygSDFWXMfXVZxu
createdb: could not connect to database template1: could not translate host name "postgres" to address: Name or service not known
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

Following the docs: https://cookiecutter-django.readthedocs.io/en/latest/docker-postgres-backups.html
- docker-compose -f local.yml run postgres backup
- docker-compose -f local.yml run postgres list-backups
- docker-compose -f local.yml run postgres restore filename.sql

* **What is the expected behavior?**
Restored database.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
MacOS 10.12.6 w/ Docker 17.12.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by jayfk** [comment]
You need to make sure that the database is running in the background.

**Comment by afgane** [comment]
Since the command to create the backup worked without the service running, I didn't post that output but I had tried that as well and was getting the following:
```
postgres_1  | 2018-03-08 04:59:42.925 UTC [37] ERROR:  database "obygSDFWXMfXVZxu" is being accessed by other users
postgres_1  | 2018-03-08 04:59:42.925 UTC [37] DETAIL:  There are 2 other sessions using the database.
postgres_1  | 2018-03-08 04:59:42.925 UTC [37] STATEMENT:  DROP DATABASE "obygSDFWXMfXVZxu";
postgres_1  | 2018-03-08 04:59:42.961 UTC [38] ERROR:  database "obygSDFWXMfXVZxu" already exists
postgres_1  | 2018-03-08 04:59:42.961 UTC [38] STATEMENT:  CREATE DATABASE "obygSDFWXMfXVZxu" OWNER "obygSDFWXMfXVZxu";
```

**Comment by webyneter** [comment]
@afgane repoduced locally. I personally have not been using `backup.sh`/`restore.sh` but rather custom scripts. Will give you an update soon.

**Comment by jayfk** [comment]
@afgane you are getting this error because your database is still in use. 

```
ERROR:  database "obygSDFWXMfXVZxu" is being accessed by other users
There are 2 other sessions using the database.
```

All you have to do is to stop these processes (probably a running Django container/shell) and you are good to go.

Leaving this open so that we can add it to the docs.
