### ISSUE TITLE
Migrate to Pathlib

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1559]
It's time to consider migrating to [Pathlib](https://docs.python.org/3/library/pathlib.html) (thanks @browniebroke for raising the concern). Affected files:

* `pre_gen_project.py`;
* `post_gen_project.py`;
* `test_cookiecutter_generation.py`;
* `manage.py`;
* `wsgi.py`;
* `merge_production_dotenvs_in_dotenv.py`;
*  settings.

**Comment by browniebroke** [comment]
Just noting down that we currently cannot use it static-related settings due to an [issue in Whitenoise](https://github.com/evansd/whitenoise/issues/192).

**Comment by yunti** [comment]
@browniebroke @webyneter Is this a change you still wanted to make in the project as Whitenoise has resolved the issue now? Did you want to drop django-environ altogether as there looks to be functionality used in the project that wouldn't be covered by pathlib, but may not be necessary.

**Comment by browniebroke** [comment]
Would be nive to have it yes, but I don't think we want to drop django-environ.
