### ISSUE TITLE
django-autoslug package development dropped.

### ISSUE THREAD

**Issue by sebastian-code** [pydanny/cookiecutter-django#1560]
* **I'm submitting a ... **
  - [X] bug report
  - [ ] feature request
  - [ ] support request 

* **What is the current behavior?**
The template comes with the package [django-autoslug](https://github.com/neithere/django-autoslug), this package development appears to have been dropped and is not currently supporting Django 2.x, the new Django version creates an incompatibility with the package because of the changes on the `django.core.urlresolvers` in favor of `django.urls`.

**Comment by browniebroke** [comment]
Where is it being used? I thought django-autoslug [was removed from the template](https://github.com/pydanny/cookiecutter-django/blob/master/CHANGELOG.md#removed) a while back.

**Comment by webyneter** [comment]
@sebastian-code, @browniebroke is right: we don't have `django-autoslug` in our template's codebase anymore.

**Comment by sebastian-code** [comment]
Well, I reported it, because it appears listed in #1111

**Comment by luzfcb** [comment]
Em 08/03/2018 18:12, "Sebastian Reyes Espinosa" <notifications@github.com>
escreveu:
