### ISSUE TITLE
WEB_CONCURRENCY environment variable missing

### ISSUE THREAD

**Issue by reggieriser** [pydanny/cookiecutter-django#1562]
In baf08b2, `WEB_CONCURRENCY` was set to 4 in `env.example` so that users didn't accidentally deploy gunicorn with only 1 worker process.  In splitting up environment variables in 3f8aa26, we seem to have lost `WEB_CONCURRENCY`.  I'm assuming it should go in the new `.envs/.production/.django` file.

**Comment by webyneter** [comment]
@reggieriser true! My bad. Fixing this now.

**Comment by webyneter** [comment]
@reggieriser by the way, there's a safety net for that, in the Heroku deployment guide:

```bash
heroku config:set WEB_CONCURRENCY=4
```

Thanks @browniebroke :)
