### ISSUE TITLE
Feature Request: Docker bin/bash for django container

### ISSUE THREAD

**Issue by nh2d** [pydanny/cookiecutter-django#1563]
**Note: for support questions, please use the `cookiecutter-django` tag on stackoverflow**. This repository's issues are reserved for feature requests and bug reports. If you need quick professional paid support for your project, contact support@cookiecutter.io.

* **I'm submitting a ... **
  - [ ] bug report
  - [ X] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Feature

This may have already been addressed, but it would be nice to have a /bin/bash in the Docker image

`docker-compose -f local.yml run django  /bin/bash`

This would enable stuff like 
`docker-compose -f local.yml run django manage.py dbshell`

I can't think of other use cases off the top of my head, but I have wanted to have a bash on several occasions. I understand it might require pulling more unnecessary code into packages, but if it's not too expensive it could be useful for SSH into containers, too (if that's not already possible). I've only been using Docker for a few months.

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by webyneter** [comment]
@nh2d our `django` service's `Dockerfile` is built upon `python:3.6-alpine` which has an `ash` shell instead:
```bash
docker-compose -f local.yml run --rm django ash
# or 
docker-compose -f local.yml exec django ash
```

For `dbshell` management command to work, however, [you must install `psql` into `django` ](https://docs.djangoproject.com/en/2.0/ref/django-admin/#dbshell); given our present setup you'll need to `apk add postgresql-client` with the `django`'s `Dockerfile`:

```Dockerfile
# ...
RUN apk update \
  # psycopg2 dependencies
  && apk add --virtual build-deps gcc python3-dev musl-dev \
  && apk add postgresql-dev \
  # ... \
  && apk add postgresql-client
# ...
```

Then, 

1. `docker-compose -f local.yml build django`
1. `docker-compose -f local.yml run --rm django python manage.py dbshell`

and you should be good to go.

**Comment by webyneter** [comment]
@nh2d also note this fix is now in the latest code base: e1bce92ad98a10efdb542cb811ee08a611d78db0
You can save yourself some time by re-generating the project from scratch with the latest mainline.

**Comment by jsmedmar** [comment]
@webyneter, just curious why alpine and not an ubuntu distribution?

**Comment by jsmedmar** [comment]
Was trying to install pandoc and not trivial in `ash`
