### ISSUE TITLE
.envs in .gitignore 

### ISSUE THREAD

**Issue by Marpop** [pydanny/cookiecutter-django#1565]
Hey, is this a bug?
.gitignore file when keep_local_envs_in_vcs [y]: y
```
.envs/**/*
!.envs/.local/
```
doesn't work and I need to change it to:
```
.envs/*/*
!.envs/.local/*
```

**Comment by webyneter** [comment]
Yep, thanks for pointing this out (however, I have to say that had worked for me when I was testing that with GitKraken). What eventually worked for me was

```.gitignore
.envs/*
!.envs/.local/
```

@Marpop, would you mind checking if this works for you as well? This follows the sample from [here](https://stackoverflow.com/a/5534865).

**Comment by webyneter** [comment]
@Marpop if the approach I've mentioned turns out to work for you I'll commit it to `master`.

**Comment by Marpop** [comment]
Your solution works too.

**Comment by webyneter** [comment]
@Marpop thank you for the feedback, patching now.
