### ISSUE TITLE
No env.example?

### ISSUE THREAD

**Issue by howardjones** [pydanny/cookiecutter-django#1566]
* **I'm submitting a ... **
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
No env.example file exists anywhere in the created project (or indeed in the git repo).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

Run cookiecutter as described in the README

* **What is the expected behavior?**

A template project that the documentation describes accurately.

* **What is the motivation / use case for changing the behavior?**

Either the documentation is incorrect, or the the cookiecutter template is incorrect. When faced with a wall of somewhat unfamiliar code, this undermines confidence in the reliability of the rest of it.

* **Please tell us about your environment:**

Ubuntu 16.04, Python 3.5.2, 64-bit.

**Comment by browniebroke** [comment]
This is a documentation issue, the behaviour has been changed recently. The `.env` files should now be located in the `.envs` folder in the project root.

**Comment by webyneter** [comment]
@howardjones the docs have been updated in a31f5090d1e7fa2d3c7c34d00a92ea14cb2167dd.
