### ISSUE TITLE
Missing REDIS_URL

### ISSUE THREAD

**Issue by reggieriser** [pydanny/cookiecutter-django#1570]
It looks like the `REDIS_URL` environment variable was taken out of `entrypoint.sh` as part of 03ee6c7.  If using Docker, this breaks the communication between the django container and the redis container since the cache location defaults to `redis://127.0.0.1:6379/0` in `base.py` (unless you had the environment variable set up elsewhere).  It also fails silently since we have `IGNORE_EXCEPTIONS` on in `production.py`.

To avoid confusion, should we add `REDIS_URL` back to `entrypoint.sh`?  Or should we add it to the new `.envs/.production/.django` file?

**Comment by webyneter** [comment]
@reggieriser in the same commit, there are `.celery` local and production env files present both settings `CELERY_BROKER_URL=redis://redis:6379/0`.

**Comment by webyneter** [comment]
Provided you opt for `use_celery` `y` and `use_docker` `y` those envs will come up in the corresponding dirs exposing the vars you're looking for.

**Comment by reggieriser** [comment]
In this project, I use Docker but not celery, so `REDIS_URL` doesn't appear.  It did previously.

**Comment by webyneter** [comment]
Now I see, whenever `use_docker` is `y` and `use_celery` is `n`, `.celery` envs get removed even though `REDIS_URL` is not Celery-specific. This is a bug indeed. I'm not sure I'll have time to fix this in the coming hours, so I suggest you
1. create a `.celery` env file manually with `REDIS_URL` set to whatever you need;
2. append `./.envs/.local/.celery` as another `env_file` with whatever the container needs it.
