### ISSUE TITLE
[questions]Local development with docker

### ISSUE THREAD

**Issue by Arti3DPlayer** [pydanny/cookiecutter-django#1577]
I've never use docker for development on local machine so I have few questions that I didn't find in documentation.

1. After setup I can't figure out how do I can install my packages via pip. I tried:
`docker-compose -f local.yml run --rm django pip install some-package`. It installed package somewhere, but not in project. Do I need to build every time when I add new package?

2. How to run django managment commands in another thread
`docker-compose -f local.yml run --rm django python manage.py mycommand` stop `runserver` command that is not convenient

3. Where do I see celery tasks log ?  How to run:
```
celery -A apps.taskapp worker -l info
celery -A  apps.taskapp beat -l INFO
```
 to see debug messages of my tasks

**Comment by jayfk** [comment]
Hi @Arti3DPlayer!

This is a bugtracker, not a general help forum for questions on how to use certain features. Please ask your questions on stackoverflow, the Cookiecutter Django gitter chat or one of the general chats about Docker/Django on IRC.

**Comment by Arti3DPlayer** [comment]
@jayfk I did, thanks

https://stackoverflow.com/questions/49389440/cookiecutter-django-local-development-with-docker
