### ISSUE TITLE
Install boto3 as extra of django-storages

### ISSUE THREAD

**Issue by browniebroke** [pydanny/cookiecutter-django#1586]
It's now possible to install `django-storages` dependencies [using `extra_requires`](https://github.com/jschneier/django-storages/blob/master/CHANGELOG.rst#166-2018-03-26).

That means we don't need to list `boto3` as an explicit requirement:

https://github.com/pydanny/cookiecutter-django/blob/80ae32259ccfb7e9bc52db48bb33520ec011e733/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/production.txt#L7

We just need to change django-storages to `django-storages[boto3]==1.6.6`

**Comment by sfdye** [comment]
👏 This would be mean less noise from pyup for boto!
