### ISSUE TITLE
add pylint-common and pylint-django to requirements/local.txt

### ISSUE THREAD

**Issue by jsmedmar** [pydanny/cookiecutter-django#1590]
pylint-common, pylint-celery and pylint-django are defined as plugins in `pylintrc`, perhaps we should add them to the requirements?

```
# Code quality
# ------------------------------------------------------------------------------
flake8==3.5.0  # https://github.com/PyCQA/flake8
coverage==4.5.1  # https://github.com/nedbat/coveragepy
pylint-common==0.2.5  # https://github.com/landscapeio/pylint-common
pylint-django==0.9.4  # https://github.com/PyCQA/pylint-django
pylint-celery==0.3  # https://github.com/PyCQA/pylint-celery
```

**Comment by MarcSkovMadsen** [comment]
Or for pylint-common remove it from the pylintrc instead as according to https://github.com/landscapeio/pylint-common

"Note: No longer maintained
This was used as part off prospector but has been removed. It is no longer maintained (in this fork at least) as most of the functions are now replaced by pylint builtins or are no longer valid."

**Comment by Marpop** [comment]
What about pylint-plugin-utils?

`pylint-plugin-utils==0.4`  # https://github.com/PyCQA/pylint-plugin-utils`

**Comment by browniebroke** [comment]
I don't think we should `pylint-plugin-utils`, as far as I understand, it's a module to help write plugin, not meant to be used directly?

Agree with @MarcSkovMadsen, we should clean up our references to `pylint-common`, but the other 2 are welcome additions, I think.
