### ISSUE TITLE
Probot integration

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1594]
As by @browniebroke's suggestion, it's worth considering to integrate some of the [Probot apps](https://probot.github.io/apps/) with out development workflow. 

For now, the shortlisted ones are:

* [Work In Progress](https://probot.github.io/apps/wip/): "Prevent merging of Pull Requests with "WIP" in the title".
* [First Timers](https://probot.github.io/apps/first-timers/): "Create starter issues to help onboard new open source contributors".
* [todo](https://probot.github.io/apps/todo/): "Creates new issues from actionable comments in your code.".
* (?) [Reminders](https://probot.github.io/apps/reminders/): "Set reminders on Issues and Pull Requests".
* [Welcome](https://probot.github.io/apps/welcome/): "Welcomes new users".
* [Polls](https://probot.github.io/apps/polls/): "Create polls in GitHub issues.".
* [Request Info](https://probot.github.io/apps/request-info/): "Requests more info on issues and pull requests with the default title or an empty body.".
* (?) [Unfurl Links](https://probot.github.io/apps/unfurl-links/): "Add context to the links shared in discussions".

**Comment by sfdye** [comment]
I've tried almost all of these bots, they seemed cool at first, but I totally forgot about them after a few days 😂 

Some of them can be easily replaced by the community best practices we already have, like First Timers/Request Info (issue/PR templates), Reminders (codetriage)

But it wouldn't hurt to add some fun automation (polls, Unfurl Links) either 😄

**Comment by browniebroke** [comment]
Agree with @sfdye, these bots are good ideas, but not always helpful IMO. Our issues can remain open for a very long time, but that doesn't make them less valid. 

I've recently added a couple of Github action which are more flexible than Probot apps. These are helping with

- Generate the [list of contributors](https://github.com/pydanny/cookiecutter-django/blob/master/.github/workflows/update-contributors.yml)
- Generate [changelog by date](https://github.com/pydanny/cookiecutter-django/blob/master/.github/workflows/update-changelog.yml). Some actions exist for changelog, but they are more release based than date based as we want.
- [Release drafter](https://github.com/pydanny/cookiecutter-django/blob/master/.github/workflows/draft-release.yml) which create Github release as PR are merged.
- [Issue manager](https://github.com/tiangolo/issue-manager), which automatically closes issues tagged with a comment in the last message from certain people.

We can re-evaluate specific pieces as we see room for automation, I'm closing this old discussion for now.
