### ISSUE TITLE
not able to retrive namespace and name url in template

### ISSUE THREAD

**Issue by rahul6612** [pydanny/cookiecutter-django#1597]
**my main url is:**
`url(r'^posts/', include("posts.urls", namespace="posts")),`

**my app url is:**
`url(r'^(?P<pk>\d+)/update/$', PostUpdateView.as_view(), name='update'),`

i am trying to access it in my template like this:
` <small> <a href='{% url 'posts:update' %}'>***</a></small>`

**and getting this error:**
NoReverseMatch at /
Reverse for 'update' with no arguments not found. 1 pattern(s) tried: ['posts/(?P<pk>\\d+)/update/$']

**Comment by browniebroke** [comment]
Please read the issue template before opening an issue. It starts with:

> **Note: for support questions, please use the `cookiecutter-django` tag on stackoverflow**. This repository's issues are reserved for feature requests and bug reports. If you need quick professional paid support for your project, contact support@cookiecutter.io.

This is not a bug with cookie cutter template, you need to provide the primary key of the post you want to update as argument, for example: {% url 'posts:update' **1** %}

**Comment by rahul6612** [comment]
ok thanks

**Comment by browniebroke** [comment]
Correct, you need to replace the number `1` with a variable in your template context pointing at the post you want to update, it would be something like: `{% url 'posts:update' post.pk %}`.

https://docs.djangoproject.com/en/2.0/ref/templates/api/
