### ISSUE TITLE
support for django-storages / django AWS S3 media store on python3

### ISSUE THREAD

**Issue by matheusjardimb** [pydanny/cookiecutter-django#161]
Hello there,

I've been watching this repo for a while and you guys are doing a great job! :smile: 

What you think about this idea:
I've followed this post (https://ashokfernandez.wordpress.com/2014/03/11/deploying-a-django-app-to-amazon-aws-with-nginx-gunicorn-git/) and now I'm able to create as many ec2 instances as I want with one single command and make my project use RDS and S3. 

The problem is: this setup relies on djang-storages which is not supporting py3 yet. That's why I'm facing problems to upload files into S3. 

My point is: do you consider using S3 in this setup? The post I mentioned is a great starting point. And, if so, I'd be very insterested in a solution that works in a py3 env.

Great project!

**Comment by theskumar** [comment]
This should be addressed after we wrap up #186
