### ISSUE TITLE
Removing Bootstrap

### ISSUE THREAD

**Issue by ACPK** [pydanny/cookiecutter-django#1616]
How would I load bootstrap.js from being included on Heroku?

**Comment by luzfcb** [comment]
I do not know if I could understand your question, but
js files, should be included in base.html , like:

https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/templates/base.html#L106

For css and js files to work on heroku, you must set environment variables to use Amazon S3, or have chosen to use [whitenoise](http://whitenoise.evans.io/en/stable/] when you generated the project.

That said, the title of your question, and the content of it is very vague.
I can recommend reading these two links:

http://www.catb.org/esr/faqs/smart-questions.html

http://sscce.org/
