### ISSUE TITLE
Feature Request: pipenv

### ISSUE THREAD

**Issue by ppython** [pydanny/cookiecutter-django#1621]
Why not offer a solution for user using [pipenv](https://docs.pipenv.org/)?

**Comment by luzfcb** [comment]
This questioning was answered in https://github.com/pydanny/cookiecutter-django/issues/1425#issuecomment-355601470

if anything in relation to this has changed in pipenv, feel free to reopen the issue .

Having said that, I recently met another option that seems interesting too.

https://github.com/sdispater/poetry

**Comment by ppython** [comment]
Thanks for the follow-up!
