### ISSUE TITLE
In production Caddy is throwing duplicate address error 

### ISSUE THREAD

**Issue by venkat0708** [pydanny/cookiecutter-django#1622]
**Note: for support questions, please use the `cookiecutter-django` tag on stackoverflow**. This repository's issues are reserved for feature requests and bug reports. If you need quick professional paid support for your project, contact support@cookiecutter.io.

caddy env file:

# Caddy
# ------------------------------------------------------------------------------
DOMAIN_NAME=balajidigitals.in

caddy production config

www.{$DOMAIN_NAME} {
    redir https://balajidigitals.in
}

{$DOMAIN_NAME} {
    proxy / django:5000 {
        header_upstream Host {host}
        header_upstream X-Real-IP {remote}
        header_upstream X-Forwarded-Proto {scheme}
    }
    log stdout
    errors stdout
    gzip
}

Here is the error:
caddy_1         | 2018/04/26 00:15:44 duplicate site address: balajidigitals.in

**Comment by venkat0708** [comment]
When I built it again and fired it up it worked

**Comment by browniebroke** [comment]
Closing as we've migrated away from Caddy to Traefik (#1714).
