### ISSUE TITLE
Unable to restore the database in docker version

### ISSUE THREAD

**Issue by venkat0708** [pydanny/cookiecutter-django#1623]
**Note: for support questions, please use the `cookiecutter-django` tag on stackoverflow**. This repository's issues are reserved for feature requests and bug reports. If you need quick professional paid support for your project, contact support@cookiecutter.io.

* **I'm submitting a ... **
  - [* ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
report bug

* **What is the current behavior?**
```
INFO: Dropping all connections to the database...
psql: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?


```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
when I ran the following command
 sudo docker-compose -f local.yml run --rm postgres restore  her.sql.gz
instead of restoring the db I got the above error

* **What is the expected behavior?**
restore should have taken place normally

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
Docker version of the project

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by webyneter** [comment]
Reproduced the issue: it has to do with `sudo` execution priviliges; the below has worked [as expected](https://cookiecutter-django.readthedocs.io/en/latest/docker-postgres-backups.html), however, the docs do need to be fixed:

```bash
cookiecutter https://github.com/pydanny/cookiecutter-django --overwrite-if-exists --no-input project_slug=test use_docker=y
docker-compose -f local.yml build
docker-compose -f local.yml up -d
docker-compose -f local.yml exec postgres backup
docker-compose -f local.yml exec postgres restore <backup filename>
```
