### ISSUE TITLE
Deploy To Dokku not work

### ISSUE THREAD

**Issue by chayutzee** [pydanny/cookiecutter-django#164]
I'm Zee . I'm newbie in django . 
my problem is when I try to use cookiecutter-django with dokku 

notting error but can't open site 

# this is my config 

DATABASE_URL:                   postgres://root:JS1IZcVlrtphxvri@xxxxxxxxxx/db
DJANGO_AWS_ACCESS_KEY_ID:       XXXXXXXXXXXXXXXXXX
DJANGO_AWS_SECRET_ACCESS_KEY:   XXXXXXXXXXXXXXXXXXXXXXX
DJANGO_AWS_STORAGE_BUCKET_NAME: xxxxxxxxx
DJANGO_CONFIGURATION:           Production
DJANGO_SECRET_KEY:              XXXXXXXXXXXXXXXXXXXXXXXXXXXX
MEMCACHE_SCHEME:                memcached://127.17.0.19:11211
SENDGRID_PASSWORD:              XXXXXX
SENDGRID_USERNAME:              XXXXX

# this is my docker ps 

CONTAINER ID        IMAGE                                    COMMAND                CREATED             STATUS              PORTS                     NAMES
b498a10b90f7        dokku/repo_ohizee:latest                 "/bin/bash -c '/star   4 minutes ago       Up 4 minutes        0.0.0.0:49169->5000/tcp   sick_elion                        
f3601e94b735        postgresql/repo_ohizee-postgres:latest   "/usr/bin/start_pgsq   39 minutes ago      Up 39 minutes       0.0.0.0:49157->5432/tcp   nostalgic_yonath                  
62bce341d64e        jlachowski/memcached:latest              "/usr/bin/memcached    42 minutes ago      Up 42 minutes       11211/tcp                 memcached_repo_ohizee-memcached 

Everything look good but when i try to connect to : 128.199.xxx.xx:49169
![screen shot 2557-12-12 at 8 56 06 pm](https://cloud.githubusercontent.com/assets/1681564/5412694/9b942204-8241-11e4-9971-9ea418b5adb2.png)

### This is my dokku version : v0.3.7-25-g7d8ec62

Please Helppp T^T

**Comment by pydanny** [comment]
Is this resolved? Can I close this issue?
