### ISSUE TITLE
no module named debug_toolbar at celery containers at docker-compose -f production.yml up

### ISSUE THREAD

**Issue by scripterkaran** [pydanny/cookiecutter-django#1643]
**Note: for support questions, please use the `cookiecutter-django` tag on stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**

Using docker and celery, the celerybeat and celeryworker containers uses `config.settings.local` DJANGO_SETTINGS_MODULE , which basically loads wrong settings. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

Create a new project and enable docker and celery usage. 
Run the project in production mode (docker-compose -f production.yml up) 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

Docker env 
Django 2.0.3 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I checked the envs of each containers line by line. Then I found out that DJANGO_SETTINGS_MODULE is not set for both celeryworker and celerybeat, which was falling back to `conf.settings.local`

I'll attach a PR for this. My solution is to add `./.envs/.production/.django` to both celery env file of production.yml

**Comment by webyneter** [comment]
@scripterkaran thank you for pointing this out! And don't forget to add yourself to `CONTRIBUTORS` if that'll be your first time PRing here.

**Comment by scripterkaran** [comment]
I think this has been taken care of in 34673ff686e346bd4bf63c7fff7007ffb634d06c on 8th April. 
I had a 7th April version of django-cookiecutter. @webyneter

**Comment by webyneter** [comment]
@scripterkaran I did take care of that already, ineed :)
