### ISSUE TITLE
Don't migrate during Heroku release phase

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1646]
[Release Phase, Design considerations](https://devcenter.heroku.com/articles/release-phase#design-considerations):
> If you perform a database migration, you should always use transactions. A transaction ensures that all migration operations are successful before committing changes to the database. This minimizes the possibility of a failed partial migration during release phase. If a database migration fails during release phase (i.e., the migration command exits with a non-zero status), your new release will not be deployed. If transactions were not used, this can leave your database in a partially migrated state. **We suggest using heroku run, rather than release phase, to correct your schema/data**.

**Comment by browniebroke** [comment]
Yea, also I think it's broken when deploying the app the first time.

**Comment by mcastle** [comment]
Good point, esp for projects using neither PostgreSQL nor SQLite (django migrations for these db's run inside a transaction by default... https://docs.djangoproject.com/en/2.0/howto/writing-migrations/#non-atomic-migrations).
