### ISSUE TITLE
pycharm configuration is not working properly(windows+docker)

### ISSUE THREAD

**Issue by shlomikushchi** [pydanny/cookiecutter-django#1647]
* **I'm submitting a ... **
  - [x ] bug report**s**
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
report bugs

* **What is the current behavior?**
**for version > 2**
1. .env files are not read by pycharm run configurations - result, can't run django project in pycharm (relevant in version 2)
2. docker container settings inside the Pycharm Run/Debug configuration still maps `/opt/project` instead of newly used `/app` folder
3. docker container settings inside the Pycharm Run/Debug configuration points to network `bridge`
   instead of `projectname_default` which is the docker compose default network for running projects
4. psycopg2 package is missing in dev/local requirements file. I still want to work with postgres in dev mode.
***for version 1.11.10***
5. database configuration is defaulted to : 
```
DATABASES = {
    'default': env.db('DATABASE_URL', default='postgres://localhost/test1'),
}
```
while it should be defaulted to something like
```
DATABASES = {u'default':
    {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'HOST': 'postgres',
        'NAME': 'postgres',
        'PASSWORD': '',
        'PORT': 5432,  
        'USER': 'postgres'
    }
}
```

*****note: all is for windows + docker + pycharm configuration

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
I'm using a windows machine but run everything inside docker

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by webyneter** [comment]
What was the latest version of Cookiecutter Django you used to generate a project?

**Comment by shlomikushchi** [comment]
sorry.. I tried these 2:
2.0.2
1.11.10

**Comment by shlomikushchi** [comment]
also `ALLOWED_HOST` are not configured in v1.11.10 for local dev..

**Comment by webyneter** [comment]
@shlomikushchi if you were referring to the Cookiecutter Django tag versions, I should let you know that we don't provide any backward compatibility support for previous version, meaning, there's one and only one "true" (referential if you wish) edition -- the latest one, as by the latest commit.
