### ISSUE TITLE
Add documentation for Deployment in Docker in Detach Mode

### ISSUE THREAD

**Issue by emilepetrone** [pydanny/cookiecutter-django#1650]
* **I'm submitting a ...**
 
Feature request

* **Do you want to request a *feature* or report a *bug*?**

I'm requesting adding 2 lines for added documentation to the "Deployment with Docker" page. 

* **What is the current behavior?**

Right now the  page has instructions for deploying with Docker, but those instructions will not detach the image. That means you deploy the image with it running in your terminal. This is not a bug, but for new Docker users, it is not the expected experience.

(I realize this is an issue more with knowledge of Docker/Docker-compose than Cookiecutter, but it took me hours to hunt down the solution and figure this small change will be helpful for others.)

* **What is the expected behavior?**

As a new Docker user, I expected 'build up' to deploy the image and then present me with a new command prompt. Instead, Docker builds the image and leaves the services running. For those more experienced with Docker, I am sure it is fine. For novices, it is something I spent many hours trying to understand and debug.

* **What is the motivation / use case for changing the behavior?**

My motivation is to save others time by adding 2 lines to the documentation. Specifically:

```
To run the stack and detach the containers, run::

    docker-compose -f production.yml up -d
```

I tried to push a branch and create a PR, but realized there are now privileges to the repo.

**Comment by sfdye** [comment]
Makes sense. You can push the branch on your fork, not this repo, then create the PR.

**Comment by browniebroke** [comment]
Thanks for the suggestion!
