### ISSUE TITLE
Management commands when using docker

### ISSUE THREAD

**Issue by saschalalala** [pydanny/cookiecutter-django#1656]
**Note: for support questions, please use the `cookiecutter-django` tag on stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

As far as I know, using this project template with docker enabled makes it quite annoying to execute management commands from the command line (perhaps I am doing it wrong). What I saw me doing instead of `./manage.py <whatever>` was `docker-compose -f local.yml run django python manage.py <whatever>`

* **What is the expected behavior?**

Independent of shell completion, aliases etc., I would like to be able to just do single command management actions when using docker, so I created a really simple bash script called `manage.sh` which is located in my project root next to the `manage.py` file with just the following content:

```bash
#!/bin/bash

docker-compose -f local.yml run django python manage.py $@
```

* **What is the motivation / use case for changing the behavior?**

Now you can call `./manage.sh makemigrations` inside your docker-compose setup. Is that something that would be benefical to others? If yes, I could have a look at how to integrate a file like this depending on the project setup.

* **Please tell us about your environment:**

Python3.6, Docker

**Comment by e-ht** [comment]
A more general solution would be to use a Docker explorer. Most code editors have plugins that support easy viewing and command/shell access.

A plugin example in VSCode: 
![docker-explorer](https://user-images.githubusercontent.com/1045813/40752883-6548b78a-6426-11e8-81d0-f597bc5ffb78.png)

Right click shell access/starts/stops/removes, etc.

**Comment by pydanny** [comment]
Some of us prefer to use the command-line, so I like the original submission

**Comment by webyneter** [comment]
Not sure if we need that extra layer of abstraction...

**Comment by global2alex** [comment]
The migration step happens every time you bring up, or take down docker. If you really want shell access, just run `docker exec -it <Name of the running container> sh` and you have a shell into your running docker container. You can do all the things you want from the command line. 
For example: `docker exec -it polls_django_1 sh` will give you the shell. 
If you'd rather have bash, just install it from the shell with `apt-get`, `yum`, `dnf`, `apk`, whatever the linux distro you have... When you exec, you are actually changing the image, it will be saved when you bring up the image again. But be cautious, if you break your image and can't bring it up with docker-compose anymore, you will have to rebuild it.

Docker has many tools, I too think getting a shell like this is a far better option over adding another layer of abstraction like @webyneter said.

**Comment by saschalalala** [comment]
@global2alex Yeah, I understand what you are saying. Nevertheless, I quite often do things in a running docker container during development, even migrations etc. and I prefer doing so from my local shell, e.g. for command history purposes. But I understand why this seems to be a not so common use case so I'll stick with adding this file in my projects ;) 

And adding it with cli option seems to be quite overkill and just an unnecessary question more to ask during setup. Thanks for your feedback everyone, I'll close this one then.
