### ISSUE TITLE
Update README, use cookiecutter -c to install latest tagged version

### ISSUE THREAD

**Issue by msaizar** [pydanny/cookiecutter-django#1660]
**Note: for support questions, please use the `cookiecutter-django` tag on stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Request a feature

* **What is the current behavior?**

Documentation recommends installing like: `cookiecutter https://github.com/pydanny/cookiecutter-django`
Master builds can sometimes fail, pinning to tags like: `cookiecutter -c 2.0.2 https://github.com/pydanny/cookiecutter-django` might be a better way to go

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by webyneter** [comment]
@msaizar we encourage the use of master builds whereas tags are there for historical reference only: we want our users to stay up-to-date with the latest version of Cookiecutter Django, its features, improvements, and bug fixes. What's more, we don't maintain bacward compatibility across `master` commits. Our `master` branch build status is "Success"ful most often than not.
