### ISSUE TITLE
Database authentication fails with Docker

### ISSUE THREAD

**Issue by emilepetrone** [pydanny/cookiecutter-django#1672]
## What happened?
Postgres authentication fails after initial setup for a Cookiecutter project using Docker. 
- encountered locally & in production on Digital Ocean droplets (multiple)
- In current cookiecutter release and older versions over the last few weeks

The error:

```
postgres_1      | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1      | 2018-06-03 16:19:08.175 UTC [39] FATAL:  password authentication failed for user "xxx"
postgres_1      | 2018-06-03 16:19:08.175 UTC [39] DETAIL:  Password does not match for user "xxx".
```

I had this first happen in production, and I thought it was something I had done. I tried to resolve it in multiple ways in prod from setting up new droplets, updating different packages, trying many different solutions but without any success.

To debug it further this morning, I set up a fresh cookiecutter project, and decided to deploy that to Digital Ocean. I did not change anything other than the `ALLOWED_HOSTS` and `DJANGO_SENTRY_DSN` settings.

When trying to `build` and `up` locally, this error popped up for the first time on my local machine.

For context, this error was mentioned in one [stackoverflow post](https://stackoverflow.com/questions/50103437/password-authentication-failed-for-user-when-using-new-docker-compose/50106300#50106300) a few months ago. The answer from @webyneter  works locally, however in production, it seems like a bad idea to kill the data volume that you want to persist.

## What should've happened instead?

There shouldn't be authentication errors to your database when the values are stored in the .env files for either local or production development. 

## Steps to reproduce

* Set up a project with docker
* `build` and `up`
* Try making a change, and then `build` and `up` (Make sure you are not in `-d` detached mode as the error will not appear
* Result should be hundreds of lines of:

```
django_1        | Waiting for PostgreSQL to become available...
django_1        | Waiting for PostgreSQL to become available...
django_1        | Waiting for PostgreSQL to become available...
django_1        | Waiting for PostgreSQL to become available...
celeryworker_1  | Waiting for PostgreSQL to become available...
postgres_1      | 2018-06-03 16:19:02.895 UTC [28] FATAL:  password authentication failed for user "xxxxx"
postgres_1      | 2018-06-03 16:19:02.895 UTC [28] DETAIL:  Password does not match for user "xxxxx".
postgres_1      | 	Connection matched pg_hba.conf line 95: "host all all all md5"
celerybeat_1    | Waiting for PostgreSQL to become available...
postgres_1      | 2018-06-03 16:19:04.200 UTC [29] FATAL:  password authentication failed for user "xxxxx"
postgres_1      | 2018-06-03 16:19:04.200 UTC [29] DETAIL:  Password does not match for user "xxxxx".
postgres_1      | 	Connection matched pg_hba.conf line 95: "host all all all md5"
django_1        | Waiting for PostgreSQL to become available...
postgres_1      | 2018-06-03 16:19:04.207 UTC [30] FATAL:  password authentication failed for user "xxxxx"
postgres_1      | 2018-06-03 16:19:04.207 UTC [30] DETAIL:  Password does not match for user "xxxxx".
postgres_1      | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1      | 2018-06-03 16:19:04.217 UTC [31] FATAL:  password authentication failed for user "xxxxx"
postgres_1      | 2018-06-03 16:19:04.217 UTC [31] DETAIL:  Password does not match for user "xxxxx".
postgres_1      | 	Connection matched pg_hba.conf line 95: "host all all all md5"
celeryworker_1  | Waiting for PostgreSQL to become available...
django_1        | Waiting for PostgreSQL to become available...
celerybeat_1    | Waiting for PostgreSQL to become available...
```

[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)

I've now encountered this on older cookiecutter versions and the current version as well.

```
Docker version: Version 18.03.1-ce-mac65 (24312)
FROM python:3.6-alpine
```

[//]: # (* Project generation options)

docker: Y
celery: Y
sentry: Y

**Comment by emilepetrone** [comment]
I'm not sure if this is related or not, but I've also run into situations where I've had celery tasks run that create new objects. The symptoms are:

* Celery task runs, creates new objects
* Logs reflect task running
* Look in /admin and the objects are not there

When I run `docker-compose -f production.yml run --rm django python manage.py shell`, I am able to query these objects that are present within the DB shell is referencing. 

Basically I've seen a few different very odd behaviors from Cookiecutter & Docker. Almost like there are multiple data volumes when I wouldn't expect there to be. Without any ENV or settings changes, that is my only (hypothetical) explanation why the database authentication would fail after setting up a DB, and why objects would be created but not present when I try to access them via the /admin.  

However this seems like a crazy theory and that brings me back to the start, and trying to just launch a project that I made minimal alterations to.

**Comment by webyneter** [comment]
@emilepetrone thank you for reporting.
To clarify, every time you re-generate the project with Cookiecutter Django `POSTGRES_USER` and `POSTGRES_PASSWORD` are set to randomly-generated values (see our `hooks/post_gen_project.py` for implementation details) unless `debug` option is `y` since in that case those envs will always be `debug`:`debug` across setups.
With that in mind, my hypothesis would be that you production setup's `postgres` instance user:password are still the ones you had upon first-time project creation effectively persisted within the database's volumes.

**Comment by emilepetrone** [comment]
> To clarify, every time you re-generate the project with Cookiecutter Django POSTGRES_USER and POSTGRES_PASSWORD are set to randomly-generated values (see our hooks/post_gen_project.py for implementation details) unless debug option is y since in that case those envs will always be debug:debug across setups.

@webyneter Thanks for the fast reply. I saw that mentioned in the SO answer, but that confused me. Why would you want to create a random `POSTGRES_USER` & `POSTGRES_PASSWORD` each time? It would seem that, since the DB should be in a persistent data volume, that you'd want the user & password, to remain the same so that it could be authenticated. I think I am missing something.

Thanks again for taking the time to reply.

**Comment by webyneter** [comment]
@emilepetrone 
1. so that we ensure a healthy degree of entropy for each and everyone of our users;
2. when you "re-generate" the project it remains *another* project generated from blank slate, with its own set of cookiecutter options.

**Comment by webyneter** [comment]
Should you like changing some of the envs you do so with your project instance. The scenario where you'd have PostgreSQL user credentials changed is to be resolved by that specific project's maintainer which we generally have nothing to do with.
Provided you really want to change the by-default generated postgres credentials feel free to create a new user manually and grant him permissions to the database manually.

**Comment by webyneter** [comment]
> Why would you want to create a random POSTGRES_USER & POSTGRES_PASSWORD each time?
The credentials are always unique *among consequtive Cookiecutter Django-based project setups*, but ones they're set they persist in *your*, mine or any other user's project instance.

**Comment by emilepetrone** [comment]
> The credentials are always unique across consequtive Cookiecutter Django-based project setups, but ones they're set they persist in your, mine or any other user's project instance.

Right, after they are generated, I leave them alone in my .envs directory. 

> With that in mind, my hypothesis would be that you production setup's postgres instance user:password are still the ones you had upon first-time project creation effectively persisted within the database's volumes.

This is what I want, but am confused when the authentication error appears upon `up` with an updated image.  As the image is built with the .envs credentials, I would expect the image to be able to authenticate into the DB in the Docker data volume. 

Just to make sure we are talking about the same thing - 
* I 100% agree and understand why the unique values are generated upon project creation 
* My issue is after project creation, when deploying an updated image, the DB authentication fails when the credentials are the same as they were when the project was originally created

**Comment by global2alex** [comment]
@emilepetrone What do you mean exactly by `via newly built images`

**Comment by webyneter** [comment]
@emilepetrone did you use `merge_production_dotenvs_in_dotenv.py` from your project directory to combine `.envs/.production/*` into `.env`?

**Comment by webyneter** [comment]
@emilepetrone by the way, you might've noticed `.*` (therefore, `.envs` etc. except for `.env`) are ommited from any of the resulting images through `.dockerignore`.

**Comment by emilepetrone** [comment]
@webyneter I wasn't using `merge_production_dotenvs_in_dotenv.py` but thinking that since the DockerFiles reference the environmental files, then that is what would be used in the building of those images. 

@global2alex  like the following. I just ran:

```
python merge_production_dotenvs_in_dotenv.py
docker-compose -f production.yml build --no-cache
docker-compose -f production.yml up

```
The result was again:

```
postgres_1      | 2018-06-03 20:45:19.645 UTC [110] FATAL:  password authentication failed for user "xxxxxx"
postgres_1      | 2018-06-03 20:45:19.645 UTC [110] DETAIL:  Password does not match for user "xxxxxx".
postgres_1      | 	Connection matched pg_hba.conf line 95: "host all all all md5"
celerybeat_1    | Waiting for PostgreSQL to become available...
postgres_1      | 2018-06-03 20:45:19.992 UTC [111] FATAL:  password authentication failed for user "xxxxxx"
postgres_1      | 2018-06-03 20:45:19.992 UTC [111] DETAIL:  Password does not match for user "xxxxxx".
postgres_1      | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1      | 2018-06-03 20:45:19.993 UTC [112] FATAL:  password authentication failed for user "xxxxxx"
postgres_1      | 2018-06-03 20:45:19.993 UTC [112] DETAIL:  Password does not match for user "xxxxxx".
postgres_1      | 	Connection matched pg_hba.conf line 95: "host all all all md5"
```

**Comment by global2alex** [comment]
@emilepetrone I cant recreate the issue. Are you sure postgres credentials weren't accidentally/erroneously added to the django env file? Is there a typo somewhere?  
- Check for differences between the local postgres and the production postgres. 
- Try to login to the running postgres with any of the credentials. `psql -h <psql host or ip address> -U <db username> -p <port>` ... You'll be prompted for the password or just add it, i think that's `-p`? Find what the correct ones are, and then find the ones you are using.

**Comment by webyneter** [comment]
@emilepetrone 

> thinking that since the DockerFiles reference the environmental files, then that is what would be used in the building of those images

It doesn't matter whether or not specific files are *referenced* in your code -- if you haven't got those in the container filesystem by the time it starts, should they come from the underlying image or be copied to the running container directly it won't work. Make sure you've got `.env` there.

**Comment by emilepetrone** [comment]
@global2alex thanks for trying. This must be tied to not producing the `.env` file like @webyneter is advising. 
Thank you all for your help. I will keep working on it as it must be on my end.

**Comment by emilepetrone** [comment]
@global2alex when you tested this, did you:

- make changes
- build new image
- up

The reason I ask, I got hit with this again today. My `envs` have not changed, I generated the `.env` file with `merge_production_dotenvs_in_dotenv.py` as @webyneter advised, and that is when I found a few things interesting.

So I did the following:
`docker-compose -f production.yml exec postgres psql -U <my_pg_user>`  - it could not find the user
`docker-compose -f production.yml exec postgres psql -U postgres`  - and it did find the `postgres` user

The databases within the `postgres` service did not follow my `.env`. The `POSTGRES_DB`  & `POSTGRES_USER` were not the name defined in `.env` or `.envs/.production/.postgres` 

So it appears:
- The first time I `docker-compose -f production.yml up` to my Digital Ocean Droplet, it will follow my `.env` as I do not get an authentication error
- Subsequent times, I can get the authentication error as the `POSTGRES_DB`  & `POSTGRES_USER` are not used. 

To verify:
- My celery tasks just ran, and the data is not shown when I hit my production Admin pages. 
- However the logs show the tasks ran successfully without errors.

Something odd is definitely happening.

**Comment by emilepetrone** [comment]
Making progress - upon running build, postgres is actually defaulting to user `postgres` 

```
(bla) Emiles-MBP:bla emile$ docker-compose -f production.yml up
Creating network "bla_default" with the default driver
Creating volume "bla_postgres_data" with default driver
Creating volume "bla_postgres_backup" with default driver
Creating volume "bla_caddy" with default driver
Pulling redis (redis:3.2)...
3.2: Pulling from library/redis
4d0d76e05f3c: Pull complete
cfbf30a55ec9: Pull complete
82648e31640d: Pull complete
1d925e96c510: Pull complete
86679c1efcc4: Pull complete
5a287785a075: Pull complete
Digest: sha256:08d54e5c3ef779601f8db9b8fa3c67dab235559501df2b3d7b29ad088cffd02a
Status: Downloaded newer image for redis:3.2
Creating bla_postgres_1 ... done
Creating bla_redis_1    ... done
Creating bla_celerybeat_1   ... done
Creating bla_celeryworker_1 ... done
Creating bla_django_1       ... done
Creating bla_caddy_1        ... done
Attaching to bla_postgres_1, bla_redis_1, bla_celerybeat_1, bla_django_1, bla_celeryworker_1, bla_caddy_1postgres_1      | The files belonging to this database system will be owned by user "postgres".
postgres_1      | The files belonging to this database system will be owned by user "postgres".
postgres_1      | This user must also own the server process.
postgres_1      |
postgres_1      | The database cluster will be initialized with locale "en_US.utf8".
postgres_1      | The default database encoding has accordingly been set to "UTF8".
postgres_1      | The default text search configuration will be set to "english".
postgres_1      |
postgres_1      | Data page checksums are disabled.
postgres_1      |
postgres_1      | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1      | creating subdirectories ... ok
redis_1         | 1:C 06 Jun 14:48:18.540 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
postgres_1      | selecting default max_connections ... 100
redis_1         |                 _._
redis_1         |            _.-``__ ''-._
redis_1         |       _.-``    `.  `_.  ''-._           Redis 3.2.11 (00000000/0) 64 bit
redis_1         |   .-`` .-```.  ```\/    _.,_ ''-._
redis_1         |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1         |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1         |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1         |   `-._    `-._  `-./  _.-'    _.-'
redis_1         |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1         |  |    `-._`-._        _.-'_.-'    |           http://redis.io
redis_1         |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1         |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1         |  |    `-._`-._        _.-'_.-'    |
redis_1         |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1         |       `-._    `-.__.-'    _.-'
redis_1         |           `-._        _.-'
redis_1         |               `-.__.-'
redis_1         |
postgres_1      | selecting default shared_buffers ... 128MB
redis_1         | 1:M 06 Jun 14:48:18.542 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1         | 1:M 06 Jun 14:48:18.543 # Server started, Redis version 3.2.11
redis_1         | 1:M 06 Jun 14:48:18.543 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
postgres_1      | selecting dynamic shared memory implementation ... posix
redis_1         | 1:M 06 Jun 14:48:18.543 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
postgres_1      | creating configuration files ... ok
postgres_1      | running bootstrap script ... ok
postgres_1      | performing post-bootstrap initialization ... ok
postgres_1      | syncing data to disk ... ok
postgres_1      |
postgres_1      | WARNING: enabling "trust" authentication for local connections
postgres_1      | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1      | --auth-local and --auth-host, the next time you run initdb.
postgres_1      |
postgres_1      | Success. You can now start the database server using:
postgres_1      |
postgres_1      |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1      |
postgres_1      | waiting for server to start....2018-06-06 14:48:21.563 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1      | 2018-06-06 14:48:21.576 UTC [37] LOG:  database system was shut down at 2018-06-06 14:48:21 UTC
postgres_1      | 2018-06-06 14:48:21.581 UTC [36] LOG:  database system is ready to accept connections
postgres_1      |  done
postgres_1      | server started
postgres_1      | CREATE DATABASE
postgres_1      |
postgres_1      | CREATE ROLE
postgres_1      |
postgres_1      |
postgres_1      | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1      |
postgres_1      | 2018-06-06 14:48:22.305 UTC [36] LOG:  received fast shutdown request
postgres_1      | 2018-06-06 14:48:22.307 UTC [36] LOG:  aborting any active transactions
postgres_1      | 2018-06-06 14:48:22.329 UTC [36] LOG:  worker process: logical replication launcher (PID 43) exited with exit code 1
postgres_1      | 2018-06-06 14:48:22.338 UTC [38] LOG:  shutting down
postgres_1      | waiting for server to shut down....2018-06-06 14:48:22.348 UTC [36] LOG:  database system is shut down
caddy_1         | Activating privacy features...
caddy_1         | Your sites will be served over HTTPS automatically using Let's Encrypt.
caddy_1         | By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
caddy_1         |   https://acme-v01.api.letsencrypt.org/terms
caddy_1         | Please enter your email address so you can recover your account if needed.
caddy_1         | You can leave it blank, but you'll lose the ability to recover your account.
postgres_1      |  done
postgres_1      | server stopped
postgres_1      |
postgres_1      | PostgreSQL init process complete; ready for start up.
postgres_1      |
postgres_1      | 2018-06-06 14:48:22.490 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1      | 2018-06-06 14:48:22.491 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1      | 2018-06-06 14:48:22.493 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1      | 2018-06-06 14:48:22.546 UTC [63] LOG:  database system was shut down at 2018-06-06 14:48:22 UTC
django_1        | PostgreSQL is unavailable (sleeping)...
celerybeat_1    | PostgreSQL is unavailable (sleeping)...
caddy_1         | Email address: 2018/06/06 14:48:22 [INFO] acme: Registering account for
caddy_1         | 2018/06/06 14:48:23 [INFO][www.bla.com] acme: Obtaining bundled SAN certificate
caddy_1         | 2018/06/06 14:48:23 [INFO][www.bla.com] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/opg1gjrwf38fxmoFK3QvI_T5NxosdBy0kMceRsXNVyk
celeryworker_1  | PostgreSQL is unavailable (sleeping)...
caddy_1         | 2018/06/06 14:48:23 [INFO][www.bla.com] acme: Trying to solve HTTP-01
celerybeat_1    | PostgreSQL is up - continuing...
```

**Comment by emilepetrone** [comment]
I'm going to close this again. I've been testing all morning and it seems to be ok right now. I'm not sure if it's my connection, something getting corrupted, or what.

**Comment by kentrosi** [comment]
It could be many things, but i’m really guessing at what it could be because I don’t have the same issue. Maybe it’s referencing the older Postgres image volume somehow? Glad you solved it!

**Comment by emilepetrone** [comment]
Ok I've nailed it down.

* If I open a new terminal and `up` without setting `eval $(docker-machine env <name>)`, then `up` goes to somewhere unknown. **Does anyone understand this?**
* If I run `eval` and then `up`, it deploys properly to the production machine / Digital Ocean droplet

**How I can see this:**
* If I do not run `eval` and enter the Postgres CLI, I  can see objects that are not accessible via my web admin.
* The command: `docker-compose -f production.yml exec postgres psql -d <db_name> -U <db_user>`


**Questions:**
* If you run `up` without setting the docker-machine environment, where is it deploying to?
* Does this make sense? 

Thank you again to everyone for your help. This took much longer than expected but at least I've nailed it down.

**Comment by ExpertNET** [comment]
I propose you do the following if you understand the implications of these commands. 

POTENTIALLY DANGEROUS COMMANDS:

stop all containers:
docker kill $(docker ps -q)

remove all containers
docker rm $(docker ps -a -q)

remove all docker images
docker rmi $(docker images -q)

**Comment by webyneter** [comment]
@ExpertNET I'd suggest [`docker system prune`](https://docs.docker.com/engine/reference/commandline/system_prune/) instead -- this would be the eqivalent of what you're proposing:

```bash
# Being picky:
docker stop $(docker ps -q -f "label=<some label your target containers share>")
# or, feeling dangerous:
docker stop $(docker ps -q)

docker system prune --all
```
