### ISSUE TITLE
Celery not finding tasks defined in apps tasks.py module using shared_task decorator

### ISSUE THREAD

**Issue by github-account-because-they-want-it** [pydanny/cookiecutter-django#1681]
## What happened?

I had this issue in my cookiecutter-django based project so I tried to replicate it in a new and simple cookiecutter project and the same issue happened there as well.

I have this in my `users/tasks.py`:
```
from celery import shared_task
@shared_task
def do_stuff():
    return 42
```

When I run the celery worker, the `@shared_task` decorated task does not show under the `[tasks]` tag in the logs. The one defined by default in `celery.py` using `@app.task` shows, though.

## What should've happened instead?

The task defined using `shared_task` decorator should list under registered tasks as well.

## Steps to reproduce

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Project generation options)

use_celery: True
[//]: # (* Logs)
```
---- **** -----
--- * ***  * -- Windows-10-10.0.17134-SP0 2018-06-14 18:30:58
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         celery_cookie_cutter:0x42fb7d0
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 6 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[tasks]
  . celery_cookie_cutter.taskapp.celery.debug_task

[2018-06-14 18:30:58,787: INFO/SpawnPoolWorker-1] child process 22428 calling self.run()
```

**Comment by browniebroke** [comment]
Could you try to import the `tasks` module in the [app config's `ready()` method](https://github.com/pydanny/cookiecutter-django/blob/75c423c88e2f5eb3038517314e81315c6fb7c6d3/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/users/apps.py#L8-L16)? Like the `signals` module is imported...

**Comment by browniebroke** [comment]
I tried to generate a project and [reproduce the problem](https://github.com/browniebroke/celery-shared-task-debugging/commit/9b16cff721c6e9c49bcf0827df30552281ed21f0), but it seems to work on my end:

```
celeryworker_1  |
celeryworker_1  |  -------------- celery@4cd6a7239dd2 v3.1.25 (Cipater)
celeryworker_1  | ---- **** -----
celeryworker_1  | --- * ***  * -- Linux-4.9.87-linuxkit-aufs-x86_64-with
celeryworker_1  | -- * - **** ---
celeryworker_1  | - ** ---------- [config]
celeryworker_1  | - ** ---------- .> app:         my_awesome_project:0x7f69bd4eb860
celeryworker_1  | - ** ---------- .> transport:   redis://redis:6379/0
celeryworker_1  | - ** ---------- .> results:     redis://redis:6379/0
celeryworker_1  | - *** --- * --- .> concurrency: 4 (prefork)
celeryworker_1  | -- ******* ----
celeryworker_1  | --- ***** ----- [queues]
celeryworker_1  |  -------------- .> celery           exchange=celery(direct) key=celery
celeryworker_1  |
celeryworker_1  |
celeryworker_1  | [tasks]
celeryworker_1  |   . my_awesome_project.taskapp.celery.debug_task
celeryworker_1  |   . my_awesome_project.users.tasks.do_stuff
```

Could you share a project showing with the problem? I see you are on Windows 10, is that right? Finally, could you please confirm the version of Celery you're using?

**Comment by github-account-because-they-want-it** [comment]
Thanks @browniebroke . I cloned your project and then I found that when I downgrade my celery down to the project's `3.1.25` vs. mine _latest and greatest_ `4.1.1` the tasks are registered. I'm closing this now as it's not strictly related to cookiecutter anymore but if you have more information about why recent celery doesn't work that'd be appreciated.

**Comment by ArtemBernatskyy** [comment]
@github-account-because-they-want-it you need to reload `celeryworker` to register task.
