### ISSUE TITLE
Default Postgres Version to 9.6

### ISSUE THREAD

**Issue by jeffshek** [pydanny/cookiecutter-django#1686]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)

One unique thing that came up using this was I selected Postgres 10, not fully cognizant of the latest version AWS/GCP support. The latest version AWS and GCP currently support is 9.6, Azure is 10.3. Would it useful to have the default be 9.6? Or have some kind of note?

## Rationale

[//]: # (Why should this feature be implemented?)
Maybe I'm wrong, but I imagine most users swap out settings for a production RDS once they're ready to go live? So it's slightly annoying to know you have a mismatch of Postgres versions between locally and production.

I don't mind making the PR if this is given the go-ahead!

**Comment by browniebroke** [comment]
It looks like [AWS supports Postgres 10](https://aws.amazon.com/about-aws/whats-new/2018/02/postgresql-10-now-supported-in-amazon-rds/). It's true that GCP [doesn't support Postgres 10](https://cloud.google.com/sql/docs/postgres/db-versions) yet. 

Not sure it's worth changing the default value, but if you feel like adding a note in the docs, you're welcome to send a pull request.

**Comment by webyneter** [comment]
@browniebroke https://console.cloud.google.com/marketplace/details/google/postgresql10 ?
