### ISSUE TITLE
Redis configuration in local django not needed (using Docker)

### ISSUE THREAD

**Issue by demestav** [pydanny/cookiecutter-django#1691]
In local environment, Redis is installed [only if you choose to use Celery](https://github.com/pydanny/cookiecutter-django/blob/5309fbf5e7135087f61f58bb2a940d92596e371b/%7B%7Bcookiecutter.project_slug%7D%7D/local.yml#L48). However, the [`.envs/.local/.django` file defines the Redis URL](https://github.com/pydanny/cookiecutter-django/blob/5309fbf5e7135087f61f58bb2a940d92596e371b/%7B%7Bcookiecutter.project_slug%7D%7D/.envs/.local/.django#L7). Is that referring to something else I am missing, or could it be removed?

**Comment by luzfcb** [comment]
@demestav Redis is also used for django caching
https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/production.py#L25

**Comment by webyneter** [comment]
@demestav Celery.

**Comment by webyneter** [comment]
Oh, @luzfcb was ahead on this :)

**Comment by demestav** [comment]
@luzfcb @webyneter I see. However, you are referring to production environment, while I was referring to the [local environment](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/local.py) where (maybe I am wrong?) the cache is memory based.

**Comment by webyneter** [comment]
@demestav oh, sure, `.django`'s `REDIS_URL` is supposed to be a conditional setting like the rest of Celery stack -- feel free to send a PR fixing this :)

**Comment by demestav** [comment]
@webyneter Sure!

**Comment by demestav** [comment]
Is [this line](https://github.com/pydanny/cookiecutter-django/blob/ee2bb3f2efef6add9a598597354ef5b3d3541f0b/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/django/entrypoint#L9) required in entrypoint?

- What if Celery is not used in production either?
- Can this association between Celery and Redis variable be moved in the .env file of the production?

**Comment by global2alex** [comment]
Can you post what configuration you used to create your cookie? @demestav

**Comment by global2alex** [comment]
@demestav Yes. Accuracy, reproducibility, future reference... or make a pull request!

**Comment by demestav** [comment]
@global2alex I used the default choices in most of them, except 'yes' to Docker and Celery.There is an open P.R. https://github.com/pydanny/cookiecutter-django/pull/1693
