### ISSUE TITLE
django <2.0

### ISSUE THREAD

**Issue by KingOlami** [pydanny/cookiecutter-django#1701]
I would like to know if there is a version compatible with django 1.11.x

**Comment by luzfcb** [comment]
no. This project is compatible only with django 2.0.x and Python 3.6

To previous version se the git tags

https://github.com/pydanny/cookiecutter-django/tree/1.11.10

**Comment by KingOlami** [comment]
how do I use pip to install this 1.11.10 version

**Comment by webyneter** [comment]
@KingOlami as by the [cookiecutter docs](https://cookiecutter.readthedocs.io/en/0.9.1/advanced_usage.html#cmdoption-c), 

```bash
cookiecutter --checkout 1.11.10 https://github.com/pydanny/cookiecutter-django/
```
