### ISSUE TITLE
Generate project's setup.py 

### ISSUE THREAD

**Issue by enomado** [pydanny/cookiecutter-django#1708]
## Rationale
https://lincolnloop.com/blog/using-setuppy-your-django-project/
https://docs.djangoproject.com/en/2.0/intro/reusable-apps/

**Comment by browniebroke** [comment]
Maybe I'm missing the point, but I'm not really convinced by the first article. 

The second link is not relevant to this project IMO as it's not a template to generate a reusable Django app, but to generate a whole Django project.
