### ISSUE TITLE
Docker image not building.

### ISSUE THREAD

**Issue by sebastian-code** [pydanny/cookiecutter-django#1710]
## What happened?
When building docker-compose image, fails with the following error:
```bash
ERROR: unsatisfiable constraints:
  openssl-dev-1.0.2o-r0:
    conflicts:
               libressl-dev-2.6.5-r0[pc:libcrypto=1.0.2o]
               libressl-dev-2.6.5-r0[pc:libssl=1.0.2o]
               libressl-dev-2.6.5-r0[pc:openssl=1.0.2o]
    satisfies: world[openssl-dev]
  libressl-dev-2.6.5-r0:
    conflicts:
               openssl-dev-1.0.2o-r0[pc:libcrypto=2.6.5]
               openssl-dev-1.0.2o-r0[pc:libssl=2.6.5]
               openssl-dev-1.0.2o-r0[pc:openssl=2.6.5]
    satisfies:
               postgresql-dev-10.4-r0[libressl-dev]
```
returning a `non-zero code: 3`

## What should've happened instead?

The docker-compose should have worked without problem.

## Steps to reproduce

Trying to build any of the docker-compose files.

## Additional info.

Looking for a solution, it looks than is related to a dependency constrain reported in gliderlabs/docker-alpine#303 

I was able to fix it deleting the library from the `Dockerfile`, but my docker skills are not that sharp and I'm not aware if that impacted somehow, but looks like it didn't.

**Comment by narnikgamarnikus** [comment]
I had a similar problem.
I managed to solve it by replacing `openssl-dev` with `libressl-dev` in `./compose/local/django/Dockerfile`

However, on another OS this problem arose again, and this time I decided to replace `libressl-dev` with `openssl-dev` back.

**Comment by MarkerDave** [comment]
I also had a similar problem, I can confirm that Narnikgamarnikus solution worked.

**Comment by sebastian-code** [comment]
You're right @browniebroke, there is no need for this anymore.
