### ISSUE TITLE
Adding support postgis

### ISSUE THREAD

**Issue by narnikgamarnikus** [pydanny/cookiecutter-django#1712]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)

It seems to me that it's worth asking users if they want to see the possibility of using `postgis` in this project. I tried to install `postgis` and` gdal`, but I did not succeed.

If I'm not mistaken, is it enough to find a good example of postgis on dockerhub, which is maintained for a long time so that it can be included in this project?

## Rationale

[//]: # (Why should this feature be implemented?)

Gis is one of the django apps that comes out of the box. This is the best geo framework from all that I've come across. I also think that cookiecutter is the best boilerplace for Django, so it would not be bad to unite them :)

**Comment by webyneter** [comment]
I've never used PostGIS in any of my previous production projects, and neither did the teams which I personally has been part of or which I know of -- I don't have expertise to seriously consider the proposal, yet to my mind introducing PostGIS dependency would make Cookiecutter Django maintenance burden way heavier than it used to be, especially in the light of potential hurdles your description indicates.
Maybe @pydanny, @jayfk, @luzfcb, @browniebroke, @sfdye have other thoughts?

**Comment by sfdye** [comment]
I also think supporting POSTGIS is outside of the scope of cookiecutter-django. If someone is interested, they can make always make a fork.

**Comment by luzfcb** [comment]
up to this date, I have not had any need to use postgis on any project. so for lack of long-term maintainer, I agree @sfdye, that this is outside the scope of cookiecutter-django, and may well live on a fork

**Comment by sww314** [comment]
I use the postgis and geo-django on most of my projects. The Django docker images requires a few mods to install the required libraries. 
I swap the Postgres image for this one: https://hub.docker.com/r/mdillon/postgis/
and this Dockerfile for Django. 
https://gist.github.com/sww314/4638d2605bc1400b000f7d1e73d3d793

**Comment by webyneter** [comment]
I believe @sww314's comment addresses this specific issue. However, we don't have plans to integrate PostGIS with our current project template in the foreseeable future.

**Comment by senderle** [comment]
The alpine linux GIS packages are all only on edge, and break frequently. After 48 hours of debugging ABI incompatibilities, I decided to just compile them myself. Here is the result, in case it is useful! This performs the first half of the work done in the [Dockerfile](https://gist.github.com/sww314/4638d2605bc1400b000f7d1e73d3d793) from @sww314. My local Django dockerfile now looks like [this](https://gist.github.com/senderle/20fd0007d104af2e360b2440278e89e8).

**Comment by julianwagle** [comment]
No need for adding extra support, just change compose/production/postgres/Dockerfile line 1 to "FROM postgis/postgis"

**Comment by xjlin0** [comment]
Did anyone try this one?  https://gist.github.com/mmmcorpsvit/3614e2396f94fb7bdc555e3b61ec6202

**Comment by ishiland** [comment]
I struggled with this a bit since none of the above worked for me. I finally got it working - it would be nice to put this is the docs I suppose but I'll leave it here for now:

1. install gdal in the django/Dockerfile per the Django [docs](https://docs.djangoproject.com/en/3.2/ref/contrib/gis/install/geolibs/)
`RUN apt-get update && apt-get install -y  binutils libproj-dev gdal-bin`
(add this after the 'Install required system dependencies ' section)

2. Change your database to postgis in the postgres dockerfile. This worked for me:
`FROM postgis/postgis:13-master`

3. Modify the default engine for postgis in the `base.py` config:
 `DATABASES["default"]["ENGINE"] = 'django.contrib.gis.db.backends.postgis'`

**Comment by julianwagle** [comment]
It’s incomplete but for the most part accurate. If you go to my repo (work
in progress) titled octopod-spork you will see an option to all postgis
titled “use gis tools”. If you download the repo and search for all
mentions of {{ cookiecutter.use_gis_tools }} you can see all the add ons
that need to take place. Good luck!

**Comment by stephendwolff** [comment]
> use_gis_tools

I couldn't find `use_gis_tools` much in octopod-spork, but did in CookieFlutter-Django:

 - https://github.com/search?q=use_gis_tools&type=code

**Comment by julianwagle** [comment]
Sorry I failed to remember everything on the internet lives forever haha. I ended up taking octopod-spork in a very different direction. The setting you are looking for on Octopod Spork is now "use_postgis", however, I'm glad you were able to find it on CookieFlutter-Django. If I'm not mistaken, "use_gis_tools" at one point also included other features such as mapbox integration and GeoDjango. "use_postgis" was designed to be much more exclusive in its scope.

**Comment by Andrew-Chen-Wang** [comment]
@browniebroke can this be considered for a PR? The steps are pretty simple, and there is a bot that updates PostGIS to be inline with Postgres.

> I struggled with this a bit since none of the above worked for me. I finally got it working - it would be nice to put this is the docs I suppose but I'll leave it here for now:
> 
> 1. install gdal in the django/Dockerfile per the Django [docs](https://docs.djangoproject.com/en/3.2/ref/contrib/gis/install/geolibs/)
>    `RUN apt-get update && apt-get install -y  binutils libproj-dev gdal-bin`
>    (add this after the 'Install required system dependencies ' section)
> 2. Change your database to postgis in the postgres dockerfile. This worked for me:
>    `FROM postgis/postgis:13-master`
> 3. Modify the default engine for postgis in the `base.py` config:
>    `DATABASES["default"]["ENGINE"] = 'django.contrib.gis.db.backends.postgis'`
> 4. Add `django.contrib.gis` to your installed apps per the Django [docs](https://docs.djangoproject.com/en/3.2/ref/contrib/gis/commands/).

**Comment by browniebroke** [comment]
Adding support for Docker seems pretty simple, yes, but I feel like think might get a bit more complicated to cover the other cases:

- Developing locally without Docker
- Deploying to prod without Docker: Heroku, etc...

Especially with regards to what one needs to do on the DB side of things when the DB is configured outside of the template.

**Comment by masavini** [comment]
> @browniebroke can this be considered for a PR? The steps are pretty simple, and there is a bot that updates PostGIS to be inline with Postgres.
> 
> > I struggled with this a bit since none of the above worked for me. I finally got it working - it would be nice to put this is the docs I suppose but I'll leave it here for now:
> > 
> > 1. install gdal in the django/Dockerfile per the Django [docs](https://docs.djangoproject.com/en/3.2/ref/contrib/gis/install/geolibs/)
> >    `RUN apt-get update && apt-get install -y  binutils libproj-dev gdal-bin`
> >    (add this after the 'Install required system dependencies ' section)
> > 2. Change your database to postgis in the postgres dockerfile. This worked for me:
> >    `FROM postgis/postgis:13-master`
> > 3. Modify the default engine for postgis in the `base.py` config:
> >    `DATABASES["default"]["ENGINE"] = 'django.contrib.gis.db.backends.postgis'`
> > 4. Add `django.contrib.gis` to your installed apps per the Django [docs](https://docs.djangoproject.com/en/3.2/ref/contrib/gis/commands/).

@Andrew-Chen-Wang 
thanks for your snippet, i successfully replaced the postgres with postgis.

when running `docker-compose -f local.yml exec postgres backup`, however, i get this error:
`pg_dump: error: query failed: ERROR:  could not access file "$libdir/postgis-3": No such file or directory`

can you suggest how to fix it?
