### ISSUE TITLE
Portainer support when using docker

### ISSUE THREAD

**Issue by vladdoster** [pydanny/cookiecutter-django#1713]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)

The option for enabling portainer alongside flower when using docker. Integrate it using Docker.

https://portainer.io/

## Rationale

[//]: # (Why should this feature be implemented?)

Allows for easy viewing of containers from web ui.

## Use case(s) / visualization(s)

[//]: # ("Better to see something once than to hear about it a thousand times.")

**Comment by webyneter** [comment]
Not sure why we'd need that: isn't shell enough already?

**Comment by vladdoster** [comment]
Fair enough, just thought it might be LHF somewhat similar to Flower. I would be more than happy to implement.

**Comment by webyneter** [comment]
I'm hesitant upon adding this as a bootstrapping option to the current cookiecutter template, let alone ship it unconditionally so I'm closing this one.
