### ISSUE TITLE
postgresql backup errors

### ISSUE THREAD

**Issue by mr-ant** [pydanny/cookiecutter-django#1729]
Hi,
when I start my projects with cookiecutter-django in ubuntu, running is ok,but backup database get an error.
```
/usr/bin/env: ‘bash\r’: No such file or directory
```
run in windows also get this error. Is anybody can tell me how to fix this.

**Comment by browniebroke** [comment]
It looks like the shebang for the backup script has an extra [trailing character](https://stackoverflow.com/a/1761086) `\r`

https://github.com/pydanny/cookiecutter-django/blob/602bb22a2e959f1a82e8f797b61e76d7d736dab3/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/postgres/maintenance/backup#L1

Maybe it was opened with an editor using a wrong setting for end-of-line character? 

PS: if you resolve your problem, could you please close this issue?

**Comment by mr-ant** [comment]
thanks.
