### ISSUE TITLE
What is the purpose of exposing the list of users?

### ISSUE THREAD

**Issue by demestav** [pydanny/cookiecutter-django#1739]
## Description
The `users` app provides a view to list all the users.

https://github.com/pydanny/cookiecutter-django/blob/28160d06ac15635a3596db53bf53493bc252f141/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/users/urls.py#L12

Probably I am missing something obvious, but is this necessary? Why would a user be able to view all the registered users of the web service? At first I thought this would be only accessible in local environment, but I couldn't find a setting which prevents it from showing up the production environment.

**Comment by webyneter** [comment]
I'd say, our `users` is pretty much a placeholder app: it's not intended to be rolled out to production as-is, and I'm sure no one would seriously consider doing so. For what it's worth, you're right, it's no good practice. Maybe you could send a PR fixing this?

**Comment by webyneter** [comment]
@demestav we can just remove that route.

**Comment by yunti** [comment]
For what it's worth I always thought this was a bit weird too, so good suggestion to put make it local only (or even better just remove it).

**Comment by demestav** [comment]
@yunti In https://github.com/pydanny/cookiecutter-django/pull/1761 (still pending review) the `users` app is only exposed when `DEBUG` is `True` so the developer is free to explore it, and at the same time, prevent an accidental exposure of the users in production.

**Comment by browniebroke** [comment]
After seeing the final result to get the views locally debug-only, I now believe the list view should be deleted. I've opened #2062 to do that. I didn't touch the user detail on purpose...

Thoughts on this?
