### ISSUE TITLE
Caddy HTTP 500 when uploading a file

### ISSUE THREAD

**Issue by zmaximo1990** [pydanny/cookiecutter-django#1740]
Hi!, how are you?. I've a system in production. When i try to upload a file with POST Caddy show me error 500. In local deployment it's ok but in production with caddy doesn't.

The log line is:
caddy_1 | 181.31.240.183 - - [07/Aug/2018:05:24:12 +0000] "POST /.../app_configurations/appconfiguration/1/change/ HTTP/2.0" 500 1646

Request doesn't reach Django never. can someone help me please?. I've checked upload file size but the image has 66kb.

<img width="1249" alt="captura de pantalla 2018-08-07 a la s 02 25 09" src="https://user-images.githubusercontent.com/7076329/43773861-80d398da-9a1d-11e8-8fa0-2b3e06799992.png">

**Comment by browniebroke** [comment]
Thanks for the report. We've migrated away from Caddy due to its licence (see #1714), so I'm going to close this. If there is still an issue with the new config, let's start a new issue.
