### ISSUE TITLE
AttributeError: '_Environ' object has no attribute 'Path'

### ISSUE THREAD

**Issue by spider-hand** [pydanny/cookiecutter-django#1750]
It might be my fault but seems like there are some errors on setting files. I'm really new to cookiecutter and I'm trying to run server on local anyway but there are some errors. 

First I saw this error so I changed it to `from os import environ`
>   ModuleNotFoundError: No module named 'environ'

and then there is still an error.

>  ROOT_DIR = environ.Path(__file__) - 3  # (project/config/settings/base.py - 3 = project/)
AttributeError: '_Environ' object has no attribute 'Path'

How can I fix this?

I'm using python3.6, Django2.1 and WSL.

**Comment by sfdye** [comment]
`environ` is from [django-environ](https://github.com/joke2k/django-environ), not a built-in module from `os`.

Please use the following instructions to set up, depending on whether you use docker:

https://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html
https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html

**Comment by browniebroke** [comment]
Closing as it doesn't look like an issue with the project. Happy to re-open if more info is provided showing otherwise.
