### ISSUE TITLE
Release for django 2.0.8

### ISSUE THREAD

**Issue by cshaley** [pydanny/cookiecutter-django#1751]
It's been a while since you tagged a new version for release.  Can you please tag/package a release for django 2.0.8 at this commit? https://github.com/pydanny/cookiecutter-django/commit/36f3558ccc934e19ba54cfe16c92abb5d720b5bd

**Comment by cshaley** [comment]
Good question - I don't remember why there.  Looks like the most [recent version](https://github.com/pydanny/cookiecutter-django/commit/d95bdc6a378062382c536da07364bf8c46f8ea9c) should be fine and the build failed on the commit I pointed to...

**Comment by browniebroke** [comment]
I've tagged all the recent commits to when we updated the Django version. The latest commit is also tagged to `2.0.8-01`.
