### ISSUE TITLE
[SECURITY] Access to other user's profile

### ISSUE THREAD

**Issue by bdrhoa** [pydanny/cookiecutter-django#1752]
## What happened?
 It turns out that if you're logged in as one user and happen to know the id another user, you can access that other user’s profile page. E.g. mysite.com/users/someotheruserid.

## What should've happened instead?
Probably give a 404 response?

## Steps to reproduce
Login as user A. Change URL to mysite.com/users/userb.

**Comment by bdrhoa** [comment]
So this is easily handled with more
  {% if object == request.user %}
   ...
 {% endif %}

statements. But I think the out of box user_detail.html should already have them in place.

**Comment by browniebroke** [comment]
I'm not sure it's a problem. Many websites have a public profile for their users. Aren't you able to access the profile page of any Facebook/Twitter/LinkedIn user if you know their username? 

It's not like the default layout is exposing much sensitive info by default. If the app you build is NOT meant to have a public user profile page, then I guess one would audit their URLs beforehand.

If one is not happy with a public profile, it's pretty much [one Mixin away](https://django-braces.readthedocs.io/en/latest/access.html#userpassestestmixin). It's not a one-size-fits-all currently, but I'm not sure it's worth adding an option to the template either.

**Comment by demestav** [comment]
@browniebroke I think https://github.com/pydanny/cookiecutter-django/pull/2062 takes care of this.

**Comment by demestav** [comment]
Disregard my previous comment, I though the PR removed all the user's views.

**Comment by xjlin0** [comment]
Hmm, this still exists.  Here is my code using mixin

<<app_name>>/users/views.py
```python
from django.contrib.auth.mixins import UserPassesTestMixin

class UserDetailView(UserPassesTestMixin, DetailView):

    # original code goes here ......

    def test_func(self):
        return self.request.user.get_username() == self.kwargs['username']
```

**Comment by browniebroke** [comment]
Yes, it still exists. As per [my above comment](https://github.com/pydanny/cookiecutter-django/issues/1752#issuecomment-479591956), I don't consider it a security risk. Unless I misunderstood, lots of website do have a public profile (including the one we're using right now).
