### ISSUE TITLE
Selected Gulp and CSS compilation. `npm run dev` does not run automatically when docker-compose build+up is invoked

### ISSUE THREAD

**Issue by sharmi** [pydanny/cookiecutter-django#1762]
I have selected CSS compilation to be enabled and have chosen Gulp to be used as a task runner.  
When `docker-compose up` is  invoked auto compilation of css does not take place. I have to manually install nodejs, npm, gulp, compass to get the whole thing working. 

I also had to run npm run dev manually.

It kind of feels like a leaky abstraction, when some setup and commands work automatically, while others don't.

The expectation is that,  because of the choices made while setting up the project, `npm run dev` command will be automatically started, when docker-compose is invoked.

It also appears that the DockerFile does not install nodejs, npm or gulp in spite of choosing Gulp as task runner.

It should be trivial to incorporate.

The gulp task runner already has `python manage.py runserver` as one of it's options. So all the start script has to do is run `npm run dev` instead of `python manage.py runserver_plus`. (The gulpfile.js should be changed to use runserver_plus instead of runserver).

One way to incorporate this would be to have two Dockerfiles, one where gulp and bootstrap compilation is enabled and one where gulp and bootstrap compilation is disabled.

I am new to the cookiecutter-django community. So maybe I am missing something obvious. If so, I would be very interested in knowing the reasons behind not incorporating the above steps.

If there is interest in the community, I would be happy to implement the solution after discussing and deciding on the right way to do the same.

**Comment by browniebroke** [comment]
This is indeed not very well supported at the moment, and you should have seen [a warning](https://github.com/pydanny/cookiecutter-django/blob/4b6e2b503a4fdc9739574c78b7f953c18def855a/hooks/post_gen_project.py#L317-L327) when generating the project...

I've started [some work](https://github.com/pydanny/cookiecutter-django/pull/1687/) to improve this, you can use that version of the template by adding the option `--checkout feature/docker-compose-gulp` when generating your project. This should also provide hot reloading on SCSS changes. Maybe you can test and feedback in the PR if you encounter any problems?
