### ISSUE TITLE
How to remove templates/static files to make base application an API?

### ISSUE THREAD

**Issue by ankitgoyal100** [pydanny/cookiecutter-django#1763]
I plan to use cookiecutter-django as an API and want to remove all the extra templates, static files, and other pre-configured files from my project. What specifically do I need to change/remove?

Thanks,
Ankit

**Comment by sfdye** [comment]
You can manually remove all the unnecessary files or consider using something like [cookiecutter-django-rest](https://github.com/agconti/cookiecutter-django-rest)

**Comment by browniebroke** [comment]
Going to close this as it's more a question than a bug or feature request. Next time, we would really appreciate if you could follow [the relevant template](https://github.com/pydanny/cookiecutter-django/issues/new?template=question.md).

> First, make sure to examine [the docs](https://cookiecutter-django.readthedocs.io/en/latest/). If that doesn't help post a question on [StackOverflow](https://stackoverflow.com/questions/tagged/cookiecutter-django) tagged with `cookiecutter-django`. Finally, feel free to join [Gitter](https://gitter.im/pydanny/cookiecutter-django) and ask around.
