### ISSUE TITLE
Environment variables error in base.py.

### ISSUE THREAD

**Issue by Chhaya02** [pydanny/cookiecutter-django#1774]
When I am setting the default environment variable in base.py, its working and not giving any error to set the environment variable. But I want to take the value from the  .env files for local and django.

**Comment by sfdye** [comment]
Hi could you fire an issue with the [bug template](https://github.com/pydanny/cookiecutter-django/issues/new?template=bug.md), else it's very hard for us to help you out.

**Comment by Chhaya02** [comment]
Thank you for the response. Created the issue with bug template. Please go
through it,

Regards,
Chhaya Kuamri

**Comment by sfdye** [comment]
Closing in favor of #1775
