### ISSUE TITLE
Environment variables error in base.py and local.py

### ISSUE THREAD

**Issue by Chhaya02** [pydanny/cookiecutter-django#1775]
![screen shot 2018-08-30 at 12 49 17 pm](https://user-images.githubusercontent.com/20675052/44835946-3f5b2100-ac53-11e8-8cc6-aa24dbb2d4dd.png)
When I try to run my project using cookiecutter setup, I got this exception : 
     django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

To solve this, Followed this steps and include the code in manage.py : 
i)import django 
ii)django.setup()
inside the If block.

After that, the new exception raised i.e
   django.core.exceptions.ImproperlyConfigured: Set the DATABASE_URL environment variable

So, it's saying that values are not getting set from the .env files.
To solve this I made changes and set the default value for the variables.

Before setting the default values for my environment variable in my base.py: 
DATABASES = {
    'default': env.db('DATABASE_URL'),
 }
CELERY_BROKER_URL = env('CELERY_BROKER_URL')

After setting the default values for my environment variable in my base.py: 
DATABASES = {
   'default': env.db('DATABASE_URL',default="postgres://user_name:password@127.0.0.1:5432/db_name"),
 }
CELERY_BROKER_URL = env('CELERY_BROKER_URL',default='redis://redis:6379/0')

I can't hard code values for every service. it should be taken from the .env files i.e  .django and .postgres from .local folder of .envs directory

Os: macOS 
version : 10.13.3

**Comment by sfdye** [comment]
Are you using docker?

**Comment by Chhaya02** [comment]
No, Right now we are not using Docker but we have opted it for local and production environment for the future.

**Comment by connectgautam** [comment]
How we will run migration if we are using Docker

**Comment by browniebroke** [comment]
@connectgautam your question seems off-topic, please could you find a more appropriate channel?

> First, make sure to examine [the docs](https://cookiecutter-django.readthedocs.io/en/latest/). If that doesn't help post a question on [StackOverflow](https://stackoverflow.com/questions/tagged/cookiecutter-django) tagged with `cookiecutter-django`. Finally, feel free to join [Gitter](https://gitter.im/pydanny/cookiecutter-django) and ask around.

**Comment by browniebroke** [comment]
@Chhaya02 if you're not using Docker, I would recommend answering "no" when being asked the question by cookiecutter. 

> I can't hard code values for every service. it should be taken from the .env files i.e .django and .postgres from .local folder of .envs directory

Docker enables to control the target environment from the code, by settings all the required environment variables in the `.envs`, and telling in the docker-compose file what to use. Without Docker, the equivalent is to set things manually on your host machine (i.e. your Mac).

One thing that can help, which unfortunately not well documented, is to create a single `.env` file for the local dev. It's where you define all the variables for Django https://cookiecutter-django.readthedocs.io/en/latest/settings.html

Then on your host machine, you should be able to get your app to read it when `DJANGO_READ_DOT_ENV_FILE=True`.

If you find this helpful, you are welcome to send us a pull request to update our documentation. Maybe the page to [develop locally](https://github.com/pydanny/cookiecutter-django/blob/master/docs/developing-locally.rst) can be updated and link to the [setting page](https://github.com/pydanny/cookiecutter-django/blob/master/docs/settings.rst).

**Comment by Chhaya02** [comment]
Thank you. I will try this.

**Comment by h0h0h0** [comment]
@browniebroke It seems like one would need to remove .env from the .dockerignore file if they wanted to use them in docker.   I might be thinking about this wrong. Can you give your opinion?
