### ISSUE TITLE
How do you collectstatic in production?

### ISSUE THREAD

**Issue by jkleve** [pydanny/cookiecutter-django#1786]
I've been searching around not finding much on this.Hope it's fine to ask this here as I originally started the project from this template.

My first thought to collect the static files in a production environment was to go onto the production server and run `./manage.py collectstatic`. The issue with this was that the developer pip packages weren't installed so running manage.py threw an import error. I'm assuming this is the incorrect way to do it. My next thought was that `collectstatic` should be done in a similar fashion to the Amazon S3 collectstatic class but I can't seem to find an already built solution to send your static files to your own server and save them in some directory. Is there a solution to this already?

**Comment by sfdye** [comment]
This is one of project features.

When you create a new project, if you say "no" to use_whitenoise, I believe you will get this behavior in production, serving statics files from s3.

**Comment by browniebroke** [comment]
> The issue with this was that the developer pip packages weren't installed so running manage.py threw an import error

You should be able to run `collectstatic` on your prod server, it doesn't require any dev requirements. What import error specifically?

If you use Docker, collectstatic is run automatically [when the server starts](The issue with this was that the developer pip packages weren't installed so running manage.py threw an import error).

If you deploy on Heroku, [it should be done automatically](https://devcenter.heroku.com/articles/django-assets).

The `collectstatic` command is working with your static files config and copies files to whatever static file storage you have configured.

**Comment by jkleve** [comment]
@browniebroke the import error I was getting was for django debug-toolbar. It tries to import the local settings file which contains this dependency because of [line 6 in manage.py|https://github.com/pydanny/cookiecutter-django/blob/ffbec778a6fb3b0231755bb40560f4af83b7643c/%7B%7Bcookiecutter.project_slug%7D%7D/manage.py#L6]. 

`    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.local")`

This made me think I shouldn't be using manage.py on the production server. Maybe whitenoise is what I'm looking for. 

@sfdye does whitenoise allow for deploying static files to your own server or is it only configurable for S3 instances?

**Comment by jkleve** [comment]
Would a safe solution be to simply change which settings file manage.py uses  and run collectstatic directly on the production server? For this server I'm serving the static files.

That brings up the question of serving files from S3 then. Collectstatic in that case should be done from a local development environment?

**Comment by browniebroke** [comment]
This is working as expected, the manage script defaults to local settings, and on production, you should set an environment variable to use the production settings: `DJANGO_SETTINGS_MODULE='config.settings.production'`

Here are links:

* Doc for [Python anywhere](https://cookiecutter-django.readthedocs.io/en/latest/deployment-on-pythonanywhere.html#setting-environment-variables-in-the-console)
* Doc for [Heroku](https://cookiecutter-django.readthedocs.io/en/latest/deployment-on-heroku.html#deployment-on-heroku)
* For Docker, it should be done out of the box by [the env file](https://cookiecutter-django.readthedocs.io/en/latest/deployment-on-heroku.html#deployment-on-heroku).

If you deploy the project on another type of production machine, not using Docker, I would recommend checking with your hosting provider how to set environment variables.

**Comment by jkleve** [comment]
@browniebroke That seems obvious now, thank you.
