### ISSUE TITLE
Ipython history: keep it around for the django shell

### ISSUE THREAD

**Issue by YAmikep** [pydanny/cookiecutter-django#1794]
Every time you run this command to use the django shell, the history is gone:
```
docker-compose -f local.yml run --rm django python manage.py shell_plus
```

Is there a way to keep the ipython history around?

I tried the following:
```
docker-compose -f local.yml run --rm -v /d/my_project/.ipython/:/root/.ipython django python manage.py shell_plus
```

but I get a warning from Ipython:

```
The history saving thread hit an unexpected error (OperationalError('unable to open database file')).History will not be written to the database.
```

**Comment by webyneter** [comment]
@YAmikep didn't quite look into this one, but I guess you gotta play around with https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/shell_plus.py#L77.

**Comment by hangtwenty** [comment]
Related: https://github.com/pydanny/cookiecutter-django/issues/1589
