### ISSUE TITLE
Travis builds failing with E402 module level import not at top of file

### ISSUE THREAD

**Issue by kevgathuku** [pydanny/cookiecutter-django#180]
Travis builds have been failing due to an import in:
https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/wsgi.py#L28

What's the best way to deal with this? Ignore it or move the import to the top of the line?
All Pull Requests are failing due to this.

**Comment by luzfcb** [comment]
Fixed in 5fefde8a66af02ae0948e5fe668831b90db905a4
