### ISSUE TITLE
production environment

### ISSUE THREAD

**Issue by connectgautam** [pydanny/cookiecutter-django#1802]
Hi All,
I am trying to run production.yml without AWS. Django is up but i am not able to get anything on localhost:8000 . I change the port number in my start file.

![screenshot from 2018-09-15 11-14-18](https://user-images.githubusercontent.com/36084962/45583051-afff7000-b8d8-11e8-856d-0a1c8bec3699.png)

Please let me know what going wrong because i am not getting any error log also.

**Comment by browniebroke** [comment]
For best support, please make sure to follow the issues templates. Looks like you want to ask a question, and opening an issue isn't the recommended way to go:

> First, make sure to examine [the docs](https://cookiecutter-django.readthedocs.io/en/latest/). If that doesn't help post a question on [StackOverflow](https://stackoverflow.com/questions/tagged/cookiecutter-django) tagged with `cookiecutter-django`. Finally, feel free to join [Gitter](https://gitter.im/pydanny/cookiecutter-django) and ask around.

Thanks for the understanding

**Comment by browniebroke** [comment]
In production, the django container doesn't expose any port to the outside, caddy does. It looks like your caddy container has an error.

Production setup is not designed to be run locally...

**Comment by connectgautam** [comment]
@browniebroke Thanks after exposing port and running nginx in background its works

**Comment by abbas133** [comment]
@connectgautam Facing same issue. Could you let me know how did you resovled it?
