### ISSUE TITLE
Having production only settings leads to deployment bugs

### ISSUE THREAD

**Issue by carlmjohnson** [pydanny/cookiecutter-django#1827]
## Description
Move all security settings out of production.py and into base.py.

## Rationale
I have been bitten multiple times by security settings that are set only in production.py that I don't become aware of until deploying. If the setting is worth setting, it should be set in base.py, so that I can learn about clickjacking, CORS, HTTP only cookies, etc. when I'm still developing, rather than after I deploy and a feature is mysteriously broken. The only exception I can think of are secure cookies, and even that's only because it's a pain to get HTTPS working locally. (It still bit me when I was trying to "debug" my non-HTTPS staging site.)

**Comment by cmackenzie1** [comment]
Hi @carlmjohnson, I have a solution for your issue of running HTTPS locally
> The only exception I can think of are secure cookies, and even that's only because it's a pain to get HTTPS working locally.

This project comes with `django-extensions` installed, which supports running your app in HTTPS mode locally - autogenerating a cert.

You can achieve this by
```bash
pip install pyOpenSSL
python manage.py runserver_plus --cert local
```

**Comment by webyneter** [comment]
@carlmjohnson let us know if you ever find time to submit a PR elaborating on the issue at hand -- we'll gradly review it.
