### ISSUE TITLE
Comprehensive tutorial

### ISSUE THREAD

**Issue by tluanga** [pydanny/cookiecutter-django#1838]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)

Can you please make a comprehensive tutorial

## Rationale

[//]: # (Why should this feature be implemented?)

## Use case(s) / visualization(s)

[//]: # ("Better to see something once than to hear about it a thousand times.")

**Comment by webyneter** [comment]
This project is maintained by unpaid volunteers, and we try our best to spare some time keeping it floating. However, a "comprehensive tutorial" is something requiring a week or more of full-time effort, which I doubt anyone of us has. Make sure to check out our [docs](https://cookiecutter-django.readthedocs.io/en/latest/) for in-depth examination.

**Comment by tluanga** [comment]
Is there any free lancer who will help me in learning how to setup

**Comment by webyneter** [comment]
@tluanga what's your email?

**Comment by tluanga** [comment]
tluangahauhnar@gmail.com
