### ISSUE TITLE
how cookiecutter django use mysql?

### ISSUE THREAD

**Issue by StupidTAO** [pydanny/cookiecutter-django#1844]
I need use mysql database in the project of cookiecutter-django,but cookiecutter only support postgresql,what should i do?

**Comment by browniebroke** [comment]
You're right, cookiecutter-django only supports postgres. 

However, at the end of day, the output is a Django project, so I suggest to refer to the documentation from Django itself, especially the [`DATABASES` setting](https://docs.djangoproject.com/en/2.1/ref/settings/#databases). You will need to swap out the settings we generate by the appropriate one for mysql.

If you use Docker, you will need to change the `postgres` service to use a MySQL Docker image.

I've never done it, but it should be feasible. Feel free to add more information here for others, but I do not think we plan to support MySQL in the cookiecutter-django.

**Comment by pydanny** [comment]
@browniebroke is correct, Cookiecutter Django will not be supporting MySQL. That could change per my specification in #111.

Rather than changing out `postgre` for `mysql`, having you considered staying with `postgre`? Here are some considerations:

- PostgreSQL is the default database for Django. There are features in Django that only work for PostgreSQL
- PostgreSQL is much better at handling database migrations than MySQL. It's really nice when for large tables things don't get locked for *hours*

**Comment by xjlin0** [comment]
Here are my steps to use MySQL 5.7 on OS 10.13.6.  My local mysql administrator account is `root` without password, so I can enter local mysql console by `mysql -uroot` and create the database:

1. follow cookiecutter-django instructions to start a project
https://github.com/pydanny/cookiecutter-django#usage
https://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html
2. install MySQL 5.7, ensure `mysql` is in the path, start the MySQL service
```
brew install mysql@5.7
echo 'export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"' >> ~/.bash_profile
source ~/.bash_profile
brew services start mysql@5.7
```
3. install mysqlclient for python, please ensure you are still in the virtual env for the python version you need.
```
pip install mysqlclient
```
4. change database setting of Django setup by cookiecutter, in <your project>/<your app>/config/settings/base.py, around DATABASES dictionary
```
    # "default": env.db("DATABASE_URL", default="postgres:///<your database name>")
    "default": env.db("DATABASE_URL", default="mysql://root:@127.0.0.1:3306/<your database name>")
```
And it just works! Enjoy!

**Comment by doemski** [comment]
For anybody looking to use MySQL / MariaDB with the Docker setup (possibly future me...), here's the changes I needed to get it running:

1. Add a MariaDB env file under .envs/.local/.mariadb with
```
MYSQL_ROOT_PASSWORD=test
MYSQL_USER=test
MYSQL_PASSWORD=test
MYSQL_HOST=mariadb
MYSQL_PORT=3306
MYSQL_DATABASE=technical_drawings_database
```

2. Change the Docker entrypoint for your app under compose/production/django/entrypoint like this:
![image](https://user-images.githubusercontent.com/11717392/116364511-8d5dc380-a804-11eb-8835-bf5dea0f3994.png)

3. Add pymysql to your requirements (requirements/base.txt):
```
pymysql==1.0.2 (Or newer version)
```

4. In your base settings file (config/settings/base.py) add:
```
import pymysql
pymysql.install_as_MySQLdb()
```

5. In your local docker-compose file (local.yml) add the MariaDB container and remove postgres like so:
![image](https://user-images.githubusercontent.com/11717392/116365707-cea2a300-a805-11eb-9571-4332354feebd.png)

**Comment by mabdullahadeel** [comment]
For anybody looking for MySQL option with cookiecutter support, 
you can try this fork -> 🦈 https://github.com/mabdullahadeel/cookiecutter-django-mysql

Here are the docs -> 📖 https://cookiecutter-django-mysql.readthedocs.io/en/latest/
