### ISSUE TITLE
SyntaxError leads to exited docker container

### ISSUE THREAD

**Issue by TaylanT** [pydanny/cookiecutter-django#1856]
## What happened?
every syntaxerror leads to an exited docker container. It has to be restarted again. 

`django_1    |     if form.is_valid():
django_1    |                       ^
django_1    | SyntaxError: invalid syntax
test_django_1 exited with code 1`

## Steps to reproduce

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
[//]: # (* Logs)

**Comment by browniebroke** [comment]
I don't think it's a bug or a problem related to cookiecutter-django or Docker... It's just how Django works. If you have a syntax error that prevents the Python code to be parsed, Django's auto-reloader will crash and will need to be restarted, docker or not docker. It will happen if you start a project with Django's create project.

**Comment by browniebroke** [comment]
Feel free to provide more details if you feel like it's an actual problem, but for now, I'm going to close this.
