### ISSUE TITLE
Better testing for this cookiecutter

### ISSUE THREAD

**Issue by kevgathuku** [pydanny/cookiecutter-django#186]
I would like to make a small suggestion, how might better testing be implemented for this? 
i.e testing that the output is produced by the template
There are a bunch of issues coming up with regards to this e.g #145, #177, #185 
that would be avoided beforehand with some testing of the output.

What do you guys think about this?

**Comment by luzfcb** [comment]
Yes, test the generated project would be good.
The possible tests that can i see are:

- [ ] Test generated project
- [ ] Test deploy (on Heroku) of generated project

I saw recently that @ionelmc implemented something like this in your own library [cookiecutter-pylibrary](https://github.com/ionelmc/cookiecutter-pylibrary)

So it's a good example of the ways to implement feature.

At this moment I have no free time to implement this.

Feel free to send a pull-request.

thank you for opening this, will serve for I do not forget this

**Comment by kevgathuku** [comment]
@luzfcb Thanks for considering this suggestion.
I will look into the mentioned project and try to have a go at testing the generated project.

**Comment by theskumar** [comment]
+1

**Comment by theskumar** [comment]
I think we should also add testing against python 2 and python 3, right now there is no way to ensure whether this project is compatible with python 3 or not.

**Comment by luzfcb** [comment]
@pydanny @theskumar  You agree to include `isort`?

**Comment by pydanny** [comment]
I'm :+1: on the `isort` inclusion, if only to see how the final implementation is done. @luzfcb I love the thoughtfulness behind your proposed solution!

**Comment by luzfcb** [comment]
@pydanny @theskumar  I'm doing some experiments[1][2][3] to test if generated project work as expected on Heroku.

I tried using the Travis Heroku Deploy API[4], but I have not found a way to make it work with a subdirectory.

The script [2] works properly locally, but does not work when used in Travis, because cannot autenticate in Heroku. I requested help from Travis support, to try to resolve some doubts not covered by the Travis documentation. With no response yet ( not even an automatic response message from email server ) :-(


[1] https://github.com/luzfcb/cookiecutter-django/tree/test-deploy
[2] https://github.com/luzfcb/cookiecutter-django/blob/test-deploy/deploy_by_travis.sh
[3] https://github.com/luzfcb/cookiecutter-django/blob/test-deploy/.travis.yml
[4] http://docs.travis-ci.com/user/deployment/heroku/

**Comment by theskumar** [comment]
How about not deploying to heroku at all. Have a bunch of tests in the generate project itself, which checks that project is working after the migration are run. Some integration test cases I can think are:

1. `/admin/` url is accessible and you are able to login 
2. Homepage is accessible
3. User detail page is authorised, etc.

This would provide some test cases for the functionality we already provide in the generated project and base for writing more tests. What do you think?

**Comment by kevgathuku** [comment]
I agree with @theskumar there may not be a need to deploy to Heroku at all. Maybe just checking that the project can be deployed there. How about testing that the project is run successfully through the Procfile?

**Comment by pydanny** [comment]
I think most of this has been implemented now. Anyone mind if I close this issue?

**Comment by luzfcb** [comment]
I still like to find a less complicated way to test in travis-ci (or other ci) the django application with all generation possibilities. perhaps docker in travis-ci help it.

**Comment by jayfk** [comment]
I'd really like to have some unit tests for this cookiecutter. 

I don't have the time to implement this right now on upstream, but I've been working on a small unit test class that makes it super easy to test small fragments.

The `CookiecutterTest` class provides a dictionary of all generated project files accessible by file name and the `context` that is used to render the templates 
```
COOKIECUTTER_DIR = os.path.join(
    os.path.dirname(os.path.realpath(__file__)),
    "../"
)

TEST_DIR = "/tmp/cookiecutter-test/"

class CookiecutterTest(unittest.TestCase):

    def setUp(self):
        self.project_directory = TEST_DIR + self.__class__.__name__
        with open(os.path.join(COOKIECUTTER_DIR, "cookiecutter.json"), "r") as f:
            self.context = json.loads(f.read())

    def render(self):
        self.context["repo_name"] = inspect.stack()[1][3]
        cookiecutter(COOKIECUTTER_DIR, output_dir=self.project_directory,
                     extra_context=self.context, overwrite_if_exists=True, no_input=True)
        content = {}
        for root, subdirs, files in os.walk(os.path.join(self.project_directory, self.context["repo_name"])):
            for filename in files:
                file_path = os.path.join(root, filename)
                relative_path = file_path.replace(self.project_directory + "/" + self.context["repo_name"], "")
                with open(file_path, 'r') as f:
                    f_content = f.read()
                    content[relative_path] = f_content
        return content
```

An example of a unit test might look like this. It just checks if `nginx` is in `docker-compose.yml` if the *webserver* context is set to *nginx* during project generation.
```
class NginxTestCase(CookiecutterTest):

    def setUp(self):
        super(NginxTestCase, self).setUp()
        self.context["webserver"] = "nginx"

    def test_nginx_in_docker_compose_yml(self):
        files = self.render()
        self.assertTrue("nginx:" in files["/docker-compose.yml"])
```

**Comment by pydanny** [comment]
We should also start using @hackebrot's pytest-cookies.

**Comment by ssteinerx** [comment]
@luzfcb @pydanny  As per my discussions vis-à-vis Heroku, we should remove checkbox 4 as specific Heroku support is not something we want to get into in the main project any more.

**Comment by pydanny** [comment]
Closing this as we will never be able to meet the terms of this issue.
