### ISSUE TITLE
Typical place to create app in cookiecutter-django

### ISSUE THREAD

**Issue by playma** [pydanny/cookiecutter-django#1876]
I have a question.
Startapp creates the app in the first level, the same directory where manage.py is. 
Why not create the app in the <project_name>/ level, where also the users app is?

**Comment by ahhda** [comment]
I think this has been tried before (See #1725 ). The django startapp, apparently, was not projected to be extended.

**Comment by webyneter** [comment]
Yes, the second level is the right place for your Django apps. 
FWIW, I personally do not use the srartapp command, and just create a Django package with `apps.py` myself, as well as reference it in settings. This is what a typical `apps.py` looks like for me (and I don't even have to write the most part of it since I have it generated from a PyCharm Live Template of mine): 

```python
# apps.py in your new shiny Django app under the project's root `<project_slug>/` dir

from django.apps import AppConfig
from django.utils.translation import ugettext_lazy as _


class <YourCamelCaseAppName>AppConfig(AppConfig):
    name = "<project_slug>.<your_snake_case_app_name>"
    verbose_name = _("<Your app brand name>")

    def ready(self):
        try:
            # noinspection PyUnresolvedReferences
            from . import signals  # noqa F401
        except ImportError:
            pass
```

And this where you should install your new app:

```python
# `base.py`

# ...
LOCAL_APPS = [
    # ...
    "<project_slug>.<your_snake_case_app_name>.apps.<YourCamelCaseAppName>AppConfig",
    # ...
]
# ...
```

Should you need that specific app installed in some specific environment only, provided that environment has an associated settings file like `local.py` or `production.py`: 

```python
# anywhere else but in `base.py`

# ...
INSTALLED_APPS += ["<project_slug>.<your_snake_case_app_name>.apps.<YourCamelCaseAppName>AppConfig"]
# ...
```

**Comment by reyesvicente** [comment]
Hi, does this mean we don't need to include the new app on the urls.py?

**Comment by webyneter** [comment]
It depends: if your app contains urls you'd like to expose to the outer world then you gotta include those urls from the root `urls.py` via `include`.

**Comment by reyesvicente** [comment]
Thats weird. I tried to include it but it doesn't recognize my app and returns `ModuleNotFoundError: No module named '<project_slug>.<app_name>.urls'`

**Comment by webyneter** [comment]
If your app contains models did you install it into `INSTALLED_APPS`?

**Comment by reyesvicente** [comment]
Yes, I followed the instructions here. :smile:

**Comment by reyesvicente** [comment]
![Screen Shot 2019-10-19 at 3 11 00 PM](https://user-images.githubusercontent.com/45283313/67139455-f2854000-f282-11e9-9ebd-5cf66ed63097.png)

**Comment by webyneter** [comment]
Try including the app under a different root, like `"pages/" rather than `""`

**Comment by webyneter** [comment]
Also, did you specify `app_name="pages"` in `icvn/pages/urls.py`?

**Comment by reyesvicente** [comment]
> Also, did you specify `app_name="pages"` in `icvn/pages/urls.py`?

Yes I did. I followed what was here on [this](https://github.com/pydanny/cookiecutter-django/issues/1876#issuecomment-449341435) comment on this thread.

I tried also including `pages/` on the urls.py but it didn't work

**Comment by reyesvicente** [comment]
This is my apps.py

<pre>from django.apps import AppConfig
from django.utils.translation import ugettext_lazy as _


class PagesConfig(AppConfig):
    name = "icvn.pages"
    verbose_name = _("Pages")

    def ready(self):
        try:
            from . import signals
        except ImportError:
            pass
</pre>

**Comment by webyneter** [comment]
Hm, then, I can't say for sure what's wrong without inspecting the code base first. My email is posted on my github profile, feel free to reach out.

**Comment by reyesvicente** [comment]
> Hm, then, I can't say for sure what's wrong without inspecting the code base first. My email is posted on my github profile, feel free to reach out.

Cool. I just sent an email.

**Comment by webyneter** [comment]
@reyesvicente I'll get back to you by the end of the weekend.

**Comment by reyesvicente** [comment]
> @reyesvicente I'll get back to you by the end of the weekend.

Thanks!

**Comment by webyneter** [comment]
@reyesvicente you don't actually have `icvn,pages.urls` module, hence the error. An empty one would suffice, for instance:

```python
# icvn/pages/urls.py

app_name = "pages"
urlpatterns = [
]
```

You may also replace the `config/urls.py` `path("pages/", include('icvn.pages.urls', namespace='pages')),` line with just `path("pages/", include('icvn.pages.urls')),`, just make sure to specify `app_name` in the referenced routes file.

**Comment by reyesvicente** [comment]
> @reyesvicente you don't actually have `icvn,pages.urls` module, hence the error. An empty one would suffice, for instance:
> 
> ```python
> # icvn/pages/urls.py
> 
> app_name = "pages"
> urlpatterns = [
> ]
> ```
> 
> You may also replace the `config/urls.py` `path("pages/", include('icvn.pages.urls', namespace='pages')),` line with just `path("pages/", include('icvn.pages.urls')),`, just make sure to specify `app_name` in the referenced routes file.

It worked! Thank you!
