### ISSUE TITLE
Serverless deployment with aws lambda using zappa.io

### ISSUE THREAD

**Issue by adilnaimi** [pydanny/cookiecutter-django#1889]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)
deploy to aws lambda using zappa.io 

I tried to make zappa working with django-cookicutter, but I'm facing an issue with the project directory structure

zappa wants the apps to be in the top directory, whilst Django-cookicutter has them all in project_slug subdirectory, moving all my apps to the root directory it's a huge refactoring task.

Can  you help make django-cookicutter working with zappa

I think @pydanny, the author of Django-cookiecutter, got it working with Zappa, links [Reddit](https://www.reddit.com/r/django/comments/8fiz89/how_are_you_regularly_deploying_new_django/dy5i6zb) and [Twitter](https://twitter.com/pydanny/status/1017182406728548352)

## Rationale

[//]: # (Why should this feature be implemented?)

embrace serverless 

## Use case(s) / visualization(s)

[//]: # ("Better to see something once than to hear about it a thousand times.")

**Comment by browniebroke** [comment]
Hi, this project doesn't support Zappa at this stage, and from what you say, it sounds like several significant changes are required. 

I recently stumbled upon [this article](https://www.agiliq.com/blog/2019/01/complete-serverless-django/) which explains in details how to deploy a Django project using Zappa.

Unfortunately, I haven't played enough with Zappa myself to know the quirks and limitations. If you manage to make it work, we would greatly appreciate if you could share your learning. To make a change to the template, it's very helpful to first see the change required to the output of the template.

**Comment by hangtwenty** [comment]
Another resource - this one is specifically about `django-cookiecutter` and Zappa.

https://andytwoods.com/python-zappa-django-cookiecutter-via-pycharm.html

**Comment by IAmNatch** [comment]
Zappa has not been updated in some time. I've tried both and have had much more enjoyment using [serverless-framework](https://www.serverless.com/) and the WSGI plugin. The plugin system makes it much more extendable and it's got up a great community as well.

**Comment by browniebroke** [comment]
I believe that adding support for some sort of serverless framework would give a significant maintenance overhead to this project, which we don't have the bandwidth to support at the moment.

We could link some external resources in our docs, but even that may cause some maintenance: the [link above](https://github.com/pydanny/cookiecutter-django/issues/1889#issuecomment-484606536) no longer exists.

I'll close this issue for now, there isn't much to action on the project IMO, but people are welcome to link to useful resources in here.
