### ISSUE TITLE
add support for 'Request-ID' logging

### ISSUE THREAD

**Issue by theskumar** [pydanny/cookiecutter-django#189]
**Why**

By including a `Request-Id` header in each response, which is a UUID value, we can provide facility to log these values on the client, server and any backing services, it provides a mechanism to trace, diagnose and debug requests.

Heroku has `Request-ID` support automatically, so it make sense to enable this feature here.

**Third-party library required**
- https://github.com/dabapps/django-log-request-id (it is stable at 1.0.0)

**References:**
- https://github.com/dabapps/django-log-request-id#why
- https://github.com/interagent/http-api-design#provide-request-ids-for-introspection
- https://devcenter.heroku.com/articles/http-request-id#usage-with-django

If there is consensus, I can work to include this feature. 

cc: @pydanny @luzfcb 

Cheers,

**Comment by luzfcb** [comment]
@theskumar The only objection I have is if django-log-request-id works well with Django 1.8

**Comment by theskumar** [comment]
Sure. I'll test against Django 1.8 although I'm still using 1.7 for most of my projects.

**Comment by burhan** [comment]
Sentry provides this as well they call it [message references](https://docs.getsentry.com/hosted/clients/python/integrations/django/#message-references).

**Comment by webyneter** [comment]
=
