### ISSUE TITLE
Could you please tell me whether channels are supported in this project?

### ISSUE THREAD

**Issue by laiyazhou** [pydanny/cookiecutter-django#1892]
When I tested channels in a local cookiecutter-django project,it didn't work.

**Comment by browniebroke** [comment]
Hi,

This is currently not supported out of the box by this project, but the thing you would get is a Django site, so it should be possible to add it, although I don't have much experience with it myself.

I'm going to close this as there is another issue to add support already #1058

If you need more guidance on Django channels, I suggest one of the following follow the suggested resources https://channels.readthedocs.io/en/latest/support.html

For questions specific to cookiecutter-django itself, you will get a better response from [Stackoverflow](https://stackoverflow.com/questions/tagged/cookiecutter-django) or on [Gitter](https://gitter.im/pydanny/cookiecutter-django)

I would recommend posting some details about your code: how to get the same version as you, what have you tried? What worked? What didn't?
