### ISSUE TITLE
django secure middleware

### ISSUE THREAD

**Issue by philippeluickx** [pydanny/cookiecutter-django#190]
djangosecure package is defined in Production conf
middleware djangosecure.middleware.SecurityMiddleware is defined in Common conf

When running Local, leads to ImportError: No module named djangosecure.middleware

Considering that the middleware should be run before anything else, I added the middleware in Production this way:

```python
    # django-secure
    INSTALLED_APPS += (
        "djangosecure",
    )

    MIDDLEWARE_CLASSES = (
        # Make sure djangosecure.middleware.SecurityMiddleware is listed first
        'djangosecure.middleware.SecurityMiddleware',
    )
    MIDDLEWARE_CLASSES += Common.MIDDLEWARE_CLASSES
```

**Comment by theskumar** [comment]
Yeah. It makes sense to me. Thanks :+1:

**Comment by philippeluickx** [comment]
My pleasure, thans for merging!
