### ISSUE TITLE
Optionally make Celery able to access Django models

### ISSUE THREAD

**Issue by butla** [pydanny/cookiecutter-django#1904]
## Description
I would like for the option be added in the template to put

```python
import django; django.setup()

# import your models here AND NOT BEFORE setup()
```

before `app = Celery(...` in `{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/taskapp/celery.py` so that the Celery tasks can access Django models.

## Rationale
Some Celery tasks will probably want to interact with the DB (they do for my project), which is normally done through Django app's models, from my understanding. To use the models, Django needs to be initialized.

As, judging by that this isn't in the template already, this isn't needed by everyone, I'd make this optional.

There's a chance that there's a different way of making models work in tasks, I'm not experienced with Django.

## Use case(s) / visualization(s)

When going through the template creation you should be presented with the option in the form of a question: `Do you want your Celery tasks using Django models? (insert any text if you do)`. The default would be an empty string (as [real boolean options aren't yet there](https://github.com/audreyr/cookiecutter/issues/126)) that will result in not adding the bit of code I want. But if you do put something in, the text will get there.

**Comment by japrogramer** [comment]
I can use django models just fine ..

**Comment by butla** [comment]
Oh. Then from django's perspective, why would setup need to be called for me and not for you?

**Comment by japrogramer** [comment]
Show your whole celery file .. I'm not convinced you can't use model s.
I think you are importing them before they are ready

**Comment by foarsitter** [comment]
You cannot use your models as parameters of the tasks but use the id of the object an query it again in the async task. Maybe that is your problem? This works perfectly fine for my projects.

**Comment by butla** [comment]
@japrogramer Well, it works without any changes if I put Django model imports, which is what I should've done (don't know why I didn't think about it sooner).

Maybe adding a comment about it in the file will save somebody the same problem in the future? I could add that.
