### ISSUE TITLE
Replace django-environ library

### ISSUE THREAD

**Issue by jbagot** [pydanny/cookiecutter-django#1910]
## What happened?

django-environ is dead. There aren't commits since June 2018. Also the last version (0.4.5) has a big bug: 
https://github.com/joke2k/django-environ/issues/192

## What should've happened instead?

First of all I recommend to downgrade the version to 0.4.4 to avoid this bug. And then check another libraries like python-dotenv (https://github.com/theskumar/python-dotenv)

**Comment by browniebroke** [comment]
> django-environ is dead. There aren't commits since June 2018

I'm not sure I would declare an open source project "dead" after only 7 months without commits. AFAIK it's a pretty stable project which I believe is used across many production applications.

However, thanks for the report about this limitation, but unless it **directly** affects one of cookiecutter-django's environment, I'm not sure it's worth downgrading. I'll leave this open and leave it to our user's discretion to downgrade or not.

**Comment by jbagot** [comment]
I close the issue, the django-environ is not dead and they replied in the project and is not an issue anymore.
