### ISSUE TITLE
Docker containers fail to built without removing --no-cache-dir from pip install.

### ISSUE THREAD

**Issue by IAmNatch** [pydanny/cookiecutter-django#1929]
## What happened?
Running "docker-compose -f production.yml build" fails during pip installation.

## Steps to reproduce
[//]: # create cc-django docker project
[//]: # docker-compose -f production.yml build
### 

Currently I'm removing the line --no-cache-dir to resolve this issue.

**Comment by lioman** [comment]
There is an issue on pip repository: https://github.com/pypa/pip/issues/6197

**Comment by browniebroke** [comment]
As per above comment, this was related to an issue with pip which has now been fixed in pip 19.0.2 (see #1934). Should no longer be a problem.
