### ISSUE TITLE
Switch to mailgun

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#193]
For a number of reasons, mailgun is the right product to promote.

**Comment by benregn** [comment]
@pydanny Out of curiosity, could you elaborate on those reasons?

**Comment by pydanny** [comment]
Let's leave it at, "From a technical perspective, I prefer Mailgun more."

**Comment by theskumar** [comment]
Also I am experiencing that sendgrid sends email after a long time in the free version. Had to replace sendgrid with SES in most of my projects.

**Comment by benregn** [comment]
Have you guys any experience using Mandrill?  Because at a quick glance it
seems to support what Mailgun does but is cheaper.

**Comment by theskumar** [comment]
1. http://stackshare.io/stackups/mailgun-vs-sendgrid-vs-mandrill
2. https://www.quora.com/What-is-the-difference-between-Mandrill-and-Mailgun

PS: I've using SES in production and never had a complain. Although SES requires you to get production access. I've used mandrill a bit and it looked like a good product. No opinion on Mailgun.

**Comment by benregn** [comment]
@pydanny was not at all looking to change your mind on Mailgun, only curious to find out why you chose it - be it personal or technical reasons :smile: 

@theskumar I haven't used SNS or Mailgun, only Mandrill.  Don't remember Mandrill being slow on the free level and I like that they give you access to all of their features regardless of volume (they have a flat pricing structure).  Also they have pretty nice mobile apps.

As always just choose what fits you and the problem at hand :)

**Comment by burhan** [comment]
There is a 2000 email difference between the free quotas of both services; I prefer mailgun because their documentation is more friendly and clear to me.

I have [a fork that integrates it](https://github.com/burhan/cookiecutter-django/tree/feature/mailgun-support), if anyone is interested.

**Comment by pydanny** [comment]
I'm interested. Submit it as a PR! :smile:

**Comment by burhan** [comment]
I am using the API (not SMTP) for mailgun for better compatibility across networks.

**Comment by stepmr** [comment]
I think this should be closed :+1:
