### ISSUE TITLE
add example how to use mutiple domains in documentation

### ISSUE THREAD

**Issue by linuxluigi** [pydanny/cookiecutter-django#1931]
## Description

Add example in the documentation how to setup multiple domains for ``ALLOWED_HOSTS`` as environment variable. I tried many times to setup this right but couldn't figure out how to setup heroku environment for multiple domains.

## Rationale

Faster setup for some users.

## Use case(s) / visualization(s)

...

**Comment by browniebroke** [comment]
This is managed by `django-environ` in our setting, using [the `env.list()` API](https://django-environ.readthedocs.io/en/latest/index.html?highlight=list#environ.environ.Env.list):

https://github.com/pydanny/cookiecutter-django/blob/7fe87d9c97e9e3ad5d5efeaa239021d6754e4a6c/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/production.py#L13

The values it supports is not very well documented on their end, but looking at [their test data](https://github.com/joke2k/django-environ/blob/b32c07d7ed57cdeaef246f995a29e5fe39a076b3/environ/test_env.txt#L23) as well as [the code](https://github.com/joke2k/django-environ/blob/b32c07d7ed57cdeaef246f995a29e5fe39a076b3/environ/environ.py#L313), values are comma-separated. 

So the environment variable should look like this:

```
DJANGO_ALLOWED_HOSTS=domain.com,www.domain.com,api.domain.com
```

Maybe django-environ would accept a pull request to improve [the relevant docstring](https://github.com/joke2k/django-environ/blob/b32c07d7ed57cdeaef246f995a29e5fe39a076b3/environ/environ.py#L177)?

**Comment by linuxluigi** [comment]
Thanks you, now it works. It would be really nice if your example would be included in cookiecutter-djang documentation.

**Comment by browniebroke** [comment]
After some though, I think it belongs in `django-environ` docs, not in ours. When using this project, one should be aware of the underlying dependencies and look at their documentation when needed. I don't think we should start documenting this kind of cases ourselves.

If you feel like the use of `django-environ` isn't clear enough, however, feel free to send a pull request to add this where you see fit.
