### ISSUE TITLE
We need to ensure that pip is at least 19.0.2

### ISSUE THREAD

**Issue by ArtemBernatskyy** [pydanny/cookiecutter-django#1934]
## What happened?

When using with docker and building for production we receive this issue https://github.com/pypa/pip/issues/6197

## What should've happened instead?

Fixed via adding `RUN pip install --upgrade pip`
to `production/django/Dockerfile`

**Comment by browniebroke** [comment]
Hi, thanks for the report, but I don't think `cookiecutter-django` should implement a workaround/fix for this issue, as it's a temporary issue. Plus, it looks like [the base image has been fixed](https://github.com/docker-library/python/commit/65a048b4c3e198d418c9a5293446169e22336258) already.

**Comment by browniebroke** [comment]
Looks like the image hasn't been [updated yet on Dockerhub](https://github.com/docker-library/python/blob/662514b58264cff440912d93648ecf202a43f31c/3.6/alpine3.9/Dockerfile), I guess it'll be done when [this issue](https://github.com/docker-library/python/issues/380) is closed.

**Comment by browniebroke** [comment]
I'm leaving this open until the Alpine image is updated.

**Comment by browniebroke** [comment]
Should be fixed now, so closing this.
