### ISSUE TITLE
Upgrade to Gulp 4

### ISSUE THREAD

**Issue by takkaria** [pydanny/cookiecutter-django#1937]
There are several npm dependencies with known security issues or that aren't compatible with the latest version of browserslist or gulp (the version of cssnano this project uses is quite old and doesn't support all the browserslist queries that might be put in `package.json` now.).  It would be great to upgrade to Gulp 4 - is there interest for this from the maintainers?  I'm happy to do the work to make a pull request.

**Comment by browniebroke** [comment]
This would be very much welcome. I think we haven't updated our npm dependencies in a while and it would be great to update all of them!

**Comment by itaden1** [comment]
I made the upgrade to Gulp4 recently in a project generated from cookiecutter-django. Are you still working on this @takkaria ? Happy to share my Gulpfile if need be.

**Comment by takkaria** [comment]
@itaden1 i'm in a similar situation - I did the upgrade for a project but I haven't had time to get it upstream yet.  Race you to a pull request? 😆
