### ISSUE TITLE
Cookiecutter Django does not support Python 2....

### ISSUE THREAD

**Issue by KrunchMuffin** [pydanny/cookiecutter-django#1942]
## What happened?
Tried to run cookiecutter for django, ran through the options, go to the end and got the warning
> Cookiecutter Django does not support Python 2. Stability is guaranteed with Python 3.6+ only, are you sure you want to proceed (y/n)?

## What should've happened instead?
Not give the warning because I have 3.6.7 installed.

## Steps to reproduce

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
```
ubuntu 18.04 fresh install. 
derek@derek-ubuntu:~/PycharmProjects$ which python
/usr/bin/python
derek@derek-ubuntu:~/PycharmProjects$ python --version
Python 3.6.7
derek@derek-ubuntu:~/PycharmProjects$ python3 --version
Python 3.6.7
derek@derek-ubuntu:~/PycharmProjects$ python2 --version
Python 2.7.15rc1
```

```
derek@derek-ubuntu:~/PycharmProjects$ python
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
>>> import sys
>>> sys.version_info[0]
3
```

[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
```
{
    "cookiecutter": {
        "keep_local_envs_in_vcs": "n",
        "author_name": "Daniel Roy Greenfeld",
        "use_heroku": "y",
        "js_task_runner": "Gulp",
        "timezone": "UTC",
        "_template": "https://github.com/pydanny/cookiecutter-django",
        "use_compressor": "y",
        "use_celery": "n",
        "use_pycharm": "y",
        "project_slug": "my_awesome_project",
        "domain_name": "example.com",
        "version": "0.1.0",
        "email": "daniel-roy-greenfeld@example.com",
        "project_name": "My Awesome Project",
        "description": "Behold My Awesome Project!",
        "use_whitenoise": "y",
        "custom_bootstrap_compilation": "n",
        "use_travisci": "n",
        "windows": "n",
        "use_mailhog": "n",
        "debug": "n",
        "postgresql_version": "10.5",
        "use_docker": "n",
        "use_sentry": "y",
        "open_source_license": "Not open source"
    }
}
```

[//]: # (* Logs)

**Comment by browniebroke** [comment]
How have you installed the cookiecutter command line? I

**Comment by browniebroke** [comment]
PS Sorry, pressed the wrong button and closed by mistake

**Comment by browniebroke** [comment]
I've tried to change the Homebrew recipe a while ago, but the pull request was never merged: https://github.com/Homebrew/homebrew-core/pull/27028

**Comment by KrunchMuffin** [comment]
Yes I had cc installed. I went back to Windows so this is not an issue for me now, but should be fixed

**Comment by browniebroke** [comment]
Yes, you had cc installed, my question was more about **HOW** it was installed.

This warning is not checking that Python 3 is installed on your system, it only checks the version of Python which is used to run the cookiecutter CLI. If installed with Homebrew, it's running Python 2:

```
> which cookiecutter
/usr/local/bin/cookiecutter
> cat /usr/local/bin/cookiecutter
#!/usr/local/Cellar/cookiecutter/1.6.0/libexec/bin/python
...
> /usr/local/Cellar/cookiecutter/1.6.0/libexec/bin/python --version
Python 2.7.10
```

Maybe we can reword this warning to be less misleading, but I don't think we can check much more than that in this template.

This warning comes from here:

https://github.com/pydanny/cookiecutter-django/blob/6e72169ffe3022b54db3d44297226226cf86c1e8/hooks/pre_gen_project.py#L30-L34

Would you find it less confusing if it was worded like this?

> You're running cookiecutter under Python 2, but Cookiecutter Django generates a project only compatible with Python 3.6+. Do you want to proceed (y/n)?

**Comment by KrunchMuffin** [comment]
Wasn't homebrew, was via terminal. But you can see in my post I used the same cmd `sys.version_info[0]` and it gave me 3. Unless I am misunderstanding something?

**Comment by browniebroke** [comment]
It's not clear from your post where was `cookiecutter` installed. Maybe it was installed in another interpreter? Depending on your setup, the `python` command might point to Python 3, but `pip` still points at pip from Python 2. Then, the system is finding the first place where the command is installed, which end up being under Python 2.

A way to make sure it's installed in the right interpreter is to run it like this `python -m cookiecutter`. If you get this `Usage: cookiecutter [OPTIONS] TEMPLATE [EXTRA_CONTEXT]...`, it means it correctly installed there. Otherwise, you'd get `No module named cookiecutter`.

Under unix system, you can also check where the command is coming from using the `which` command from my previous message, take the shebang in this file and execute it to get the python version. I don't know how that works on Windows, unfortunately.

As a side note, I noticed that Homebrew is now using Python 3 to install cookiecutter.

**Comment by KrunchMuffin** [comment]
OK, I see now. CC is forcing python2 in the script itself. Confusing.
```
> python -m cookiecutter
Usage: cookiecutter [OPTIONS] TEMPLATE [EXTRA_CONTEXT]...

> which python
/usr/bin/python
> python --version
Python 3.6.7
> which cookiecutter
/usr/bin/cookiecutter
> cat /usr/bin/cookiecutter
#! /usr/bin/python2
> cd /usr/bin
```

**Comment by luzfcb** [comment]
@KrunchMuffin My personal rule: Never touch Python that comes installed by default in the operating system. Strange things can happen, and you may end up breaking something and being forced to reinstall the operating system. If you are using Linux or OSX, use [`pyenv`](https://github.com/pyenv/pyenv) to download the Python interpreter source code, compile it, install it on your user's home, and manage installations.

## Quick tutorial to OSX:

### 1 - Install Xcode from App Store, and all updates.

After, run this: 
```bash
xcode-select --install
```

### 2 - Install [Homebrew](https://brew.sh/)

```bash
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

### 3 - Install Git

```bash
brew install git
```
Create an SSH keypair: 
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

Add your public SSH key to your GitHub account: 
https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

### 4 - Install Pyenv Via Homebrew

```bash
brew install pyenv
brew install pyenv-virtualenv
brew install pyenv-virtualenvwrapper
```

#### Configure Pyenv With Your Shell

Add this to `$HOME/.bash_profile`

```bash
if [ -r ~/.bashrc ]; then
   source ~/.bashrc
fi
```
After that, your `$HOME/.bash_profile` should contain only the content above

Add this to `$HOME/.bashrc`
```bash
# directory that contains the virtualenvs of all projects
export WORKON_HOME=~/.virtualenvs
# directory that contains the projects
export PROJECT_HOME=~/projects

# enable pyenv
eval "$(pyenv init -)"

# enable pyenv virtualenvwrapper plugin
pyenv virtualenvwrapper_lazy

```

Close your terminal/iterm and open again.

### 5 - Install Python via pyenv

```bash
# download and compile python 3.7.2
pyenv install 3.7.2
# download and compile python 2.7.15
pyenv install 2.7.15
# set "python", "python3", "python3.7" to point python3.7.2, and "python2" and "python2.7" to point python2.7.15
pyenv global 3.7.2 2.7.15
```

## Quick tutorial to Ubuntu based Linux:

https://gist.github.com/luzfcb/1a7f64adf5d12c2d357d0b4319fe9dcd

**Comment by KrunchMuffin** [comment]
OK, thanks for the info.
