### ISSUE TITLE
Flower - Tornado version in dependency preventing start 

### ISSUE THREAD

**Issue by rich5851** [pydanny/cookiecutter-django#1953]
## What happened before?
Flower started with no issues

## What happens now?
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/flower/api/tasks.py", line 83, in TaskApply
celeryworker_1  |     @web.asynchronous
celeryworker_1  | AttributeError: module 'tornado.web' has no attribute 'asynchronous'

## Steps to reproduce
docker local and production setup with celery and flower
docker-compose build and docker-compose run

Fixed by adding tornado==4.5.2 at the bottom of requirements/base.txt

**Comment by luzfcb** [comment]
Thanks to report, but is duplicated to https://github.com/pydanny/cookiecutter-django/pull/1949
