### ISSUE TITLE
Add py.test as testing runner/framework

### ISSUE THREAD

**Issue by theskumar** [pydanny/cookiecutter-django#196]
Inspired by https://github.com/taigaio/taiga-back. It will bring all the awesomeness of py.test like parallel testing, plugins and whole lot of other things, while supporting the existing way of writing test. It's a no brainer to anyone who has not been using py.test. 

Things to do:

- modify requirements
- add pytest configuration
- demonstrate on working test project

__References__

1. http://pytest.org/latest/

**Comment by pydanny** [comment]
:+1:

**Comment by theskumar** [comment]
Want to include this as a part of pytest adoption initiative http://pytest.org/latest/adopt.html too :blush:

**Comment by pydanny** [comment]
I do. :+1:

**Comment by luzfcb** [comment]
@theskumar @pydanny this is beautiful: https://github.com/Frozenball/pytest-sugar

**Comment by pydanny** [comment]
I might give this a whirl soon.

**Comment by pydanny** [comment]
Resolved in 05abf35. Added py.test sugar because @luzfcb is right, it's beatiful!
