### ISSUE TITLE
Remove coreapi requirement

### ISSUE THREAD

**Issue by greyhare** [pydanny/cookiecutter-django#1969]
## Description

The ``coreapi`` requirement should be removed from ``requirements/base.txt``.

## Rationale

From the [CoreAPI](https://github.com/core-api/core-api/) page:

>DEPRECATION NOTICE: As of djangorestframework 3.9, the plan is to phase out CoreAPI in favor of OpenAPI as the default schema representation. New projects should consider using OpenAPI rather than CoreAPI. See the DRF 3.9 release announcment for more details.

The [DRF 3.9 page](https://www.django-rest-framework.org/community/3.9-announcement/#whats-next) has an example of how to use the integrated OpenAPI support.

## Use case(s) / visualization(s)

None. It's a requirement for a module no longer developed. If it's used somewhere in the template that I've missed, it should be replaced with [OpenAPI](https://www.openapis.org/) equivalents.

I only noticed it because I'm going through a Django project generated by this cookiecutter and can't explain why the requirement exists.

**Comment by browniebroke** [comment]
Thanks for this report. DRF (and Core API) are not directly used by the generated project, but it's so common to find them in Django projects that [they have been added](https://github.com/pydanny/cookiecutter-django/commit/d6e0b95d81c0ea98f54a7d0d1e8a0064ef762888) by default.

It should be easy to remove it, pull requests are welcome!

**Comment by greyhare** [comment]
LOL maybe later, especially if "present but not used" is intended behavior.

If I'm going to the effort of a pull request, I'll wait until it's something more substantial, like say adding an actual DRF option to the template. Especially since I'll be constantly rebasing as pyupbot moves master along. (It's changing the same files, after all.)

I just figured this was something that could be rolled into some other minor fix update. Right now I'm in "I'm new here and might break things" mode.

**Comment by greyhare** [comment]
Another fix to toss on there: in ``.gitignore``,

    ### VirtualEnv template
    # Virtualenv
    # http://iamzed.com/2009/05/07/a-primer-on-virtualenv/

URL is 404. Suggested replacement: https://www.simononsoftware.com/virtualenv-tutorial-part-2/

**Comment by browniebroke** [comment]
Can you please avoid chucking unrelated problems you find in the same GitHub issue? 

I appreciate the effort to report problems, but it's easier to actually fix them if they are in separate issues. 

Thanks again.

**Comment by greyhare** [comment]
OK, that's now #1972.

**Comment by demestav** [comment]
Are you sure `CoreAPI` is not used? The deprecation note talks about "phasing out". In DRF documentation, there are instructions to install it in order to generate the API documentation (https://www.django-rest-framework.org/topics/documenting-your-api/).

**Comment by greyhare** [comment]
I'm running a project generated from this cookiecutter that has DRF v3.9.1 installed and no coreapi package, and I think I'm seeing the API doc screens fine. They're the ones that look like this, right?


![apiroot_page](https://user-images.githubusercontent.com/18636280/54856899-ac570680-4cca-11e9-8c72-5c08ec098745.png)

**Comment by luzfcb** [comment]
@greyhare No, this is not the documentation.

```python
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    # ...
    url(r'^docs/', include_docs_urls(title='My API title'))
]
```

https://www.django-rest-framework.org/topics/documenting-your-api/#installation

**Comment by greyhare** [comment]
Those instructions result in:

    AssertionError: `coreapi` must be installed for schema support.

And it looks like CoreAPI is still hardwired. So the question is now "Do you want a dependency that is an archived GitHub project with no developers, hoping that the DRF crew replace it someday, and even though the template does not even provide commented-out URLconfs or settings for anything DRF?"

**Comment by foarsitter** [comment]
Is it an idea to add an extra option `use_api_tools` to cookiecutter? This give us the options to add more packages useful for API development like: 
```
django-cors-headers
django-rest-auth
drf-yasg
```

**Comment by carlmjohnson** [comment]
FWIW, Core API depends on Jinja, which has a security vulnerability in 2.10.0, so this isn't a "freebie" dependency.

**Comment by morenoh149** [comment]
so what's the fix just remove the line from requirements.txt?

**Comment by cole** [comment]
coreapi has clearly been deprecated by DRF (see the [3.10 release announcement](https://www.django-rest-framework.org/community/3.10-announcement/)) The method of generating documentation given above is no longer recommended in the docs.
