### ISSUE TITLE
And and encourage use of 'CHANGELOG.md'

### ISSUE THREAD

**Issue by theskumar** [pydanny/cookiecutter-django#198]
Olivier Lacan (@olivierlacan) has put up a nice website[1] explaining the logic and reasoning behind using `CHANGELOG.md` with a prescribed format. 

We can just put a default `CHANGELOG.md` in generated project with default prescribed formatting and link to read further. 

__References__

- http://keepachangelog.com/
- https://github.com/olivierlacan/keep-a-changelog
- http://5by5.tv/changelog/127

**Comment by pydanny** [comment]
:+1:

**Comment by pydanny** [comment]
Began the changelog.md file.
