### ISSUE TITLE
Add PostgreSQL 11 as an option 

### ISSUE THREAD

**Issue by browniebroke** [pydanny/cookiecutter-django#1989]
## Description

It's been out for a few months. I also suggest removing older version of PostgreSQL 10, and just keep the latest version. They changed their [versioning policy in v10](https://www.postgresql.org/support/versioning/), which means that 10.1 vs 10.2 is the same type of change as 9.6.1 vs 9.6.2 was. 

## Rationale

We should provide recent versions, and not overload with minor versions.

## Use case(s) / visualization(s)

Update options in `cookiecutter.json`, and documentation where applicable.

**Comment by blaise-sumo** [comment]
FWIW, @browniebroke I have Postgresql 11.2 and I just tried to `pip install requirements/local.txt` and it fails at psycopg2:
```
Command "/Users/blaise/.local/share/virtualenvs/lens-0NGmQ8l5/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/ln/r9gkbz5d0rgcmrh23n9cqlnr0000gp/T/pip-install-axjv4atk/psycopg2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ln/r9gkbz5d0rgcmrh23n9cqlnr0000gp/T/pip-record-x_ytiog6/install-record.txt --single-version-externally-managed --compile --install-headers /Users/blaise/.local/share/virtualenvs/lens-0NGmQ8l5/bin/../include/site/python3.7/psycopg2" failed with error code 1 in /private/var/folders/ln/r9gkbz5d0rgcmrh23n9cqlnr0000gp/T/pip-install-axjv4atk/psycopg2/
```
It could be a coincidence, but the timing seems suspicious.

**Comment by luzfcb** [comment]
@blaise-sumo be sure to have `libpq-dev` installed previously.

```
sudo apt-get install libpq-dev
```

**Comment by blaisep** [comment]
Thank you @luzfcb ,  I solved the problem with a tip from https://stackoverflow.com/questions/9678408/cant-install-psycopg2-with-pip-in-virtualenv-on-mac-os-x-10-7
In one of the comments, they mention how to pull the LDFLAGS and include the current values into the pip install line:
```
pg_config --ldflags
-L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -Wl,-dead_strip_dylibs
```

In my case I had python 3.6.7 and Postgresql 11.2, so I wasn't sure which psycopg2 I needed:
```
env LDFLAGS='-L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -Wl,-dead_strip_dylibs' pip install psycopg2
...
Successfully installed psycopg2-2.8.2
```
