### ISSUE TITLE
Issues installing on Pixelbook

### ISSUE THREAD

**Issue by chr1s3sw0rthy** [pydanny/cookiecutter-django#1999]
## What happened?

Installing latest version on Pixelbook. Pixelbook Debian has Python 3.5.3. Had to revert to a previous version of cookiecutter-django.

I had to search quite a bit for the command to install a previous version.

## What should've happened instead?

Please make this command more prominent in the docs.

## Steps to reproduce

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
[//]: # (* Logs)

Thank you.

**Comment by browniebroke** [comment]
This project is Python 3.6 only, it's listed quite high in the README:

> Works with Python 3.6

Not sure what else you're asking for here?

**Comment by chr1s3sw0rthy** [comment]
Yes - latest version works with 3.6.

Im on a pixelbook (Debian) and only have 3.5.3. I was looking for the command to install a prior version of cookiecutter-django. I finally found it (thank you internet_hive_mind.).

low priority.
