### ISSUE TITLE
Enabling whitenoise in production does not work

### ISSUE THREAD

**Issue by cvipul** [pydanny/cookiecutter-django#2000]
## What happened?
I am trying to use whitenoise in my production, but its not getting activated (as I can see the static files still being served from app server and not the cloudfront set up in whitenoise settings)

I believe the problem is with cookiecutter adding the whitenoise middleware to the end of middleware list (appending in production.py to a list created in base.py)

## What should've happened instead?
Whereas, in the documentation of whitenoise (http://whitenoise.evans.io/en/latest/django.html#enable-whitenoise) we are expected to add it directly after the security middleware and before everything else

## Steps to reproduce
Just setup a project in django with whitenoise enabled.
Configure it for cloudfront as provided in whitenoise documentation and check whether its functioning

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
[//]: # (* Logs)

**Comment by Marpop** [comment]
Have you tried to include whitenoise middleware directly inside middleware list in base settings?

**Comment by browniebroke** [comment]
> cookiecutter adding the whitenoise middleware to the end of middleware

Are you using the latest version of the template? It doesn't look like it's added at the end of the list currently:

https://github.com/pydanny/cookiecutter-django/blob/74ed3ab7152bb178f4b589d6e988b78908c9c578/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/production.py#L174

It does insert, not append. This should add it in 2nd position, as expected by Whitenoise.

**Comment by cvipul** [comment]
Sorry, my mistake @browniebroke this was fixed in Sep 2018, I deployed via cookiecutter before that.
@Marpop I will make the similar changes, try and let you know if whitenoise starts working.

Thanks for your responses.

**Comment by browniebroke** [comment]
This doesn't look like an issue with cookiecutter-django, so closing this for now. I'll reopen if you find anything wrongly setup here. Otherwise, best to check with Whitenoise directly.

Thanks
