### ISSUE TITLE
Docs are out of date

### ISSUE THREAD

**Issue by browniebroke** [pydanny/cookiecutter-django#2004]
## What happened?

The docs are not being updated anymore. It looks like RTD hasn't been building [in the past 3 months](https://readthedocs.org/projects/cookiecutter-django/builds/). Looks like it's due to a change in how they receive webhooks: https://blog.readthedocs.com/webhook-deprecations/

We'll need to update the webhooks in the repo settings to the new URL.

**Comment by browniebroke** [comment]
I don't have access to update the webhook, so in the meantime, I've deployed the latest version here: https://cookiecutter-django-mirror.readthedocs.io/en/latest/index.html

**Comment by sfdye** [comment]
![image](https://user-images.githubusercontent.com/1016390/56255107-2aee6a80-60f6-11e9-9f25-705bd5d26c79.png)
Fixed by @luzfcb
