### ISSUE TITLE
Documentation needs to be updated to add details on Google Cloud Storage

### ISSUE THREAD

**Issue by burhan** [pydanny/cookiecutter-django#2026]
## Description

The documentation needs to be updated to reflect that Google Cloud Storage is now an option, in addition to S3.

[//]: # (What's it you're proposing? How should it be implemented?)

Update the relevant files

## Rationale

[//]: # (Why should this feature be implemented?)

## Use case(s) / visualization(s)

[//]: # ("Better to see something once than to hear about it a thousand times.")

**Comment by vladdoster** [comment]
Could I knock this out? I would love to contribute back to a project I have used alot.

**Comment by burhan** [comment]
Absolutely. Tag me if you need any help.

**Comment by browniebroke** [comment]
Link to the pull request which added the code: https://github.com/pydanny/cookiecutter-django/pull/2012
