### ISSUE TITLE
docker-compose -f local.yml build

### ISSUE THREAD

**Issue by elpablo92** [pydanny/cookiecutter-django#2042]
What happened? help please 
Building postgres ERROR: 
invalid reference format: repository name must be lowercase

**Comment by browniebroke** [comment]
Can you please provide more details to help reproduce the problem? What options have you selected? Full error logs would help too.

**Comment by elpablo92** [comment]
pablo@pabloPC:~/Django_projects/Docker_store$ cookiecutter https://github.com/pydanny/cookiecutter-django
You've downloaded /home/pablo/.cookiecutters/cookiecutter-django before. Is it okay to delete and re-download it? [yes]: yes
project_name [My Awesome Project]: Store
project_slug [store]: Docker_store
description [Behold My Awesome Project!]: 
author_name [Daniel Roy Greenfeld]:    
domain_name [example.com]: 
email [daniel-roy-greenfeld@example.com]: zapeta.pablo@gmail.com
version [0.1.0]: 
Select open_source_license:
1 - MIT
2 - BSD
3 - GPLv3
4 - Apache Software License 2.0
5 - Not open source
Choose from 1, 2, 3, 4, 5 (1, 2, 3, 4, 5) [1]: 1
timezone [UTC]: UTC
windows [n]: n
use_pycharm [n]: n
use_docker [n]: y
Select postgresql_version:
1 - 10.5
2 - 10.4
3 - 10.3
4 - 10.2
5 - 10.1
6 - 9.6
7 - 9.5
8 - 9.4
9 - 9.3
Choose from 1, 2, 3, 4, 5, 6, 7, 8, 9 (1, 2, 3, 4, 5, 6, 7, 8, 9) [1]: 
Select js_task_runner:
1 - None
2 - Gulp
Choose from 1, 2 (1, 2) [1]: 
Select cloud_provider:
1 - AWS
2 - GCE
Choose from 1, 2 (1, 2) [1]: 
custom_bootstrap_compilation [n]: n
use_compressor [n]: y
use_celery [n]: n
use_mailhog [n]: n
use_sentry [n]: n
use_whitenoise [n]: y
use_heroku [n]: n
use_travisci [n]: n
keep_local_envs_in_vcs [y]: 
debug [n]: y
 [SUCCESS]: Project initialized, keep up the good work!

then cd docker_store
then sudo docker-compose -f local.yml build
return 
pablo@pabloPC:~/Django_projects/Docker_store$ docker-compose -f local.yml build
Building postgres
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
pablo@pabloPC:~/Django_projects/Docker_store$

**Comment by elpablo92** [comment]
create another project and it worked !!! I had created another three and these did not work I do not know what happened but thank you very much for the prompt response

**Comment by browniebroke** [comment]
If I had to guess, I'd say that it's because `project_slug` should be lowercase and that you added a capital letter in yours. I haven't tested, though.

If that's the problem, we should have a better error somewhere when generating the project, to tell the users that uppercase is not accepted in slug.

Something that could help: https://github.com/lwanger/cooked_input

**Comment by elpablo92** [comment]
exactly, that was the problem, thank you very much for your prompt response
