### ISSUE TITLE
Problems with the database

### ISSUE THREAD

**Issue by flaviobarros** [pydanny/cookiecutter-django#206]
I'm using a docker based postgres. I'm setting the database with:

docker run -p ::5432 \
--name db \
-e POSTGRESQL_DB=hartl \
-e POSTGRESQL_USER=docker \
-e POSTGRESQL_PASS=docker \
kamui/postgresql

and it's ok and working from terminal. After this i used the DATABASE_URL as an environment variable:

> export DATABASE_URL=postgres://docker:docker@dbserver_ip:5432/hartl

as my variable is postgres://docker:docker@dbserver_ip:5432/hartl.

BUT when i try:

> python myapp/manage.py migrate 

i'm having this error:

django.core.exceptions.ImproperlyConfigured: Error importing module dj_database_url: "No module named dj_database_url"

what can be wrong?

**Comment by pydanny** [comment]
Did you install all your pip requirements?

**Comment by flaviobarros** [comment]
Was a pip problem. Fixed.
