### ISSUE TITLE
Upgrade Werkzeug version to 0.15+

### ISSUE THREAD

**Issue by browniebroke** [pydanny/cookiecutter-django#2077]
## Description

We had to revert to Werkzeug <0.15 due to a bug with Docker on Windows (see #2070). It looks like we do something wrong in our scripts which is not compatible with Werkzeug 0.15+.

When we upgrade, we should check that everything works on Windows (with and without Docker).

**Comment by foarsitter** [comment]
Just updated two projects to `Werkzeug==0.16.0` on my Windows machine and everything is running fine.
