### ISSUE TITLE
upgrade to django 1.8

### ISSUE THREAD

**Issue by saurabh-fueled** [pydanny/cookiecutter-django#208]
TODO:

- [x] update requirements.txt.
- [ ] `django.middleware.security.SecurityMiddleware` integration w.r.t [django-secure update]
- [x] check compatibility with each of the included third-party party lib.
- [x] mention that [postgres suppport] is now 9.0+ only 
- [ ] make 1.7 tagged release
- [ ] ...

__Roadblocks__

- [x] ~~django-configurations 0.8 is not compatible with django 1.8, it requires a [new release][djc-release]~~. (django-configuration is no longer used)
- [x] django-avatar doesn't have support for django 1.8 (drop support)

__References__

[1] https://www.djangoproject.com/weblog/2015/apr/01/release-18-final/
[2] https://docs.djangoproject.com/en/1.8/releases/1.8/
[postgres suppport]: https://docs.djangoproject.com/en/1.8/releases/1.8/#support-for-postgresql-versions-older-than-9-0
[django-secure update]: https://docs.djangoproject.com/en/1.8/releases/1.8/#security-enhancements
[djc-release]: https://github.com/jezdez/django-configurations/issues/105

**Comment by saurabh-fueled** [comment]
Added things to do in order to upgrade this project to use latest django 1.8. If I'm missing something let me know.

@pydanny @luzfcb

**Comment by jayfk** [comment]
django-configurations works when installed from source.

**Comment by pydanny** [comment]
@jayfk Yes it does, but we should have a tagged release. What about a temporary fork with a DeprecationWarning?

**Comment by pydanny** [comment]
After trying Django 1.8 on cookiecutter-django, I discovered a lot of packages aren't quite ready to work with Django 1.8. Therefore, I'm implementing some stuff in a branch that might mitigate a lot of the issues. I'll put something up in a bit.

**Comment by theskumar** [comment]
Sounds like a plan. :

**Comment by theskumar** [comment]
We now have one roadblock out of our way. A much simpler library `django-environ`[1] by @joke2k is used now, instead of `django-configuration`  (#215).

[1] https://github.com/joke2k/django-environ
