### ISSUE TITLE
Celery task time limit not working

### ISSUE THREAD

**Issue by demestav** [pydanny/cookiecutter-django#2080]
## What happened?
Celery worker is set to timeout after 10 seconds with soft timeout of 5 seconds. A delay is introduced to the celery task in order to cause a timeout.

**The timeout Exception is never raised by Celery worker.**

## What should've happened instead?
A [timeout Exception](https://docs.celeryproject.org/en/latest/reference/celery.exceptions.html#celery.exceptions.SoftTimeLimitExceeded) should have been raised by Celery worker.

## Steps to reproduce
1. Set the appropriate values (10 and 5) to the following settings:
https://github.com/pydanny/cookiecutter-django/blob/729dddcab6afacdce49f5ce200af1c1b97ebbbea/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/base.py#L267-L272
2. Make sure that the task is run by celery worker, not by Django by setting the following to `False`:
https://github.com/pydanny/cookiecutter-django/blob/729dddcab6afacdce49f5ce200af1c1b97ebbbea/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/local.py#L80-L84
3. Add a delay to the task longer than the timeout:
```python
...
import time
time.sleep(15)
...
```

## Note
I was able to make this work (Exception raised, and restart worker) by changing `CELERYD_TASK_TIME_LIMIT` to `CELERY_TASK_TIME_LIMIT` and `CELERYD_TASK_SOFT_TIME_LIMIT` to `CELERY_TASK_SOFT_TIME_LIMIT`. 

However, the original names are the correct ones as per the [documentation of Celery](https://docs.celeryproject.org/en/latest/userguide/configuration.html#new-lowercase-settings). 

Not sure why this happens yet, but I am guessing that since the celery settings are loaded with the namespace option, they are later converted to the new type of settings. Therefore, when defining them with `CELERYD_...` maybe they weren't picked up by the configuration manager of Celery.
https://github.com/pydanny/cookiecutter-django/blob/b039e241302deeeec211ea5bf80c61254dede022/%7B%7Bcookiecutter.project_slug%7D%7D/config/celery_app.py#L11-L13

**Comment by browniebroke** [comment]
Thanks for the report, looks like the fix is to chnage the settings name then. The [Celery doc about Django](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html) says:

> The uppercase name-space means that all Celery configuration options must be specified in uppercase instead of lowercase, and start with `CELERY_`, so for example the `task_always_eager` setting becomes `CELERY_TASK_ALWAYS_EAGER`, and the `broker_url` setting becomes `CELERY_BROKER_URL`.

It's not super explicit that it also affects workers-related settings prefixed `CELERYD_` but if you looks into [their test suite](https://github.com/celery/celery/blob/193be0be9dd8b925b3a46fed80887e73707db935/t/unit/app/test_app.py#L323-L337) that's how it works: it's `CELERY_WORKER_AGENT` instead of `CELERYD_WORKER_AGENT`.
