### ISSUE TITLE
No support for python3? I am getting: invalid syntax: raise ValueError, "No frame marked with %s." % fname

### ISSUE THREAD

**Issue by emanresu92** [pydanny/cookiecutter-django#2106]
File "/home/user/hosting/cookiecutter/lib/python3.6/site-packages/environ.py", line 114
    raise ValueError, "No frame marked with %s." % fname
                    ^
SyntaxError: invalid syntax

**Comment by travelspun** [comment]
Anyone solve this?  Same error for me

**Comment by luzfcb** [comment]
@travelspun if your error is the same, please, open a new issue in the django-environ ( https://github.com/joke2k/django-environ )describe how to reproduce the error.

**Comment by tiborsimon** [comment]
For me the issue was that I installed the `environ` package instead of the `django-environ` package.

**Comment by hobson** [comment]
Same here @tiborsimon

**Comment by parnus01** [comment]
any update for this error ?

**Comment by evilbullet** [comment]
same, year 2020

**Comment by evilbullet** [comment]
> For me the issue was that I installed the `environ` package instead of the `django-environ` package.

solved

**Comment by webdagger** [comment]
> django-environ

This worked for me.

**Comment by brianetaveras** [comment]
> For me the issue was that I installed the `environ` package instead of the `django-environ` package.

Thank you! This solved my issue :)

**Comment by kayuzee** [comment]
> For me the issue was that I installed the `environ` package instead of the `django-environ` package.

This worked for me as well! I was looking at my django project as a template but actually needed 

```
from dotenv import load_dotenv
load_dotenv()
```

Instead of 

`import env`

**Comment by Nandita2704** [comment]
> For me the issue was that I installed the `environ` package instead of the `django-environ` package.

thanks, I also solve my error through this term

**Comment by info3g** [comment]
i got same error please give me correct reply. thanks in advance

**Comment by yusufadell** [comment]
> For me the issue was that I installed the `environ` package instead of the `django-environ` package.

Thaks, solved for me...

**Comment by kilicheva** [comment]
same, year  2021

**Comment by foarsitter** [comment]
@kilicheva the same what? Same error? Same solution? Commenting with no information on a closed issue is not gone help anyone.

**Comment by mathpadam** [comment]
Same error when use it with Python 3.8.5

**Comment by foarsitter** [comment]
@mathpadam and the solution posted in https://github.com/cookiecutter/cookiecutter-django/issues/2106#issuecomment-553089821 did not resolve it?

**Comment by hobson** [comment]
@foarsitter people just install your dependencies one at a time in their environment. So if they typo any of the dependencies in their requirements.txt or environment.yml or whatever they have this problem. It's a know issue with pip. Hackers use it to get ususpecting users to install malicious packages.  Only think you can do about it is have a very unique and easy to spell/remember package name and contact any other package maintainers that squat near your name.

**Comment by CRodz13** [comment]
> For me the issue was that I installed the `environ` package instead of the `django-environ` package.

Worked for me perfectly.  Sometimes youre just in a groove throwing elbows with pip installs and you forget

**Comment by ramona-2020** [comment]
Same here 2022

**Comment by Rafilek** [comment]
Solved: issue was that I installed the environ package instead of the django-environ package. (Ubuntu 20.04)

**Comment by GoudekettingRM** [comment]
Installed `django-environ` instead of `environ` and still get the same error...

**Comment by rubenba2** [comment]
@GoudekettingRM I get the same. Did you find why?

**Comment by ss-sebastian** [comment]
> Installed `django-environ` instead of `environ` and still get the same error...

same here
