### ISSUE TITLE
Why aren’t you using just one configuration file (12-Factor App)?

### ISSUE THREAD

**Issue by danihodovic** [pydanny/cookiecutter-django#2118]
This question is outlined in the Q&A, but there is no answer to it. I think this project looks really good, but it comes with a massive complexity cost w.r.t configuration management due to maintaining three environments: local, test, prod.

Ideally the configuration should be the same and configured using environment variables (injected from deployment tools or envrc locally). I understand that production needs hardened security configuration, but you could achieve this with a DEBUG flag and conditional statements. With three files it's hard to reason about what configuration flags are enabled when.

Could someone enlighten me as to why:
-  3 (4 including base.py) settings files are required
- 4 requirements.txt files are required
- 2 Dockerfiles are required
- 2 env files are required
- 2 docker-compose.yml files are required (are people using docker-compose on single instances without any failover in production...?)

I'm not trying to be a negative nancy; I'm wondering if this project could be simplified a little bit.

**Comment by danihodovic** [comment]
After digging deeper into the project the separation of configs make sense:

- ability to serve static files locally without running S3 or a S3 mock
- hardened security settings in production
- improved performance for tests

Django's middle-wares abstract the different backends for images and static files nicely between environments.

I've forked and removed the additional requirements.txt and Dockerfiles as I consider that too much overhead. I prefer a larger image with less complexity and reproducible builds between local / test / prod.

Thank you for your work on this project, I learned quite a few new things by reading the code...

**Comment by Afrowave** [comment]
Thank you @danihodovic for looking through the code. @pydanny and @audreyr wrote the book on the thinking behind Cookiecutter Django. It is the [Two Scoops of Django](https://www.twoscoopspress.com/products/two-scoops-of-django-1-11). You may have a look. I learnt a lot from it.
