### ISSUE TITLE
Add isort

### ISSUE THREAD

**Issue by danihodovic** [pydanny/cookiecutter-django#2123]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)

isort is an opinionated formatter that sorts imports.
https://github.com/timothycrosley/isort

The following sort cfgs would make it compatible with black:
```
$ cat .isort.cfg
[settings]
recursive=True
skip=venv
skip_glob=**/migrations/*.py
atomic=True
multi_line_output=3
include_trailing_comma=True
force_grid_wrap=0
use_parentheses=True
line_length=<line_len>
```

## Rationale

[//]: # (Why should this feature be implemented?)

We already use black to sort code, but black doesn't sort imports. We isort we can deterministically sort imports and avoid manual maintainance of import order.

## Use case(s) / visualization(s)

[//]: # ("Better to see something once than to hear about it a thousand times.")

**Comment by luzfcb** [comment]
cookiecutter-django already has some settings for isort.
The isort going to use the editorconfig file

https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.editorconfig

what you can do is make the current setting also compatible with black
