### ISSUE TITLE
Add an option to choose default email backend (AWS SES or Mailgun)

### ISSUE THREAD

**Issue by mostaszewski** [pydanny/cookiecutter-django#2140]
## Description

Add an option to choose default email backend (AWS SES or Mailgun)

## Rationale

Currently Mailgun is set as a default email backend.
In my opinion it would be nice to add an option to choose default email backend (AWS SES or Mailgun).

## Use case(s) / visualization(s)

`
"default_email_backend": [
    "Mailgun",
    "AWS SES"
  ],
`

I can do it if You will decide to add this feature.
Thanks

**Comment by browniebroke** [comment]
Why add only SES and not any [other ESP](https://anymail.readthedocs.io/en/stable/esps/) provided by `django-anymail`? Should we allow no ESP too? That could make the template a fair bit more complex I think.

I'm a bit on the fence on this, but if you put together a pull request, that mnight convince me :)

**Comment by mostaszewski** [comment]
@browniebroke Sure, it is a good idea to add other ESP either. 
I focused only on my needs so that is why I forgot about rest of providers.
I will create a pull request in a few days.
