### ISSUE TITLE
403_csrf.html should be 403.html, no?

### ISSUE THREAD

**Issue by step21** [pydanny/cookiecutter-django#2163]
## What happened?
When testing a custom 403 page, I would expect the 403_csrf.html template to map to 403_csrf in debug mode.

## What should've happened instead?
 However instead this only works and maps to 403 if it is renamed to 403.html

## Steps to reproduce
Make a django-cookiecutter site. Change the default 403_csrf template.

**Comment by browniebroke** [comment]
Looking at the view it maps to, it's a Django view, which is indeed expecting the file to be called `403.html`.

https://github.com/django/django/blob/master/django/views/defaults.py#L11

Feel free to send a pull request to fix it.
