### ISSUE TITLE
Version as an environment variable

### ISSUE THREAD

**Issue by demestav** [pydanny/cookiecutter-django#2164]
## Description
Right now the version of the project is defined explicitly here:
https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/__init__.py

## Rationale
It is possible that I am missing the purpose of the `__version__` variable, but it would fit the current structure of the project, if this value was set as an environment variable.

What are your thoughts on this?

**Comment by browniebroke** [comment]
This was introduced in 2013 as part of #52. Looking at the purpose of the pull request, I don't think it makes sense to make it an environment variable, this is more somthing that belong in source control. 

However, I don't think it's of much use now, things that were added back in this pull request are now gone (e.g. `setup.py`).

**Comment by demestav** [comment]
So, how should we proceed with this?

Also since we are on the subject, what is you suggested way to keep the version of a project? There are use-cases that the version has to be exposed to the client, which requires the version variable to be kept within the application context.

**Comment by browniebroke** [comment]
I don't have any problems with how things are currently, so as far as I'm concerned, I don't see a reason to change it. 

For your second question, I think it really depends on your project. I've seen it working with git tags, docker tags or no version at all (running with latest/master).

**Comment by demestav** [comment]
:+1: So we are closing this.

**Comment by luzfcb** [comment]
@demestav you can create a [template context processor](https://docs.djangoproject.com/en/2.2/topics/templates/#context-processors) to inject the version into the template context and use it to expose the version to the user.

**Comment by demestav** [comment]
@luzfcb Thank you. I agree with you, however, what I was referring to, was the process of storing the version within the Django application, in order to then go and expose it (using for example the method you said above).

Therefore, having the version as an environment variable rather than explicitly defining in `__init__.py` provides a way to set the version number dynamically.

**Comment by luzfcb** [comment]
@demestav for me it does not make sense to configure the version number dynamically from an environment variable. In my mind, the concept of software version is closely linked to the application codebase itself. You end up losing control of what exact version of the application is running on a given server. This is really critical when you have multiple parallel instances of the application, behind a load balancer.

In one of the projects I participated in, I used to use the git tag as a version. In this project, deploy was only done from the git tag and never from the master or other branches.

Does it make sense?

**Comment by demestav** [comment]
@luzfcb Thank you for the insightful information! Indeed what you describe is what I want to achieve. How would you go and define the version variable to the git tag? This is where I thought the environment variable fits in; it is set before the application starts to the appropriate value which is then injected in the Django application.

**Comment by luzfcb** [comment]
@demestav maybe something like this in your `config/settings/base.py`
```python
from subprocess import check_output

def get_current_git_tag():
     current_commit_short_hash = check_output("git log -n1 --pretty='%h'".split()).decode().replace("\n", "").replace("'", "")
     return check_output(f"git describe --exact-match --tags {current_commit_short_hash}".split()).decode().replace("\n", "").replace("'", "")

CURRENT_GIT_TAG = get_current_git_tag()
```
