### ISSUE TITLE
Cookiecutter in VisualStudio

### ISSUE THREAD

**Issue by Drak0** [pydanny/cookiecutter-django#2176]
Hello,

i've followed the guides for creating a project from cookiecutter in Visualstudio 2015. 
after the project is created, i cannot seem to get the tasks run.

Appreciate your kind support.

**Comment by browniebroke** [comment]
I've never used Visualstudio 2015 to write Python, and I don't think we support any sort of integration with it. Can you link to the guide you followed? What error are you getting? What configuration have you selected when generating the project?

I know there is an issue with docker-compose on Windows, but it's not a problem with the template, see #2074.

**Comment by pydanny** [comment]
We do not officially support VisualStudio. If Microsoft wants us to support it, they can lend us the help of their VS team.
