### ISSUE TITLE
Lack of app.json

### ISSUE THREAD

**Issue by ad-m** [pydanny/cookiecutter-django#218]
Hello,

We generate a lot of staff, we was in some part heroku oriented, so I think support for `app.json` will be good. We have all of data to do it. We can simplify README.rst by button to deploy on heroku.

Greetings,

**Comment by ad-m** [comment]
Here is docs for `app.json`: https://devcenter.heroku.com/articles/app-json-schema
Here is docs for heroku button: https://devcenter.heroku.com/articles/heroku-button

**Comment by theskumar** [comment]
Haven't been using it. At a bird I view, it does look promising. Considering the maintainability part it, I'll try to read more and implement it myself first.  I'm very happy to review a Pull Request for this project!

Thanks,

**Comment by ad-m** [comment]
I will do it today.

Wysłano z urządzenia mobilnego
24 kwi 2015 06:41 "Saurabh Kumar" <notifications@github.com> napisał(a):

**Comment by ad-m** [comment]
I am don't have enough time to run AWS, but this `app.json` looks reliable:
```json

{
  "name": "{{cookiecutter.project_name}}",
  "description": "{{cookiecutter.description}}",
  "scripts": {
    "postdeploy": "python {{cookiecutter.repo_name}}/manage.py migrate"
  },
  "env": {
    "BUILDPACK_URL": "https://github.com/heroku/heroku-buildpack-python",
    "DJANGO_SECRET_KEY": {
      "description": "A secret key for verifying the integrity of signed cookies.",
      "generator": "secret"
    },
    "WEB_CONCURRENCY": {
      "description": "The number of processes to run.",
      "value": "1"
    },
    "DJANGO_AWS_ACCESS_KEY_ID": {
      "value": ""
    },
    "DJANGO_AWS_SECRET_ACCESS_KEY": {
      "value": ""
    },
    "DJANGO_AWS_STORAGE_BUCKET_NAME": {
      "value": ""
    },
  },
  "addons": [
    "heroku-postgresql:dev",
    "sendgrid:starter",
    "memcachier:dev"
  ]
}
```

**Comment by luzfcb** [comment]
@ad-m :+1: Cool. Works fine, but I'll do some more tests.
