### ISSUE TITLE
Add django-livereload-server

### ISSUE THREAD

**Issue by mmmcorpsvit** [pydanny/cookiecutter-django#2184]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)
Add LiveUpdate website, use: https://github.com/tjwalch/django-livereload-server
work fine

**Comment by browniebroke** [comment]
Can you expand a bit on why is it better than what we currently have with browserSync? Does it work with Docker?

**Comment by mmmcorpsvit** [comment]
0_о... in windows 10 not work, i do more deep check

**Comment by mmmcorpsvit** [comment]
my fault, all work now fine (was my error)
