### ISSUE TITLE
.gitignore ignores scripts conflicts with runscript

### ISSUE THREAD

**Issue by bmihelac** [pydanny/cookiecutter-django#2226]
## What happened?

`.gitignore` ignores every `scripts` directory that can be used by `runscript` command of included `django-extensions` package. 

https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.gitignore#L332

## What should've happened instead?

`scripts` directory should not be ignored IMHO.

**Comment by luzfcb** [comment]
@bmihelac the `scripts` directory is ignored to avoid commit the `scripts` or `Scripts` directory of the virtualenv. These directories only are created on Windows machine


Looking briefly at the implementation in django-extensions, I saw that there are some configurations that can be made in django settings, which are currently not properly documented in django-extensions. 

Have you ever tried any of them like `RUNSCRIPT_SCRIPT_DIR` and the others to check if is possible to customize the `scripts` directory name?

https://github.com/django-extensions/django-extensions/blob/f7eacd2263a1069c61bbee316e9c32cf22fa121f/django_extensions/management/commands/runscript.py#L94

**Comment by bmihelac** [comment]
Hi @luzfcb  and thanks for looking into this.

Unfortunately I am not familiar with virtualevn on windows and have no idea if this could be handled in other ways.

While workaround with  `RUNSCRIPT_SCRIPT_DIR` is probably possible, I still feel  that ignoring every `scripts` (and others directories too) directory in project is maybe too broad and users would not be aware what and why is ignored. This is why I opened issue, but feel free to close it if you do not agree.

**Comment by browniebroke** [comment]
I did some investigation, and I think we can remove these lines safely:

https://github.com/pydanny/cookiecutter-django/blob/9075bdb39b98f88e9210e04cc4cae5f5920baa68/%7B%7Bcookiecutter.project_slug%7D%7D/.gitignore#L326-L333

When creating a virtual environment, such directories are actually **inside** the top directory, which we aim at excluding from these lines:

https://github.com/pydanny/cookiecutter-django/blob/9075bdb39b98f88e9210e04cc4cae5f5920baa68/%7B%7Bcookiecutter.project_slug%7D%7D/.gitignore#L70-L73

Example with `venv`:

```
.
`- venv
   |- Lib
   |- Scripts
   `- pyvenv.cfg
```

It sounds to me like we are being extra careful...
