### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by browniebroke** [pydanny/cookiecutter-django#2236]
## Description

Python 3.7 has been out for quite a while now. Celery was a blocker to upgrade for a little while, bit it should be supported in the version that we use.

It's time to update this project to use Python 3.7 by default.

## Use case(s) / visualization(s)

It should be fairly straightforward with Docker, but there is also a couple of files with Heroku, Travis and the documentation. The things I see so far:

- Bump versions in various Dockerfile
- Update tox file to use 3.7
- Update `.travis.yml` file to use 3.7 in both the template project and the template content under `{{cookiecutter.project_slug}}`
- Update `runtime.txt` to use latests 3.7 on Heroku
- Update mypy settings in `setup.cfg`
- Update documentation

**Comment by nicolas471** [comment]
Hi! Can i take this?

**Comment by browniebroke** [comment]
Sure!

**Comment by nicolas471** [comment]
:ok_hand:
