### ISSUE TITLE
Button donation github for django cookie cutter ?

### ISSUE THREAD

**Issue by scwall** [pydanny/cookiecutter-django#2238]
Hello, I recently finished a project, and I count a small amount to my customers to redistribute to the libraries I use. I wanted to make a donation to you but I don't see a git button or a link to make it. Can you inform me if this is available? Thank you in advance

**Comment by sfdye** [comment]
I believe only the repo admin can enable it from the settings:

![image](https://user-images.githubusercontent.com/1016390/75088142-55b21680-5584-11ea-963c-30379bd7c4d3.png)

**Comment by browniebroke** [comment]
Update: this is now available (added about 2 months ago) 🎉

**Comment by scwall** [comment]
@browniebroke  thanks in the meantime I had subscribed to the site "patreon" of "django cookie cutter" but here I just changed today :)
