### ISSUE TITLE
The heroku addon "pgbackups" does not exist.

### ISSUE THREAD

**Issue by ad-m** [pydanny/cookiecutter-django#224]
> The addon "pgbackups" does not exist. Please ensure that the addon is spelled correctly.

**Comment by ad-m** [comment]
Here is heroku' docs related: https://devcenter.heroku.com/articles/pgbackups

**Comment by luzfcb** [comment]
We are already aware of this. We will update the documentation coming soon

**Comment by theskumar** [comment]
This is resolved in master. closing this now.

**Comment by theskumar** [comment]
ref: https://github.com/pydanny/cookiecutter-django/commit/815fa26611892ebb22987e866eeb636773400f88
