### ISSUE TITLE
Broken static files with whitenoise=n & cloud_provider=none

### ISSUE THREAD

**Issue by browniebroke** [pydanny/cookiecutter-django#2249]
## What happened?

If the user chooses `use_whitenoise=n` & `cloud_provider=None`, then the static files are not served properly.

## What should've happened instead?

This combination should not be allowed and show an error when trying to generate the project.

**Comment by browniebroke** [comment]
To fix that, I think we should implement a check in one of the hooks, show an error to the user and not generate anything. 

The tests will need to be updated to:

1. Cover only the working combination in the main fixture:

   https://github.com/pydanny/cookiecutter-django/blob/63453b6e51faae64c872059cb4d90dd38d4b8865/tests/test_cookiecutter_generation.py#L39-L40

2. Add a new test to make sure the project isn't generated when the invalid combination is selected.

More details about cookiecutter's hook mechanism: https://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html#writing-hooks

**Comment by caioariede** [comment]
@browniebroke I'll be working on this one as well
