### ISSUE TITLE
No staticfile storage with GCP without Whitenoise

### ISSUE THREAD

**Issue by browniebroke** [pydanny/cookiecutter-django#2250]
## What happened?

If the user chooses GCP as cloud provider & no Whitenoise, then `STATICFILES_STORAGE` is unset in production.

https://github.com/pydanny/cookiecutter-django/blob/164e2aa69c2bf58104de7ad3474d89995329b8b5/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/production.py#L104-L111

## What should've happened instead?

The `STATICFILES_STORAGE` setting should be set to `"storages.backends.gcloud.GoogleCloudStorage"` or a subclass.

## Steps to reproduce

Reproducible using:

`cookiecutter https://github.com/pydanny/cookiecutter-django use_whitenoise=n cloud_provider=GCP`

**Comment by caioariede** [comment]
@browniebroke I'll be working on this one
