### ISSUE TITLE
Traefik's configuration parameters are not valid in newer version

### ISSUE THREAD

**Issue by demestav** [pydanny/cookiecutter-django#2258]
The current configuration file used for Traefik uses *frontend* and *backend* parameters. Traefik v2 no longer supports that, and uses different parameters as described [here](https://docs.traefik.io/migration/v1-to-v2/#frontends-and-backends-are-dead-long-live-routers-middlewares-and-services).

A temporary solution would be to pin the Traefik version in Dockerfile to v1 which supports the current configuration. Or we could update to the new configuration style. Not sure whether v2 is backwards compatible.

**Comment by browniebroke** [comment]
Thanks for the report. I've opened a pull request to pin the version for now, I think we should create another separate issue to handle the upgrade to v2 once it's merged.

If you would like to give it a spin, that would be helpful.
