### ISSUE TITLE
Bad Gateway in admin user list (Docker + Traefik)

### ISSUE THREAD

**Issue by sgabb** [pydanny/cookiecutter-django#2266]
## What happened?
Getting Bad Gateway (502) error only in admin account user list (https://appurl.ext/admin/account/user/)
Both .../admin/account/user/add/ or .../admin/account/user/1/change/ works.
Running locally with runserver works.
Unfortunately I have no error logs to show.
Using whitenoise for serving statics.

Any idea?
Thanks in advance.

## Steps to reproduce
No changes to documented flow to build docker stack as in https://cookiecutter-django.readthedocs.io/en/latest/deployment-with-docker.html#building-running-production-stack

[x]: # (* Host system configuration: OS, Docker & friends' versions etc.)
CentOS Linux release 7.7.1908
Docker:
Server Version: 19.03.3
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.27.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.455GiB
 Name: instance-1
 ID: 6WG3:3OCI:BDI3:YHUG:GOV7:YSK7:T5I3:PYV7:ADAC:SFQD:ZHVO:5GSC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by browniebroke** [comment]
Can you please try again? I've just merged this which might solve this problem: https://github.com/pydanny/cookiecutter-django/pull/2262

**Comment by sgabb** [comment]
Hi,
thanks for your response, but I changed it already when I saw the issue you are referring to..!

An update by my side is that I changed the DEBUG settings to true (hoping that some more nice error would come out), but actually that "fixed" it and now the user list in the admin is working again (no idea why).

Do you think could be some no-debug-mode error that ends in a Bad Gateway page?

I haven't switched it back to DEBUG=False to see if it would broke again...

**Comment by browniebroke** [comment]
> Do you think could be some no-debug-mode error that ends in a Bad Gateway page?

I really don't know. I would strongly recommend you to switch it back to `False`, running `DEBUG=True` in production is a major security issue.

**Comment by sgabb** [comment]
Yes, I know, it is a testing environment that I set up in order to test the Django Docker deploy.

**Comment by sgabb** [comment]
UPDATE:
switched it back to DEBUG=True and finally got a log error:
```
Internal Server Error: /admin/account/user/
ValueError at /admin/account/user/
Missing staticfiles manifest entry for 'admin/img/icon_searchbox.png'
```
After adding the image in the static admin folder and rebuilding the django service the errore went away!
It is strange that the app crashes instead than just not showing the missing icon as it does while debug is true, anyway it is maybe more a Whitenoise issue.

I'm closing it, and thanks again for the feedback.
