### ISSUE TITLE
Using WhiteNoise in development when it's enabled?

### ISSUE THREAD

**Issue by mapx** [pydanny/cookiecutter-django#2303]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)
`WhiteNoise`, if enabled, is available in production mode. Might it be a good idea to have this feature in development as well?

We enabled this feature in both modes. No conflicts were noticed so far.

## Rationale
As described in http://whitenoise.evans.io/en/latest/django.html#using-whitenoise-in-development , `WhiteNoise` can be enabled in development and it's suggested to do so.

**Comment by mapx** [comment]
If the suggestion is approved, I'd be glad to trigger a PR :)

**Comment by browniebroke** [comment]
Thanks for bringing this up, I didn't know about this.  Feel free to send a pull request 👍
