### ISSUE TITLE
black flake8 incompatibility 

### ISSUE THREAD

**Issue by morenoh149** [pydanny/cookiecutter-django#2348]
## What happened?
I am using the precommit hooks as instructed at https://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html

I have also chosen black as my formatter in the wizard as well as in my editor. When I go to commit the following form

```

class FooForm(forms.ModelForm):
    objective = forms.CharField(
        required=False, widget=forms.Textarea(attrs={"placeholder": "Objective",}),
    )

    class Meta:
        model = Foo
        fields = [
            "objective",
        ]
```
I get the error
```
$ gc
Trim Trailing Whitespace.............................(no files to check)Skipped
flake8...................................................................Failed
hookid: flake8

foo/forms.py:10:80: E231 missing whitespace after ','
```
Thats for the CharField trailing comma in the keyword args.

## What should've happened instead?
Flake8 should not complain about black's formatting.

## Steps to reproduce

[//]: make a cookiecutter app and select black
[//]: install precommit hooks
[//]: make a form like mine and attempt to commit

## Solution

Should we add https://github.com/peterjc/flake8-black ?

**Comment by luzfcb** [comment]
@morenoh149 did you use flake8-black before? I haven't had time to try it yet... If you find a fix for this, feel free to submit a pull-request.

**Comment by morenoh149** [comment]
I have not used that plugin even though it was the first thing to show up for the incompatibility. For now I just removed the precommit with `rm .git/hooks/pre-commit` (or `mv .git/hooks/pre-commit .git/hooks/pre-commit.bkup`) :)

**Comment by demestav** [comment]
@morenoh149 please correct me if I am wrong, but the trailing comma in the dictionary you specify does not serve a purpose, so it should be removed, which will pass flake8 check. In my understanding, you may want to add a trailing comma in a single (or more) element dictionaries, to minimize diffs when inserting new lines. But for that to be true,  the dictionary should be written like

    attrs = {
        "placeholder": "Objective",
    }

Regarding tools to help in this situation, I use [flake8-commas](https://pypi.org/project/flake8-commas/). Checking against your example, it does raise an error on that trailing comma. @luzfcb Maybe we can include this in requirements? I did not thoroughly checked if it is fully compatible with black though, but that seems the case.

**Comment by browniebroke** [comment]
Also see https://github.com/psf/black/issues/1288

**Comment by browniebroke** [comment]
I'm going to close this, as I don't think there is much we can do on our end, it's an issue that should solved soon in Black.

Thanks for the report!
