### ISSUE TITLE
Proper absolute import app loading with ROOT_DIR structure change

### ISSUE THREAD

**Issue by rdmurphy** [pydanny/cookiecutter-django#235]
Hello!

Working on a project loosely based on the arrangement that created the `config` directory at project root.

Does this mean in apps that are referencing modules in other apps, the absolute path you'd use has changed from:

```py
from <app_name>.models import <Model>
```

To:

```py
from <project_name>.<app_name>.models import <Model>
```
A little wordy, but not too bad! I wanted to double check I'm going about it right before I go too far down that path.

**Comment by theskumar** [comment]
@rdmurphy the new import always need be from the top of the root. This to avoid any kind of confusion w.r.t PYTHON_PATH. The new import need to be in the form `from <project_name>.<app_name>.models import <Model>`.

That said, you can are now free to add apps/modules on the top level of directory if you prefer, but that would be your way of logically organising your project and it's different modules.

The idea behind this change is that your Django apps are nothing but yet another python module and they should not get any special privileges.

**Comment by rdmurphy** [comment]
Thanks @theskumar! Makes sense.
