### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by wahello** [pydanny/cookiecutter-django#2352]
## Django 3.0 support?

[//]: # (What's it you're proposing? How should it be implemented?)
when will django 3.0 be supported?

 

[//]: # (Why should this feature be implemented?)

 

[//]: # ("Better to see something once than to hear about it a thousand times.")

**Comment by luzfcb** [comment]
Support will be done sometime in the future, when all dependencies have updated support for Django 3.0.

**Comment by emilepetrone** [comment]
Is there a list already of the packages and which have been updated? So we can keep track of which have been which need to be updated and their status. 

I'm noticing many packages not in Cookiecutter are updated for 3.0 so it would be good to just have a simple table to keep track for this ticket.

**Comment by browniebroke** [comment]
Good idea, such table would be very helpful indeed. I don't think anyone is doing it at the moment :+1:

**Comment by elcolie** [comment]
@emilepetrone I am about to move to Django manually, but if you have that list please list them here to save up community time

**Comment by emilepetrone** [comment]
**Base.txt**

| Name        | Version in Master | 3.0 Compatible Version  |
| ------------- |:-------------:| -----:|
| django    | 2.2.9 | 3.0 |

**Comment by Andrew-Chen-Wang** [comment]
Besides Traefik, since Django 3.0 offers async, what service should be setup for [Django's asgi](https://docs.djangoproject.com/en/3.0/howto/deployment/asgi/) for Docker? And should asgi be the default if we offer both Traefik and the asgi server?

**Comment by elcolie** [comment]
@Andrew-Chen-Wang 
Let me share my opinion. This is my use case with former `Caddy` and current `Traefik`. <br>(I omit `celery` others and their required containers for sake of simplicity here, but I always enable them in my `compose.yml` file)
- 2 IPs point to single VM
- Reverse Proxy configured to response between 2 containers

Next project my `compose.yml` would be like this
- 3 IPs point to single VM
- 1 container for `wsgi`
- 1 container for `Node server Vue, React, Angular, ... etc`
- 1 container for `asgi`. For `django-channels`
In my dream I have 1 another `PostGIS` database, but unfortunately it is tremendous effort to put in down to `Dockerfile` I spent 3 days to get outdated version up and running

**Comment by Andrew-Chen-Wang** [comment]
@elcolie Thanks for your setup! (just went through [uvicorn's deployment doc](https://www.uvicorn.org/deployment/) with some [benchmarks](https://gist.github.com/erm/975e9a8dda60d94823dc5f8a8d354b57)).

I found this https://www.uvicorn.org/#running-with-gunicorn, but I still stand on having asgi support in docker production be an optional thing rather than immediately implement gunicorn with uvicorn.

**Comment by antonagestam** [comment]
@emilepetrone Collectfast officially adds support for Django 3.0 in [1.3.2](https://github.com/antonagestam/collectfast/releases/tag/1.3.2) released today.

**Comment by snmishra** [comment]
[django-environ](https://github.com/joke2k/django-environ) looks dormant. I switched to [environs](https://github.com/sloria/environs), which has a very similar api (inspired by django-environ)

**Comment by browniebroke** [comment]
I tried to bump the Django version to see what was broken, and the build is now green: https://travis-ci.org/pydanny/cookiecutter-django/builds/656629680 :tada: 

These are the libraries where support is not yet official:

- `django-environ`: there is [a pull request open](https://github.com/joke2k/django-environ/pull/240/) which adds Django 3.0 to their CI config. Looking at the changes, I don't see any Django specific code changes, they seem mostly about dropping Python 2.
- `django-anymail`: it's on master, and [the changes to add it](https://github.com/anymail/django-anymail/commit/c6ab1e374c53a5ae87cc9e5ee0e7821a06eb8702) are mostly updating the CI config, which indicates the current version should work.
- `django-allauth`: again, not officially supported but [I was able to update their CI config](https://github.com/pennersr/django-allauth/pull/2441) and get a green build without any code changes.

We should be able to upgrade now, just need to test the generated production app works with various setup.

> [django-environ](https://github.com/joke2k/django-environ) looks dormant. I switched to [environs](https://github.com/sloria/environs), which has a very similar api (inspired by django-environ)

We have -at least- 2 other issues for it: #2291 and #2195, I think we should consider it but it doesn't look like a blocker here.

**Comment by Andrew-Chen-Wang** [comment]
Are we adding Uvicorn and the asgi file? This is what I've been following for playing around with web sockets on native Django 3.0:

https://dev.to/jaydenwindle/adding-websockets-to-your-django-app-with-no-extra-dependencies-2f6h

**Comment by wadkar** [comment]
> @Andrew-Chen-Wang
>       In my dream I have 1 another `PostGIS` database, but unfortunately it is tremendous effort to put in down to `Dockerfile` I spent 3 days to get outdated version up and running

I just swapped `FROM postgres:11.3` with `FROM postgis/postgis:11-2.5` and it didn't crash. Maybe your dream can come true! If you have a test app for PostGIS can you try it out and let me know? I spent an enormous amount of time as well, but looks like it's working with ubuntu/debian (don't go for alpine).

**Comment by Andrew-Chen-Wang** [comment]
@wadkar I did get a postgis Docker configuration going by replacing the current postgres manually. Just make sure you include the required libraries in your `Dockerfile`s, i.e. GEOS, GDAL, PROJ.4 etc. You can use the Debian package website to look all of them up, too.

I also created a PR for the implementation of Uvicorn and Gunicorn at #2506. Also, you need to change the driver. You can do that by doing:

`DATABASES["default"]["engine"] = 'django.contrib.gis.db.backends.postgis'`

I also didn't use the alpine version as some thing could go wrong without some of the missing packages of Alpine.
