### ISSUE TITLE
Add Python Anywhere as a hosted option

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#236]
:bell:  @hjwp

**Comment by pydanny** [comment]
Maybe place docs here? https://github.com/pydanny/cookiecutter-django/blob/c54628c90e9cef1eca83ea6caefbd23b798b3ca0/%7B%7Bcookiecutter.repo_name%7D%7D/README.rst

**Comment by hjwp** [comment]
Taking a look at this today...

**Comment by hjwp** [comment]
A few comments as I go through, with apologies for the stream-of-consciousness style

**Comment by hjwp** [comment]
i didn't want to have to install postgres on my local machine for dev, and the docs seem to say it's required, but i found that using a sqlite for the `DATABASE_URL` (`sqlite:///db.sqlite`) worked just fine.  Is using sqlite locally likely to lead me into any trouble?  If not, might you be inclined to suggest it as a solution?  postgres feels heavyweight for a dev environment, but i'm assuming a world with a ci server that runs the real db...

**Comment by hjwp** [comment]
question:  what are you using gevent for?

**Comment by hjwp** [comment]
comment re requirements/production.txt -- gunicorn won't be needed on pythonanywhere.  doesn't do any harm to install it, but feels wasteful. i imagine the same thing applies to gevent.  not the end of the world.

**Comment by hjwp** [comment]
tripped over the fact that DJANGO_SETTINGS_MODULE defaults to the dev version.

**Comment by hjwp** [comment]
managed to set all the other required environment vars as documented in the README, although there were two extra that were undocumented:  `SENDGRID_USERNAME` and `SENDGRID_PASSWORD`.

**Comment by hjwp** [comment]
re: the AWS stuff, I'm guessing you're using these to serve static assets?  We have a static files hosting solution on pythonanywhere, if people don't fancy signing up for amazon as well...

**Comment by hjwp** [comment]
hm, mysql support in python 3.4 with django is still pretty sketchy isn't it?   will use postgres for now.

**Comment by hjwp** [comment]
arg, force-https.  skipping that for now.

**Comment by hjwp** [comment]
oh danny where are you hiding my logs?  what was wrong with sys.stderr... hunting...

**Comment by hjwp** [comment]
ok, got pretty far.  site loads, with css.  seems to give a 500 when i try to register or login, but not logging anything.  will do some more debugging this weekend or next week maybe.  cheers danny!

http://test2.ottg.eu/

**Comment by pydanny** [comment]
We advocate against using sqlite3 in development, as we've seen cases of local dev and tests that work against sqlite3 break in production against PostgreSQL and MySql. FWIW, this was why Django Packages was stuck on sqlite3 for so long.

**Comment by pydanny** [comment]
`gevent`? I need to look into why we have that in place.

We're providing an option for whitenoise serving of assets, which I *believe* should work on PythonAnywhere, providing asset serving.

**Comment by hjwp** [comment]
ok, the error was due to my not having configured email correctly.  was slightly frustrating that sendgrid (or whoever) was just silently failing

**Comment by hjwp** [comment]
switching it out for gmail temporarily worked.  so the site is up and running.

**Comment by hjwp** [comment]
re: postgres vs sqlite in dev, I totally get where you're coming from.  I think I'd want to recommend "test on a staging / CI server before deploying" rather than "try to make your laptop environment look as much like prod as possible".  (not that the two bits of advice are mutually exclusive)

**Comment by hjwp** [comment]
OK I've had a first crack at it:  https://github.com/hjwp/cookiecutter-example-project#pythonanywhere

Not totally happy with the duplication of environment vars between virtualenv-postactivate and wsgi-config-file.  but applying DRY in a non-brittle fashion is nonobvious...

**Comment by hjwp** [comment]
I mean, [this](https://gist.github.com/hjwp/0d29ec23940438a2d5e3) is crazy, right?

**Comment by pydanny** [comment]
@hjwp :Bell:

**Comment by hjwp** [comment]
Oops, what's the emoji for dropping a ball? Will ping in an update next
week.

**Comment by hjwp** [comment]
https://github.com/pydanny/cookiecutter-django/pull/532 :) :runner: :soccer:
