### ISSUE TITLE
makemigration and migrate doesn't work docker production

### ISSUE THREAD

**Issue by scwall** [pydanny/cookiecutter-django#2360]
## What happened?

Hello, I don't know if it's a bug, but I have a problem with makemigrations and docker, I use django helpdesk on a project, I had to add a new model and new package django. When I apply migration he explains to me "

```
Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run "manage.py makemigrations" to make new migrations, and then re-run "manage.py migrate' to apply them."
```

 So I launch a makemigrations. First problem if I don't run as root I get the error: 

`PermissionError:[Errno 13] Permission denied: /usr/local/lib/python3.7/sitepackages/helpdesk/migrations/0018_auto_20191211_2241.py'`

if I run makemigrations this one creates a migration file but even if I run the migration command it never applies. 

Thank you in advance

## Steps to reproduce
- Use docker
- Install django-helpdesk
- apply migrate in production
- add new model
- add new django package
- create migration file in local 
- apply migration file in server production 
- use makemigrations in production for django helpdesk package (alter field)
- apply migrate 

[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
- ubuntu 18.04 server
 - use docker 
[//]: # (* Logs)
```
makemigration django helpdesk : 
Migrations for 'helpdesk':
  /usr/local/lib/python3.7/site-packages/helpdesk/migrations/0018_auto_20191211_2241.py
    - Alter field public on followup
    - Alter field keep_in_mailbox on ignoreemail
    - Alter field allow_email_submission on queue
    - Alter field allow_public_submission on queue
    - Alter field email_box_ssl on queue
    - Alter field shared on savedsearch
    - Alter field on_hold on ticket
    - Alter field can_update on ticketcc
    - Alter field can_view on ticketcc
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 182, in handle
    self.write_migration_files(changes)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 221, in write_migration_files
    with open(writer.path, "w", encoding='utf-8') as fh:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/helpdesk/migrations/0018_auto_20191211_2241.py'
e@vmi:~/django$ docker-compose -f production.yml run -u root --rm django python manage.py makemigrations
Starting e_redis_1 ... done
Starting e_postgres_1 ... done
PostgreSQL is available
Migrations for 'helpdesk':
  /usr/local/lib/python3.7/site-packages/helpdesk/migrations/0018_auto_20191211_2241.py
    - Alter field public on followup
    - Alter field keep_in_mailbox on ignoreemail
    - Alter field allow_email_submission on queue
    - Alter field allow_public_submission on queue
    - Alter field email_box_ssl on queue
    - Alter field shared on savedsearch
    - Alter field on_hold on ticket
    - Alter field can_update on ticketcc
    - Alter field can_view on ticketcc
e@vmi:~/django$ docker-compose -f production.yml run --rm django python manage.py migrateStarting e_postgres_1 ... 
Starting e_postgres_1 ... done
PostgreSQL is available
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, django_celery_beat, helpdesk, payment, project, sessions, sites, socialaccount, terms_and_abouts, users
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
e@vmi:~/django$ docker-compose -f production.yml run -u root --rm django python manage.py migrate
Starting e_postgres_1 ... done
Starting e_redis_1 ... done
PostgreSQL is available
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, django_celery_beat, helpdesk, payment, project, sessions, sites, socialaccount, terms_and_abouts, users
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
e@vmi:~/django$ docker-compose -f production.yml run --rm django python manage.py migrateStarting e_redis_1 ... done
PostgreSQL is available
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, django_celery_beat, helpdesk, payment, project, sessions, sites, socialaccount, terms_and_abouts, users
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
e@vmi:~/django$ 

```

**Comment by geldabhojal** [comment]
HOw did you solve it?

**Comment by scwall** [comment]
Hello, it's not possible to migrate after a build, the image is 'fixed' once the build is executed. To solve this problem, I downloaded the library and I manually installed the library directly at the root of my project, so I can execute the migrations before the deployment of my project :)

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by l-kotzur** [comment]
I have a similar issue. What would be the best-practice here?

Make the migrations always locally and push them to the production and just call migrate after a successful build?

**Comment by scwall** [comment]
@l-kotzur 

a possibility that could work sharing the migration file with a local folder in production so that it can write the changes.
production/yml 
volumes:
  -./migrations:./app/nameapp/migrations

**Comment by browniebroke** [comment]
Migrations should not be created in the production environment, this is not specific to Cookiecutter Django, this is [general advice from Django](https://docs.djangoproject.com/en/3.1/topics/migrations/#workflow).

You create you migrations file locally with `makemigrations`, commit them in version control and run what is in source control on production with `migrate`.

**Comment by RamsesMartinez** [comment]
> Migrations should not be created in the production environment, this is not specific to Cookiecutter Django, this is [general advice from Django](https://docs.djangoproject.com/en/3.1/topics/migrations/#workflow).
> 
> You create you migrations file locally with `makemigrations`, commit them in version control and run what is in source control on production with `migrate`.

What to create the migration files and then commit them is understood, but I have one doubt.

Why does the migrate command not exist in the production file and has only been placed in the local environment?

**Comment by scwall** [comment]
the easiest way is to add the library manually in the project so that it creates a migration file in the project locally. (that's how I proceeded, now it's a lot harder to update it.)
**The problem does not come from django or cookie cutter but from the library itself**. I think you should rather ask the person who manages the external library to make a change request.
@browniebroke  yes it's a bad idea to migrate to production and I totally agree, it was time to find an intermediate solution during the time of change for @l-kotzur .
