### ISSUE TITLE
What does triple bang mean? (!!!)

### ISSUE THREAD

**Issue by morenoh149** [pydanny/cookiecutter-django#2372]
I'm trying to get my production env working. I have a db user set at https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.envs/.production/.postgres#L6

Which is not what is in the source code `!!!SET POSTGRES_USER!!!`. Does Cookiecutter replace things wrapped in triple exclamation points?

**Comment by demestav** [comment]
I believe those are processed by a post generation hook, a feature of cookiecutter https://github.com/pydanny/cookiecutter-django/blob/master/hooks/post_gen_project.py
