### ISSUE TITLE
Proposal to use python-slim instead of python-alpine

### ISSUE THREAD

**Issue by rsynnest** [pydanny/cookiecutter-django#2373]
## Description

Use the python-slim Docker image as a base instead of the python-alpine variant.

## Rationale

I believe you guys switched to the Alpine image to reduce space, but the python-slim variant is about the same size. Alpine does not support manylinux wheels from Pypi, so many packages have to be built from source, including cython, numpy, pandas (which takes FOREVER), and others. This is further complicated by the fact that Alpine doesn't contain undocumented build dependencies of some pip packages such as gcc , g++, etc. 

Further justification can be found here https://pythonspeed.com/articles/base-image-python-docker-images/

**Comment by browniebroke** [comment]
I can't talk for everyone else, but I'm +1 on this one.

**Comment by luzfcb** [comment]
It's Okay to me. A pull-request is welcome.

Em qui, 19 de dez de 2019 07:59, Bruno Alla <notifications@github.com>
escreveu:

**Comment by enzolutions** [comment]
+1
