### ISSUE TITLE
Celery Flower is not configured for Traefik

### ISSUE THREAD

**Issue by msamoylov** [pydanny/cookiecutter-django#2394]
## What happened?

Even though [production.yml](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/production.yml#L60) has Flower configured, [traefik.toml](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/traefik/traefik.toml) doesn't contain anything related.

## What should've happened instead?

Flower should be working with Docker.

**Comment by juliantroeps** [comment]
You can access the Flower service on your domain on port 5555. If you need Flower on a subdomain with SSL you can update the trafeik.toml file accordingly and add another frontend and baackend.

**Comment by jameswilliams1** [comment]
It's possible this isn't configured properly depending on options chose when setting up - I also can't use flower on a prod site over HTTPS and theres nothing in the Traefik config that mentions it.
