### ISSUE TITLE
Failing mypy tests in users app with django-stubs

### ISSUE THREAD

**Issue by danifus** [pydanny/cookiecutter-django#2395]
## What happened?
After installing `django-stubs` (`pip install django-stubs`) the typing tests in the `users` app fail with `Name 'settings.AUTH_USER_MODEL' is not defined`.

`reveal_type(settings.AUTH_USER_MODEL)` returns `Any` which doesn't provide much value. Did this work differently at some stage in the past? If not, an easy fix would be to remove the annotations in the test function signatures.

Furthermore, the type of `settings.AUTH_USER_MODEL` is `str` and the `user` type should be a subclass of a django model. If that is correct, that might be another reason to remove the annotation.

## What should've happened instead?
No mypy errors

## Steps to reproduce
```
pip install django-stubs
mypy <project dir>
```

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
[//]: # (* Logs)

**Comment by browniebroke** [comment]
I don't think it worked differently in the past. We should fix this. PR welcome.
