### ISSUE TITLE
documentation - broken link on testing.html

### ISSUE THREAD

**Issue by johnmathews** [pydanny/cookiecutter-django#2408]
## What happened?
on https://cookiecutter-django.readthedocs.io/en/latest/testing.html the link to  `develop locally` in the second paragraph is broken

## Steps to reproduce
go to  https://cookiecutter-django.readthedocs.io/en/latest/testing.html 
click on  `develop locally`

**Comment by browniebroke** [comment]
Thanks for the report. Should be fixed in the docs source, but the docs failed to generate due to an error in pip it seems: https://readthedocs.org/projects/cookiecutter-django/builds/10305162/
