### ISSUE TITLE
Write tests for the DRF setup

### ISSUE THREAD

**Issue by browniebroke** [pydanny/cookiecutter-django#2415]
## Description

A new option has been added to bring support for DRF in #2224.
However, this is currently not tested. We should write tests covering various components of the DRF option and remove them when the user opts out.

**Comment by PilhwanKim** [comment]
May I try this issue? @browniebroke

**Comment by browniebroke** [comment]
Yes of course!

**Comment by PilhwanKim** [comment]
https://github.com/pydanny/cookiecutter-django/pull/2567
I make a pull request. could you reivew this pull request?
