### ISSUE TITLE
How do I know the Django connection is secured?

### ISSUE THREAD

**Issue by elcolie** [pydanny/cookiecutter-django#2424]
I had posted my question to [stackoverflow](https://stackoverflow.com/questions/60003766/how-to-verify-my-container-that-has-ssl-with-postgres)

But does not found any useful answer, got down vote instead. 
With the same `DATABASE_URL` I can run it and confirm that my connection is secured
However, on `container` I don't have `psql` therefore I can't confirm that connection is encrypted

**Question:**<br>
How to check that my connection is secured by SSL/TLS?
I know how to force it, but it is another story. I will force it later on after this

**Comment by browniebroke** [comment]
I don't think we have a better answer than what is linked in the Stackoverflow answer you found....

If you don't have `psql` installed in the prod image, nothing prevents you from changing the production Docker file to add it, it should be part of the PostgreSQL client.

Closing this as I assume we've answered the question.
