### ISSUE TITLE
media storage amazon aws

### ISSUE THREAD

**Issue by two9seven** [pydanny/cookiecutter-django#243]
Thanks Pydanny for creating this great cookie-cutter. I am a novice, teaching myself python and django. I've sucessfully deployed my cookie-cutter app to heroku and conncected my static assets using amazon aws. My problem is that the /media/ directory is not being created. Is there a setting in the configuration files that I'm missing? Not sure if this is proper git hub etiquite but here is the section of my production.py referencing storage. I don't see a mention of /media/. Any help is appreciated. 

Donovan

# STORAGE CONFIGURATION
    # See: http://django-storages.readthedocs.org/en/latest/index.html
    INSTALLED_APPS += (
        'storages',
    )

    # See: http://django-storages.readthedocs.org/en/latest/backends/amazon-S3.html#settings
    STATICFILES_STORAGE = DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

    # See: http://django-storages.readthedocs.org/en/latest/backends/amazon-S3.html#settings
    AWS_ACCESS_KEY_ID = values.SecretValue()
    AWS_SECRET_ACCESS_KEY = values.SecretValue()
    AWS_STORAGE_BUCKET_NAME = values.SecretValue()
    AWS_AUTO_CREATE_BUCKET = True

    AWS_QUERYSTRING_AUTH = False

    # See: https://github.com/antonagestam/collectfast
    # For Django 1.7+, 'collectfast' should come before 'django.contrib.staticfiles'
    AWS_PRELOAD_METADATA = True
    INSTALLED_APPS = ('collectfast', ) + INSTALLED_APPS

    # AWS cache settings, don't change unless you know what you're doing:
    AWS_EXPIRY = 60 * 60 * 24 * 7
    AWS_HEADERS = {
        'Cache-Control': 'max-age=%d, s-maxage=%d, must-revalidate' % (
            AWS_EXPIRY, AWS_EXPIRY)
    }

    # See: https://docs.djangoproject.com/en/dev/ref/settings/#static-url
    STATIC_URL = 'https://s3.amazonaws.com/%s/' % AWS_STORAGE_BUCKET_NAME
    # END STORAGE CONFIGURATION

**Comment by acquayefrank** [comment]
I have a similar issue ... I'm not using AWS though and my server is not loading my media files.  I've commented out all the needed sections in production.py

**Comment by pydanny** [comment]
@two9seven Did this ever get resolved? For what it's worth, we switched over the django-environ, which uses a different method for loading secret values.

@acquayefrank Apologies, but cookiecutter-django only supports AWS and Whitenoise for management of uploaded media. As much as we would like to support other systems, we have to focus on what we know best.

**Comment by acquayefrank** [comment]
@pydanny  Thanks. But for anyone with a similar issue, you could try out [Django-RedNoise](https://github.com/ryanmcgrath/django-rednoise). the only issue is, it does not work well with the 2.0 version of Whitenoise. the author is yet to fix it

**Comment by pydanny** [comment]
Closing this. Reopen if it needs to stay open.
