### ISSUE TITLE
ValueError at /en/catalog/earphones/

### ISSUE THREAD

**Issue by jncs** [pydanny/cookiecutter-django#2440]
## What happened?

ValueError at /en/catalog/earphones/

## What should've happened instead?

I dont know, perhaps open an site with the requestet items?

## Steps to reproduce

Standart Installation followed all default answers.
German os. (Majaro linux, google chrome)

Request Method: | GET
-- | --
http://localhost:8000/en/catalog/earphones/
2.2.10
ValueError
Can not add/substract money in different currencies.
/home/schatten/sync/prog/django-shop/.env/lib/python3.8/site-packages/shop/money/money_maker.py in _assert_addable, line 233
/home/schatten/sync/prog/django-shop/.env/bin/python
3.8.1
['/home/schatten/sync/prog/django-shop/my-shop',  '/home/schatten/sync/prog/django-shop/.env/lib/python38.zip',  '/home/schatten/sync/prog/django-shop/.env/lib/python3.8',  '/home/schatten/sync/prog/django-shop/.env/lib/python3.8/lib-dynload',  '/usr/lib64/python3.8',  '/usr/lib/python3.8',  '/home/schatten/sync/prog/django-shop/.env/lib/python3.8/site-packages']
Mon, 10 Feb 2020 18:14:58 +0000

**Comment by browniebroke** [comment]
Can you explain how does this relates to the `cookiecutter-django` project? It looks like you run Python 3.8, while this template generate a 3.7 project, so this doesn't look like a "standard installation". Did you intend to open an issue over there? https://github.com/awesto/cookiecutter-django-shop
