### ISSUE TITLE
Purpose of install_python_dependencies.sh

### ISSUE THREAD

**Issue by cdvv7788** [pydanny/cookiecutter-django#245]
I know that it intends to check if there is pip + virtualenv before trying to install the requirements in the requirements files.
If the checks pass, it installs everything (local, test and production). Installing every dependency probably won't matter if it is not used on some setting, but it may be a little overkill on any instance to have everything.
It is not in the installation steps, so i would like to know when it would be a good idea to use this instead of the regular pip -r requirements/some_set_of_requirements.txt.

**Comment by luzfcb** [comment]
I added this file, and my goal was facilitate to create the development environment, and try to avoid that install the dependencies python outside of a virtualenv.

That said, you have no gain when using this utility, except save you some typing to prepare the development environment. 

I intend to include some documentation when I have a free time.

**Comment by pydanny** [comment]
:+1:
