### ISSUE TITLE
The project directory created uses {{cookiecutter.repo_name}} instead of {{cookiecutter.project_name}}

### ISSUE THREAD

**Issue by afosterw** [pydanny/cookiecutter-django#246]
I might be misunderstanding the desired layout but from what I read in Two Scoops it seems like these directories should not both be using the {{cookiecutter.repo_name}} variable.

**Comment by pydanny** [comment]
Hi @afosterw, one thing to keep in mind is that cookiecutter-django, amongst other things, is a place where we explore new concepts and ideas. Things we learned from building it went into Two Scoops of Django 1.8. See https://github.com/pydanny/cookiecutter-django#for-readers-of-two-scoops-of-django-18

For example, right now we are just using `{{cookiecutter.project_name}}` for front facing text, not for directory naming.

I hope that explains our methodology!
