### ISSUE TITLE
Potentially invalid file selector pattern for pre-commit

### ISSUE THREAD

**Issue by demestav** [pydanny/cookiecutter-django#2478]
## What happened?
The pre-commit hook `trailing-whitespace` does not seem to run against any file. This is indicated by the pre-commit report during git staging, which is as follows:

> Trim Trailing Whitespace.............................(no files to check)Skipped

## What should've happened instead?
Looking at the `.pre-commit-config.yaml` file, the `files` hook parameter is `(^|/)a/.+\.(py|html|sh|css|js)$`. Therefore **I am assuming** that the indented behavior is to target all the `.py`, `.html`, `.sh`, `.css` and `.js` files.

## Steps to reproduce
1) Create a new project with cookiecutter
2) `git init`
3) `pre-commit install`
4) `git add .`
5) `git commit -m "Project created"` and you should be able to see the pre-commit report as specified above.

## Comments
Maybe I am missing something but looking at the regular expression for the `files` hook parameter `(^|/)a/.+\.(py|html|sh|css|js)$`, the `a/` does not seem to belong there as it matches the `a/` characters. Is there a purpose for that? By removing that, the hook report as `passed` rather than `Skipped`.

Let me know if this issue is valid and I can submit a pull request.

**Comment by browniebroke** [comment]
Thanks for your patience 😄 

I agree, it seems like a bug. Pull request welcome 👍

**Comment by demestav** [comment]
Great. I will submit a pull request shortly.
