### ISSUE TITLE
Adding telnet to celeryworker

### ISSUE THREAD

**Issue by allen-munsch** [pydanny/cookiecutter-django#2480]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)

Adding `busybox-extras` to the `celery` dockerfile

- https://pkgs.alpinelinux.org/package/edge/main/x86/busybox-extras
- https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/local/django/Dockerfile#L14

```
  # local debugging dependencies ( aka telnet )
  && apk add busybox-extras
```

## Rationale

[//]: # (Why should this feature be implemented?)

Allowing a user to then run something like:

```
# in the celery task

@celery_app.task()
def some_task(model_id: int):
     rdb.set_trace()

# in the shell of the local dev computer
docker-compose -f local.yml exec celeryworker busybox-extras telnet 127.0.0.1 6902
```

## Use case(s) / visualization(s)
```
$ docker-compose -f local.yml exec celeryworker busybox-extras telnet 127.0.0.1 6902
-> pass
(Pdb) l     
10 @celery_app.task()
11 def some_task(model_id: int):
12     rdb.set_trace()
13     pass
(Pdb) print(f"whats the model_id {model_id}")
whats the model_id 123
(Pdb) c
Connection closed by foreign host
```
[//]: # ("Better to see something once than to hear about it a thousand times.")

##### extra note

If it's something that would be of interest let me know and I can try to open a PR. 

Thanks for the great repo!

**Comment by browniebroke** [comment]
The links are for the Alpine distribution, however, we've recently switched to [the Debian based python-slim image](https://github.com/pydanny/cookiecutter-django/pull/2391). Can you confirm whether this is still a problem with the new setup & possibly update the suggestion? Thanks

**Comment by allen-munsch** [comment]
Haven't been able to test this. Closing.
