### ISSUE TITLE
Use pip-compile for requirements?

### ISSUE THREAD

**Issue by blueyed** [pydanny/cookiecutter-django#252]
I think it might be a good idea to use `pip-compile` from [pip-tool's future branch](https://github.com/nvie/pip-tools/tree/future) to maintain the requirements files.

This would mean to have `*.in` files (where no pinning would be used in general), and then a `make` task to build the `*.txt` from there via `pip-compile`, where the current versions (for unpinned inputs) would be used for pinning.

While this is good for maintaining the files in the cookiecutter project by itself, it's also good practice for the generated projects.

Sadly pip-tools has a few issues currently (e.g. it does not handle VCS URLs), but there a PRs for this.

Another issue would be to not resolve the `-r` includes maybe (https://github.com/nvie/pip-tools/issues/174), and the template wrappers for `{% if cookiecutter.use_whitenoise == 'y' -%}` etc need to get addressed (which is relevant for cookiecutter-django, not the generated project).

**Comment by pydanny** [comment]
My concern with some of the more awesome pip tools is their Windows support is sometimes not as solid as `pip` itself. There are a lot of Windows users for this project, so using the tool might exclude them.

**Comment by blueyed** [comment]
@pydanny 
Even when pip-compile was not working well on Windows, it could still be used to manage the Repo's own requirements?!

**Comment by pydanny** [comment]
Ah... I see. We could use Linux/OSX with `pip-compile` to maintain the requirements versions, which then could go anywhere. Is that correct?

**Comment by blueyed** [comment]
Yep.
