### ISSUE TITLE
Extend django-allauth

### ISSUE THREAD

**Issue by WhiskySoda** [pydanny/cookiecutter-django#253]
The inclusion of basic authorisation is extremely handy, but makes the files one would usually find like the templates inaccessible. How does one go about extending the authorisation? e.g. change the content of the e-mails. 

Should one add in Django-auth as a separate app, rip out the CookieCutter User app (which would be sad, because its otherwise perfect)? 

Preferably CookieCutter-Django could include a directory and documentation to override the standard templates? (which I believe is possible if the directory is found in the code). Thank you for reading & your consideration.

**Comment by cdvv7788** [comment]
Django allauth can be extended like any other app. Just place in the template directory the templates you want to override, following the folder structure (https://github.com/pennersr/django-allauth/tree/master/allauth/templates). For emails it should be something like account/email/email_confirmation_message.txt, etc.
This uses 3rd party apps for most things, so just refer to the docs for those apps if you want to override them.

**Comment by WhiskySoda** [comment]
Thank you so much @cdvv7788 - that's really clear. Will do.
