### ISSUE TITLE
The MEDIA_URL and STATIC_URL settings must have different values (Production settings issue)

### ISSUE THREAD

**Issue by cdvv7788** [pydanny/cookiecutter-django#254]
Django is complaining about the paths being the same (which is the default on the template). I fixed this on my settings with:

MEDIA_URL = 'https://s3.amazonaws.com/%s/media/' % AWS_STORAGE_BUCKET_NAME
STATIC_URL = 'https://s3.amazonaws.com/%s/static/' % AWS_STORAGE_BUCKET_NAME

instead of:

MEDIA_URL = 'https://s3.amazonaws.com/%s/' % AWS_STORAGE_BUCKET_NAME
STATIC_URL = MEDIA_URL

What is the purpose of treating them as the same as default? Is this issue showing up for everybody?

**Comment by luzfcb** [comment]
Oh, really. Thanks for reporting this.

@theskumar  this was introduced in https://github.com/pydanny/cookiecutter-django/commit/7fb6f94d5e8b41e4f407c5aacac6fbe452b28a7e#diff-26beb9938fe6c9635e2c57dd6b0f1c5bL87 .
Are there any special reason for this configuration?

or a small mistake which went without anyone see

![Your Unit Tests are Passing ](http://cdn.makeagif.com/media/6-26-2015/jpdwZQ.gif)

**Comment by theskumar** [comment]
> What is the purpose of treating them as the same as default? 
To answer your question, there is no specific reason. 

> Is this issue showing up for everybody?
I don't see it. @cdvv7788 which version of Django are you using and how is it possible to see that complain. `manage.py check --deploy`?

**Comment by theskumar** [comment]
> @theskumar  this was introduced in https://github.com/pydanny/cookiecutter-django/commit/7fb6f94d5e8b41e4f407c5aacac6fbe452b28a7e#diff-26beb9938fe6c9635e2c57dd6b0f1c5bL87 .
> Are there any special reason for this configuration?

It was introduced to make sure that `MEDIA_URL` and `STATIC_URL` are different when using whitenoise. When using whitenoise STATIC_URL should point to a relative `/static/` url which is inherited from `common.py`, instead of fully qualified domain name to `http://s3.amazon.com/...`

**Comment by cdvv7788** [comment]
I am using django1.8.2...that setting is enforced since 1.4 i think.

**Comment by pydanny** [comment]
Is this still an issue?

**Comment by cdvv7788** [comment]
https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/config/settings/production.py 
line 115: STATIC_URL = MEDIA_URL
The setting is still there

**Comment by jayfk** [comment]
fixed in #496
