### ISSUE TITLE
Unable to get certificate for Flower

### ISSUE THREAD

**Issue by browniebroke** [pydanny/cookiecutter-django#2542]
## What happened?

When trying to deploy a site a few days ago, I noticed Traefik logged an error that seem to indicate it was unable to get a certificate for Flower:

```
traefik_1       | time="2020-04-13T13:55:28Z" level=error msg="Unable to obtain ACME certificate for domains \"browniebroke.me\": unable to generate a certificate for the domains [browniebroke.me]: acme: Error -> One or more domains had a problem:\n[browniebroke.me] acme: error: 403 :: POST :: https://acme-v02.api.letsencrypt.org/acme/finalize/83298394/2988033929 :: urn:ietf:params:acme:error:orderNotReady :: Order's status (\"processing\") is not acceptable for finalization, url: \n" providerName=letsencrypt.acme rule="Host(`browniebroke.me`)" routerName=flower-secure-router
```

## What should've happened instead?

Certificate should be issued.

## Steps to reproduce

I'm not sure if it's happening all the time, but that's what I did:

- Generate a new project with Docker & Celery
- Deploy to production
- Wait a few (~5) minutes, error log appears in the Traefik container

**Comment by wadkar** [comment]
I don't suppose this is related to #2217 - it looks like a LetsEncrypt issue. Specifically, your order for certificate is in "processing" state and that hints to something outside Traefik's control to me.

Maybe check community.letsencrypt.org forum and get help? In any case, I am not sure if it's bug in this project.

**Comment by demestav** [comment]
I have deployed a new project just last week and works as expected. The flower entrypoint is served with a valid certificate. As @wadkar said, it possible that this is unrelated to this project.

**Comment by browniebroke** [comment]
Ok thanks for the comments! Yes it looks like it was a one off issue.
