### ISSUE TITLE
How to use non docker Postgres Database

### ISSUE THREAD

**Issue by autoferrit** [pydanny/cookiecutter-django#2546]
I am trying to connect a new app to the database on my host machine where I have PG installed. The reason for this is that I am going to be using a hosted database when deploying so I dont need the docker version of PG. 

Looking up my local IP, I get `192.168.0.64` which works for another container I have to connect to the host instance. But this does not seem to work here. If I `docker exec` into the django container, it does show that IP as the host for the database. I just get this:
```bash
django_1        | Waiting for PostgreSQL to become available...
flower_1        | Waiting for PostgreSQL to become available...
celerybeat_1    | Waiting for PostgreSQL to become available...
celeryworker_1  | Waiting for PostgreSQL to become available...
django_1        | Waiting for PostgreSQL to become available...
flower_1        | Waiting for PostgreSQL to become available...
celerybeat_1    | Waiting for PostgreSQL to become available...
```
So I am hoping to get some input on how to configure this.

**Comment by browniebroke** [comment]
This is a bit out of scope of this project, but the local IP won't work as the Docker Compose stack is actually in a separate network. You can list the networks created by Docker with `docker network ls`.

You need to tell your container to connect to your host machine, which requires to use special value as host IP. I don't know for the others OS, but if you use Docker for Mac, it's `docker.for.mac.host.internal`. [This StackOverflow question](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach) seems to give a lot of options.

**Comment by foarsitter** [comment]
The reason you are coining for not using the PostgreSQL docker container is invalid imho. All that Django needs is a valid database URL. Thus the project will work perfectly in production with a hosted database (It is even designed to work on Heroku with a managed database). I recommend to use the setup as is so other developers added to the project later on, our you using a other dev machine, will be up and running in no-time.

**Comment by browniebroke** [comment]
> The reason for this is that I am going to be using a hosted database when deploying so I dont need the docker version of PG.

I read again the first message and I think I might have misunderstood it... The solution I gave is for connecting to a database outside of Docker but on the host machine, not hosted elsewhere.

@autoferrit could you clarify your question please? Did I answer it or were you asking something else?

> All that Django needs is a valid database URL. Thus the project will work perfectly in production with a hosted database

@foarsitter I totally agree and I would actually recommend this unless you know what you're doing. 

> I recommend to use the setup as is so other developers added to the project later on, our you using a other dev machine, will be up and running in no-time.

Personally, I wouldn't recommend this in development (hence the "a bit out of scope"), I think Docker gives a better isolation between projects, and if you mess up a migration, you can destroy and recreate your DB without affecting other devs. I see your point though.
