### ISSUE TITLE
I am getting a "ModuleNotFoundError: No module named 'flask'" on Heroku 

### ISSUE THREAD

**Issue by prakharrathi25** [pydanny/cookiecutter-django#2557]
## What happened?
I see a I am getting a "ModuleNotFoundError: No module named 'flask'". This is stopping my application from loading on Heroku. 
I have already installed flask on virtual environment as well as on my system and the issue still persists. 

## What should've happened instead?
The application should have loaded without this error. 

## Steps to reproduce ( Logs ) 
<pre><font color="#06989A">2020-04-24T13:17:39.316886+00:00 app[web.1]:</font> self.wsgi = self.app.wsgi()
<font color="#06989A">2020-04-24T13:17:39.316887+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py&quot;, line 67, in wsgi
<font color="#06989A">2020-04-24T13:17:39.316887+00:00 app[web.1]:</font> self.callable = self.load()
<font color="#06989A">2020-04-24T13:17:39.316887+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py&quot;, line 52, in load
<font color="#06989A">2020-04-24T13:17:39.316888+00:00 app[web.1]:</font> return self.load_wsgiapp()
<font color="#06989A">2020-04-24T13:17:39.316888+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py&quot;, line 41, in load_wsgiapp
<font color="#06989A">2020-04-24T13:17:39.316889+00:00 app[web.1]:</font> return util.import_app(self.app_uri)
<font color="#06989A">2020-04-24T13:17:39.316889+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py&quot;, line 350, in import_app
<font color="#06989A">2020-04-24T13:17:39.316889+00:00 app[web.1]:</font> __import__(module)
<font color="#06989A">2020-04-24T13:17:39.316890+00:00 app[web.1]:</font> File &quot;/app/app.py&quot;, line 2, in &lt;module&gt;
<font color="#06989A">2020-04-24T13:17:39.316890+00:00 app[web.1]:</font> from flask import Flask, render_template, url_for, request, redirect
<font color="#06989A">2020-04-24T13:17:39.316898+00:00 app[web.1]:</font> ModuleNotFoundError: No module named &apos;flask&apos;
<font color="#06989A">2020-04-24T13:17:39.317183+00:00 app[web.1]:</font> [2020-04-24 13:17:39 +0000] [11] [INFO] Worker exiting (pid: 11)
<font color="#06989A">2020-04-24T13:17:39.441061+00:00 app[web.1]:</font> [2020-04-24 13:17:39 +0000] [4] [INFO] Shutting down: Master
<font color="#06989A">2020-04-24T13:17:39.441187+00:00 app[web.1]:</font> [2020-04-24 13:17:39 +0000] [4] [INFO] Reason: Worker failed to boot.
<font color="#8AE234"><b>2020-04-24T13:25:42.000000+00:00 app[api]:</b></font> Build started by user <font color="#4E9A06">prakharrathi25@gmail.com</font>
<font color="#06989A">2020-04-24T13:26:50.779076+00:00 heroku[web.1]:</font> State changed from crashed to <font color="#FCE94F">starting</font>
<font color="#8AE234"><b>2020-04-24T13:26:50.551463+00:00 app[api]:</b></font> Deploy <font color="#06989A">75ff8400</font> by user <font color="#4E9A06">prakharrathi25@gmail.com</font>
<font color="#8AE234"><b>2020-04-24T13:26:50.551463+00:00 app[api]:</b></font> Release <font color="#75507B">v4</font> created by user <font color="#4E9A06">prakharrathi25@gmail.com</font>
<font color="#06989A">2020-04-24T13:27:11.485811+00:00 heroku[web.1]:</font> State changed from <font color="#FCE94F">starting</font> to crashed
<font color="#06989A">2020-04-24T13:27:11.342925+00:00 app[web.1]:</font> [2020-04-24 13:27:11 +0000] [4] [INFO] Starting gunicorn 19.9.0
<font color="#06989A">2020-04-24T13:27:11.343731+00:00 app[web.1]:</font> [2020-04-24 13:27:11 +0000] [4] [INFO] Listening at: http://0.0.0.0:29934 (4)
<font color="#06989A">2020-04-24T13:27:11.344060+00:00 app[web.1]:</font> [2020-04-24 13:27:11 +0000] [4] [INFO] Using worker: sync
<font color="#06989A">2020-04-24T13:27:11.349766+00:00 app[web.1]:</font> [2020-04-24 13:27:11 +0000] [10] [INFO] Booting worker with pid: 10
<font color="#06989A">2020-04-24T13:27:11.360106+00:00 app[web.1]:</font> [2020-04-24 13:27:11 +0000] [10] [ERROR] Exception in worker process
<font color="#06989A">2020-04-24T13:27:11.360124+00:00 app[web.1]:</font> Traceback (most recent call last):
<font color="#06989A">2020-04-24T13:27:11.360130+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py&quot;, line 583, in spawn_worker
<font color="#06989A">2020-04-24T13:27:11.360218+00:00 app[web.1]:</font> worker.init_process()
<font color="#06989A">2020-04-24T13:27:11.360220+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py&quot;, line 129, in init_process
<font color="#06989A">2020-04-24T13:27:11.360220+00:00 app[web.1]:</font> self.load_wsgi()
<font color="#06989A">2020-04-24T13:27:11.360220+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py&quot;, line 138, in load_wsgi
<font color="#06989A">2020-04-24T13:27:11.360221+00:00 app[web.1]:</font> self.wsgi = self.app.wsgi()
<font color="#06989A">2020-04-24T13:27:11.360230+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py&quot;, line 67, in wsgi
<font color="#06989A">2020-04-24T13:27:11.360231+00:00 app[web.1]:</font> self.callable = self.load()
<font color="#06989A">2020-04-24T13:27:11.360231+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py&quot;, line 52, in load
<font color="#06989A">2020-04-24T13:27:11.360231+00:00 app[web.1]:</font> return self.load_wsgiapp()
<font color="#06989A">2020-04-24T13:27:11.360232+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py&quot;, line 41, in load_wsgiapp
<font color="#06989A">2020-04-24T13:27:11.360232+00:00 app[web.1]:</font> return util.import_app(self.app_uri)
<font color="#06989A">2020-04-24T13:27:11.360232+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py&quot;, line 350, in import_app
<font color="#06989A">2020-04-24T13:27:11.360233+00:00 app[web.1]:</font> __import__(module)
<font color="#06989A">2020-04-24T13:27:11.360233+00:00 app[web.1]:</font> File &quot;/app/app.py&quot;, line 2, in &lt;module&gt;
<font color="#06989A">2020-04-24T13:27:11.360233+00:00 app[web.1]:</font> from flask import Flask, render_template, url_for, request, redirect
<font color="#06989A">2020-04-24T13:27:11.360291+00:00 app[web.1]:</font> ModuleNotFoundError: No module named &apos;flask&apos;
<font color="#06989A">2020-04-24T13:27:11.360477+00:00 app[web.1]:</font> [2020-04-24 13:27:11 +0000] [10] [INFO] Worker exiting (pid: 10)
<font color="#06989A">2020-04-24T13:27:11.392341+00:00 app[web.1]:</font> [2020-04-24 13:27:11 +0000] [4] [INFO] Shutting down: Master
<font color="#06989A">2020-04-24T13:27:11.392461+00:00 app[web.1]:</font> [2020-04-24 13:27:11 +0000] [4] [INFO] Reason: Worker failed to boot.
<font color="#8AE234"><b>2020-04-24T13:27:12.000000+00:00 app[api]:</b></font> <font color="#8AE234">Build succeeded</font>
<font color="#06989A">2020-04-24T13:28:07.813602+00:00 heroku[web.1]:</font> State changed from crashed to <font color="#FCE94F">starting</font>
<font color="#06989A">2020-04-24T13:28:24.647126+00:00 heroku[web.1]:</font> State changed from <font color="#FCE94F">starting</font> to crashed
<font color="#06989A">2020-04-24T13:28:24.442681+00:00 app[web.1]:</font> [2020-04-24 13:28:24 +0000] [4] [INFO] Starting gunicorn 19.9.0
<font color="#06989A">2020-04-24T13:28:24.443179+00:00 app[web.1]:</font> [2020-04-24 13:28:24 +0000] [4] [INFO] Listening at: http://0.0.0.0:6805 (4)
<font color="#06989A">2020-04-24T13:28:24.443379+00:00 app[web.1]:</font> [2020-04-24 13:28:24 +0000] [4] [INFO] Using worker: sync
<font color="#06989A">2020-04-24T13:28:24.447064+00:00 app[web.1]:</font> [2020-04-24 13:28:24 +0000] [10] [INFO] Booting worker with pid: 10
<font color="#06989A">2020-04-24T13:28:24.453997+00:00 app[web.1]:</font> [2020-04-24 13:28:24 +0000] [10] [ERROR] Exception in worker process
<font color="#06989A">2020-04-24T13:28:24.453998+00:00 app[web.1]:</font> Traceback (most recent call last):
<font color="#06989A">2020-04-24T13:28:24.453998+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py&quot;, line 583, in spawn_worker
<font color="#06989A">2020-04-24T13:28:24.453998+00:00 app[web.1]:</font> worker.init_process()
<font color="#06989A">2020-04-24T13:28:24.453998+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py&quot;, line 129, in init_process
<font color="#06989A">2020-04-24T13:28:24.453999+00:00 app[web.1]:</font> self.load_wsgi()
<font color="#06989A">2020-04-24T13:28:24.453999+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py&quot;, line 138, in load_wsgi
<font color="#06989A">2020-04-24T13:28:24.453999+00:00 app[web.1]:</font> self.wsgi = self.app.wsgi()
<font color="#06989A">2020-04-24T13:28:24.453999+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py&quot;, line 67, in wsgi
<font color="#06989A">2020-04-24T13:28:24.454002+00:00 app[web.1]:</font> self.callable = self.load()
<font color="#06989A">2020-04-24T13:28:24.454002+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py&quot;, line 52, in load
<font color="#06989A">2020-04-24T13:28:24.454002+00:00 app[web.1]:</font> return self.load_wsgiapp()
<font color="#06989A">2020-04-24T13:28:24.454002+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py&quot;, line 41, in load_wsgiapp
<font color="#06989A">2020-04-24T13:28:24.454002+00:00 app[web.1]:</font> return util.import_app(self.app_uri)
<font color="#06989A">2020-04-24T13:28:24.454002+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py&quot;, line 350, in import_app
<font color="#06989A">2020-04-24T13:28:24.454003+00:00 app[web.1]:</font> __import__(module)
<font color="#06989A">2020-04-24T13:28:24.454003+00:00 app[web.1]:</font> File &quot;/app/app.py&quot;, line 2, in &lt;module&gt;
<font color="#06989A">2020-04-24T13:28:24.454003+00:00 app[web.1]:</font> from flask import Flask, render_template, url_for, request, redirect
<font color="#06989A">2020-04-24T13:28:24.454006+00:00 app[web.1]:</font> ModuleNotFoundError: No module named &apos;flask&apos;
<font color="#06989A">2020-04-24T13:28:24.454171+00:00 app[web.1]:</font> [2020-04-24 13:28:24 +0000] [10] [INFO] Worker exiting (pid: 10)
<font color="#06989A">2020-04-24T13:28:24.470439+00:00 app[web.1]:</font> [2020-04-24 13:28:24 +0000] [11] [INFO] Booting worker with pid: 11
<font color="#06989A">2020-04-24T13:28:24.476282+00:00 app[web.1]:</font> [2020-04-24 13:28:24 +0000] [11] [ERROR] Exception in worker process
<font color="#06989A">2020-04-24T13:28:24.476283+00:00 app[web.1]:</font> Traceback (most recent call last):
<font color="#06989A">2020-04-24T13:28:24.476284+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py&quot;, line 583, in spawn_worker
<font color="#06989A">2020-04-24T13:28:24.476284+00:00 app[web.1]:</font> worker.init_process()
<font color="#06989A">2020-04-24T13:28:24.476285+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py&quot;, line 129, in init_process
<font color="#06989A">2020-04-24T13:28:24.476285+00:00 app[web.1]:</font> self.load_wsgi()
<font color="#06989A">2020-04-24T13:28:24.476285+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py&quot;, line 138, in load_wsgi
<font color="#06989A">2020-04-24T13:28:24.476286+00:00 app[web.1]:</font> self.wsgi = self.app.wsgi()
<font color="#06989A">2020-04-24T13:28:24.476286+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py&quot;, line 67, in wsgi
<font color="#06989A">2020-04-24T13:28:24.476287+00:00 app[web.1]:</font> self.callable = self.load()
<font color="#06989A">2020-04-24T13:28:24.476287+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py&quot;, line 52, in load
<font color="#06989A">2020-04-24T13:28:24.476287+00:00 app[web.1]:</font> return self.load_wsgiapp()
<font color="#06989A">2020-04-24T13:28:24.476288+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py&quot;, line 41, in load_wsgiapp
<font color="#06989A">2020-04-24T13:28:24.476289+00:00 app[web.1]:</font> return util.import_app(self.app_uri)
<font color="#06989A">2020-04-24T13:28:24.476289+00:00 app[web.1]:</font> File &quot;/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py&quot;, line 350, in import_app
<font color="#06989A">2020-04-24T13:28:24.476289+00:00 app[web.1]:</font> __import__(module)
<font color="#06989A">2020-04-24T13:28:24.476290+00:00 app[web.1]:</font> File &quot;/app/app.py&quot;, line 2, in &lt;module&gt;
<font color="#06989A">2020-04-24T13:28:24.476290+00:00 app[web.1]:</font> from flask import Flask, render_template, url_for, request, redirect
<font color="#06989A">2020-04-24T13:28:24.476295+00:00 app[web.1]:</font> ModuleNotFoundError: No module named &apos;flask&apos;
<font color="#06989A">2020-04-24T13:28:24.476455+00:00 app[web.1]:</font> [2020-04-24 13:28:24 +0000] [11] [INFO] Worker exiting (pid: 11)
<font color="#06989A">2020-04-24T13:28:24.581572+00:00 app[web.1]:</font> [2020-04-24 13:28:24 +0000] [4] [INFO] Shutting down: Master
<font color="#06989A">2020-04-24T13:28:24.581678+00:00 app[web.1]:</font> [2020-04-24 13:28:24 +0000] [4] [INFO] Reason: Worker failed to boot.
<font color="#4E9A06">2020-04-24T13:29:35.587344+00:00 heroku[router]:</font> at=<font color="#CC0000">error</font> code=<font color="#EF2929"><b>H10</b></font> desc=&quot;App crashed&quot; method=<font color="#AD7FA8"><b>GET</b></font> path=<font color="#4E9A06">&quot;/&quot;</font> host=flair-prediction-app.herokuapp.com request_id=24015513-f2af-4174-a057-3e0d95406412 fwd=&quot;122.162.96.112&quot; dyno= connect= service= status=<font color="#CC0000">503</font> bytes= protocol=https
<font color="#4E9A06">2020-04-24T13:29:37.330254+00:00 heroku[router]:</font> at=<font color="#CC0000">error</font> code=<font color="#EF2929"><b>H10</b></font> desc=&quot;App crashed&quot; method=<font color="#AD7FA8"><b>GET</b></font> path=<font color="#4E9A06">&quot;/&quot;</font> host=flair-prediction-app.herokuapp.com request_id=8caba2a9-f9ba-4c9b-9bb9-2a66a24044e9 fwd=&quot;122.162.96.112&quot; dyno= connect= service= status=<font color="#CC0000">503</font> bytes= protocol=https
<font color="#4E9A06">2020-04-24T13:30:04.497866+00:00 heroku[router]:</font> at=<font color="#CC0000">error</font> code=<font color="#EF2929"><b>H10</b></font> desc=&quot;App crashed&quot; method=<font color="#AD7FA8"><b>GET</b></font> path=<font color="#4E9A06">&quot;/&quot;</font> host=flair-prediction-app.herokuapp.com request_id=2773ad5b-b466-4a23-aa58-96091748fb0f fwd=&quot;122.162.96.112&quot; dyno= connect= service= status=<font color="#CC0000">503</font> bytes= protocol=https
<font color="#4E9A06">2020-04-24T13:31:42.603319+00:00 heroku[router]:</font> at=<font color="#CC0000">error</font> code=<font color="#EF2929"><b>H10</b></font> desc=&quot;App crashed&quot; method=<font color="#AD7FA8"><b>GET</b></font> path=<font color="#4E9A06">&quot;/&quot;</font> host=flair-prediction-app.herokuapp.com request_id=1b9f111c-c505-4796-a2f8-012346ae306a fwd=&quot;122.162.96.112&quot; dyno= connect= service= status=<font color="#CC0000">503</font> bytes= protocol=https
</pre>

**Comment by luzfcb** [comment]
cookiecutter-django does not use `flask` as a direct or indirect dependency

**Comment by luzfcb** [comment]
If you want to use cookiecutter-django on Heroku, generate a new project, mark `y` when the `use_heroku` message was displayed and follow this documentation: 

https://cookiecutter-django.readthedocs.io/en/latest/deployment-on-heroku.html#deployment-on-heroku
