### ISSUE TITLE
How to copy .sql file with backup from host machine into backups folder inside container?

### ISSUE THREAD

**Issue by unixconky** [pydanny/cookiecutter-django#2569]
I want to make it available on the list after I run: 

`docker-compose -f local.yml run postgres list-backups`

and then be able to restore:

`docker-compose -f local.yml exec postgres restore my_file_from_host_machine.sql`

**Comment by browniebroke** [comment]
The location used for backups is mounted] as [a `docker-compose` volume](https://docs.docker.com/compose/compose-file/#volumes):

- Locally: 
  https://github.com/pydanny/cookiecutter-django/blob/ff0e1a21e1c3f7f671eb18d026b1868b98be4096/%7B%7Bcookiecutter.project_slug%7D%7D/local.yml#L36

- In production:
  https://github.com/pydanny/cookiecutter-django/blob/ff0e1a21e1c3f7f671eb18d026b1868b98be4096/%7B%7Bcookiecutter.project_slug%7D%7D/production.yml#L29

You can list all the volumes with `docker volume ls` and see the location of the one you're interested in with `docker volume inspect <volume_name>`. The host location is in the `Mountpoint` ([source](https://forums.docker.com/t/host-path-of-volume/12277)).

**Comment by browniebroke** [comment]
Actually our [ducumentation oulines](https://cookiecutter-django.readthedocs.io/en/latest/docker-postgres-backups.html#copying-backups-locally) how to do so with [`docker cp`](https://docs.docker.com/engine/reference/commandline/cp/), which sounds even easier.

Looks like you can copy from the host to the container or from the container to the host, which I think answers your question.
