### ISSUE TITLE
I am getting problems while trying to execute the following code

### ISSUE THREAD

**Issue by Anurag24coder** [pydanny/cookiecutter-django#2585]
**THE PROGRAM IS THIS :**
import os
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session, sessionmaker
engine = create_engine(os.getenv("DATABASE_URL"))
db = scoped_session(sessionmaker(bind=engine))

def main():
    flights=db.execute("SELECT origin ,destination, duration FROM flights").fetchall()
    for flight in flights:
        print(f"{flight.origin} to {flight.destination} in {flight.duration}")

if __name__=="__main__":
    main()

**THE ERROR IS THIS:-**

Traceback (most recent call last):
  File "C:\Users\user\.spyder-py3\temp.py", line 4, in <module>
    engine = create_engine(os.getenv("DATABASE_URL"))
  File "C:\Users\user\anaconda3\lib\site-packages\sqlalchemy\engine\__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "C:\Users\user\anaconda3\lib\site-packages\sqlalchemy\engine\strategies.py", line 56, in create
    plugins = u._instantiate_plugins(kwargs)
AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'

**PLEASE HELP AS I'M NEW TO PROGRAMMING : )**

**Comment by Afrowave** [comment]
@Anurag24coder I am sorry but the problem you are having has nothing to do with this project, `cookiecutter-django`.

You will get a faster response by looking for a solution on [StackOverflow](https://stackoverflow.com/) platform..

**Comment by browniebroke** [comment]
☝️ Yes, basically what @Afrowave wrote.
