### ISSUE TITLE
Missing "rest_framework.authtoken"

### ISSUE THREAD

**Issue by cgajagon** [pydanny/cookiecutter-django#2587]
## What happened?
The server sends an error message when posting to the API end point "/auth-token".
The error message is the following:
AttributeError: type object 'Token' has no attribute 'objects'

## What should've happened instead?
This request should send the access token for the user

## Potential solution
The issue is because "rest_framework.authtoken" is missing in the settings' INSTALLED_APPS.
So far it is only register "rest_framework" within INSTALLED_APPS.
However without the additional line the command "Token.objects.get_or_create(user=user)" is abstract and doesn't have the default manager (objects).

Thank you!

**Comment by Andrew-Chen-Wang** [comment]
When did you generate the app? And did you generate it with use_drf? It's in the settings: https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/base.py#L82

**Comment by browniebroke** [comment]
Yes, that was fixed on the 15th of March (#2471).

**Comment by cgajagon** [comment]
Perfect! Thank you!
