### ISSUE TITLE
ImproperlyConfigured exception when running createsuperuser in docker container

### ISSUE THREAD

**Issue by stodge** [pydanny/cookiecutter-django#2589]
## What happened?

I started using Docker, opened a shell into the container and ran:

`python manage.py createsuperuser`

as per the readme, but it gave an error:

`django.core.exceptions.ImproperlyConfigured: Set the DATABASE_URL environment variable`

I had to define the database URL before running manage.py:

`DATABASE_URL=postgres://user:pw@postgres:5432/db_name python manage.py createsuperuser`

## What should've happened instead?

The manage.py script should load the Django environment, the env should be configured and the management command should run as expected.

## Steps to reproduce

```
docker-compose -f local.yml up
docker-compose -f local.yml exec django sh
python manage.py createsuperuser
```

**Comment by foarsitter** [comment]
By entering the container through `exec django sh` you skip the 
 `compose/production/django/entrypoint` script. Running manage.py commands should be done as explained in the [docs](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html?highlight=shell#execute-management-commands) i.e.: `docker-compose -f local.yml run --rm django python manage.py createsuperuser`.

**Comment by browniebroke** [comment]
Thanks @foarsitter I think that covers it. Feel free to reopen if the problem persists.
