### ISSUE TITLE
RuntimeError when importing users.models in Django shell

### ISSUE THREAD

**Issue by stodge** [pydanny/cookiecutter-django#2590]
## What happened?

I started the Django shell in the container and tried to import the user models but I got an error:

```
from users.models import *
RuntimeError: Model class users.models.User doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

## What should've happened instead?

The models module should be imported and I should be able to access user data, e.g. `User.objects.all()`

## Steps to reproduce

```
docker-compose -f local.yml up
docker-compose -f local.yml exec django sh
from users.models import *
```

**Comment by foarsitter** [comment]
When I run `docker-compose -f local.yml run --rm django python manage.py shell` the same error arises. But if you used this project template you need to import the user model from the correct package: `from project_slug.users.models import *`.

**Comment by stodge** [comment]
Ah of course, the project layout is probably slightly different to what I'm used to. Thanks.

**Comment by browniebroke** [comment]
That's a bit annoying though, would be nice if both could work maybe?

**Comment by Andrew-Chen-Wang** [comment]
Hm, considering `manage.py` is where the main directory is located, I don't think `users.model` will work. The only thing that would work is `project_slug.users.model`

**Comment by PersonRP7** [comment]
I got around it like this:
`from django.contrib.auth import get_user_model`
`User = get_user_model()`

**Comment by Andrew-Chen-Wang** [comment]
I think the purpose was to be able to import directly from users.models or app.models. That wouldn't work if you had a custom model totally unrelated to AUTH_USER_MODELS

**Comment by browniebroke** [comment]
As previously mentioned, it's not possible to import with `users.model`, one should import with `project_slug.users.model` (or using `django.contrib.auth.get_user_model`).

I think this answers the question, closing this.
