### ISSUE TITLE
Remove support for PostgreSQL 9.4

### ISSUE THREAD

**Issue by luzfcb** [pydanny/cookiecutter-django#2592]
## Rationale

1. PostgreSQL 9.4 officially reached end-of-life at February 13, 2020:
https://www.postgresql.org/support/versioning/

2. The Django 3.0 defines that PostgreSQL 9.5 is the minimum version
https://docs.djangoproject.com/en/3.0/ref/databases/#postgresql-notes

3. PostgreSQL 9.4 is already deprecated on Heroku
https://devcenter.heroku.com/changelog-items/1661

  - [ ] Update cookiecutter.json
  - [ ] Update README.rst
  - [ ] Update tests/test_cookiecutter_generation.py
  - [ ] Add yourself to CONTRIBUTORS.rst
  - [ ] Update CHANGELOG.md

**Comment by PilhwanKim** [comment]
May I try this issue? @luzfcb

**Comment by luzfcb** [comment]
@PilhwanKim Thanks for showing interest. 👍  Go ahead if you have free time to work on it.

**Comment by Andrew-Chen-Wang** [comment]
@PilhwanKim If it's ok, you should probably also try doing #2593 simultaneously.

**Comment by PilhwanKim** [comment]
@Andrew-Chen-Wang OK, I I'll do it together.

**Comment by browniebroke** [comment]
Done in #2676
