### ISSUE TITLE
Add PostgreSQL 12 support

### ISSUE THREAD

**Issue by luzfcb** [pydanny/cookiecutter-django#2593]
PostgreSQL 12 was released several months ago and is now widely available on major cloud platforms.

- [ ] Update cookiecutter.json
- [ ] Update README.rst
- [ ] Update tests/test_cookiecutter_generation.py
- [ ] Add yourself to CONTRIBUTORS.rst
- [ ] Update CHANGELOG.md

**Comment by Andrew-Chen-Wang** [comment]
Oh, that README with the configurations (like project_name, project_slug, etc.) should just be completely changed, btw. I don't even think it's in the right order anymore, unless that's the desired format for show.

**Comment by PilhwanKim** [comment]
OK, I I'll do it together. #2592

**Comment by arnav13081994** [comment]
As I understand, postgresql version number is only being used in the dockerfile to create the right settings and get the correct image from docker, right? 

I could only find it here: 

> /<PROJECT_SLUG>/compose/production/postgres/Dockerfile 

I am using Postgresql 12.3 with docker and so far everything is working fine. I just changed the version number from 11.3 to 12.3 

```
FROM postgres:12.3
```

**Comment by Andrew-Chen-Wang** [comment]
@arnav13081994 Yes, unless my PR for a faster Travis and GitLab is merged #2637. But it's not compatible with celery yet. Works fine on v4.4.2 but not latest for some reason. Tracking celery/celery#6199 Hopefully it's a fixable bug or different command or configuration.

If it's merged, then you can copy psycopg/psycopg3's configuration for Travis. I'm not sure about GitLab however. I do know that PostgreSQL 12 should be much faster than other Postgres versions, so it'd be great to have this.
