### ISSUE TITLE
Running pytest on Docker has DEBUG=False, even with intervention

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [pydanny/cookiecutter-django#2599]
## What happened?

When testing with the command `docker-compose -f local.yml run --rm django pytest`, my program asserted that DEBUG was False. From config.settings.base, it makes sense why.

However, if you add DEBUG=True above and below the import in config.settings.test, the DEBUG is still False.

## What should've happened instead?

settings.DEBUG should've been False.

## Steps to reproduce

Create a view or something that raises an error if debug is False. In config.settings.test, add DEBUG=True above and below the import statement, but the bottom is most important. Finally, check DEBUG with a test.

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
[//]: # (* Logs)

**Comment by browniebroke** [comment]
This is set by `pytest-django` [here](https://github.com/pytest-dev/pytest-django/blob/ee7858af1a80e0091af4d260c0a70e5766c1196a/pytest_django/plugin.py#L473) and it's apparently the same thing in Django.

There was [an issue](https://github.com/pytest-dev/pytest-django/issues/228) opened a while ago to change that, a [first PR which was merged](https://github.com/pytest-dev/pytest-django/pull/231), then [revered here](https://github.com/pytest-dev/pytest-django/commit/3cd0d32c0f92908251eaa397ad61596c988aaa45). There is now [an open PR](https://github.com/pytest-dev/pytest-django/pull/463) for it.

I'll close this, feel free to get in touch with `pytest-django` to get the above PR merged.

**Comment by Andrew-Chen-Wang** [comment]
Can’t believe it was a pytest django problem. Thank you!
