### ISSUE TITLE
Separate/isolate per platform setup/deployment to different repositories

### ISSUE THREAD

**Issue by theskumar** [pydanny/cookiecutter-django#260]
Continuing from here: https://github.com/pydanny/cookiecutter-django/pull/258#issuecomment-119078354

We should start to think about separating out, platform specific setups to a different repo and while supporting on 1 or 2(at max.) in the core cookiecutter.

Currently we have Heroku, dokku, Docker and Ubuntu and we had a PR for Fedora.

**Comment by theskumar** [comment]
Quoting @burhan from https://github.com/pydanny/cookiecutter-django/pull/258#issuecomment-119169813 
> I recommend adding them as `feature/` branches; and then giving people access to maintain those branches (ie, sponsors for certain platforms).
> 
> My personal order of preference would be:
> 
> 1. Docker (with docker-compose) - as this is most agnostic and has widest support (osx, linux, windows, Amazon, GAE, etc.)
> 2. Ubuntu
> 3. Heroku
> 
> The others, based on interest/support from the community. I personally use the following; and can support these:
> 
> 1. AWS BeanStalk
> 2. Docker on AWS
> 3. Oracle
> 4. RHEL

**Comment by burhan** [comment]
I recommend adding them as feature/ branches; and then giving people access to maintain those branches (ie, sponsors for certain platforms).

My personal order of preference would be:

1. Docker (with docker-compose) - as this is most agnostic and has widest support (osx, linux, windows, Amazon, GAE, etc.)
2. Ubuntu
3. Heroku

The others, based on interest/support from the community. I personally use the following; and can support these:

1. AWS BeanStalk
2. Docker on AWS
3. Oracle
4. RHEL

**Comment by jpatel3** [comment]
+1 AWS BeanStalk

**Comment by pydanny** [comment]
In my experience vendors won't provide support here. Sure, they might do a drive-by pull request, but they aren't going to maintain things. That falls upon us, the community and especially the core contributors. 

That's why we don't provide more options, Redhat, Amazon, et al, they just aren't going to help us maintain tools to access their systems.

**Comment by pydanny** [comment]
As much as I want to support separate repos, I don't think its feasible. None of us have the time to execute this feature.
