### ISSUE TITLE
Easy upgrade ?

### ISSUE THREAD

**Issue by jarod51** [pydanny/cookiecutter-django#2601]
Hi

I have a few month old project made with django cookiecutter :) Nice !

Now i see that there were many updates in the last few weeks/months. Is there an easy way to update files ? Should I diff them one by one to find updates ?

Thank you

**Comment by luzfcb** [comment]
@jarod51 There is no easy way to upgrade. You should probably generate a new project with the exact same options you used initially, and then use git diff.
