### ISSUE TITLE
Update domain name for traefik cert generation

### ISSUE THREAD

**Issue by ohimors** [pydanny/cookiecutter-django#2621]
What's the best way to update my domain?  The domain I created the project with isn't available.  I tried replacing all references and rebuilding the project but it looks like there are still references to the old domain.  I haven't blown away the database image because I have some test data and that seems a bit aggressive.

**Comment by demestav** [comment]
> but it looks like there are still references to the old domain

What is causing the problem?

**Comment by Andrew-Chen-Wang** [comment]
@ohimors Try going to project_slug/contrib/sites/migrations/0001_initial.py. Seems like the domain names are stored there in that little table.

**Comment by browniebroke** [comment]
This migration is pre-populating the data for [Django' sites framework](https://docs.djangoproject.com/en/3.0/ref/contrib/sites/) with the domain you answered in the setup step. This contrib app is accessible via the admin, where you may edit it after it's been generated.
