### ISSUE TITLE
{{project}}.utils.storages isn't created when cloud_provider = AWS

### ISSUE THREAD

**Issue by johnmathews** [pydanny/cookiecutter-django#2626]
## What happened?
project was generated with cloud_provider set to AWS. 
the module `{{project}}.utils.storages` isn't created, causing an error during deployment to prod.
this seems like it could be an oversight? sorry if its not :) 

## What should've happened instead?
he module `{{project}}.utils.storages` should be created

## Steps to reproduce
Is there a way I can retrieve my project generation options?

**Comment by luzfcb** [comment]
> project was generated with cloud_provider set to AWS.
the module {{project}}.utils.storages isn't created, causing an error during deployment to prod.

I can't see a cause for the file not being generated. The only way it doesn't exist is if `cloud_provider` is None


https://github.com/pydanny/cookiecutter-django/blob/aefbbb0a9edbdbced3fb02b744befcf9ce6d5b58/hooks/post_gen_project.py#L373-L378



> Is there a way I can retrieve my project generation options?

Currently no...

https://github.com/cookiecutter/cookiecutter/issues/1417

**Comment by johnmathews** [comment]
i have all the the other settings that come from cloud_provider=AWS and i generated the project using the current version.

**Comment by luzfcb** [comment]
@johnmathews 

I still couldn't reproduce the error.


This is the recording of my session:


![](https://gist.githubusercontent.com/luzfcb/967d530d95d30abc84746c5dbc3b4321/raw/dbac6f774ec142ca74028b760cfe8da34dde23e1/termtosvg_osbjxrx2.svg)

**Comment by johnmathews** [comment]
you are right, I cannot reproduce the error either. Apologies. Thanks for working on a really useful tool. 👍 https://asciinema.org/a/ImbsrwB4dD4WgnYhBzEX10OM3
