### ISSUE TITLE
error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/app/.env/bin/python3.8'

### ISSUE THREAD

**Issue by nomhoi** [pydanny/cookiecutter-django#2641]
## What happened?

Run the command:
docker-compose -f local.yml up

I get this error in logs:
django          | WARNING:  error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/app/.env/bin/python3.8'

## What should've happened instead?

After running this command
docker-compose -f local.yml up
django server should run.

## Steps to reproduce

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
### Replay file:
{"cookiecutter": {"use_async": "y", "keep_local_envs_in_vcs": "y", "author_name": "nomhoi", "use_heroku": "n", "js_task_runner": "None", "timezone": "UTC", "_template": "https://github.com/pydanny/cookiecutter-django", "use_compressor": "n", "use_celery": "y", "use_pycharm": "y", "cloud_provider": "None", "mail_service": "Other SMTP", "project_slug": "project", "domain_name": "example.com", "version": "0.1.0", "email": "info@example.com", "project_name": "project", "description": "project", "use_whitenoise": "y", "custom_bootstrap_compilation": "n", "windows": "n", "use_drf": "y", "ci_tool": "None", "use_mailhog": "y", "debug": "y", "postgresql_version": "11.3", "use_docker": "y", "use_sentry": "n", "open_source_license": "Not open source"}}

### Logs

django          | WARNING:  error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/app/.env/bin/python3.8'
django          | WARNING:  error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/app/.env/bin/python3.8'
django          | WARNING:  error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/app/.env/bin/python3.8'
django          | WARNING:  error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/app/.env/bin/python3.8'
django          | WARNING:  error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/app/.env/bin/python3.8'

**Comment by nguyenthanhquangbbs** [comment]
In **compose/local/django/start**, just remove **--reload**

**Comment by nomhoi** [comment]
> In **compose/local/django/start**, just remove **--reload**

Thank you! This works.

**Comment by ajaidanial** [comment]
So yes removing `--reload` solved the problem. 

But how do we enable live reloading when the code changes?

**Comment by nguyenthanhquangbbs** [comment]
I found another solution @ajaidanial :
You can use `--reload` option.
If you create a `venv` folder by `virtualenv --python=python3.8 venv`, you should exclude this folder when mapping volume in `local.yml`. For example:
```
    volumes:
      - .:/app:z
      - /app/venv/
```

**Comment by asencis** [comment]
FYI @pydanny :

I'd like to add my ten cents here to this issue for future information. What causes this error?

As @nguyenthanhquangbbs mentions, you've probably created a /env or /venv file in the root of the project whilst working with Django. And you need to ignore this from your docker-compose setup.

*However*, that being said - I believe the true solution is to update the docker ignore file for this project to the following: `cookiecutter-django/{{cookiecutter.project_slug}}/.dockerignore`

```
.*
!.coveragerc
!.env
!.pylintrc
venv
env
```

Or we could go full hog and update it to this:

```
.*
!.coveragerc
!.env
!.pylintrc
__pycache__
*.pyc
*.pyo
*.pyd
.Python
env
venv
pip-log.txt
pip-delete-this-directory.txt
.tox
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*,cover
*.log
.git
```

CC. @nomhoi @ajaidanial
