### ISSUE TITLE
Ask before writing into an existing project directory

### ISSUE THREAD

**Issue by lgp171188** [pydanny/cookiecutter-django#265]
I have an existing Django project that does not use the cookiecutter-django template. When running ``cookiecutter https://github.com/pydanny/cookiecutter-django``, it writes into the project directory even if it already exists without warning the user about it.

The correct behaviour would be to abort if the project directory already exists or at least warn the user and ask for confirmation before writing into the existing directory.

**Comment by lgp171188** [comment]
After having a quick look at the source for cookiecutter-django, it looks like this could be an issue with cookiecutter

**Comment by luzfcb** [comment]
@lgp171188 yes, this can be a problem with cookiecutter. please, you could report it in https://github.com/audreyr/cookiecutter

**Comment by pydanny** [comment]
As this is a cookiecutter issue, I'm closing it here. Thank you @lgp171188 for reporting this ticket.
