### ISSUE TITLE
Adding django-cors-headers to requirements if drf selected

### ISSUE THREAD

**Issue by ghost** [pydanny/cookiecutter-django#2650]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)
Adding django-cors-headers to requirements/base.txt if drf is selected in the setup process, having it setup in the settings.

## Rationale

[//]: # (Why should this feature be implemented?)
As far as I know, data from the DRF cannot be consumed without the cors headers properly configured.

**Comment by aadithpm** [comment]
Would this be adding `django-cors-headers` when `use_drf` is true in `{{cookiecutter.project_slug}}/requirements.base.txt` or would there be more steps involved? I'd like to take this if it's open.

**Comment by browniebroke** [comment]
I think that's all we need to do, yes.

**Comment by aadithpm** [comment]
Okay, I'll take a look at the guidelines and make a PR. Thanks!

**Comment by aadithpm** [comment]
Created a PR here: #2683
