### ISSUE TITLE
"docker-compose -f local.yml docs" not working

### ISSUE THREAD

**Issue by Qoyyuum** [pydanny/cookiecutter-django#2666]
## What happened?

Following the [documentation](https://cookiecutter-django.readthedocs.io/en/latest/document.html), it says that I can have a copy of this cookiecutter doc if I ran `$ docker-compose -f local.yml up docs` only to realize that its not defined in the `local.yml` file.

## What should've happened instead?

Build the docs and run it in a container instance.

## Steps to reproduce

[//]: # (Any or all of the following:) 

1. cookiecutter a new django project that uses Docker

2. `docker-compose -f local.yml build`

3. `docker-compose -f local.yml up docs`

[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)

Windows 10 Pro : version 1909
OS-Build: 18363.900
Docker-Desktop: 2.3.0.3
Docker-Engine: 19.03.8
Docker Compose: 1.25.5

[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)

[//]: # (* Logs)

Console log

```
$ docker-compose -f local.yml up docs
ERROR: No such service: docs
```

**Comment by Andrew-Chen-Wang** [comment]
@Qoyyuum this commit may be what you're looking for: https://github.com/pydanny/cookiecutter-django/commit/3152bdaeb37c863a4e7942d8a243af1d7453c9ce#diff-9daff9f0fd336c81c20e7805b1aade63

**Comment by browniebroke** [comment]
Thanks @Andrew-Chen-Wang, yes that's a new addition to the temnplate, maybe you generated your project just before? If that's the case, I think we can close this issue.

**Comment by Qoyyuum** [comment]
Give me sometime to re-clone a cookiecutter to confirm this.

**Comment by Qoyyuum** [comment]
After I re-cloned the cookiecutter, the `docker-compose.yml` file does now indeed have a `docs` service. Thanks guys!
