### ISSUE TITLE
 DJANGO_SECRET_KEY is not generated automatically

### ISSUE THREAD

**Issue by seenureddy** [pydanny/cookiecutter-django#267]
I did not find any django auto generated secret-key in base.py file. Doc says without auto generated secret-key there will be security issues. Can you follow the link: https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-SECRET_KEY

**Comment by luzfcb** [comment]
You need define `DJANGO_SECRET_KEY` environment variable

See:

https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/config/settings/local.py#L22

https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/config/settings/production.py#L22

__
Fábio C. Barrionuevo da Luz Acadêmico de Sistemas de Informação na
Faculdade Católica do Tocantins - FACTO Palmas - Tocantins - Brasil -
América do Sul

http://pythonclub.com.br/

Blog colaborativo sobre Python e tecnologias Relacionadas, mantido
totalmente no https://github.com/pythonclub/pythonclub.github.io .

Todos são livres para publicar. É só fazer fork, escrever sua postagem e
mandar o pull-request.
Leia mais sobre como publicar em README.md e contributing.md.
Regra básica de postagem: "Você" acha interessante? É útil para "você"?
Pode ser utilizado com Python ou é útil para quem usa Python? Está
esperando o que? Publica logo, que estou louco para ler...
Em 11/07/2015 16:46, "seenureddy" <notifications@github.com> escreveu:

**Comment by pydanny** [comment]
Since `settings/local.py` is not meant for anything beyond local development, and we use environment variables to more securely protect our apps (storing secret keys in git isn't the best idea), and this practice has been vetted by several core Django members on the Django security team (as explained in Chapter 5 of Two Scoops of Django), I'm marking this as closed.
