### ISSUE TITLE
Implicit global settings  in utils/context_processors.py is a security risk

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#2670]
## What happened?

https://github.com/feldroy/two-scoops-of-django-3.x/issues/80

## What should've happened instead?

We shouldn't dump all settings into the context processor. All it takes is one mistake and a critical password or key is now public.

Solution in https://github.com/feldroy/django-crash-starter/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/utils/context_processors.py

**Comment by luzfcb** [comment]
This issue was first reported on https://github.com/pydanny/cookiecutter-django/issues/2614
