### ISSUE TITLE
Why is postgres taking computer user as login user? 

### ISSUE THREAD

**Issue by Ruhulcse** [pydanny/cookiecutter-django#2687]
as though i have set postgres user as postgres in my env file. where is the problem ?
![Screenshot from 2020-07-20 23-30-00](https://user-images.githubusercontent.com/20565147/87970943-5d9bc580-cae6-11ea-8493-9370ba82a8f4.png)

**Comment by Afrowave** [comment]
Hi @Ruhulcse,  
  
From what I see in the posted image, you are in the wrong place here. If you really want help with Cookiecutter Django, please ask your questions on about this project on [StackOverflow.](https://stackoverflow.com/search?q=cookiecutter-django)

**Comment by luzfcb** [comment]
@Ruhulcse cookiecutter-django does not read the `.env` file by default, you must define `DJANGO_READ_DOT_ENV_FILE=True` manually (outside the .env file)

https://github.com/pydanny/cookiecutter-django/blob/8c8d9c1825e0bd7332fe1e3791ff09bb2f275e32/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/base.py#L13-L16


In addition, if you are not chosen `use_docker=y` when generating the project and have not defined a `DATABASE_URL` in the environment variables or `.env` file, cookiecutter-django will try to access postgresql using unix socket.


https://github.com/pydanny/cookiecutter-django/blob/8c8d9c1825e0bd7332fe1e3791ff09bb2f275e32/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/base.py#L43-L49
