### ISSUE TITLE
How can you manage the postgres DB with pgAdmin or other tools? 

### ISSUE THREAD

**Issue by luanjubica-helius** [pydanny/cookiecutter-django#2692]
Since the username/password created is random how do you connect to the Postgres DB with a client tool?

**Comment by Andrew-Chen-Wang** [comment]
Are you using the Docker configuration? If so, it's in `.envs/.local/.postgres` and you can follow a tutorial on how to connect using psql... I think. Otherwise, you can use `dbshell`

**Comment by luanjubica-helius** [comment]
Hello, yes I see the .envs/.local/.postgres I thought those were encrypted, it seems they are not. Thanks!
