### ISSUE TITLE
django-cors-headers CORS origin whitelist

### ISSUE THREAD

**Issue by aadithpm** [pydanny/cookiecutter-django#2696]
## What happened?

A recent PR added `django-cors-headers` to the project if it used the Django REST Framework (DRF). The `CORS_ORIGIN_WHITELIST` as part of the CORS headers configuration was not set correctly.

## What should've happened instead?

From `pyup`:

> 
> In django-cors-headers version 3.0.0, ``CORS_ORIGIN_WHITELIST`` requires URI schemes, and optionally ports. This is part of the CORS specification (Section 3.2 <https://tools.ietf.org/html/rfc6454section-3.2>) that was not implemented in this library, except from with the ``CORS_ORIGIN_REGEX_WHITELIST`` setting. It fixes a security issue where the CORS middleware would allow requests between schemes, for example from insecure ``http://`` Origins to a secure ``https://`` site.
> 
> You will need to update your whitelist to include schemes, for example from this:
> 
> CORS_ORIGIN_WHITELIST = ['example.com']
> 
> to this:
> 
> CORS_ORIGIN_WHITELIST = ['https://example.com']
> 

I made the original PR and this was my oversight, apologies for that - I wanted to bring this up here so we're aware.

**Comment by browniebroke** [comment]
We don't specify this setting, so I don't think it's the real problem. The problem was that the version was pinned to an old one, instead of the latest one. [I've fixed this](https://github.com/pydanny/cookiecutter-django/commit/6fffaf13cab98d4ae2682fcb58d28af406d9ec95) in the main branch.

**Comment by aadithpm** [comment]
Ah, that's my bad as well.  I'm honestly not sure why I pinned that version when PyPI explicitly says the latest version is 3.4.0. Thanks!

**Comment by browniebroke** [comment]
No problem, I also missed it, and I'm a bit confused why it was caught earlier, safety CI doesn't work with PRs coming from forks it seems.
