### ISSUE TITLE
database configuration unclear

### ISSUE THREAD

**Issue by musicformellons** [pydanny/cookiecutter-django#270]
I run into problems when installing. Instruction says 
>Then, create a PostgreSQL database and add the database configuration using the dj-database-url >app pattern: postgres://db_owner:password@dbserver_ip:port/db_name either:
>
>in the config.settings.common.py setting file,
>or in the environment variable DATABASE_URL"

Remarks:
1) I get this error: "FATAL:  password authentication failed for user "cookie" "; cookie is my db_owner. For dbserver_ip:port  I use 127.0.0.1:5432
2) config.settings.common.py should be config/settings/common.py 
3) I used the common.py file; I am curious though how exactly I would set the environment variable DATABASE_URL ; I tried to look it up but do not get clear answers.
4) it seems to implicate one should install dj-database-url ...? More detail please.

Please help.

**Comment by pydanny** [comment]
What is the precise value that you used for `postgres://db_owner:password@dbserver_ip:port/db_name`?

**Comment by musicformellons** [comment]
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'cookieDB',
        'USER': 'cookie',
        'PASSWORD': 'mypassword',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }}

DATABASES['default']['ATOMIC_REQUESTS'] = True


2015-07-13 22:27 GMT+02:00 Daniel Greenfeld <notifications@github.com>:

**Comment by musicformellons** [comment]
I also tried (but get same error):
DATABASES = {
    # Raises ImproperlyConfigured exception if DATABASE_URL not in
os.environ
    'default': env.db("DATABASE_URL", default="postgres://
cookie:mypassword@127.0.0.1:5432/cookieDB"),
}


2015-07-14 16:21 GMT+02:00 mailsietse . <mailsietse@gmail.com>:

**Comment by luzfcb** [comment]
please try to set the environment variable: 
`DATABASE_URL` environment variable

into terminal:

```bash
export DATABASE_URL=postgres://cookie:mypassword@127.0.0.1:5432/cookieDB
```

in the same terminal, run:

```
python manage.py migrate
python manage.py runserver
```

about question 4: 
[django-environ](https://github.com/joke2k/django-environ) use the same [api](https://github.com/joke2k/django-environ/blob/master/environ/environ.py#L315) of dj-database-url

**Comment by musicformellons** [comment]
did that, but error remains.

2015-07-14 16:37 GMT+02:00 Fábio C. Barrionuevo da Luz <
notifications@github.com>:

**Comment by pydanny** [comment]
Password authentication. Hmmm.... When you created your database, did you also spell correctly the `cookie` user and `mypassword` password?

FWIW, I make mistakes on this all the time, which is why for local development I create databases without username and passwords. My thought is that if someone can access my local dev databases without my permission I've got much, much, much bigger things to worry about.

**Comment by musicformellons** [comment]
mmh, i tried twice before but will try now without user & pw

2015-07-14 18:07 GMT+02:00 Daniel Greenfeld <notifications@github.com>:

**Comment by musicformellons** [comment]
[embarassing:] how do you create a db without username and pw? In psql I
did 'create user with password' so leaving blanks (no ''). Furthermore I
do:
'default': env.db("DATABASE_URL", default="postgres://:@
127.0.0.1:5432/cookieDB"),
and I get now:
django.db.utils.OperationalError: fe_sendauth: no password supplied


2015-07-14 18:25 GMT+02:00 mailsietse . <mailsietse@gmail.com>:

**Comment by musicformellons** [comment]
Solved! Sorry... I messed up Postgres database creation: I did not use ; at the end of psql commands... Now I can continue the setup! Thanks for your help!

**Comment by lgp171188** [comment]
When every other environment variable used in this cookiecutter template has a ``DJANGO_`` prefix, it seems to be ambiguous to have the environment variable for database URL as ``DATABASE_URL``

**Comment by pydanny** [comment]
@lgp171188, please open your observation as a separate issue, as it is arguably unrelated to this issue.
