### ISSUE TITLE
Short project name causes failure in flake8-isort

### ISSUE THREAD

**Issue by janfabry** [pydanny/cookiecutter-django#2711]
## What happened?

`flake8-isort` fails on two files if the project name is too short.

For my project name with 8 characters, it fails in `[project_apps_dir]/users/tests/test_views.py` and `[project_apps_dir]/users/urls.py`

_Originally posted by @alexche77 in https://github.com/pydanny/cookiecutter-django/issues/2502#issuecomment-638589822_

## What should've happened instead?

No flake8 failure. All style failures should either not be there, or be fixed by pre-commit hooks.

## Steps to reproduce

```
# cookiecutter gh:pydanny/cookiecutter-django --no-input project_slug=abcdefgh
# git init
# pre-commit install
# git add .
# git commit
# (pre-commit fix cycle for trailing-whitespace, end-of-file-fixer and black)
# git commit
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Passed
black....................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

abcdefgh/users/urls.py:3:1: I001 isort found an import in the wrong position
abcdefgh/users/urls.py:4:1: I001 isort found an import in the wrong position
abcdefgh/users/urls.py:5:1: I001 isort found an import in the wrong position
abcdefgh/users/urls.py:6:1: I001 isort found an import in the wrong position
abcdefgh/users/urls.py:7:1: I001 isort found an import in the wrong position
abcdefgh/users/tests/test_views.py:8:1: I001 isort found an import in the wrong position
abcdefgh/users/tests/test_views.py:9:1: I001 isort found an import in the wrong position
abcdefgh/users/tests/test_views.py:10:1: I001 isort found an import in the wrong position
abcdefgh/users/tests/test_views.py:11:1: I001 isort found an import in the wrong position
abcdefgh/users/tests/test_views.py:12:1: I001 isort found an import in the wrong position
```

## Suggested solution

Either use a different import clause depending on the project name length (ugly?), or put `isort`as a separate hook in pre-commit (before `flake8`) so it will auto-correct before `flake8` runs. I tested the latter and it works.

**Comment by browniebroke** [comment]
I think we can indeed add isort to pre-commit config and autofix these issues. I think that pre-commit might fail the first time, when it does the fixes, though.

We should be aware that currently flake8-isort is imcompatible with isort 5+, hence we're still on isort 4 for now. I'm not sure if that would affect the sorting logic, we might be fine to use in a pre-commit hooks context.

**Comment by janfabry** [comment]
> I think that pre-commit might fail the first time, when it does the fixes, though.

Is this an issue? I have had pre-commit failures (fixes) on `trailing-whitespace`, `end-of-file-fixer` and `black` in my initial project generated by this cookie cutter, should I report them as separate issues?

> We should be aware that currently flake8-isort is imcompatible with isort 5+, hence we're still on isort 4 for now. I'm not sure if that would affect the sorting logic, we might be fine to use in a pre-commit hooks context.

If isort is used in pre-commit, does it still need to be in flake8?

**Comment by browniebroke** [comment]
> Is this an issue? I have had pre-commit failures (fixes) on trailing-whitespace, end-of-file-fixer and black in my initial project generated by this cookie cutter, should I report them as separate issues?

That's a small annoyance IMO, I don't think there is an easy way to fix `black` 100% of the time, but the others would be nice if not too complicated.

> If isort is used in pre-commit, does it still need to be in flake8?

Probably not, but since we have it in our requirements, people might use it in their CI via flake8:

https://github.com/pydanny/cookiecutter-django/blob/ed90a04bdb981e7e7c5c7419e2727a822f5efc01/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/local.txt#L29

I'm not sure if this is actually a problem, but I thought I mention that we're a bit in a transitional state currently with versions, just in case there isort 4 and 5 end up with different formatting. But yes, using isort as pre-commit hook means we no longer need flake8-isort in the flake8 pre-commit hook.
