### ISSUE TITLE
Use django-allauth custom signup forms

### ISSUE THREAD

**Issue by wldcordeiro** [pydanny/cookiecutter-django#272]
I'm trying to figure out how to use the custom signup forms with this cookiecutter, in the past when it had used django-configurations the config folder was within the project folder so the import path worked without issue, however now since it was moved django-allauth always seems to raise an error.

`django.core.exceptions.ImproperlyConfigured: Module "testproject.users.forms" does not define a "CustomSignupForm" class`

The relevant settings that seem to be affected with what I assume would be the values.
```py
ACCOUNT_SIGNUP_FORM_CLASS = '{{ repo_name}}.users.forms.CustomSignupForm'
AUTH_USER_MODEL = '{{ repo_name}}.users.User'
```

Any ideas?

**Comment by nortigo** [comment]
I would have been nice to show your solution.
