### ISSUE TITLE
Error in users/admin.py UserCreationForm.clean_username

### ISSUE THREAD

**Issue by wldcordeiro** [pydanny/cookiecutter-django#273]
https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/users/admin.py#L27

We try to raise a ValidationError with the error_messages['duplicate_username'] key, however in Django 1.8's release notes [Miscellaneous section](https://docs.djangoproject.com/en/1.8/releases/1.8/#miscellaneous) it looks like that key no longer exists.

**Comment by pydanny** [comment]
I think I fixed this at some point. Is this still a problem for you?

**Comment by wldcordeiro** [comment]
Nope, got it out of the way. :+1:

**Comment by pydanny** [comment]
:+1:
