### ISSUE TITLE
RTD Support

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [pydanny/cookiecutter-django#2733]
## Description

ReadTheDocs support

## Rationale

Hosting an open-source website with documentation 

Also somewhat of a bug report because you need a .readthedocs.yml (I think) file in order to pip install the local.txt packages.

## Use case(s) / visualization(s)

Developers for an open-source (or closed-source) website can easily read up on how the website functions.

**Comment by browniebroke** [comment]
More details on the `.readthedocs.yml` file:

https://docs.readthedocs.io/en/stable/config-file/v2.html

Agree that we need to at least configure the requirement file to use, and probably also the python version. Not sure if we can set environment variables to avoid similar issues as in #2674

**Comment by Andrew-Chen-Wang** [comment]
Hm so long as .envs/.local environment variables are set, we can use the USE_DOCKER environment variables to force Django-environ to read the env files.

**Comment by Andrew-Chen-Wang** [comment]
@browniebroke I'm currently testing the RTD support for a PR in a few. Primary concern is, in the conf.py file, I have:
```python
import os
import sys
import django


if os.getenv("READTHEDOCS", default=False) == "True":
	sys.path.insert(0, os.path.abspath(".."))
	os.environ["DJANGO_READ_DOT_ENV_FILE"] = "True"
	os.environ["CELERY_BROKER_URL"] = "redis://redis:6379"
	os.environ["USE_DOCKER"] = "no"
	master_doc = "_source/index"
else:
	sys.path.insert(0, os.path.abspath("/app"))
os.environ.setdefault("DATABASE_URL", "")

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.local")
django.setup()
```
The build is passing... but there's no documentation :P If you can spot a reason why, I'd love to hear it and try it out. The previous builds failed but adding the master_doc worked out. Unfortunately, that means none of the `.rst` files are actually documented...........

In the meantime... I'm curious, for celery support, in the `settings/base.py` files, can we set the default to `REDIS_URL`?
