### ISSUE TITLE
Compressor CACHE not publicly available on S3

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [pydanny/cookiecutter-django#2739]
## What happened?

Using Django compressor with AWS on S3 will cache outputs and send them to S3. Unfortunately, if you have CORS setup, the CACHE directory is still sending back 403 errors. If you go directly to the static directory of your S3, there's no problem.

## What should've happened instead?

The public new files should be publicly available. I believe this COULD help but I haven't tested it out yet: https://django-compressor.readthedocs.io/en/latest/remote-storages/

## Steps to reproduce

- Start a new cookiecutter-django project. 
- Enable django compressor
- If you'd like, enable compress in a different HTML file with a different static file.
- Go to your production website.

I could only fix it by making each file public.

**Comment by Andrew-Chen-Wang** [comment]
Ah I see. It's probably because COMPRESS_STORAGE is not equal to STATICFILES_STORAGE which is what the compressor documentation asks for https://django-compressor.readthedocs.io/en/latest/remote-storages/#using-staticfiles

**Comment by browniebroke** [comment]
I also noticed something similar. Pull request welcome!
