### ISSUE TITLE
Use Redis 6.0

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [pydanny/cookiecutter-django#2758]
https://github.com/pydanny/cookiecutter-django/blob/6f02a737bdf7b6bfaca94511587e30e7e6cfa344/%7B%7Bcookiecutter.project_slug%7D%7D/local.yml#L67

Redis 6.0 had some nice features added. I'm not sure about stability of those features, but for the most part, for web devs, Redis shouldn't have changed to much between major versions to be unstable. So should cookiecutter-django upgrade Redis?

**Comment by browniebroke** [comment]
I think the Redis-py library supports it, but it doesn't seem widely available on hosting platforms, in case people want to use it outside of Docker:

- Heroku offers Redis 4.0 and 5.0 at the moment: https://devcenter.heroku.com/articles/heroku-redis#version-support-and-legacy-infrastructure
- AWS Elasticache offers 2 up to 5.0.6 (as far as I can tell)
- Google memorystore seems to support only [up Redis 5.0](https://cloud.google.com/memorystore/docs/redis/release-notes)

**Comment by Andrew-Chen-Wang** [comment]
Ah ok, I'll ping once the hosting platforms have them upgraded. In the meantime, here's a task list:

 - [ ] GCP
 - [ ] AWS
 - [ ] Heroku

Out of curiosity, I wonder how many people still use Heroku. I've just been hearing it's been dying down quite a bit in the Django community with integration become a little more difficult over the years.

**Comment by vegerta** [comment]
Heroku support version 6 by default.
AWS Elasticache offers 6 already.
Google memorystore is just support up to version 5.0.7

**Comment by Andrew-Chen-Wang** [comment]
@browniebroke GCP finally supports 6.X
