### ISSUE TITLE
Buggy env/local/postgres file

### ISSUE THREAD

**Issue by julialoh** [pydanny/cookiecutter-django#2768]
## What happened?
I can't develop locally on docker due to an issue with my env file. The POSTGRES_USER and POSTGRES_PASSWORD are set to debug in my env, and I'm not sure how to fix this. 

## What should've happened instead?
I should have some characters in POSTGRES_USER and POSTGRES_PASSWORD that will let me develop locally on docker. 

## Steps to reproduce
Here is my env/local/postgres file: 
```
# PostgreSQL
# ------------------------------------------------------------------------------
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=cmw
POSTGRES_USER=debug
POSTGRES_PASSWORD=debug
```

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
[//]: # (* Logs)

**Comment by Afrowave** [comment]
I have answered this in #2767.
