### ISSUE TITLE
Documentation is inaccurate for running celery

### ISSUE THREAD

**Issue by tarkatronic** [pydanny/cookiecutter-django#279]
As noted in [the original pull request](https://github.com/pydanny/cookiecutter-django/pull/266#commitcomment-12102184), celery needs to be run with `celery -A proj.taskman` (now taskapp). However, the README states that you need to run `celery -A {{cookiecutter.repo_name}} worker -l info`. The command given in the README will just produce a very unhelpful, confusing error.

**Comment by kaidokert** [comment]
I was about to pullrequest this .. and then i stepped through celery loader line by line and got even more confused. By default its looking for {{appname}}.celery as a fallback,  as per celery.app.utils.find_app()

>                    try:
>                        return find_app(
>                            '{0}.celery'.format(app),
>                            symbol_by_name=symbol_by_name, imp=imp,

That code is also looking for found = sym.app and found = sym.celery as an attribute of loaded module.

So if i rename taskapp->celery then it somehow works with `celery -A {{appname}} worker`, but completely does not pick up the correct config and starts looking for amqp:// default broker..
Running with `celery -A proj.taskapp` works for now though.
Would be awesome to know what the best practice actually should be.
