### ISSUE TITLE
Django 3.1

### ISSUE THREAD

**Issue by huydbui** [pydanny/cookiecutter-django#2795]
I haven't seen anyone asked this question yet. So I'll go first. Is it ok now to upgrade to django 3.1.x?

Another newbie question: beside the tests that I wrote, is there any other test that I could run to make sure the django-cookiecutter on my computer works with django 3.1.1?

Thank you.

**Comment by huydbui** [comment]
I did some research. The very first one was djangorestframework only supports upto django 3.0. Case closed. Sorry about this.

**Comment by bandoche** [comment]
https://www.django-rest-framework.org
Seems latest DRF support Django 3.1. Any plan for go with Django 3.1?

**Comment by browniebroke** [comment]
It's not only about DRF, but all our django libraries. I'm going to start a table that'll keep up to date to gather where are our dependencies, taken from @emilepetrone idea in #2352:

**Base.txt**

| Name        | Version in Master | 3.1 Compatible Version  | OK |
| ------------- |:-------------:| :-----:|:--:|
| [pytz](https://github.com/stub42/pytz) | 2020.4  | n/a | ✅ |
| [python-slugify](https://github.com/un33k/python-slugify)| 4.0.1  | n/a | ✅ |
| [Pillow](https://github.com/python-pillow/Pillow) | 8.0.1 | n/a | ✅ |
| [rcssmin](https://github.com/ndparker/rcssmin) | 1.0.6 | n/a | ✅ |
| [argon2-cffi](https://github.com/hynek/argon2_cffi) | 20.1.0 | n/a | ✅ |
| [whitenoise](https://github.com/evansd/whitenoise) | 5.2.0 | | |
| [redis](https://github.com/andymccurdy/redis-py) | 3.5.3 | n/a | ✅ |
| [celery](https://github.com/celery/celery) | 4.4.6 | n/a | ✅ |
| [django-celery-beat](https://github.com/celery/django-celery-beat) | 2.1.0 | | |
| [flower](https://github.com/mher/flower) | 0.9.5 | n/a | ✅ |
| [uvcorn](https://github.com/encode/uvicorn) | 0.12.2 | n/a | ✅ |
| [django-environ](https://github.com/joke2k/django-environ) | 0.4.5 | | |
| [django-model-utils](https://github.com/jazzband/django-model-utils) | 4.0.0 | | |
| [django-allauth](https://github.com/pennersr/django-allauth) | 0.43.0 | | |
| [django-crispy-forms](https://github.com/django-crispy-forms/django-crispy-forms)| 1.9.2 | | |
| [django-compressor](https://github.com/django-compressor/django-compressor)| 2.4 | | |
| [django-redis](https://github.com/niwinz/django-redis)| 4.12.1 | | |
| [djangorestframework](https://github.com/encode/django-rest-framework) | 3.12.2 | | |
| [django-cors-headers](https://github.com/adamchainz/django-cors-headers) | 3.5.0 | | |

**local.txt**

| Name        | Version in Master | 3.0 Compatible Version  | OK |
| ------------- |:-------------:| :-----:|:--:|
| [Werkzeug](https://github.com/pallets/werkzeug)  | 1.0.1 | n/a | ✅ |
| [ipdb](https://github.com/gotcha/ipdb)  | 0.13.4 | n/a | ✅ |
| [psycopg2](https://github.com/psycopg/psycopg2)  | 2.8.6 | n/a | ✅ |
| [watchgod](https://github.com/samuelcolvin/watchgod)  | 0.6 | n/a | ✅ |
| [mypy](https://github.com/python/mypy)  | 0.790 | n/a | ✅ |
| [django-stubs](https://github.com/typeddjango/django-stubs) | 1.7.0 | | |
| [pytest](https://github.com/pytest-dev/pytest)  | 6.1.2 | n/a | ✅ |
| [pytest-sugar](https://github.com/Frozenball/pytest-sugar) | 0.9.4 | n/a | ✅ |
| [sphinx](https://github.com/sphinx-doc/sphinx)  | 3.3.1 | n/a | ✅ |
| [flake8](https://github.com/PyCQA/flake8) | 3.8.4 | n/a | ✅ |
| [coverage](https://github.com/nedbat/coveragepy) | 5.3 | n/a | ✅ |
| [black](https://github.com/ambv/black) | 20.8b1 | n/a | ✅ |
| [pylint-django](https://github.com/PyCQA/pylint-django) | 2.3.0 | | |
| [pylint-celery](https://github.com/PyCQA/pylint-celery) | 0.3 | n/a | ✅ |
| [pre-commit](https://github.com/pre-commit/pre-commit) | 2.8.2 | n/a | ✅ |
| [factory-boy](https://github.com/FactoryBoy/factory_boy) | 3.1.0 | | |
| [django-debug-toolbar](https://github.com/jazzband/django-debug-toolbar) | 3.1.1 | | |
| [django-extensions](https://github.com/django-extensions/django-extensions) | 3.0.9
| [django-coverage-plugin](https://github.com/nedbat/django_coverage_plugin) | 1.8.0 | | |
| [pytest-django](https://github.com/pytest-dev/pytest-django) | 4.1.0 | | |

**production.txt**

| Name        | Version in Master | 3.0 Compatible Version  | OK |
| ------------- |:-------------:| :-----:|:--:|
| [gunicorn](https://github.com/benoitc/gunicorn)  | 20.0.4 | n/a | ✅ |
| [Collectfast](https://github.com/antonagestam/collectfast)  | 2.2.0 | | |
| [sentry-sdk](https://github.com/getsentry/sentry-python) | 0.19.3 | n/a | ✅ |
| [hiredis](https://github.com/redis/hiredis-py) | 1.1.0 | | |
| [django-storages](https://github.com/jschneier/django-storages) | 1.10.1 | | |
| [django-anymail](https://github.com/anymail/django-anymail) | 8.1 | | |

**Comment by mmmcorpsvit** [comment]
@browniebroke

many packages already update to Django 3.1 support, can regenerate test matrix please
p.s. how you do this matrix ?)

**Comment by browniebroke** [comment]
> can regenerate test matrix please

I'm not generating it, I took the table from the Django 3.0 issue and updated versions manually. It's quite tedious but we don't need to do this too often. If someone has a script, it would be helpful...

> many packages already update to Django 3.1 support

Which ones are missing? I'm updating the message as I merge updates, but it's possible that I missed one.

**Comment by huydbui** [comment]
base.txt
======
**django-environ** looks like we don't even need to wait
[https://github.com/joke2k/django-environ/issues/239#issuecomment-718918143](url)

**django-allauth** they added Django 3.1 to Travis/tox which I don't know what this means (testing?)

**django-compressor** I don't see an issue reported regarding Django 3.1
Django Compressor is compatible with Django 1.11 and newer.


local.txt
======
**django-stubs** looks like this one is still a no no

**django_coverage_plugin** I don't see an issue reported regarding Django 3.1


production.txt
==========
**Collectfast** I don't see an issue reported regarding Django 3.1

**Comment by browniebroke** [comment]
Feel free to send a pull request 👍

**Comment by browniebroke** [comment]
Just found out that `django-stubs` was missing https://github.com/typeddjango/django-stubs/pull/558 and it's now merged. Next release should be good to go.

**Comment by huydbui** [comment]
> Feel free to send a pull request 👍

I'm not that advance of a github user just yet. I'll be there.

**Comment by areski** [comment]
PR opened here https://github.com/pydanny/cookiecutter-django/pull/3043
