### ISSUE TITLE
django.middleware.security.SecurityMiddleware vs django-secure

### ISSUE THREAD

**Issue by stepmr** [pydanny/cookiecutter-django#280]
Quick question, is there a reason the project still uses django-secure vs relying on 1.8's django.middleware.security.SecurityMiddleware?

**Comment by pydanny** [comment]
The reason is we didn't spot that one yet. Bonking my head over not changing that one yet. Want to submit a pull request?

**Comment by stepmr** [comment]
Sure, I'll do that this evening.  Should I also resolve the outstanding warnings from  check --deploy? 

		?: (security.W001) You do not have 'django.middleware.security.SecurityMiddleware' in your MIDDLEWARE_CLASSES so the SECURE_HSTS_SECONDS, SECURE_CONTENT_TYPE_NOSNIFF, SECURE_BROWSER_XSS_FILTER, and SECURE_SSL_REDIRECT settings will have no effect.
		?: (security.W009) Your SECRET_KEY has less than 50 characters or less than 5 unique characters. Please generate a long and random SECRET_KEY, otherwise many of Django's security-critical features will be vulnerable to attack.
		?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
		?: (security.W016) You have 'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE_CLASSES, but you have not set CSRF_COOKIE_SECURE to True. Using a secure-only CSRF cookie makes it more difficult for network traffic sniffers to steal the CSRF token.
		?: (security.W017) You have 'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE_CLASSES, but you have not set CSRF_COOKIE_HTTPONLY to True. Using an HttpOnly CSRF cookie makes it more difficult for cross-site scripting attacks to steal the CSRF token.
		?: (security.W019) You have 'django.middleware.clickjacking.XFrameOptionsMiddleware' in your MIDDLEWARE_CLASSES, but X_FRAME_OPTIONS is not set to 'DENY'. The default is 'SAMEORIGIN', but unless there is a good reason for your site to serve other parts of itself in a frame, you should change it to 'DENY'.

**Comment by theskumar** [comment]
The reason `django-secure` is still used because it has more settings than `django.middleware.security.SecurityMiddleware` and I was not sure whether removing those setting is worth or not. Consider `django.middleware.security.SecurityMiddleware` as subset of `django-secure`.

Also, the change was not very important and worth the wait for https://github.com/pydanny/cookiecutter-django/issues/208 at that time.

**Comment by stepmr** [comment]
Does a decision need to be made about which to use? (IE, should I still submit a pull request)  My understanding was that most of what django-secure does is now covered by "manage.py check --deploy" and "django.middleware.security.SecurityMiddleware"...

**Comment by theskumar** [comment]
@stepmr yeah. It was mainly the decision which one to use or keep both while I was upgrading this project to 1.8. Since "django.middleware.security.SecurityMiddleware" was a subset of `django-secure` i decided not to remove `django-secure`. I would definitely, reach out to security experts for final decision. 

The pro side of using `"django.middleware.security.SecurityMiddleware"` would be that it will make `--check --deploy` happy! 

django-secure was initially added by @pydanny. I leave the decision to him on what do to.

**Comment by stepmr** [comment]
Cool, thanks for the clarification @theskumar

**Comment by yunti** [comment]
Any update on a final view of this.  using "django.middleware.security.SecurityMiddleware" would be cleaner as mentioned- would remove a check --deploy issue, so that's preferred unless there are security shortcomings vs django secure.

**Comment by pckapps** [comment]
Any update on this yet? Can I go ahead and replace djangosecure.middleware.SecurityMiddleware with django.middleware.security.SecurityMiddleware in my production file? Can I leave the other settings as is? On the securesecure site it says: _this project is now unsupported and un-maintained_ so I'm guessing the correct way forward is removing it.

**Comment by theskumar** [comment]
Yes,  you can replace django-secure with the Django module.

**Comment by pckapps** [comment]
Thanks, that removes some of the warnings with check --deploy, but I'm still getting other warnings. Not sure if there is a reason for these settings? If not, I think it should be changed. These are the warnings I'm getting (shortened):

- (security.W012) SESSION_COOKIE_SECURE is not set to True.
- (security.W016) You have 'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE_CLASSES, but you have not set CSRF_COOKIE_SECURE to True. 
- (security.W017) You have 'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE_CLASSES, but you have not set CSRF_COOKIE_HTTPONLY to True. Using an HttpOnly CSRF cookie makes it more difficult for cross-site scripting attacks to steal the CSRF token.
- (security.W019) You have 'django.middleware.clickjacking.XFrameOptionsMiddleware' in your MIDDLEWARE_CLASSES, but X_FRAME_OPTIONS is not set to 'DENY'.

Should open a new issue that will address these warnings?

**Comment by pydanny** [comment]
Fixed in #579 by @xpostudio4
