### ISSUE TITLE
Add .pylintrc and .pep8

### ISSUE THREAD

**Issue by kaidokert** [pydanny/cookiecutter-django#282]
after creating the project, i tried to run `prospector -s veryhigh`  ( pip install prospector ) which runs pylint, pep8 and a bunch of other tools.
Had to add .pylintrc and .pep8 to match the project conventions, here is what i got in `.pep8`
> [pep8]
> max-line-length = 120
> exclude=*/migrations/*

and `.pylintrc`
> [MASTER]
> ignore=migrations
> [FORMAT]
> max-line-length=120
> [MESSAGES CONTROL]
> disable=missing-docstring,invalid-name
> [DESIGN]
> max-parents=13

I would probably add disable=no-init,too-few-public-methods too, to eliminate most of the false positives.

**Comment by kaidokert** [comment]
Actually i found prospector was not loading all the plugins properly, see https://github.com/landscapeio/prospector/pull/134

Once this is addressed, the following `.pylintrc` is sufficient, and results in a  clean check when run with `prospector -F -s veryhigh`

> [MASTER]
> load-plugins=pylint_common,pylint_django,pylint_celery
> [FORMAT]
> max-line-length=120
> [MESSAGES CONTROL]
> disable=missing-docstring,invalid-name,locally-disabled
> [DESIGN]
> max-parents=13

**Comment by pydanny** [comment]
I can do this unless you want to open a pull request and get credit?

**Comment by kaidokert** [comment]
I have a PR open here https://github.com/pydanny/cookiecutter-django/pull/283

**Comment by audreyr** [comment]
Merged. Thanks much @kaidokert.
