### ISSUE TITLE
[bug] Pre-commit hooks errors on first commit

### ISSUE THREAD

**Issue by bchip50** [pydanny/cookiecutter-django#2856]
## What happened?
git commit -m "Initial commit"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/userl/.cache/pre-commit/patch1601055885.
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing <app>/templates/base.html
Fixing utility/install_python_dependencies.sh
Fixing <app>/templates/account/password_reset_done.html

[WARNING] Stashed changes conflicted with hook auto-fixes... Rolling back fixes...
[INFO] Restored changes from /home/bill/.cache/pre-commit/patch1601055885.

## What should've happened instead?
Commit to git. This is blocking the commit process. Commit fails and log says file does not match after the trailing whitespace process changed the files.

## Additional details
git output:
Looking for git in: git
Using git 2.28.0 from git
> git rev-parse --git-dir
Open repository: /home/bill/projects/dfwtaichi
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :config/settings/base.py
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git show --textconv :dfwtaichi/templates/account/password_reset_done.html
> git ls-files --stage -- /home/bill/projects/dfwtaichi/dfwtaichi/templates/account/password_reset_done.html
> git cat-file -s c59534afcf4b25c6f0c294d8c3730cf15f09e1d5
> git show --textconv :dfwtaichi/templates/base.html
> git ls-files --stage -- /home/bill/projects/dfwtaichi/dfwtaichi/templates/base.html
> git cat-file -s f37f1396ad7ca48c81e111d0b696c0201306d6ec
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :dfwtaichi/templates/account/password_reset_done.html
> git ls-files --stage -- /home/bill/projects/dfwtaichi/dfwtaichi/templates/account/password_reset_done.html
> git cat-file -s c59534afcf4b25c6f0c294d8c3730cf15f09e1d5
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git show --textconv :utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git cat-file -s bdc181a51993964f5225d68b80e08eae70bf0d45
> git status -z -u
> git symbolic-ref --short HEAD
> git ls-files --stage -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git rev-parse master
> git cat-file -s bdc181a51993964f5225d68b80e08eae70bf0d45
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git show --textconv :utility/install_python_dependencies.sh
> git config --get commit.template
> git show --textconv :dfwtaichi/templates/base.html
> git ls-files --stage -- /home/bill/projects/dfwtaichi/dfwtaichi/templates/base.html
> git cat-file -s f37f1396ad7ca48c81e111d0b696c0201306d6ec
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :dfwtaichi/templates/account/password_reset_done.html
> git ls-files --stage -- /home/bill/projects/dfwtaichi/dfwtaichi/templates/account/password_reset_done.html
> git cat-file -s c59534afcf4b25c6f0c294d8c3730cf15f09e1d5
> git show --textconv :config/settings/base.py
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git symbolic-ref --short HEAD
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git show --textconv :config/settings/base.py
> git config --get commit.template
> git check-ignore -v -z --stdin
> git show --textconv HEAD:utility/install_python_dependencies.sh
> git show --textconv :utility/install_python_dependencies.sh
> git ls-tree -l HEAD -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
fatal: Not a valid object name HEAD
> git cat-file -s bdc181a51993964f5225d68b80e08eae70bf0d45
> git check-ignore -v -z --stdin
> git branch
> git rm --cached -r -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
error: the following file has staged content different from both the
file and the HEAD:
    utility/install_python_dependencies.sh
(use -f to force removal)
> git ls-tree -l HEAD -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
fatal: Not a valid object name HEAD
> git cat-file -s bdc181a51993964f5225d68b80e08eae70bf0d45
> git ls-tree -l HEAD -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
fatal: Not a valid object name HEAD
> git cat-file -s bdc181a51993964f5225d68b80e08eae70bf0d45
> git show --textconv :dfwtaichi/templates/account/password_reset_done.html
> git ls-files --stage -- /home/bill/projects/dfwtaichi/dfwtaichi/templates/account/password_reset_done.html
> git cat-file -s c59534afcf4b25c6f0c294d8c3730cf15f09e1d5
> git show --textconv :config/settings/base.py
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git show --textconv :dfwtaichi/templates/base.html
> git ls-files --stage -- /home/bill/projects/dfwtaichi/dfwtaichi/templates/base.html
> git cat-file -s f37f1396ad7ca48c81e111d0b696c0201306d6ec
> git show --textconv :config/settings/base.py
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git checkout -q -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git ls-tree -l HEAD -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git cat-file -s bdc181a51993964f5225d68b80e08eae70bf0d45
fatal: Not a valid object name HEAD
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git show --textconv HEAD:utility/install_python_dependencies.sh
> git show --textconv :utility/install_python_dependencies.sh
> git show --textconv :config/settings/base.py
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git status -z -u
> git checkout -q -- /home/bill/projects/dfwtaichi/dfwtaichi/templates/base.html
> git symbolic-ref --short HEAD
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git ls-tree -l HEAD -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git cat-file -s bdc181a51993964f5225d68b80e08eae70bf0d45
fatal: Not a valid object name HEAD
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git show --textconv HEAD:utility/install_python_dependencies.sh
> git show --textconv :utility/install_python_dependencies.sh
> git show --textconv :config/settings/base.py
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git status -z -u
> git checkout -q -- /home/bill/projects/dfwtaichi/dfwtaichi/templates/account/password_reset_done.html
> git symbolic-ref --short HEAD
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git ls-tree -l HEAD -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git cat-file -s bdc181a51993964f5225d68b80e08eae70bf0d45
fatal: Not a valid object name HEAD
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git show --textconv HEAD:utility/install_python_dependencies.sh
> git show --textconv :utility/install_python_dependencies.sh
> git show --textconv :config/settings/base.py
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git status -z -u
> git checkout -q -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git symbolic-ref --short HEAD
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git ls-tree -l HEAD -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git cat-file -s bdc181a51993964f5225d68b80e08eae70bf0d45
fatal: Not a valid object name HEAD
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git show --textconv HEAD:utility/install_python_dependencies.sh
> git show --textconv :utility/install_python_dependencies.sh
> git show --textconv :config/settings/base.py
> git check-ignore -v -z --stdin
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git status -z -u
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git symbolic-ref --short HEAD
> git rev-parse master
> git ls-tree -l HEAD -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git show --textconv :config/settings/base.py
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git cat-file -s bdc181a51993964f5225d68b80e08eae70bf0d45
fatal: Not a valid object name HEAD
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git show --textconv HEAD:utility/install_python_dependencies.sh
> git show --textconv :utility/install_python_dependencies.sh
> git show --textconv :config/settings/base.py
> git config --get commit.template
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git status -z -u
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git status -z -u
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git symbolic-ref --short HEAD
> git ls-tree -l HEAD -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/utility/install_python_dependencies.sh
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git show --textconv :config/settings/base.py
> git cat-file -s bdc181a51993964f5225d68b80e08eae70bf0d45
fatal: Not a valid object name HEAD
> git rev-parse master
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b
> git show --textconv HEAD:utility/install_python_dependencies.sh
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git show --textconv :utility/install_python_dependencies.sh
> git show --textconv :config/settings/base.py
> git config --get commit.template
> git ls-files --stage -- /home/bill/projects/dfwtaichi/config/settings/base.py
> git cat-file -s 350adc7e53761a9193d5790d6fc2514c3197c83b

* Host system configuration: 
    * Version of cookiecutter CLI (get it with `cookiecutter --version`):
    * OS:
    * Python version:
    * Docker versions (if using Docker):
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
    ``` 
    ```
<summary>
Logs:
<details>
<pre>
$ cookiecutter https://github.com/pydanny/cookiecutter-django
project_name [Project Name]: ...
</pre>
</details>
</summary>

**Comment by bchip50** [comment]
So I tried running pre-commit run --all-files several times until the run showed that all tests had passed.
Now git commit is failing with 
[ERROR] Your pre-commit configuration is unstaged
'git add .pre-commit-config.yaml' to fix this.

However, I don't see that file anywhere.

**Comment by bchip50** [comment]
So, I found the .yaml file and did a git add on it.
pre-commit run --all-files returns Passed for all tests
git commit still will not run due to end of file fixes to a bunch of the files, including License and README.rst
"Stashed changes conflicted with hook auto-fixes.... Rolling back fixes.

**Comment by bchip50** [comment]
Ok, I ran pre-commit uninstall
I then had to re-run git add .
git commit now works.
I can still use pre-commit run --all-files to fix up the files before the commit.
Still seems fairly awkward.

**Comment by Andrew-Chen-Wang** [comment]
Yes, it's in the name. Once your files change, you need to re add all the new lines of code that black or the other hooks may have changed by doing `git add .`. If the hook fails, then the commit isn't generated; do git add then recommit.

Although I'm curious: did you not pre-commit install at first? The only way you could have gotten that error in the first place was by installing pre-commit...

**Comment by bchip50** [comment]
I did pre-commit install at first. The problem was that it indicated that it was rolling back any changes when the commit failed, that un-doing the changes done by the pre-commit steps. I have to leave pre-commit uninstalled to get a commit to work.

**Comment by Andrew-Chen-Wang** [comment]
Interesting. I don't think I've ever had pre-commit unroll the changes. I wonder if it's because of the linter's versions. This is my pre-commit configuration:

```
exclude: 'docs|node_modules|.git|.tox|.idea'
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
        args: ['--settings-path=setup.cfg', '-rc']
```

The problem I had before was that isort 5 wasn't compatible with black (or I couldn't get the configurations right) so I just stayed on isort 4. Try using that version instead.

If pre-commit fails because it fixed something, re run `git add .` and then `git commit`. Hopefully that info helped!

**Comment by bchip50** [comment]
Ok, tried it. Now black and isort are disagreeing on one of the files. When isort changes the file, black changes is back.
    bc

**Comment by Andrew-Chen-Wang** [comment]
Hm that's just something you'll have to work out in setup.cfg. Can you describe what's actually being changed to and fro?

**Comment by patoski** [comment]
I had the same issue. Per the [isort docs](https://pycqa.github.io/isort/docs/configuration/black_compatibility/), adding the section below to `setup.cfg` will make isort compatible with black formatting.
```
[isort]
profile = black
multi_line_output = 3
```

**Comment by bchip50** [comment]
Tried again after adding the change to setup.cfg. Still no luck. 
Stashed changes conflicted with hook auto-fixes. Rolling back fixes.

**Comment by bchip50** [comment]
ok, I tried pre-commit run --all-files and after three passes, it got to isort and isort threw an exception saying that the configuration option multi_line = 3 is not supported. isort version 5.7.

**Comment by browniebroke** [comment]
What lines are conflicting? I have a PR in progress where it all works on a vanilla project:

https://github.com/pydanny/cookiecutter-django/pull/3077

**Comment by bchip50** [comment]
I removed the multi_line = 3 option and it started working.

**Comment by patoski** [comment]
I just tested on a fresh repo, and the `multi_line = 3` option worked when I ran `isort .`, `black .`, and finally `isort .` again to see if there were any conflicting formatting issues. There weren't any conflicts or errors.

**Comment by browniebroke** [comment]
Just made a change to tidy things up a bit, but the formatting might vary depending on the length your project name. A longer name would wrap lines later, while a shorter one would wrap them earlier. The first commit might fail if some things are reformatted, I think there is no way around that.
