### ISSUE TITLE
Switch to Python's libsass wrapper compiler?

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#286]
@theskumar, I've been using Ruby's compass compiler for SCSS compilation. Is it possible for us to go with Python's libsass package (wraps libsass). That, or can we go to a pure Node compiler?

Either way, being explicitly off that single Ruby gem (compass) makes start-up time for new systems much faster, especially for beginners coming to the project.

**Comment by stepmr** [comment]
I just completed this yesterday, I can submit a pull request...  However I ditched compass in favour of bourbon (which is now installed via bower)...

**Comment by stepmr** [comment]
I've also added postcss with autoprefixer & cssnano to the build task if there is interest in that too...

**Comment by stepmr** [comment]
Submitted #288 as a reference

**Comment by theskumar** [comment]
@pydanny  +1 for libsass with django-compressor. I've been using it in some projects deployed on Heroku. Works like charm. Checkout https://github.com/fossevents/fossevents.in/blob/master/config/settings/common.py#L174-L194 

Wanted to open a issue here, but probably just skipped my mind :dash: 

@stepmr I'll have a look at the PR.

**Comment by stepmr** [comment]
@pydanny @theskumar wow, sorry I totally missed the "python wrapper" part of this :)

**Comment by jayfk** [comment]
I've played around with `django-compressor` today using offline compression on docker and have seen a few issues.

I'm not entirely sure why, but somehow the manifest file generation gets messed up on the second run if a file changes. I can only guess, but this might has something to do with the container recreation/recycling introduced in the recent `docker-compose` release.

**Comment by pydanny** [comment]
Addressed in #568

**Comment by theskumar** [comment]
❤️
