### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by helo-wednesday** [pydanny/cookiecutter-django#2870]
## Additional details

* Host system configuration: 
    * Version of cookiecutter CLI (get it with `cookiecutter --version`):
    * OS:
    * Python version:
    * Docker versions (if using Docker):
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
    ``` 
    ```
<summary>
Logs:
<details>
<pre>
$ cookiecutter https://github.com/pydanny/cookiecutter-django
project_name [Project Name]: ...
</pre>
</details>
</summary>

**Comment by browniebroke** [comment]
I assume this was open by mistake, feel free to reopen if you give more infos.
