### ISSUE TITLE
Uvicorn standard dependencies

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [pydanny/cookiecutter-django#2894]
https://github.com/pydanny/cookiecutter-django/blob/6865ef39fd78fc1bf0ba7efb2b7d0b129d7a19e0/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/base.txt#L27-L28

Ref: #2881

It might be best to do `uvicorn[standard]` rather than just `uvicorn` so that people get the benefit from  "Cython-based" dependencies (where possible).

My only concern is that this change was pretty breaking, and I'm not sure if we should do an installation of `uvicorn[standard]` or simply list all dependencies (i.e.. just write `httptools==blah` and `uvloop==blah` etc.).

**Comment by Andrew-Chen-Wang** [comment]
Should be fixed if I can get mypy to stop being bad in #2921

**Comment by browniebroke** [comment]
I'm in favor of simplifying the list of dependencies to list on our end, and specify only `uvicorn[standard]`.

**Comment by Andrew-Chen-Wang** [comment]
Should be reflected in that pr now.

**Comment by browniebroke** [comment]
Forgot about this one, it was fixed in #2939
