### ISSUE TITLE
Deploying on Heroku. ModuleNotFoundError: No module named 'uvloop'

### ISSUE THREAD

**Issue by westerntrix** [pydanny/cookiecutter-django#2915]
Received a  ModuleNotFoundError: No module named uvloop when deploying my app to Heroku..

Not sure if this is a breaking change.

**My solution**
I did bypass this by rolling back --> [https://github.com/pydanny/cookiecutter-django/pull/2866](https://github.com/pydanny/cookiecutter-django/pull/2866)

In requirements/base.txt 

- Change this line --> `uvicorn==0.12.1  # https://github.com/encode/uvicorn`
- To this --> `uvicorn==0.11.8  # https://github.com/encode/uvicorn`
- Redeploy

Will this have any further implicatons for my project down the line?

**Comment by foarsitter** [comment]
As mentioned in #2894 by @Andrew-Chen-Wang uvicorn has changed the way the install dependencies: https://github.com/encode/uvicorn/commit/5fa99a11d6e07367cd559a4fc8694ce537796558#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7

**Comment by Andrew-Chen-Wang** [comment]
@westerntrix No, just install those missing dependencies. Refer to uvicorn's website for any additional performance booster packages that they mention. Once you get those installed, there shouldn't be any more problems.
