### ISSUE TITLE
Use GitHub Actions for this instead of Travis's new pricing

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [pydanny/cookiecutter-django#2928]
## Description

To test cookiecutter-django itself, we should use GitHub actions which is free and unlimited for open source projects.

## Rationale

Travis recently announced a new pricing model by using a credits system. https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing Basically, we're gonna run out of builds REALLY quickly (if not already based on my two latest PRs and the current master branch commit).

GitHub actions [is completely free and unlimited for open source projects](https://github.com/features/actions). I don't see actions becoming some billing system for open source projects in the next few years.

**Comment by browniebroke** [comment]
I started to notice the slow down myself, yes.

**Comment by browniebroke** [comment]
Agree that we should to Githgub Actions, I should have some time next week, but if someone wants to take a look before that, a pull request is welcome and would be much appreciated.

**Comment by Andrew-Chen-Wang** [comment]
I'm not very good with GitHub actions, but maybe @arnav13081994 can help out -- if you're not busy!

**Comment by arnav13081994** [comment]
Sure. I can hammer this out. But give me 1-2 weekends for this. I am not super comfortable with the cookiecutter library itself, which could be relevant in this.
