### ISSUE TITLE
Can't install package argon2-cffi

### ISSUE THREAD

**Issue by liquanhui01** [pydanny/cookiecutter-django#2953]
Today, I create a Django progam using cookiecutter. However, when I was installing those packages, I got this error: Couldn't install package: argon2-cffi. Why?

**Comment by luzfcb** [comment]
@liquanhui01 
Please help us to help you. 
Whenever asking a technical question, please provides enough context data regarding the doubt.  In this case: 
- What are the exact steps i must take to reproduce the error?
- What is the complete error traceback?  
- What operating system?  
- What exact settings did you choose when generating the project?
