### ISSUE TITLE
[allauth] Template context processor no longer supports {% if socialaccount.providers  %}

### ISSUE THREAD

**Issue by Daviey** [pydanny/cookiecutter-django#296]
As of django-allauth/0.21.0:
"Template context processors are no longer used. The context processor for allauth.account was already empty, and the context processor for allauth.socialaccount has been converted into the {% get_providers %} template tag." - http://django-allauth.readthedocs.org/en/latest/changelog.html

In templates/account/login.html there is:
      {% if socialaccount.providers  %}
      <p>{% blocktrans with....

This template tag is no longer valid and therefore, even if some providers are enabled this section of template will never be displayed.

I believe the solution to be:
{% load socialaccount %}
{% get_providers as socialaccount_providers %}
{% if socialaccount_providers  %}

.. but I haven't tested it.

Thanks

**Comment by angryjoe** [comment]
In setting up allauth with Facebook, I have tested this assertion and it is correct.

Switching from the former to the later allowed the Facebook login to display in the template.

**Comment by pydanny** [comment]
Anyone want to submit a pull request?

**Comment by angryjoe** [comment]
I'll take care of that today



—
Joe Stelmach

**Comment by luzfcb** [comment]
You could test with this branch
https://github.com/pydanny/cookiecutter-django/tree/issue-296

I start, but no have free open source time on this week
Em 01/09/2015 06:52, "Joe Stelmach" <notifications@github.com> escreveu:

> I'll take care of that today
>
>
>
> —
> Joe Stelmach
>
> On Sat, Aug 29, 2015 at 2:36 PM, Daniel Greenfeld

**Comment by angryjoe** [comment]
Looks good to me

**Comment by luzfcb** [comment]
@Daviey @angryjoe Thanks for reporting/test and sorry for the very long delay

fixed in https://github.com/pydanny/cookiecutter-django/commit/8380f143c64eca14992e44956e4cc520ba4a3859
