### ISSUE TITLE
Maildump setup docs appear to be broken

### ISSUE THREAD

**Issue by audreyr** [pydanny/cookiecutter-django#297]
I tried following the cookiecutter-django maildump instructions exactly as per the project-level [README](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/README.rst), but when I go to http://127.0.0.1:1080/, there is nothing. 

Is there anything missing from the docs?

Here is the output of running `grunt start-email-server` as per the cookiecutter-django docs:

```
$ grunt start-email-server
Running "bgShell:runMailDump" (bgShell) task
Done, without errors.
Execution Time (2015-08-08 19:25:44 UTC)
loading tasks         6ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 21%
bgShell:runMailDump  21ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 72%
Total 29ms
```

I've also verified that I have the necessary packages installed, both on the Python and the npm side.

Let me know if there's anything I can try locally. I'm happy to make the corrections if I figure out the problem.

**Comment by pydanny** [comment]
Unfortunately, Maildump only works with Python 2.7: https://github.com/ThiefMaster/maildump/issues/7. 

As useful as it is, without Python 3.4+ support we'll have to remove Maildump as an option.

**Comment by burhan** [comment]
I'm working on 3.4+ support for maildump; but its in the early stages.

**Comment by luzfcb** [comment]
@burhan another problem. Two maildump dependencies not is full python3 compatible

[gevent-websocket](https://bitbucket.org/Jeffrey/gevent-websocket/src)
[gevent-socketio](https://github.com/abourget/gevent-socketio) - https://github.com/abourget/gevent-socketio/pull/212

**Comment by burhan** [comment]
I'm working on a patch that uses [circuits](https://github.com/circuits/circuits) so hopefully it should take care of everything.

**Comment by musicformellons** [comment]
I'm running into same problem, i.e. maildump not working with python 3.4.3 ; Can you 'sign in' without maildump? Where do I find the signup emails then?

**Comment by keybits** [comment]
I've replaced Maildump with MailHog so that I have a Python 3 compatible solution to this, see #409

**Comment by luzfcb** [comment]
I will close this because https://github.com/pydanny/cookiecutter-django/pull/409 was merged
