### ISSUE TITLE
Reasoning Behind Mounting our Files Multiple Times in Django and Node

### ISSUE THREAD

**Issue by omarsumadi** [pydanny/cookiecutter-django#2983]
Hi all, I have a very simple question and I apologize in advance but was wondering if my rationale was wrong.

In our local compose (local.yml) we say:
```
    volumes:
      - .:/app:z
```
In addition, we if have node selected in the project setup, we do:
```
    volumes:
      - .:/app:z
```

Since volumes are accessible in other containers, I was wondering the rationale for remounting the same volume when it should already be avaliable?

Thanks,
Omar

**Comment by browniebroke** [comment]
We need to mount the `app` folder in django and node to have changes in files reflected inside the container image without restarting it, and have the hot reloading (for both Django and node) work.

You could generate a simple project, see how it they work currently by changing a CSS property or a line of Python in the Django code.

> Since volumes are accessible in other containers

I don't think it's the case, do you have a source explaining this behaviour? A quick search didn't bring up anything...

We could also verify in the simple project by removing one of the mount and see if it still works.

**Comment by omarsumadi** [comment]
@browniebroke Thank for the follow-up - this entire question's premise is based on my understanding that volumes are accessible in other containers.

I'm still kind of new - but it turns out you are correct that unless you define the same volume in different containers, they can't be accessed by the other container and visa versa, making it necessary to mount "twice".

Thanks,
Omar
