### ISSUE TITLE
Using psycopg2-binary only?

### ISSUE THREAD

**Issue by amotl** [pydanny/cookiecutter-django#2991]
Hi @pydanny and @browniebroke,

thanks a stack for conceiving and maintaining this excellent package.

After using it, we found that when using `psycopg2-binary` only, the runtime when running the tests on GHA can be improved. We have been able to verify this through https://github.com/tunfish/tunfish-ca/commit/9ea6f6b4dcb4efcbe8d4a8e4ce20a24ed354183c.

https://github.com/pydanny/cookiecutter-django/blob/86a388b7a4bf3196cb9f2c44667ee095a5d08106/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/local.txt#L5-L9

Now, I recognize that there already have been discussions around that within #594, #1503, #1530, #1569 and #2798. Still, I want to humbly ask whether there is still a reason to provide the possibility for installing the non-binary driver? Apparently, there are binary wheels available for most of the relevant operating systems on PyPI these days [1].

With kind regards,
Andreas.

[1] https://pypi.org/project/psycopg2-binary/#files

**Comment by amotl** [comment]
The improvement in terms of runtime is about 45 seconds.

![image](https://user-images.githubusercontent.com/453543/103448264-597bf280-4c97-11eb-8ad3-414d74f388d9.png)

**Comment by browniebroke** [comment]
This is a good question. The choice between the 2 has a dedicated section in their documentation:

https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary

They are quite clear:

> For production use you are advised to use the source distribution

Hence, we use the `binary` version only for local development when not using Docker. Yes CI can is quicker with the binary distribution but apparently it may bring some weird bugs.

I'm actually tempted to go the other way, and always install from source distribution, which is [providing wheels for Windows](https://pypi.org/project/psycopg2/#files), where it may be more difficult to install from source.

This way, we might move this dependency to `base.txt`, which would enable us to solve #2810.

**Comment by amotl** [comment]
Hi Bruno,

thanks a stack for your thorough answer and for pointing out [1] to me, I haven't been exactly aware of this detail. So, while `psycopg2-binary` sounded so much more convenient, the caveats are important to consider.

> I'm actually tempted to go the other way, and always install from source distribution, which is providing wheels for Windows, where it may be more difficult to install from source.

From learning about the potential problems with `psycopg2-binary` in production, I definitively second that.

With kind regards,
Andreas.

[1] https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary
