### ISSUE TITLE
Add django-cleanup package

### ISSUE THREAD

**Issue by mmmcorpsvit** [pydanny/cookiecutter-django#2997]
https://github.com/un1t/django-cleanup

`
The django-cleanup app automatically deletes files for FileField, ImageField and subclasses. When a FileField's value is changed and the model is saved, the old file is deleted. When a model that has a FileField is deleted, the file is also deleted. A file that is set as the FileField's default value will not be deleted.
`

**Comment by areski** [comment]
There is certainly a lot of value in django-cleanup, but I would recommend that we don't add more dependencies to this project if it can be avoided.

It feels that there is too many deps already and as people are bootstrapping their project with this, we might be adding extra weight that every would want to carry in their dependencies tree.
Additionally extra dependencies means more difficulties when you have to move to new version of Python or Django if the dep is not upgrading their project.
