### ISSUE TITLE
Implement a proper secret key

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#3]
Hopefully Cookiecutter will support this soon: https://github.com/audreyr/cookiecutter/issues/33

**Comment by DanEEStar** [comment]
Is there a way now to generate a SECRET_KEY automatically?

**Comment by pydanny** [comment]
@DanEEStar Not yet. However, I saw a great technique not too long ago relying on a command-line trick to do it. I just can't find it anymore. :sob:

**Comment by guialante** [comment]
I saw something in this gist: https://gist.github.com/mattseymour/9205591
