### ISSUE TITLE
Any opinions on replacing grunt livereload with LiveReload?

### ISSUE THREAD

**Issue by burhan** [pydanny/cookiecutter-django#300]
I think it would be nice if we could maximize Python usage (and minimize other language dependencies); so how about replacing the live reload grunt task with `LiveReload` ([RTD](http://livereload.readthedocs.org/en/latest/) / [github](https://github.com/lepture/python-livereload)) - its already Python 3 compatible and provides integration with django (and flask, and bottle and other wsgi compatible frameworks).

It also supports generic watch-and-execute tasks; so it can be used to potentially run any other housekeeping tasks.

If there is consensus, I can work on a PR.

**Comment by luzfcb** [comment]
I would like also to avoid other language dependencies.
I do not have a strong opinion about it.

At this point, I would like to await the outcome of that discussion: https://groups.google.com/d/msg/django-developers/voXNIDdDcpU/mnmr9NCPCgAJ

**Comment by pydanny** [comment]
We can use LiveReload now and switch to whatever Django provides later.

**Comment by jayfk** [comment]
There's an open PR for a LiveReload django management command here: https://github.com/lepture/python-livereload/pull/121

If the PR gets accepted we just need to add `livereload` to `INSTALLED_APPS` in `local.py` and a pinned version in `local.txt`.

**Comment by audreyr** [comment]
I'm quite hesitant to switch, as I think we'll lose a lot of flexibility on the front-end development side.

If we do this, would it be possible to use LiveReload to check for changes to .scss files and run the grunt sass task, as well as other grunt tasks?

**Comment by audreyr** [comment]
Ah, I see #286 which would probably solve my Sass issue. 

However, the ability to run Grunt tasks when files change still is a big issue. If this isn't possible, I'd prefer not to switch.

**Comment by jayfk** [comment]
There is an option to run [shell commands](https://github.com/lepture/python-livereload#shell) on file changes.
