### ISSUE TITLE
The AWS Access Key Id you provided does not exist in our records.

### ISSUE THREAD

**Issue by leopolicastro** [pydanny/cookiecutter-django#3017]
## What happened?
I apologize if this is a dumb question.
I am having an issue deploying my cookiecutter-django project.  Heroku is giving me this error
`botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the DeleteObject operation: The AWS Access Key Id you provided does not exist in our records.` when I run `./manage.py collectstatic` But I am using the same access key and secret as I used in another app that I just deployed 3 days ago which still works. I also tried creating a new access key but am still getting the same results.  Is it possible this is a cookiecutter-django issue or should I look elsewhere?
## Additional details

* Host system configuration: 
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): Cookiecutter 1.7.2
    * OS: OSX
    * Python version: Python 3.8.7
    * Docker versions (if using Docker):
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
    ``` 
	  {
	    "cookiecutter": {
	      "project_name": "CryptoSwap",
	      "project_slug": "cryptoswap",
	      "description": "Bitcoin ATMs",
	      "author_name": "...",
	      "domain_name": "...",
	      "email": "...",
	      "version": "0.1.0",
	      "open_source_license": "MIT",
	      "timezone": "UTC",
	      "windows": "n",
	      "use_pycharm": "n",
	      "use_docker": "n",
	      "postgresql_version": "12.3",
	      "js_task_runner": "Gulp",
	      "cloud_provider": "AWS",
	      "mail_service": "Mailgun",
	      "use_async": "n",
	      "use_drf": "y",
	      "custom_bootstrap_compilation": "n",
	      "use_compressor": "n",
	      "use_celery": "n",
	      "use_mailhog": "n",
	      "use_sentry": "n",
	      "use_whitenoise": "n",
	      "use_heroku": "y",
	      "ci_tool": "Github",
	      "keep_local_envs_in_vcs": "n",
	      "debug": "n",
	      "_template": "gh:pydanny/cookiecutter-django"
	    }
	  }
    ```
<summary>
Logs:
<details>
<pre>
$ cookiecutter https://github.com/pydanny/cookiecutter-django
project_name [Project Name]: ...
</pre>
</details>
</summary>

**Comment by Afrowave** [comment]
Hi @leopolicastro,

Did you set these environment variables described here? [Settings](https://cookiecutter-django.readthedocs.io/en/latest/settings.html)?

You can do this using the `env-example` file and then [deploy to Heroku](https://cookiecutter-django.readthedocs.io/en/latest/deployment-on-heroku.html)

**Comment by leopolicastro** [comment]
Hey @Afrowave thanks for writing back.  I did set all those env variables but it seems like they are not being read correctly and I'm not sure why. I even hardcoded them in the production.py file just to see if it was an issue of not reading the env variables but I still got the same result.

**Comment by leopolicastro** [comment]
Closing this, not sure what the issue is yet but it's not a cookiecutter issue.
