### ISSUE TITLE
Autoanswer file ?

### ISSUE THREAD

**Issue by mmmcorpsvit** [pydanny/cookiecutter-django#3025]
## Description

Are any way to do automatically answer at create project based at file?
This can be very useful for create GUI tools and for extend this project.

I think test create etc. problems can be resolve when from every PR will be create projects and test his how own.

PR -> create matrix projects (python versions and anothers questions) -> push to child project (need only for full testing) -> on sheduler -> PR results of test

for example: we need Django 3.1, ok, fine, try inc version -> this create new project on chield repo -> full testing (use Actions of GitHub) -> then PR results of test to main project

**Comment by browniebroke** [comment]
I'm not sure I understand the question, is it that you'd like to skip the prompted questions and use default values? If so, you have several options, none specific to this template, it's all coming from the cookiecutter CLI:

- Define [a user config](https://cookiecutter.readthedocs.io/en/1.7.2/advanced/user_config.html), it will change the default answers to each question, but you'll still be prompted.
- You can skip the prompts and accept the default answers using the `--no-input` option. [We make use of it](https://github.com/pydanny/cookiecutter-django/blob/8e031e760ff8b391fcc4dbb6a7d209aa36937666/tests/test_docker.sh#L17) to test this template.
- Each question can be answered by passing as argument to `cookiecutter` at the end, e.g. `use_docker=y`
- Cookiecutter also [has a "replay" feature](https://cookiecutter.readthedocs.io/en/1.7.2/advanced/replay.html), that can take inputs from a file. [A `--replay-file` option has been added](https://github.com/cookiecutter/cookiecutter/pull/906), but unfortunately it's unreleased.

Does it answer your question?

**Comment by mmmcorpsvit** [comment]
th, yes, this what i find)
