### ISSUE TITLE
Switch from boot2django to docker-machine

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#303]

**Comment by jayfk** [comment]
The official way to install docker on OS X and Windows is now with [docker-toolbox](https://www.docker.com/toolbox). Toolbox still uses the boot2docker image internally but the `boot2docker` command switched to `docker-machine`.

In perspective of cookiecutter, all we have to changes is to rename the `boot2docker ssh` command to `docker-machine ssh`.

I thought about adding more documentation for a docker setup for development anyway and fix this along the way.

**Comment by jayfk** [comment]
Fixed in https://github.com/pydanny/cookiecutter-django/commit/d8a7081d4cfb3af0fc689aba17b2cf9c8f741eda
