### ISSUE TITLE
Missing staticfiles manifest entry for 'img/logo/logo.png'

### ISSUE THREAD

**Issue by amakko** [pydanny/cookiecutter-django#3036]
Hi
after uploading to production and starting the docker I get this error.

Sentry issue : https://sentry.io/share/issue/4f37b6bd06e84ff2925f649f23e6dd43/

I'm guessing it's a WhiteNose problem but I don't currently know how to solve it. this is my first time with django cookiecutter

besides, my static files have not been uploaded to s3.
Does anyone know how to solve this?

my production.py

```
INSTALLED_APPS += ["storages"]
AWS_ACCESS_KEY_ID = env("DJANGO_AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("DJANGO_AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = env("DJANGO_AWS_STORAGE_BUCKET_NAME")
AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL = None
AWS_IS_GZIPPED = True
AWS_S3_ADDRESSING_STYLE = 'virtual'
_AWS_EXPIRY = 60 * 60 * 24 * 7
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": f"max-age={_AWS_EXPIRY}, s-maxage={_AWS_EXPIRY}, must-revalidate"
}
AWS_S3_REGION_NAME = env("DJANGO_AWS_S3_REGION_NAME", default=None)
AWS_S3_CUSTOM_DOMAIN = env("DJANGO_AWS_S3_CUSTOM_DOMAIN", default=None)
aws_s3_domain = AWS_S3_CUSTOM_DOMAIN or f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

DEFAULT_FILE_STORAGE = "pcfame.utils.storages.MediaRootS3Boto3Storage"
MEDIA_URL = f"https://{aws_s3_domain}/media/"
```

**Comment by Andrew-Chen-Wang** [comment]
I don't think Whitenoise with S3 is supported... Taking a look here: `STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"`. Take a look at the `production.py` settings that specify S3 storage for static files and try again.
