### ISSUE TITLE
ModuleNotFoundError: No module named 'argon2._ffi'

### ISSUE THREAD

**Issue by deiv23** [pydanny/cookiecutter-django#3048]
I have finished my project in local env and now I want to run in production mode.
I'm getting this error when trying to log in from browser:

```
django_1    | Internal Server Error: /accounts/login/
django_1    | Traceback (most recent call last):
django_1    |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/hashers.py", line 179, in _load_library
django_1    |     module = importlib.import_module(mod_path)
django_1    |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
django_1    |     return _bootstrap._gcd_import(name[level:], package, level)
django_1    |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
django_1    |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
django_1    |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
django_1    |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
django_1    |   File "<frozen importlib._bootstrap_external>", line678, in exec_module
django_1    |   File "<frozen importlib._bootstrap>", line 219, in_call_with_frames_removed
django_1    |   File "/usr/local/lib/python3.6/site-packages/argon2/__init__.py", line 5, in <module>
django_1    |     from . import exceptions, low_level
django_1    |   File "/usr/local/lib/python3.6/site-packages/argon2/low_level.py", line 17, in <module>
django_1    |     from ._ffi import ffi, lib
django_1    | ModuleNotFoundError: No module named 'argon2._ffi'
```
argon2_cffi is installed.

**Comment by deiv23** [comment]
Changing argon2-cffi==20.1.0 in base.txt (requirements) solves the issue.

**Comment by browniebroke** [comment]
> Changing argon2-cffi==20.1.0 in base.txt (requirements) solves the issue.

What do you mean? This is the value we already have, did you mean to explain to which value you changed it to?

https://github.com/pydanny/cookiecutter-django/blob/8473717a910d3e1bf82e463d21962c12bac07a60/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/base.txt#L11

If this is a problem with a fresh cookiecutter deploy, we should fix it.

**Comment by deiv23** [comment]
I'm sorry I'm not using latest version, I worked on it for the last months, it must be outdated.
In my base.txt I had a 19.x.x, I can't remember exactly, i think it was 19.1.0,  for argon2-cffi

Until today, I had not tested production mode. 
I have tweaked it a bit, some changes in config files, etc... maybe I just created that issue.

**Comment by browniebroke** [comment]
Ok no worries. Thanks for clarifying, I wanted to confirm there was no problems with the template itself.
