### ISSUE TITLE
Problem in Pycharm IDE

### ISSUE THREAD

**Issue by musicformellons** [pydanny/cookiecutter-django#305]
I am installing this cookiecutter. I do use pyenv-virtualenv for my virtualenvironment needs: 
https://github.com/yyuu/pyenv-virtualenv

Everything is working fine when I run from the terminal: 
(pyenvVE) ~/projectfolder$ python manage.py runserver

To work in Pycharm I created the project as I normally do and select the pyenv-virtualenv and add it to .pycharmrc etc. Everything seems fine, I can open the terminal in Pycharm and the virtualenv is already activated and I can do python manage.py runserver from there as well.

However when I do Ctrl+R to start the django-terminal I get the following error which I can not solve (I tried fiddling with the SECRET_KEY settings but to no avail): 
Failed to get real commands on module "cookie": python process died with code 1: Traceback (most recent call last): 
File "/opt/pycharm/helpers/pycharm/_jb_manage_tasks_provider.py", line 20, in <module> 
django.setup() 
File "/home/bom/.pyenv/versions/cookie/lib/python3.4/site-packages/django/__init__.py", line 17, in setup 
configure_logging(settings.LOGGING_CONFIG, settings.LOGGING) 
File "/home/bom/.pyenv/versions/cookie/lib/python3.4/site-packages/django/conf/__init__.py", line 48, in __getattr__ 
self._setup(name) 
File "/home/bom/.pyenv/versions/cookie/lib/python3.4/site-packages/django/conf/__init__.py", line 44, in _setup 
self._wrapped = Settings(settings_module) 
File "/home/bom/.pyenv/versions/cookie/lib/python3.4/site-packages/django/conf/__init__.py", line 113, in __init__ 
raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.") 
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by pydanny** [comment]
It appears that pycharm's Django Terminal is trying to access the `production.py` settings module, instead of `local.py`. For what it's worth, this has nothing to do with cookiecutter-django. I suspect it has something to do with `pyenv-virtualenv` combined with `pycharm`. 

You might want to file an issue at https://github.com/yyuu/pyenv-virtualenv/issues.

Another place to get a possible answer is with the PyCharm team at https://intellij-support.jetbrains.com/hc/en-us/requests/new

**Comment by musicformellons** [comment]
Thanks. Could you please explain what makes you think Django Terminal heads for production.py?

**Comment by musicformellons** [comment]
@pydanny I tried several things. Using python 2.7.9 instead of 3.4.3, same error. I also tried using 'normal virtualenvironment', to see if pyenv-virtualenv (shims etc.) is causing this, same error:
 Failed to get real commands on module "Gplace": python process died with code 1: Traceback (most recent call last):
  File "/opt/pycharm/helpers/pycharm/_jb_manage_tasks_provider.py", line 20, in <module>
    django.setup()
  File "/home/bom/goodplaceVENV/lib/python3.4/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/bom/goodplaceVENV/lib/python3.4/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/bom/goodplaceVENV/lib/python3.4/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/bom/goodplaceVENV/lib/python3.4/site-packages/django/conf/__init__.py", line 113, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

So now it can just be Pycharm I suppose.

**Comment by luzfcb** [comment]
@musicformellons on Pycharm, go to FILE->SETTINGS->Languages & Frameworks-> Django and set "Settings:" to `local.py`

![pycharm4](https://cloud.githubusercontent.com/assets/807599/9358489/d0bd4736-4662-11e5-8697-2f325b8fb831.png)


you can also add different environment variables for each of the run options

![pycharm2](https://cloud.githubusercontent.com/assets/807599/9358115/d337d3ca-4660-11e5-82f7-f53239138bab.png)

The PyCharm terminal does not automatically load the currently virtualenv, you have to manually load.

https://youtrack.jetbrains.com/issue/PY-10498

PyCharm is a very good tool, however, it adds more complexity to properly configure some things, and it can be incredibly frustrating.

having said that, some time ago I saw on the PyCharm blog, which was released a book about him.

http://blog.jetbrains.com/pycharm/2015/06/interview-with-pedro-kroger-author-of-modern-python-development-with-pycharm/

keep studying :smiley:

**Comment by musicformellons** [comment]
@luzfcb Thanks for your solid suggestions, but my settings are in line with your suggestions. Apart from the the Django Support "Settings:" field, since it does not do anything when you refer it to local.py or common.py, it only works/does something when you refer it to the settings folder itself (and then gives the error mentioned). I also gave the DJANGO_SECRET_KEY or SECRET_KEY to Pycharm separately as (in the two ways) you mention, but it does not change anything: still same error.

The various virtualenvs I use for various projects do start without a problem for me; I activate them (at pycharm startup) via the .pycharmrc file. Works fine.

**Comment by musicformellons** [comment]
This appeared to be indeed a bug in Pycharm. It was solved in the current latest version Pycharm 4.5.4

Works now.
