### ISSUE TITLE
Multi-stage build for dockerfile

### ISSUE THREAD

**Issue by dadokkio** [pydanny/cookiecutter-django#3050]
## Description

Update dockerfile for django with a multistaged one. [More info](https://docs.docker.com/develop/develop-images/multistage-build/)

## Rationale
Smaller image size and when changes happens (eg. update requirements) just part of the dockerfile is executed while others are cached.

**Comment by browniebroke** [comment]
There is already a pull requestfor it, I just haven't got around to review it: #2815

**Comment by dadokkio** [comment]
Sorry, I searched for docker and multistaged and didn't find it
