### ISSUE TITLE
Database Configuration for Docker unclear

### ISSUE THREAD

**Issue by asencis** [pydanny/cookiecutter-django#3058]
On initial setup of the project, I received the following error:

```
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the NAME value.
```

I though this was due to the `DATABASE_URL` environment variable not being set somewhere in the local development config. So...

...I set the following variable inside .envs/.local/.django to match up with what was in .postgres:

```
DATABASE_URL=postgres://superstrongusername:superstrongpassword@127.0.0.1:5432/asencis
```

Inside .env/.local/.postgres:

POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=asencis
POSTGRES_USER=superstrongusername
POSTGRES_PASSWORD=superstrongpassword

I then build and up the docker-compose container.

However, the django container responds with the following error:

```
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the NAME value.
```

I read in the https://cookiecutter-django.readthedocs.io/en/latest/settings.html that this variable is auto imported: `auto w/ Docker;`. Yet, I don't think it is?

## What should've happened instead?

Django container spins up and runs correctly. No configuration errors from the database.

## Additional details

Let me know if anything else is needed...

* Host system configuration: 
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): Cookiecutter 1.7.2 from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (Python 3.8)
    * OS:
    * Python version: Python 3.8.7
    * Docker versions (if using Docker): Docker version 20.10.2, build 2291f61
    * Docker Compose versions: docker-compose version 1.27.4, build 40524192
    * Django versions: django==3.0.12

**Comment by asencis** [comment]
This was due to a password which was extremely long (and containing certain characters not authorised for postgres).

**Comment by jucajuca** [comment]
very serious mess with the DB settings. I fixed it like so. 

```

POSTGRES_USER = env_vars["POSTGRES_USER"]
POSTGRES_PASSWORD = env_vars["POSTGRES_PASSWORD"]
POSTGRES_HOST = env_vars["POSTGRES_HOST"]
POSTGRES_PORT = env_vars["POSTGRES_PORT"]
POSTGRES_DB = env_vars["POSTGRES_DB"]
DATABASE_ENGINE=env_vars["DATABASE_ENGINE"]
# DATABASE_URL=f"postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
DATABASES = {"default": {
    'NAME': POSTGRES_DB,
    'USER': POSTGRES_USER,
    'PASSWORD': POSTGRES_PASSWORD,
    'HOST': POSTGRES_HOST,
    'PORT': POSTGRES_PORT,
    'ENGINE': DATABASE_ENGINE}
}
```

This will affect also docs, so you have to load also the postgres .env into the docs.

```
  docs:
    image: piveau_frontend_local_docs
    container_name: piveau_frontend_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres

```
