### ISSUE TITLE
Просит пароль, не понятно где его брать и как вводить...

### ISSUE THREAD

**Issue by AlexNilson-hub** [pydanny/cookiecutter-django#3067]
django.db.utils.OperationalError: fe_sendauth: no password supplied

**Comment by browniebroke** [comment]
I'm sorry, this is an English speaking project. If you need support, please ask in english and provide context about the problem:

- What were you trying to do
- What is your environment (local/prod, docker/bare metal etc...)
- What did you run before the error

We have an issue template, please follow it.
