### ISSUE TITLE
Use pywatchman and watchman support for reload

### ISSUE THREAD

**Issue by snmishra** [pydanny/cookiecutter-django#3092]
## Description

Django has built-in support for watchman file watcher for auto reloading.

## Rationale

Polling based watcher adds a decent amount of CPU and IO load for large projects. Enough to be noticeable. In my case CPU spikes went from 20% to close to 0.

[Watchman](https://facebook.github.io/watchman/) is a widely used file watcher and [Django runserver has built-in integration](https://docs.djangoproject.com/en/3.1/ref/django-admin/#runserver).

I am happy to make PR if there is interest. I added watchman installation step in `compose/local/django/Dockerfile` and pywatchman in `requirements/local.txt`.

**Comment by Andrew-Chen-Wang** [comment]
@snmishra Definitely sounds good to me! Just make sure watchman ignores the static and template directories since I think those don't reload Django's server (in runserver). Not sure if node_modules will actually interfere.

**Comment by snmishra** [comment]
Thanks @Andrew-Chen-Wang . Just submitted PR #3109
