### ISSUE TITLE
Grunt support for docker

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#310]
I played around with node/grunt on docker to see if we can get this supported in cookiecutter-django out of the box. 

The cleanest solution would be to install all node dependencies in a container (like with python in /site-packages/). As far as I understand it, this is not possible because grunt looks for node_modules in the current working directory (wtf). To make this worse, npm install needs to chown the directory which leads to permission problems if the UID of the mounted container volume is not matching with the host volume.

From [getting started with grunt](http://gruntjs.com/getting-started):

> Each time grunt is run, it looks for a locally installed Grunt using node's require() system. Because of this, you can run grunt from any subfolder in your project.
> 
> If a locally installed Grunt is found, the CLI loads the local installation of the Grunt library, applies the configuration from your Gruntfile, and executes any tasks you've requested for it to run. To really understand what is happening, read the code.```

**Comment by jayfk** [comment]
Would it be possible to to provide an alternative with [libsass-python](https://github.com/dahlia/libsass-python) or [python-scss](https://github.com/pistolero/python-scss) for SASS compiling?

**Comment by jayfk** [comment]
When I take a look at https://github.com/pydanny/cookiecutter-django/issues/300 and https://github.com/pydanny/cookiecutter-django/issues/286 we should be able to drop the whole node/grunt thing.

That would make the whole docker thing a lot easier. Any thoughts? Ping @noisy

**Comment by audreyr** [comment]
It's standard for a project's node dependencies to go into `node_modules` in the current working directory (repo root of generated project), which I believe is just how node works, not just grunt. See http://stackoverflow.com/questions/16738177/grunt-possible-to-relocate-node-modules-for-plugins

What about doing an `npm install` to create `node_modules/` in the current directory as per http://stackoverflow.com/questions/32096424/dockerizing-npm-bower-install-using-the-digitallyseamless-nodejs-bower-grunt-d -- would that work?

**Comment by jayfk** [comment]
The main problem here are filesystem permissions and the way how volumes are mounted.

It would work on the production configuration, because the `/app` directory is inside the container. In development, we are mounting the `/app` directory from the host filesystem so that we don't have to rebuild on every code change. The whole stack basically runs inside of docker, but it uses the code from our filesystem.

There are ways around that on linux machines that have a native docker installation by mapping the user id of the user inside the container to the user on the host filesystem. On OS X and Windows docker actually runs inside a virtual machine which uses `vboxfs` to mount the host filesystem to the virtual machine for docker to mount to the running container. This is where it gets really painful. Actually, it's already painful on linux but with a third layer involved on Win and OS X you have to use `nfs` or `cifs` mounts with special permissions to make it accessible.
