### ISSUE TITLE
Add database controls for Docker

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#312]
Assuming a user wants to:

* backup postgresql
* restore postgresql

We have no mechanisms or documentation in place.

**Comment by noisy** [comment]
So far I have used [bakthat](https://github.com/tsileo/bakthat), but lately I have some problems with it. Another option is to use [dockup](https://github.com/tutumcloud/dockup). Both has support for Amazon S3.

**Comment by jayfk** [comment]
we have that now :)
