### ISSUE TITLE
Is this usable with python 3.8?

### ISSUE THREAD

**Issue by razaltcom** [pydanny/cookiecutter-django#3123]
Can this be used with Python3.8? My host does not support Python 3.9 yet.

**Comment by luzfcb** [comment]
Yes, it will work perfectly in Python 3.8.  The migration to Python 3.9 was
made this week.  There is no technical reason for it not to work.

Check the recent changes on {{cookiecutter.project_slug}} namespace

This pr is part of the effort to upgrade to Python3.9

https://github.com/pydanny/cookiecutter-django/pull/3023/files

you will probably only need to change the version number of Python to 3.8
in some files

Em sáb, 10 de abr de 2021 08:38, razaltcom ***@***.***>
escreveu:

**Comment by razaltcom** [comment]
Yes, according to the pr it is mostly docs and settings. So it should work. Thanks.

One (small?) problem is though that the [deployment on Pythonanywhere documentation ](https://cookiecutter-django.readthedocs.io/en/latest/deployment-on-pythonanywhere.html) also uses Python3.9 now. But pythonanywhere is yet to support Python 3.9 (yes, they are my host).

**Comment by browniebroke** [comment]
Yes you can use `/usr/bin/python3.8` instead.
