### ISSUE TITLE
Consider removing Dokku section

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#313]
Unless someone willing to make contributions is actively using Dokku with cookiecutter-django, it is irresponsible of us to keep it as part of the project.

**Comment by pydanny** [comment]
@chrisfranklin, would you be interested in providing some continual support of Dokku on this project?

**Comment by hairychris** [comment]
Nah I think we can get rid of it. The docker-compose approach is easier to understand.

**Comment by pydanny** [comment]
@chrisfranklin - Thanks for the quick answer! :ok:
