### ISSUE TITLE
Drop PostgreSQL 9

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [pydanny/cookiecutter-django#3132]
## Description

Drop PostgreSQL 9.5 and 9.6, only supporting 10+

## Rationale

All of major version 9 will have support dropped within this year. I think it'd be better to just drop it altogether. https://www.postgresql.org/support/versioning/

**Comment by brunodantas** [comment]
Looking at a [quick search](https://github.com/pydanny/cookiecutter-django/search?q=postgres) within the repo, isn't it set to v12 already?

https://github.com/pydanny/cookiecutter-django/blob/13daafe9bb0f7f1cef04e2b0eb66f6ba12402340/.github/workflows/ci.yml#L67-L68

**Comment by browniebroke** [comment]
One can still opt to get v9 here:

https://github.com/pydanny/cookiecutter-django/blob/713220f305cb61df67711d6d1010f4b660a56fca/cookiecutter.json#L24-L25

Agree that we shouldn't really suggest new project to start on these versions.

**Comment by Andrew-Chen-Wang** [comment]
Would dropping PG 10 be a stretch?

**Comment by huydbui** [comment]
I have been using django-cookiecutter with PG13.2 for a while. Is there something bad that I haven't found out?

**Comment by Andrew-Chen-Wang** [comment]
Besides not being at the highest minor version, it's mostly just that we haven't updated the PostgreSQL versions in awhile. But for minor versions, we of course can just add it whenever we feel like it.
