### ISSUE TITLE
mailgun doesn't work with Python 3

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#314]

**Comment by pydanny** [comment]
See https://github.com/BradWhittington/django-mailgun/issues/16

**Comment by pydanny** [comment]
I'll fix it tonight.

**Comment by yunti** [comment]
Thanks

**Comment by pydanny** [comment]
@yunti I switched to django-mailgun-redux 0.3.0, which is a fork I released on PyPI. Can you test it and see if it works for you?

**Comment by yunti** [comment]
confirmed - that works fine.
Thanks.

**Comment by pydanny** [comment]
:)
