### ISSUE TITLE
Cryptography now requiring rust dependency

### ISSUE THREAD

**Issue by kanusek** [pydanny/cookiecutter-django#3142]
This isn't necessarily a bug report, this is for legacy cookie cutter projects. 

## What happened?
Building an older Cookiecutter project (Django 2.2) and during pip install an error was thrown that the rust dependency was not met. 

## What should've happened instead?
Project builds without pip errors.

## Additional details

If you are using docker-compose and experiencing pip errors relating to cryptography requiring rust, then you may want to try this:

In your `compose/production/django/Dockerfile` add this:
* I added this right before pip requirements are installed

```
ENV CRYPTOGRAPHY_DONT_BUILD_RUST 1
```

* Host system configuration: 
    * Version of cookiecutter CLI (get it with `cookiecutter --version`):  Unsure
    * OS: macOs 11.2.3
    * Python version: 3.8.5
    * Docker versions (if using Docker): 20.10.5

**Comment by Andrew-Chen-Wang** [comment]
Which package is cryptography from? Caused a huge stirrup for a lot of people, but I didn't know we had a package here that used cryptography.

**Comment by kanusek** [comment]
I believe it is the argon package

**Comment by Andrew-Chen-Wang** [comment]
That's interesting. None of our PRs are broken e.g. https://github.com/pydanny/cookiecutter-django/runs/2437697244#step:4:1081 we installed the latest cryptography and nothing broke? Is Rust somehow already installed with Raspbian Buster?

**Comment by kanusek** [comment]
I'll close. It was just something I ran into and wanted to share how I resolved it. Thanks ^^

**Comment by Andrew-Chen-Wang** [comment]
Thanks for the report and resolving method!
