### ISSUE TITLE
How disable HTTPS and allow direct access via IP

### ISSUE THREAD

**Issue by mmmcorpsvit** [pydanny/cookiecutter-django#3158]
My site host at closed enterprise network, use direct access via IP

1. how edit traefik etc for this feature?
2. are possible configure and build Docker and move to another server without rebuild (access only via VPN, Internet closed)?

**Comment by Andrew-Chen-Wang** [comment]
Idk how enterprise networks work. Is the IP a private IP address? If so, why bother with Traefik? Just run the deployment without it and set `ALLOWED_HOSTS` to be the static IP address of the server. Might also be helpful to install django-ipware or use nginx to make sure you only get a specific set of IP addresses.

**Comment by mjzac** [comment]
You can use `HostRegexp` in traefik to match ip addresses.

```
http:
  routers:
    web-router:
      rule: "HostRegexp(`static.ip.of.server`)"
```
