### ISSUE TITLE
Info on custom user model

### ISSUE THREAD

**Issue by musicformellons** [pydanny/cookiecutter-django#318]
As I am still a Django noob I spend quite some time trying to build something like django-authtools or django-custom-model into cookiecutter-django which was giving me some tough times. Only now it appears to me that cookiecutter-django is in fact already using a custom user model... Am I right? 

This closed issue brought me actually into that direction:
https://github.com/pydanny/cookiecutter-django/issues/232

So indeed this might be good to mention in the docs somewhere.

**Comment by pydanny** [comment]
@musicformellons See b5876ce60a74f380c216d9a11fedea2afbf7b067. Is that good enough? If it is, close the issue. Otherwise I'm open to suggestions or pull requests!

And... thanks for the observation.

**Comment by musicformellons** [comment]
Great, thanks.
