### ISSUE TITLE
Does this framework work with sqllite

### ISSUE THREAD

**Issue by sada-narayanappa** [pydanny/cookiecutter-django#3183]
Can I use this framework with sqllite - I do not want to use postgres that makes it heavy for my use

**Comment by luzfcb** [comment]
@sada-narayanappa, yes, bug, you need to manually remove the PostgreSQL configurations and replace them with the SQLite config.

**Comment by sada-narayanappa** [comment]
Thank you - do we have instructions to do that. I am new to Django thanks
