### ISSUE TITLE
Move isort config from .editorconfig to setup.cfg

### ISSUE THREAD

**Issue by mfosterw** [pydanny/cookiecutter-django#3201]
## Description

Move the config settings for isort from .editorconfig to setup.cfg (or some other file, like isort.cfg or pyproject.toml). It would go from this in .editorconfig
```
[*.py]
line_length = 88
known_first_party = {{cookiecutter.project_slug}},config
...
```
to this in setup.cfg
```
[*.py]
line_length = 88
known_first_party = {{cookiecutter.project_slug}},config
...
```

## Rationale

Atom's (and I suspect others') editorconfig package does not have a builtin integration with isort, so when I open the editorconfig file it reads the isort configuration as an error. Putting it under the [isort] block instead of under [*.py] also makes it clear what exactly is being configured by that block (it took me a while to figure out why those settings were there in the first place since this is my first time using isort). Per their [documentation](https://pycqa.github.io/isort/docs/configuration/config_files/), .editorconfig is also the last place isort looks for settings, so moving up that list is likely an improvement.

**Comment by LECbg** [comment]
I think this configuration should be moved to pyproject.toml, as it is quickly becoming a standard place to configure all Python tools. Furthermore, .editorconfig is the last configuration file isort looks for.

Besides, the option `recursive` present in .editorconfig must be removed as well, as it is no longer necessary in isort >= 5.0.0, [as the doc states](https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0.html).

**Comment by browniebroke** [comment]
I'm +1 to move this to `setup.cfg`, definitely makes more sense than `.editorconfig`.

> I think this configuration should be moved to pyproject.toml

I'm not so sure on this one, though. I really like `pyproject.toml`, but as long as not all tools support it (flake8 being an important one missing support IMO), I'd rather stick to one file, if possible. 

We use the default config for `black`, so we don't need a `pyproject.toml` at the moment, and all the other tools support `setup.cfg`.

**Comment by LECbg** [comment]
> I'd rather stick to one file, if possible.

More than reasonable.

> not all tools support it (flake8 being an important one missing support IMO)

I also agree on flake8, but just to mention it, I don't think we will get that `pyproject.toml` support anytime soon seeing [this](https://github.com/PyCQA/flake8/issues?q=is%3Aissue+pyproject)...
