### ISSUE TITLE
Fix for hiredis version 1.1.0 installation fail when running pip install.

### ISSUE THREAD

**Issue by dark-codr** [pydanny/cookiecutter-django#3216]
Trying to install requirements/local.txt files locally on linux encounters a failure to install error due to the varsion of hiredis being used (1.1.0).

However, upgrading to the March 2021 update of hiredis version 2.0.0 resolves this issue.

When running the `pipenv install -r requirements/local.txt` command, the version of hiredis fails to complete and stops the command from running. In my attempt to fix this before today i had to comment the hiredis out of install for local machines or include the `--install-option="--without-c-extensions"` on its installation for it to work.

* Host system configuration: 
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): 1.7.2
    * OS: Linux Ubuntu 20.04
    * Python version: 3.9
    * Docker versions (if using Docker): No Need for Docker
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
    ``` 
    1. Commenting the package out solves the issue
    2. including this to the package in **requirements/base.txt** `--install-option="--without-c-extensions"` solves this also
    ```
<summary>
Logs: 
<details>
<pre>
pipenv install -r requirements/local.txt --skip-lock --dev
Requirements file provided! Importing into Pipfile...
/usr/local/lib/python3.8/dist-packages/pipenv/vendor/urllib3/util/retry.py:531: ResourceWarning: unclosed <ssl.SSLSocket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.10', 51152), raddr=('151.101.192.223', 443)>
  raise six.reraise(type(error), error, _stacktrace)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.8/dist-packages/pipenv/vendor/requests/cookies.py:521: ResourceWarning: unclosed <ssl.SSLSocket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.10', 46876), raddr=('151.101.64.223', 443)>
  names_from_jar = [cookie.name for cookie in cookiejar]
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.8/dist-packages/pipenv/vendor/requests/cookies.py:521: ResourceWarning: unclosed <ssl.SSLSocket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.10', 46068), raddr=('151.101.0.223', 443)>
  names_from_jar = [cookie.name for cookie in cookiejar]
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Installing dependencies from Pipfile...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:00
An error occurred while installing hiredis==2.2.0! Will try again.
Installing initially failed dependencies...
[InstallError]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/cli/command.py", line 233, in install
[InstallError]:       retcode = do_install(
[InstallError]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 2052, in do_install
[InstallError]:       do_init(
[InstallError]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 1304, in do_init
[InstallError]:       do_install_dependencies(
[InstallError]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 899, in do_install_dependencies
[InstallError]:       batch_install(
[InstallError]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement hiredis==2.2.0 (from -r /tmp/pipenv-jbzaxmpk-requirements/pipenv-9raprkdh-requirement.txt (line 1)) (from versions: 0.0.1, 0.0.3, 0.0.4, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.2.0, 0.3.0, 0.3.1, 1.0.0, 1.0.1, 1.1.0, 2.0.0.dev0, 2.0.0)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for hiredis==2.2.0 (from -r /tmp/pipenv-jbzaxmpk-requirements/pipenv-9raprkdh-requirement.txt (line 1))
ERROR: Couldn't install package: hiredis
 Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 —
</pre>
</details>
</summary>

**Comment by Andrew-Chen-Wang** [comment]
Should be fixed in #3110 I think @browniebroke is just busy lately; lots of PRs aren't being reviewed or checked atm, at least not dependencies
