### ISSUE TITLE
Option for python version on deployment (and docker dev)

### ISSUE THREAD

**Issue by yunti** [pydanny/cookiecutter-django#322]
It would be useful to have an option for which version of python is used for the current project.  Although  all used dependencies are targeted to be compatible with both python 2 and python3. The default deployment option (or current docker dev setup) is for python 2. 
  
Eg for heroku deployment a runtime file needs to be added or the heroku build pack will default to python 2.7.  
Additionally the docker file default is python 2.7.

Implementation:
This would probably be best done as a cookie cutter option (generally python version for a project is decided at the outset).  
For heroku we could include a runtime.txt file with something like:

{% if cookiecutter.use_python3= 'y' -%}
python-3.4.3
{%- endif %}

Assuming that a blank runtime file for Heroku would default back to python 2? (or include an else if not)

The docker file could be altered similarly:
{% if cookiecutter.use_python3= 'y' -%}
FROM python:3.4
{% else %}
FROM python:2.7
{%- endif %}

**Comment by pydanny** [comment]
Would you like to submit a pull request?

**Comment by jayfk** [comment]
I was thinking of something like this, too. What about flipping the question so that it asks for `python2` and make `python3` the default?

**Comment by yunti** [comment]
That would be the preference for me too making python 3 the default - but it still feels like I'm in the minority there, but as this is more a bleeding edge template - perhaps that's not a bad idea here.

**Comment by jayfk** [comment]
I'm closing this because the changes have been merged. Thanks @yunti
