### ISSUE TITLE
uploaded image can view in url on short period, but cannot find in directory using docker

### ISSUE THREAD

**Issue by weiphang-gdex** [pydanny/cookiecutter-django#3248]
Hi all. I got issue when I upload media file to django cookie cutter. below is the scenario.
1.) After uploaded image, the image can view temporary in url path. The image will fail to find after some time using the path.
2.) the .jpg file cannot find at server directory at all.

[models.zip](https://github.com/pydanny/cookiecutter-django/files/6752476/models.zip)

**Comment by Andrew-Chen-Wang** [comment]
@weiphang-gdex I'm slightly scared to open that zip file. Mind uploading to a git repository?

**Comment by weiphang-gdex** [comment]
@Andrew-Chen-Wang Thank. The issue solved. I not mount to a volume so the image save to memory only.

**Comment by Andrew-Chen-Wang** [comment]
gotcha. Please close the issue!
