### ISSUE TITLE
Use dependabot instead of pyup

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [pydanny/cookiecutter-django#3256]
## Description

Use dependabot for this repository and potentially for generated projects

## Rationale

We used to not want to use dependabot because we couldn't ignore specific updates. Now we can and use wildcards: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore

**Comment by luzfcb** [comment]
@Andrew-Chen-Wang unless something has changed, dependabot is not able to correctly parse requirements files if they contain jinja2 tags as in our case.

**Comment by Andrew-Chen-Wang** [comment]
ah you're right!
