### ISSUE TITLE
What is meaning of APPS_DIR?

### ISSUE THREAD

**Issue by 1oglop1** [pydanny/cookiecutter-django#3271]
Hi, 
thank you for this project it helped me to jumpstart Django app I had to deploy!

I have a question about a variable called `APPS_DIR` in `settings/base.py` [link to code](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/base.py#L10)

I wonder what is the meaning of that variable?
Does it mean that I should put all my Django applications inside that directory?

eg.

```
project/
 config/
 apps/
    app1/
      templates/
      models.py
    app2/
      templates/
      models.py
```

or should each app live in a higher directory together with `config/`?

```
project/
 config/
  app1/
    templates/
    models.py
  app2/
    templates/
    models.py
```

I'd like to achieve a state that if I create the app and then decide to make it general (`pip install my_app...`) I can move it out.

Also directory `project/` already contains a lot of other things like `docker/` `manage.py` - so if `app1/` and `app2/` are in this directory it looks like that `docker/` is an application as well.

I'm asking based on this response from SO https://stackoverflow.com/a/23469321/3580789
because I'm curious what is the more common approach for managing large projects (imagine 10+ apps).

Thank you

**Comment by d57montes** [comment]
The `APPS_DIR` variable defined in `config/settings/base.py` is the internal project directory, so if your project is named `my_project`, this would be the `my_project/my_project/` directory.
You can put your Django apps in either the root directory or apps directory: both will work just fine; however, like you mentioned the root directory is already filled with a number of files and directories, so putting them in the apps directory will make the project's file structure cleaner.

**Comment by 1oglop1** [comment]
Thank you @d57montes !
