### ISSUE TITLE
Issues with /data partition for docker on OSX local development machine

### ISSUE THREAD

**Issue by scuerda** [pydanny/cookiecutter-django#328]
I'm new to docker and just getting my bearings. I followed the instructions for creating a /data partition as written. 

First run `docker-compose up`

Then run the `migrate` and `create superuser` commands.

All works great and I can access the project as expected. 

However, when  I ssh in and run the following

```
$ sudo su
$ echo 'ln -sfn /mnt/sda1/data /data' >> /var/lib/boot2docker/bootlocal.sh
```
and then stop/start the docker vm via `docker-machine restart [machine-name]`,
the next run of `docker-compose up` produces the following error:

```
Starting demodashboard_postgres_1...
Cannot start container 041875df9c7a08cc0730ab3467b0238b6ae6898b9459b7f71da3689caa87b745: mkdir /data: file exists
```

I'm running on the default VM created by the Docker Quickstart Terminal script.  Any thoughts?

**Comment by scuerda** [comment]
Following these instructions: http://stackoverflow.com/questions/27683477/boot2docker-bootlocal-sh-not-executing I was able to get persistent storage. 

Gist of approach is,

1) create a new Virtual Machine Disk via the VirtualBox GUI
2) ssh into docker-machine
3) using fdisk, format new drive and then partition via `mkfs.ext4 -L boot2docker-data /dev/sdb1` command
4) Add the line above to `bootlocal.sh`
5) Reboot and rejoice

**Comment by pydanny** [comment]
Are you saying there is a shortcoming in our documentation? If so, let us know what we can do to fix it.

**Comment by MathijsHoogland** [comment]
I am having the same error when I am trying to set this up in OSX, so I guess it is a shortcoming in the documentation?

**Comment by sakhmedbayev** [comment]
I have same problem running docker on windows machine. I am getting error 

 `mkdir /data: file exists`

**Comment by MathijsHoogland** [comment]
I eventually solved it by creating the directory in the machine:
`mkdir /mnt/sda1/data`

**Comment by obswork** [comment]
Can confirm @MathijsHoogland 's solution worked for me on OSX

**Comment by scuerda** [comment]
I haven't had any additional issues since moving from boot2docker to docker-toolbox. It seems that docker-toolbox made underlying changes.

**Comment by sakhmedbayev** [comment]
@scuerda, are you on windows or OSX?
