### ISSUE TITLE
Fresh project generation for Heroku + Celery creates a bad Procfile

### ISSUE THREAD

**Issue by LBWright** [pydanny/cookiecutter-django#3299]
## What happened?
Just a Procfile where the worker line ends on the web line
![image](https://user-images.githubusercontent.com/36030324/129987664-42b72649-1f48-48cd-b3af-23cb4bbfec3e.png)

## What should've happened instead?
`web`, `worker`, and `beat` are all on separate lines

## Additional details
Using Celery, Heroku, and NOT Async

* Host system configuration: 
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): 1.7.2
    * OS name and version: Pop_OS 20.04 (basically ubuntu)
    * Python version, run `python3 -V`: Python3.7
    * ...

**Comment by browniebroke** [comment]
I believe this was solved in #3300, closing. Thanks for reporting the issue.
