### ISSUE TITLE
How to install package in docker container

### ISSUE THREAD

**Issue by Manjit2003** [pydanny/cookiecutter-django#3328]
Hello guys, sorry for this n00b que.
I wanted to know how do I install  a pip package in a docker container?
I added the package to the requirements/base.txt and then ran `docker-compose -f local.yml up` which runs the container. But it is showing that package is not installed. To install manually, I also ran `docker-compose -f local.yml run --rm django pip install -r requirements/local.txt` still, no luck. Can someone please help me regarding this issue?

Regards,
Manjit Pardeshi

**Comment by foarsitter** [comment]
You don't. 

Add your package to requirements/base.txt (or local.txt if it for dev only, same for production.txt). Then rebuild your container with the build command or --build flag with the `up` command. 

By using the `run` command you create a new container. After installing the package this newly created container stops.

**Comment by browniebroke** [comment]
Great answer @foarsitter 👍🏻 nothing to add
