### ISSUE TITLE
Reorganize documentation

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#335]
cookiecutter-django is sophisticated enough to warrant its own top-level documentation served by Read the Docs, as well as generated project-level documentation. Unfortunately right now we have a mish-mash of organically grown documentation in the following areas:

* README.rst
* {{ cookiecutter.repo_name }}/README.rst (mix of features, config, and instructions)
* {{ cookiecutter.repo_name }}/docs/  (mix of features, config, and instructions)

What we are implementing now is the following:

* /docs/ (All configuration, setup, and testing documentation lives here)
* /README.rst (feature list, basic usage, links to other documentation levels)
* {{ cookiecutter.repo_name }}/README.rst (basic instructions, links to repo-level docs/)
* {{ cookiecutter.repo_name }}/docs/  (Content moved to this location from /docs/ in post_gen_hook)

This makes it possible for us to have one documentation location for all the technical options and use readthedocs.org trivially.

TASK: Modify the post_gen_hook to copy files from /docs/ to {{ cookiecutter.repo_name }}/docs/. This will require using the `.cookiecutters` directory to find the files in /docs/.  This may require using a `pre_gen_hook`.

**Comment by luzfcb** [comment]
@pydanny this fits somewhere: https://gist.github.com/luzfcb/59cf1d3cf24bf801dd70

**Comment by pydanny** [comment]
Yes! Absolutely! I think it should go into a Mac OS X specific section in https://github.com/pydanny/cookiecutter-django/blob/master/docs/developing-locally.rst :smile:

**Comment by jayfk** [comment]
You moved the part about the persistent directory on boot2docker into the deprecated section.

> If you are using boot2docker to develop on OS X or Windows, you need to create a /data partition inside your boot2docker vm to make all changes persistent. If you don't do that your /data directory will get wiped out on every reboot.

> To create a persistent folder, log into the boot2docker vm by running:

> `$ bootdocker ssh`
> And then:

> `$ sudo su`
> `$ echo 'ln -sfn /mnt/sda1/data /data' >> /var/lib/boot2docker/bootlocal.sh`

This might lead to the conclusion that this is no longer the case on recent docker releases. Unless I have missed something, this is still a problem using docker-toolbox (because it uses boot2docker under the hood).

> If you are using OS X or Windows, you need to create a /data partition inside the virtual machine that runs the docker deamon in order make all changes persistent. If you don't do that your /data directory will get wiped out on every reboot.

Here's what changes when using docker-toolbox:

> To create a persistent folder, log into the virtual machine by running:

> `$ docker-machine ssh dev1`
> And then:

> `$ sudo su`
> `$ echo 'ln -sfn /mnt/sda1/data /data' >> /var/lib/boot2docker/bootlocal.sh`

**Comment by pydanny** [comment]
@jayfk Would you mind taking this discussion briefly into gitter?

**Comment by pydanny** [comment]
Marking this closed as I think we've moved on to having most documentation in the top level docs.

**Comment by arruda** [comment]
:+1: :smiley:
