### ISSUE TITLE
Django Compressor and Cookiecutter-django

### ISSUE THREAD

**Issue by andresgz** [pydanny/cookiecutter-django#342]
Hi there,
I remember in previous versions "Django Compressor" used to com by default. Is there any reason to don't be included anymore?
I configured the Django-Compressor in a recent project, but It did not work  in production. It requires some additional configuration to make it work with Django Storages and S3.

Makes sense to include compressor again?

**Comment by jayfk** [comment]
Absolutely, take a look at #310, #300 and #286 which more or less all come down to `django-compressor`. 

Maybe [django-pipeline](https://django-pipeline.readthedocs.org/en/latest/) can be another option. Haven't tried it yet, but the features look promising.

**Comment by luzfcb** [comment]
I believe this is indirectly related to #301 .

**Comment by andresgz** [comment]
Thanks @jayfk for responding.
I have checked django-pipeline and seems that configuration could be more complex and could require more modifications to the Cookiecutter. In general terms, django-compressor would be more intuitive.

**Comment by andresgz** [comment]
I configured my last project including Django Compressor, and works great. If you think It's useful, I could make a pull request to include it by default. What do you think?

**Comment by pydanny** [comment]
@andresgz, if it's not too late, please open a pull request! 😄

**Comment by andresgz** [comment]
Sure @pydanny I will open a pull request

**Comment by pydanny** [comment]
@andresgz Are you working on this today? If not someone here at the [PyCon 2016 Cookiecutter sprints](https://github.com/audreyr/cookiecutter/wiki/PyCon-2016-Cookiecutter-Sprint) says they are willing to do it. Either way, you get credit for participating.

**Comment by andresgz** [comment]
Yes, I'm on that! 
I will post any question I find during the process.

**Comment by pydanny** [comment]
Thanks @andresgz!

**Comment by andresgz** [comment]
I have created the pull request #568 
Please let me know if you found any issue.

**Comment by pydanny** [comment]
Merged.
