### ISSUE TITLE
Document the reason for `contrib.sites`

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#345]
Since we're asked this a lot, it should be done both in the code modules and the formal documentation.

**Comment by mcastle** [comment]
Was just wondering why `contrib.sites` is pulled out from Django and placed directly in the project in cookiecutter. Can you please elaborate?

**Comment by pydanny** [comment]
@mcastle I feel stupid but I can't figure out the difference between this issue and your comment on it. Could you explain it to me?

**Comment by mcastle** [comment]
I should've been more clear... I was just wondering if there was an update to this issue and whether this is done to be able to give a default domain and name to a site? Or is this related to a best practice in your two scoops book?

**Comment by pydanny** [comment]
Covered now in http://cookiecutter-django.readthedocs.org/en/latest/faq.html#why-is-there-a-django-contrib-sites-directory-in-cookiecutter-django.

**Comment by pydanny** [comment]
For reference, this isn't a best practice per se for Django projects - but it is a nice helper for a tool like cookiecutter-django.

**Comment by mcastle** [comment]
Very helpful. Thanks!
