### ISSUE TITLE
Maildump Python 3 Support

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#348]
`gevent-websocket` is a requirement of `maildump`, but has no python 3 support, see https://github.com/abourget/gevent-socketio/issues/218

**Comment by pydanny** [comment]
I'm seriously considering removing mailgun. As much as it's a fascinating tool, the Python 3 issue is a big one.

**Comment by thornomad** [comment]
Is this why I get a `ConnectionRefusedError` when signing up a user when `maildump` is enabled on Python3?  Just re-did an install with `maildump=n` and the error disappeared.

**Comment by jayfk** [comment]
You'll have to start the maildump server along runserver to make it work

**Comment by thornomad** [comment]
@jayfk - oh! I'll try it again using the `grunt serve` command instead of `./manage.py runserver` -- am in the habit of using that.  Thanks for the tip.

**Comment by thornomad** [comment]
That didn't fix it for me (running `grunt serve` that is).  I am using Python3.  Is there something else I am missing?

    >> Internal Server Error: /accounts/signup/
    >> Traceback (most recent call last):
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    >>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
    >>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 30, in inner
    >>     return func(*args, **kwds)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    >>     return self.dispatch(request, *args, **kwargs)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/django/utils/decorators.py", line 34, in _wrapper
    >>     return bound_func(*args, **kwargs)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    >>     return view(request, *args, **kwargs)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/django/utils/decorators.py", line 30, in bound_func
    >>     return func.__get__(self, type(self))(*args2, **kwargs2)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/allauth/account/views.py", line 173, in dispatch
    >>     return super(SignupView, self).dispatch(request, *args, **kwargs)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/allauth/account/views.py", line 68, in dispatch
    >>     **kwargs)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/allauth/account/views.py", line 151, in dispatch
    >>     **kwargs)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    >>     return handler(request, *args, **kwargs)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/allauth/account/views.py", line 84, in post
    >>     response = self.form_valid(form)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/allauth/account/views.py", line 189, in form_valid
    >>     self.get_success_url())
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/allauth/account/utils.py", line 171, in complete_signup
    >>     signal_kwargs=signal_kwargs)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/allauth/account/utils.py", line 135, in perform_login
    >>     send_email_confirmation(request, user, signup=signup)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/allauth/account/utils.py", line 300, in send_email_confirmation
    >>     signup=signup)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/allauth/account/models.py", line 58, in send_confirmation
    >>     confirmation.send(request, signup=signup)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/allauth/account/models.py", line 122, in send
    >>     get_adapter().send_confirmation_mail(request, self, signup)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/allauth/account/adapter.py", line 355, in send_confirmation_mail
    >>     ctx)
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/allauth/account/adapter.py", line 102, in send_mail
    >>     msg.send()
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/django/core/mail/message.py", line 303, in send
    >>     return self.get_connection(fail_silently).send_messages([self])
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    >>     new_conn_created = self.open()
    >>   File "/Users/me/.virtualenvs/myproject/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 58, in open
    >>     self.connection = connection_class(self.host, self.port, **connection_params)
    >>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/smtplib.py", line 242, in __init__
    >>     (code, msg) = self.connect(host, port)
    >>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/smtplib.py", line 321, in connect
    >>     self.sock = self._get_socket(host, port, self.timeout)
    >>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/smtplib.py", line 292, in _get_socket
    >>     self.source_address)
    >>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/socket.py", line 512, in create_connection
    >>     raise err
    >>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/socket.py", line 503, in create_connection
    >>     sock.connect(sa)
    >> ConnectionRefusedError: [Errno 61] Connection refused

**Comment by pydanny** [comment]
@thornomad Are you trying to do this on Python 3? If so, then unless a number of things have been changed that I'm not aware of, Maildump won't work. Hence my comment near the top of this discussion about potentially removing it from cookiecutter-django.

**Comment by thornomad** [comment]
Yea!  That was my first comment in the thread ... just to confirm that this was the reason it wasn't working  for me (as I couldn't figure it out) ... I thought @jayfk was suggesting it was because I wasn't running the service (and I wasn't using `grunt serve`) ... so I tried that.  But yea: it's Python3.  And that would seem to be why!  Thanks.

**Comment by keybits** [comment]
I've replaced Maildump with MailHog so that I have a Python 3 compatible solution to this, see #409

**Comment by luzfcb** [comment]
I will close this because https://github.com/pydanny/cookiecutter-django/pull/409 was merged
Thanks @keybits
