### ISSUE TITLE
OperationalError at /accounts/(login|signup)/  fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by esacteksab** [pydanny/cookiecutter-django#35]
Running locally and simply clicking on 'Log In' results in this error: 

https://gist.github.com/esacteksab/af0a9f2866018c6ea5bc

FWIW, Signing up results in the same error/behavior on form submission. 

Perhaps this is too bleeding edge for myself, rather than a problem with the project. I won't be upset if you "Close. Won't Fix. PEBKAC".

**Comment by theskumar** [comment]
closing this now as appropriate instruction has been add to README. Thanks everyone for your love, report and support :)

This serves as a doc for anyone coming from google!

**Comment by mayur200** [comment]
Thanks this helped me to solve **_django.db.utils.OperationalError: fe_sendauth: no password supplied_** issue

**Comment by Alen899** [comment]
for newbies like me just uninstall whatever database you are using and install it again, and also check if you mispelled the 'PASSWORD' i cracked my head and found that i only have one 'S' :D
