### ISSUE TITLE
Opinions on (optional) New Relic support?

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#353]
I'm using New Relic in most of my projects. Even the free tier gives a lot of helpful metrics. Since the initial setup is a little bit annoying, it might be helpful to have it as an optional thing that does everything for us.

**Comment by luzfcb** [comment]
:+1: to me

**Comment by yunti** [comment]
Would love this too

**Comment by jayfk** [comment]
Merged in #362
