### ISSUE TITLE
Possible issue with mailgun setting names and Heroku

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#355]
In a side project the generated setting names don't work so well. However, I've made lots of modifications so what I did may not apply to stock cookiecutter-django. 

How I generated the potential issue:

1. Created new Django project from cookiecutter-django
2. Deployed to Heroku, including the mailgun app
3. Tried to generate emails via signup and error management.

**Comment by dogukantufekci** [comment]
I've been seeing the same 500 Error using stock settings with mailgun. 

Besides, I had never used the service before, therefore I've switched to default django emailing with my Gmail.

Any suggestion how to use mailgun with no issues?

**Comment by jayfk** [comment]
Possibly related to https://github.com/pydanny/cookiecutter-django/issues/323

**Comment by mgargenta** [comment]
Have we resolved setting up MailGun with Heroku? I'm still having issues - the app can't send any emails.

I did verify that DJANGO_MAILGUN_API_KEY and DJANGO_MAILGUN_API_KEY and correct - and have tested sending emails from https://mailgun.com/app/dashboard for that domain. However, those setting do not work on Heroku in production.

Setting `EMAIL_BACKEND = env('DJANGO_EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend') ` is a temporary solution for verifying email addresses but the root problem is still there. The app cannot send emails via MailGun.

Any thoughts?

**Comment by pydanny** [comment]
I believe the problem may have been with django-mailgun, which we no longer use (we use django-anymail now). If my assumption is incorrect, please reopen.

**Comment by griff-rees-RIT** [comment]
I may have reproduced this via an error very similar to the one posted at the start of #323 also under Heroku. I will create a new issue if appropriate, but though it best to double check this to avoid creating a duplicate. I think it emerged after changing `ACCOUNT_AUTHENTICATION_METHOD = 'username'` to `ACCOUNT_AUTHENTICATION_METHOD = 'email'`. I've tried to change that back but I get the socket similar to the start of #323. Is this likely to be related or should I open a new ticket?

**Comment by griff-rees-RIT** [comment]
If I run under heroku local (rather than `manage.py runserver` as I do in the previous comment) I get 
```
Forbidden (403)
CSRF verification failed. Request aborted.
```
on the browser and `Session data corrupted` errors on the heroku terminal.
