### ISSUE TITLE
Add django-admin-honey-pot

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#357]
Include @dmpayton's https://github.com/dmpayton/django-admin-honeypot as an option, perhaps even a mandatory thing.

**Comment by yunti** [comment]
Sounds good as an option - mandatory might be too much extra weight.
Slight aside what's the format for setting DJANGO_ADMIN_URL ? The comment # Custom Admin URL, use {% url 'admin:index' %} - isn't clear?

**Comment by pydanny** [comment]
Upon reflection, I think django-admin-honeypot is something, that while handy, shouldn't be an option. I think our current approach of obfuscating the admin is good enough. If people want more security, they can add django-admin-honey pot on their own.
