### ISSUE TITLE
Multiple Dockerfiles

### ISSUE THREAD

**Issue by audreyr** [pydanny/cookiecutter-django#360]
If I understand the current Docker setup, we install both the requirements from `requirements/local.txt` and the Heroku `requirements.txt` into the Docker container since we just have 1 Dockerfile.

Shouldn't we have separate Dockerfiles for local, test, prod? For example, I feel uncomfortable installing local debugging tool requirements into production.

**Comment by jayfk** [comment]
That's correct, these parts should really be separated. I'll continue to work on this PR.

**Comment by jayfk** [comment]
This should work as expected. There are two dockerfiles for dev and prod. On `dev`, `local.txt` is installed. On `prod`, `production.txt`.

**Comment by audreyr** [comment]
Merged #361.
