### ISSUE TITLE
Crispy Forms horizontal layout broken with Bootstrap 4

### ISSUE THREAD

**Issue by pusateri** [pydanny/cookiecutter-django#365]
Trying to use horizontal forms and Bootstrap 4 requires "row" class for horizontal forms in form-group div (see http://www.quackit.com/bootstrap/bootstrap_4/tutorial/bootstrap_forms.cfm) but crispy-forms doesn't know about Bootstrap 4 yet so the current combination breaks horizontal forms.

**Comment by jayfk** [comment]
Related: https://github.com/maraujop/django-crispy-forms/issues/524

**Comment by pydanny** [comment]
For the time being, we might want to do a template override to make Bootstrap 4 templates work. As I've got a project that just encountered this problem, I'll try and get this done today.

**Comment by audreyr** [comment]
Looks like this was fixed in upstream crispy-forms, but there isn't a new crispy-forms release out yet.

**Comment by jayfk** [comment]
This should be working now.
