### ISSUE TITLE
Remove raven.contrib.django.raven_compat.middleware.Sentry404CatchMiddleware?

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#367]
I don't think I like that in our setup Sentry is tracking 404 errors. Any comments?

**Comment by jayfk** [comment]
Just stumbled upon this and I think it's not that bad. These errors are marked in a different color in sentry and therefore not mistaken as *real errors*.

**Comment by jayfk** [comment]
I thought about that a second time and think this is REALLY BAD.

If someone writes a bot that requests random urls on your server your mailbox is going to be in real trouble.
