### ISSUE TITLE
Python 3.4 support not working

### ISSUE THREAD

**Issue by d3prof3t** [pydanny/cookiecutter-django#372]
Here is the link to the gist.
https://gist.github.com/d3prof3t/285fefcf2aa4ae68b444

**Comment by luzfcb** [comment]
please in your project folder, with the same virtualenv enabled, and run:

```
pip uninstall environ --yes
./install_python_dependencies.sh
```
after, if the problem stops happen, please close this issue.

ps.: my guess is that you used your IDE to install the python packages, and IDE mistakenly installed the wrong package.

**Comment by d3prof3t** [comment]
Thanks!
It did work.

ps.: I didn't use any IDE I was working on the terminal.

And just one more question, when wil be the use of install_os_dependencies.sh, and why did we run the install_python_dependencies.sh.
Just want to know about this.
