### ISSUE TITLE
Mailgun is being used no matter the choice

### ISSUE THREAD

**Issue by cdvv7788** [pydanny/cookiecutter-django#374]
On the project setup mailgun settings are added even if you select "no".

MAILGUN_ACCESS_KEY = env('DJANGO_MAILGUN_API_KEY')
MAILGUN_SERVER_NAME = env('DJANGO_MAILGUN_SERVER_NAME')

Should default to another backend and avoid adding that when "no" is selected.

**Comment by cdvv7788** [comment]
Oh, i think that the option in cookiecutter is about maildump, not mailgun.

**Comment by audreyr** [comment]
They are actually different tools:
* Maildump is for receiving fake emails locally during development: https://github.com/ThiefMaster/maildump
* Mailgun is for sending real emails in production: https://www.mailgun.com/

I also just added an explanation about the Maildump option here which may be helpful: http://cookiecutter-django.readthedocs.org/en/latest/project-generation-options.html

Hope this helps @cdvv7788.

**Comment by cdvv7788** [comment]
Yeah, thanks, just misread that before i posted the issue.
