### ISSUE TITLE
django-autoslug==1.9.2

### ISSUE THREAD

**Issue by cdvv7788** [pydanny/cookiecutter-django#383]
Could not find a version that satisfies the requirement django-autoslug==1.9.2 (from versions: 1.0.1.linux-x86_64, 1.0.2.linux-x86_64, 1.0.3.linux-x86_64, 1.3.3.linux-x86_64, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.6.1, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.9.0, 1.9.1, 1.9.3.dev0, 1.9.3)
No matching distribution found for django-autoslug==1.9.2

**Comment by aniketmaithani** [comment]
Well you can directly update it to 1.9.3 and this won't give you a problem. @theskumar your take?

**Comment by cdvv7788** [comment]
I can send a pull request, is an easy fix anyway.

**Comment by theskumar** [comment]
It seems they have removed release `django-autoslug==1.9.2`, updating to `django-autoslug==1.9.3` make sense. @cdvv7788 I can do that real quick. Thanks for reporting.

**Comment by theskumar** [comment]
Closed via https://github.com/pydanny/cookiecutter-django/commit/f01cddeae691ff015879a1a658c677a8288560f0. Thanks @aniketmaithani / @cdvv7788 :)
