### ISSUE TITLE
additions to the "usage" part

### ISSUE THREAD

**Issue by ccurvey** [pydanny/cookiecutter-django#39]
new user here, please tell me if this is noise.

after pip install requirements/local.txt....

1) Go create a database for your site to use
2) edit myapp/config/settings.py and change the database URL.  This should be 

```
postgres://username:password@hostname:port/databasename
```

3) python manage.py syncdb (to create basic tables)
4) python manage.py migrate (to install the migrations)
5) python manage.py runserver (to start the server)
6) hit localhost:8000 (to see if everything worked)

At this point, you WON'T have any admin user set up.  (Is this a 1.6 bug?  Usually the initial user is set up at the first syncdb.)

7) edit your settings again and find EMAIL_BACKEND.  change "smtp" to "console".  This is so you don't have to go through all the rigamarole of getting email connectivity working right now. 

8) use the "Sign up" link available from http://localhost:8000 to sign up for an account.  The verification email will appear in the window where you started the server.  (The console.)

9) Copy the confirmation link from the console and paste it into your browser.  Confirm your email, and you'll be taken to the login screen.

10) Now you can login to the site, but you still don't have an administrative user.  To make the user you just registered an admin user, fire up a postgres query tool (psql, pgadmin3, etc), and run:

```
update users_user
set is_superuser = true
, is_staff = true
where id = 1; # or use username or email to restrict your update.
```

Now you are ready to start creating your own app.  (I'll file another ticket with that doco when I get it working.)

**Comment by audreyr** [comment]
I'm working on cleaning this up and moving it into the README :ocean:
