### ISSUE TITLE
Debug-Toolbar doesn't show - does it really works after added css?

### ISSUE THREAD

**Issue by wildd** [pydanny/cookiecutter-django#393]
I see that this problem has already mentioned in https://github.com/pydanny/cookiecutter-django/issues/317
Has anything changed again in Bootstrap 4? I have the latest cookiecutter-django, I see in server console that DDT static css and js are served every time I refresh the page (also I see the DDT HTML if I view the page source code), I see in /css/project.css the lines that should fix the bug, but anyway I don't see the DDT.

**Comment by pydanny** [comment]
django-debug-toolbar works for me. Can you describe:

1. Which settings module you are using?
2. Which operating system?
3. Which browser?
4. Which version of Django?
5. Which version of Python?

**Comment by pydanny** [comment]
@wildd I'm closing this issue. If you are still unable to get django-debug-toolbar working, please reopen this issue.
