### ISSUE TITLE
How to set up databases for tests?

### ISSUE THREAD

**Issue by ipsod** [pydanny/cookiecutter-django#407]
I'm still new to Django, and I'm working through 2 Scoops.  I get this error when I try to run tests:

`Got an error creating the test database: permission denied to create database`

I found this line in `/tests/engine.py` : `postgres_user = hitchpostgres.PostgresUser("djtasks", "password")`, so I created the postgres user `djtasks` and gave it permission to create databases, but I still get the error.

**Comment by crdoconnor** [comment]
/tests/engine.py contains the code for hitch test which are an entirely separate and new way of testing django code. It won't be run unless you tell it to run (using hitch test .) so it won't be causing your current problem.

It looks like you're trying to run the standard django tests. The user that django will be trying to use that needs the create database permission will be in your django settings file. If it's not specified I think it tries to use the username that you are logged in as.
