### ISSUE TITLE
Wait for email in 'register-and-log-in.test' failing

### ISSUE THREAD

**Issue by mimischi** [pydanny/cookiecutter-django#418]
I've got a repository that is being build by Travis-CI. Everything is working, besides the standard test that is supplied by the current cookiecutter release. It fails, while it waits for the email after the signup. The email can be found inside the log, but hitch seems to not find it?

The log of my latest build can be found here: https://travis-ci.org/mimischi/django-clock/builds/92557925

The mail in the log starts here: https://travis-ci.org/mimischi/django-clock#L4547

Exception raised by hitch starts here: https://travis-ci.org/mimischi/django-clock#L4578

I don't really know why it is failing... or is it a problem with Travis-CI?

**Comment by crdoconnor** [comment]
It looks like you've got your DJANGO_EMAIL_BACKEND set to log emails to the console rather than actually sending an email to the mock SMTP server.

**Comment by crdoconnor** [comment]
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' in local.py should be 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

**Comment by mimischi** [comment]
Well it basically says that in your documentation, that one can set it to the console. See here: http://cookiecutter-django.readthedocs.org/en/latest/developing-locally.html (STRG+F for "Alternatively simply output").

Maybe put a warning that this will break hitchtest with Travis-CI? My basic confusion here was, that it sounds like Hitch is waiting for a line inside the log and Travis-CI is putting that mail in the log. Therefore I didn't make the connection with this setting!

**Comment by mimischi** [comment]
On a related note: I would gladly use MailHog with cookiecutter, but I can't seem to find configuration line where 'grunt serve' will launch it? Am I supposed to launch it by hand everytime I'm developing locally or am I missing something?

**Comment by crdoconnor** [comment]
>Maybe put a warning that this will break hitchtest with Travis-CI? My basic confusion here was, that it sounds like Hitch is waiting for a line inside the log and Travis-CI is putting that mail in the log. Therefore I didn't make the connection with this setting!

Yes, the docs should probably have a note that it expects hitch to send an actual email to localhost:1025. I'll create a pull request to try and clarify it.

**Comment by jayfk** [comment]
> Am I supposed to launch it by hand everytime I'm developing locally

Yes. Since MailHog is running its own server the process has to be launched by hand.

**Comment by mimischi** [comment]
Thanks! So it's working with the default SmtpBackend setting and MailHog. Just noticed though, that the file 'all.settings' sets an environment variabe for exactly this setting. Does it get ignored then?

**Comment by crdoconnor** [comment]
It should get picked up if your django settings are configured to read the DJANGO_EMAIL_BACKEND environment variable.

**Comment by mimischi** [comment]
This explains everything. Thank you very much!
