### ISSUE TITLE
'dict object' has no attribute 'celery_support'

### ISSUE THREAD

**Issue by otakucode** [pydanny/cookiecutter-django#436]
I wanted to check out cookiecutter-django, but I can't seem to get it working.  Even upon accepting all defaults, I receive two errors.  First is 'unable to create file tests/engine.py' (permissions on directory in which I am running cookiecutter are 777).  The second, and less likely to be some environmental weirdness on my end, is the 'dict object' has no attribute 'celery_support' error.  Is this a known problem?  Are there workarounds?  Answering y or n to the celery support prompt does not make a difference.

Also, I looked through the README and CONTRIBUTORS docs, hoping to find a pointer to an IRC channel or mailing list or similar where I could ask about this issue but didn't find anything.  Is there a channel where cookiecutter-django authors hang out or a mailing list?

**Comment by jayfk** [comment]
Where is the `celery_support` error popping up?

The celery channel is here: https://gitter.im/pydanny/cookiecutter-django

**Comment by otakucode** [comment]
Here is the log:

You've cloned /home/otakucode/.cookiecutters/cookiecutter-django before. Is
it okay to delete and re-clone it? [yes]:
Cloning into 'cookiecutter-django'...
remote: Counting objects: 4717, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 4717 (delta 4), reused 0 (delta 0), pack-reused 4704
Receiving objects: 100% (4717/4717), 834.68 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2962/2962), done.
Checking connectivity... done.
project_name [project_name]:
repo_name [project_name]:
author_name [Your Name]:
email [Your email]:
description [A short description of the project.]:
domain_name [example.com]:
version [0.1.0]:
timezone [UTC]:
now [2015/11/04]:
year [2015]:
use_whitenoise [y]:
use_celery [n]:
use_mailhog [n]:
use_sentry [n]:
use_newrelic [n]:
use_opbeat [n]:
windows [n]:
use_python2 [n]:
Unable to create file 'tests/engine.py'
Error message: 'dict object' has no attribute 'celery_support'
Context: {
    "cookiecutter": {
        "author_name": "Your Name",
        "description": "A short description of the project.",
        "domain_name": "example.com",
        "email": "Your email",
        "now": "2015/11/04",
        "project_name": "project_name",
        "repo_name": "project_name",
        "timezone": "UTC",
        "use_celery": "n",
        "use_mailhog": "n",
        "use_newrelic": "n",
        "use_opbeat": "n",
        "use_python2": "n",
        "use_sentry": "n",
        "use_whitenoise": "y",
        "version": "0.1.0",
        "windows": "n",
        "year": "2015"
    }
}

**Comment by luzfcb** [comment]
@otakucode thanks to report this issue.

you could try again and verify if https://github.com/pydanny/cookiecutter-django/commit/fc37d656615211ba0ce044c8cb3050181600d1cb solved the problem

**Comment by otakucode** [comment]
Works perfectly now for me.  Thanks for the fix!  cookiecutter-django looks tremendously useful!

**Comment by luzfcb** [comment]
fixed in https://github.com/pydanny/cookiecutter-django/commit/fc37d656615211ba0ce044c8cb3050181600d1cb :dancer: :dancer::dancer:
