### ISSUE TITLE
Gulp with ES6 

### ISSUE THREAD

**Issue by juliomrqz** [pydanny/cookiecutter-django#443]
Hello.

Have you considered replacing Grunt with Gulp using ES6?
Regards

**Comment by pydanny** [comment]
I've wondered if we can use Webpack.

**Comment by juliomrqz** [comment]
It can be used, but I think that that should be a choice of the end-user. I have been in projects where browserify and requirejs were good option, and where a bundler is not an option to considere. Besides, System.js is catching the attention in these days. 

I think that Grunt must be replaced with Gulp, we (and others people in the web) are happy with it due to it's a little bit faster and the tasks configuration is less verbose. I can make the transition and pull a request.

**Comment by jayfk** [comment]
Is gulp playing nice with docker? We currently don't support grunt on docker because it's a pain to set up in a development environment with docker-toolbox.

**Comment by juliomrqz** [comment]
We had issues running sass, but we solved it some months ago. I don't know if that issues persist, I'm creating a new fresh container and I'll let you know if there is any issue.

**Comment by juliomrqz** [comment]
It's still a pain in the neck to make sass works with Docker. I think Grunt is the best choice so far.
