### ISSUE TITLE
Bad Request when trying to deploy in docker

### ISSUE THREAD

**Issue by MathijsHoogland** [pydanny/cookiecutter-django#451]
Hi guys,

When trying to run the docker-compose app with deployment settings, I always get an 

Bad Request (400)

Error, when looking at the log from the terminal I see the following:

django_1   | [2015-12-18 17:08:04 +0000] [15] [INFO] Booting worker with pid: 15
django_1   | [2015-12-18 17:08:04 +0000] [16] [INFO] Booting worker with pid: 16
django_1   | [2015-12-18 17:08:04 +0000] [18] [INFO] Booting worker with pid: 18
django_1   | [2015-12-18 17:08:04 +0000] [20] [INFO] Booting worker with pid: 20
django_1   | ERROR 2015-12-18 18:08:07,072 base 18 140496642320128 Invalid HTTP_HOST header: '192.168.99.100'. You may need to add '192.168.99.100' to ALLOWED_HOSTS.
nginx_1    | 192.168.99.1 - - [18/Dec/2015:17:08:08 +0000] "GET /admin HTTP/1.1" 400 37 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36" "-"
django_1   | ERROR 2015-12-18 18:08:08,570 base 20 140496642320128 Invalid HTTP_HOST header: '192.168.99.100'. You may need to add '192.168.99.100' to ALLOWED_HOSTS.
nginx_1    | 192.168.99.1 - - [18/Dec/2015:17:08:09 +0000] "GET /favicon.ico HTTP/1.1" 400 37 "http://192.168.99.100/admin" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36" "-"
django_1   | ERROR 2015-12-18 18:08:09,842 base 18 140496642320128 Invalid HTTP_HOST header: '192.168.99.100'. You may need to add '192.168.99.100' to ALLOWED_HOSTS.
nginx_1    | 192.168.99.1 - - [18/Dec/2015:17:08:11 +0000] "GET /favicon.ico HTTP/1.1" 400 37 "http://192.168.99.100/admin" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36" "-"

This is interesting, because I set DJANGO_ALLOWED_HOSTS in my .env file to ['*'] I think I shouldn't be able to get the file DisallowedHost error, or could it be something else?

**Comment by luzfcb** [comment]
it is not necessary to use a list `['*']`in .env. simply use `*` because django-environ already do the [conversion to list](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/config/settings/production.py#L87) for you. 

try change DJANGO_ALLOWED_HOSTS in .env file to:

```
DJANGO_ALLOWED_HOSTS=*
```

if this resolves the problem, please close this issue.

A great Christmas, and good studies :christmas_tree: :fireworks:
