### ISSUE TITLE
Top menu bar styling broken - Bootstrap 4? Tether?

### ISSUE THREAD

**Issue by jvanbrug** [pydanny/cookiecutter-django#452]
I'm using extremely-vanilla cookiecutter-django, with very little custom styling. Some time in the last week or so the styling for the top menu bar broke - the "My Profile" and "Logout" buttons are pulled left to join the "Home" and "About" buttons (and less importantly, the margin between the top menu bar and the page content seems to have disappeared).

![cookiecutter-django-styling-broken](https://cloud.githubusercontent.com/assets/4754114/11971257/064b5098-a8ef-11e5-96fa-61768400c81a.PNG)

However, when I revert to old, previously-working versions of my site, the styling is still broken. I assume, therefore, that something in the Bootstrap 4 CDN has changed. I'm also getting a new Javascript error on every site page:

    Uncaught Error: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/)

I implemented the fix from the bottom of [this page](http://tutsme-webdesign.info/bootstrap-4-whats-new/):

> Tooltips and Popovers now rely on the 3rd party library Tether for positioning. You must include tether.min.js before bootstrap.js (see cdn link below) in order for popovers and tooltips to work!

    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/0.7.2/tether.min.js"></script>

Although this eliminates the Javascript error, the top menu bar styling is still broken.

It's likely I did something silly, but should Tether be added to the `base.html` template? Did something happen with Bootstrap 4?

**Comment by tylerjryan** [comment]
I have also seen the same thing on my site.

**Comment by mjsisley** [comment]
If you modify "pull-right" to "pull-{size that the pull is triggered}-right", for example "pull-md-right", in the base.html file, then it should display as it used to in the navbar.

**Comment by jvanbrug** [comment]
Thanks, @mjsisley! I found the bootstrap PR that removed `pull-right` - https://github.com/twbs/bootstrap/pull/18340

**Comment by jayfk** [comment]
Fixed in #455, thanks Jan!
