### ISSUE TITLE
Choose to task manager you would like to use for the frontend

### ISSUE THREAD

**Issue by QuienEsMera** [pydanny/cookiecutter-django#453]
Gulp o grunt

**Comment by oscarelotero** [comment]
It would be very useful. Gulp is simpler!

**Comment by luzfcb** [comment]
Please, see @jayfk comment: https://github.com/pydanny/cookiecutter-django/issues/443#issuecomment-164827537


That said, if any interested in adding Gulp to this project, please send a pull-request, that adds support for Gulp that works both Heroku and Docker.

**Comment by jayfk** [comment]
As @luzfcb said, pull requests are always welcome.
