### ISSUE TITLE
Add React setup and configuration

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#466]
I've hacked `React` into a project or two, but **I'll be the first to admit I'm not React setup expert**. I would love if someone who knows and understands the `React` ecosystem submitted a pull request that included the necessary elements in our front end tooling for building projects using React. 

Requirements:

1. This would have to be an option definined in `cookiecutter.json`. I would like to default to React and make Angular an option.
2. Documentation: How to on glue React into a template or two. I want more than just one, because per https://github.com/petehunt/react-howto, the first step to getting good is to replace individual components in React, not build a single-page app from scratch.

**Comment by burhan** [comment]
+1 to this.

**Comment by hanneshapke** [comment]
+1

**Comment by onelson** [comment]
Do you have feelings about the asset pipeline?
Normally, I don't tie into `staticfiles` and treat my client source as a separate project (driven by grunt, gulp, webpack, et al).

**Comment by pydanny** [comment]
`cookiecutter-django` currently uses Gulp for front end asset management, and it's bundled in. We're not adverse to switching to something else, but will want to keep the bundling in.

**Comment by onelson** [comment]
I'm wondering if it'll even be possible to come up with a de facto implementation for this out of the gate. My projects, again, split client and backend entirely. As such, I handle identity and authorization via something similar to JWT (provided by django rest framework). This also relies on CORS being configured.

DRF has competitors, so you'll potentially want flavors for different backends. Additionally, there's a spectrum of ways to go about SPAs with Django, my preference being one of the extremes.

That all said, it's easier to decide what you like or don't like about a thing when you have the thing already in front of you. Maybe we throw something against the wall and see what sticks?

**Comment by pydanny** [comment]
I would prefer to have a really strong DRF setup for React on `cookiecutter-django` than provide alternative options for REST support. Less complexity, and keeps this already **large** project from growing more.

**Comment by Copser** [comment]
+1

**Comment by dkdndes** [comment]
+1

**Comment by Eraldo** [comment]
+1

\o/,
Eraldo

-- 
/============================================
| *E r a l d o    E n e r g y*
| *Coach*: Personal Development
| *Dancer*: Salsa, Bachata, Kizomba & Co.
| *Developer*: Python/Django
| *Legend*: coLegend.org <http://www.colegend.org>
|--------------------------------------------
| M: +49 176 97 99 44 80 <004917697994480>
| E: eraldo@eraldo.org
| W: www.eraldo.org
| S: www.facebook.com/Eraldo
\============================================
Be Awesome! Love with an Open Heart! And Live a Legendary Life.. Today!

**Comment by pydanny** [comment]
Okay, we have enough +1's on this issue. Please only comment if you have something meaningful to add or a pull request.

**Comment by Copser** [comment]
I have tried to find some discus on the web about this subject. 
Found this GitHub project [Python-React](https://github.com/markfinger/python-react) I think it can be of help.
There is a [Reddit](https://www.reddit.com/r/django/comments/2vp8ys/django_reactjs_how/) discussion about Flask, Reactjs and Django Rest Framework.
Also there is this blog post for Django, DjangoREST and ReactJS, and this is by mine opinion the best tutorial about this subject that @pydanny start about React + Django, [link](http://gregblogs.com/how-django-reactjs-and-browserify/) to the blog, and there is some official [React](http://facebook.github.io/react/blog/2013/08/19/use-react-and-jsx-in-python-applications.html) blog post about using Python + ReactJS, but I don't know if this can be off help, because it is an old post.

**Comment by jayfk** [comment]
Is someone working on this? I'd be happy to assist if there are any problems.

**Comment by pydanny** [comment]
@jayfk Not directly on it, but this mayl simplify integration: https://github.com/pydanny/cookiecutter-django/issues/538

**Comment by pydanny** [comment]
Resolved in #610 by @goldhand.
