### ISSUE TITLE
Shouldn't the dockerfile take care of installing mailhog?

### ISSUE THREAD

**Issue by ChrisPappalardo** [pydanny/cookiecutter-django#475]
In the previous versions of cookiecutter-django, maildump was installed in the docker dev container via the requirements file.  I don't see anything that installs mailhog since the switch was made from maildump - or am I missing something?

**Comment by jayfk** [comment]
Yeah it should, but nobody has had the time to bring it to docker yet. There were/are some issues with grunt on docker that make this not so trivial.

**Comment by ChrisPappalardo** [comment]
There's a mailhog image on Docker Hub.  My solution for now is to implement mailhog as a separate docker container using the mailhog image, like so:  

[https://github.com/pydanny/cookiecutter-django/compare/master...ChrisPappalardo:1.8.7_mailhog_container
](url)

I personally find this to be a cleaner and more "dockerish" implementation for development anyway, than having grunt run mailhog inside the django container.  Maybe something to consider for master.

**Comment by jayfk** [comment]
We now have a mailhog container 👍
