### ISSUE TITLE
Make Grunt optional?

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#476]
If we want to bring grunt to docker (#310), it would be good to make grunt an option first.

Why?
The grunt task comes with a full `ruby` and a `node` stack that needs to be run alongside the Django container. If we made grunt an option, we could make sure that ruby/node only have to be installed when necessary.

Thoughts?

**Comment by yunti** [comment]
Yes this would be very good to have as an option. Tooling probably varies the most at the moment and it would be to have this optional to cover a wider range of options. Particularly as having ruby and node included that is a lot of unnecessary  requirements that wouldn't be needed by many.

**Comment by theskumar** [comment]
Yes. Grunt should be optional.

**Comment by burhan** [comment]
Why not replace it with a Python task runner?

**Comment by pydanny** [comment]
Yes, would love to have grunt made an option. Especially considering #538.

In fact, I think a list of tooling options would be ideal. Something like:
```
Choose a tooling option:

1. Webpack
2. Grunt
3. ???
4. No front end tooling

**Comment by audreyr** [comment]
This was done in #516.
