### ISSUE TITLE
TypeError: is_open_for_signup() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by oryx2** [pydanny/cookiecutter-django#479]
I use github social account,but get failed.Seems ``users.SocialAccountAdapter.is_open_for_signup``missing ``sociallogin``.
 django-allauth==0.24.1

**Comment by luzfcb** [comment]
it is probable that this issue is of [django-allauth](https://github.com/pennersr/django-allauth) and not a issue of cookiecutter-django.

please, put all the error traceback in gist.github.com and send the link

**Comment by oryx2** [comment]
Thanks your reply.Here is traceback [https://gist.github.com/oryx2/23ca85696e2993ac5a47](url) @luzfcb

**Comment by angryjoe** [comment]
That link 404s

**Comment by jayfk** [comment]
What happens when you delete this https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/users/adapter.py#L12-L14?

**Comment by oryx2** [comment]
I can not just delete it. The `settings/common.py` specify `SOCIALACCOUNT_ADAPTER = 'ifeed.users.adapter.SocialAccountAdapter'` .  I add a param to  `is_open_for_signup` and it works.

**Comment by jayfk** [comment]
Would you like to submit a pull request with your changes?

**Comment by oryx2** [comment]
OK,here is the pr [https://github.com/pydanny/cookiecutter-django/pull/486](https://github.com/pydanny/cookiecutter-django/pull/486)
