### ISSUE TITLE
Move to the python:alpine docker image

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#498]
The default image we are currently using is super fat (around 700MB) as it is based on a full fletched debian. There's a lot of movement to images based on alpine going on and the official image now supports that too.

Alpine uses musl libc instead of glibc, so that might be a problem for packages that have tight dependencies with libc.

**Comment by mzdaniel** [comment]
I'll take care of this

**Comment by mjsisley** [comment]
Per @jayfk: https://github.com/frol/docker-alpine-python3/issues/1 may prove helpful. Probably will need a Dockerfile that specifies dependency on glibc and the dependencies listed in the link (you may very well know this, but just in case)

**Comment by mzdaniel** [comment]
@mjsisley: There is currently an official alpine image. Either way, we should evaluate if it is worth to create our own 'custom' image with binary wheels included to significantly simplify our use case and in particular gh #594.

**Comment by mimischi** [comment]
Any news on this?

**Comment by webyneter** [comment]
Any news on the issue?
