### ISSUE TITLE
Multiple apps per host

### ISSUE THREAD

**Issue by mimischi** [pydanny/cookiecutter-django#500]
How is one supposed to use [nginx-proxy](https://github.com/jwilder/nginx-proxy), as described in the [documentary](http://cookiecutter-django.readthedocs.org/en/latest/deployment-with-docker.html#deployment-with-docker) to serve multiple apps from one host?

Deleting the "ports:" line from docker-compose.yml and running nginx-proxy does not work. Do I need to completely replace the nginx service with nginx-proxy? The documentation is lacking some smaller details to get started!

**Comment by pydanny** [comment]
Yes, the documentation there is lacking. That's why we prefix it with "TODO: Review and revise". We apologize, but as unpaid volunteers we just haven't gotten to finishing this section yet.

If you manage to figure this out on your own, please consider opening a pull request.

**Comment by microspace** [comment]
Please, help me how to serve multiple apps from one host. For me deleting "ports" also doesn't work.
I have nginx-proxy and couple of django projects running inside containters. I want to add cookiecutter-django based site to my host. I still get 503 error and no logs to look at

**Comment by microspace** [comment]
I promise to contribute to docs on this topic
