### ISSUE TITLE
Best way to upgrade a project started with an older version of cookiecutter-django?

### ISSUE THREAD

**Issue by keybits** [pydanny/cookiecutter-django#501]
I have a project that I started with an older version of cookiecutter-django.

What's the best way to upgrade it so it uses the latest version of everything specified here? (So I'd get updated requirements files and all other latest cookiecutter-django features.)

**Comment by nfletton** [comment]
I can't say this is the best way, but in the past when I've done this I've created a new  cookie cutter project with the same names as the existing project in a temporary directory. Then I've used a visual diff tool to merge in the differences that I'm interested in.

**Comment by keybits** [comment]
Thanks for the reply. That sounds like a reasonable approach in the absence of any automated solution. I guess a `pip list --outdated` and some manual updating, followed by running some tests will help too.
