### ISSUE TITLE
How deploy cookiecutter-django with dokku

### ISSUE THREAD

**Issue by drxos** [pydanny/cookiecutter-django#502]
I want to deploy cookiecutter-django with dokku. Do you have a doc about that job ?

**Comment by pydanny** [comment]
Apologies, but we've decided to just focus on Docker and Heroku support. The core maintainers just don't have the bandwidth to review pull requests for other deployment methods.

If you do figure it out and want to maintain your own fork, let us know and we'll link to it.

**Comment by drxos** [comment]
Ok. It's very clear.
