### ISSUE TITLE
FYI pytest-cookies requires update

### ISSUE THREAD

**Issue by hackebrot** [pydanny/cookiecutter-django#505]
Hi friends, 

with Cookiecutter v1.4.0 out, pytest-cookies requires a new release. JSON user configs are no longer supported by Cookiecutter, which pytest-cookies uses to create an isolated environment.

Cheers
Raphael :bow:

**Comment by hackebrot** [comment]
Latest **master** of pytest-cookies (a91d1044bf95eff4ca7e028ac5a279a7daaeec47) should be fine. I'll release to PyPI in the next couple of days.

**Comment by hackebrot** [comment]
A new release is now on PyPI https://pypi.python.org/pypi/pytest-cookies

**Comment by luzfcb** [comment]
@hackebrot good. Thank again. :-)
