### ISSUE TITLE
install_python_dependencies.sh refer to python3 even if use_python2 was set to y

### ISSUE THREAD

**Issue by noisy** [pydanny/cookiecutter-django#508]
source: https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/install_python_dependencies.sh#L24

**Comment by luzfcb** [comment]
@noisy thanks to report.

fixed in 3d3ec182d7f730b8cc4760b7d4cc70ed01a1a36a
