### ISSUE TITLE
Generating secret keys w/o sysrandom will always fail

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#509]
We are using Django's `get_random_string` implementation in `post_gen_project.py`.

If sysrandom can't be imported the function will always fail since the if clause relies on the `settings.SECRET_KEY` to be set, see https://github.com/pydanny/cookiecutter-django/blob/master/hooks/post_gen_project.py#L42-L55

**Comment by theskumar** [comment]
The secret key is set only for the local.py, and it must be set by user while running the project using production settings. It makes sense to simplify the secret key generation.

**Comment by pydanny** [comment]
Since we aren't using Django's `get_random_string` anymore, I'm closing this issue.
