### ISSUE TITLE
Cannot install cookiecutter-django with docker on Windows 10

### ISSUE THREAD

**Issue by sakhmedbayev** [pydanny/cookiecutter-django#510]
I tried to follow [this post](https://realpython.com/blog/python/development-and-deployment-of-cookiecutter-django-via-docker/) to install cookiecutter-django with docker on windows. 

"docker-compose ps" shows that two containers are running as follow:

test_django_1  Exit 2 (State)
test_postgres_1 Up (State)

As you can see the state for first container is "Exit 2". I consulted with other folks, they said that it can be an error in Django application. If I tried to run "docker start test_django_1" nothing happens, state for the first container not changing.

"docker logs test_django_1" reveals following info:

`python: can't open file '/app/manage.py': [Errno 2] No such file or directory`

my dev.yml content as follow:

version: '2'
services:
  postgres:
    build: ./compose/postgres
    volumes:
      # If you are using boot2docker, postgres data has to live in the VM for now until #581 is fixed
      # for more info see here: https://github.com/boot2docker/boot2docker/issues/581
      - /data/dev/test/postgres:/var/lib/postgresql/data
      - /data/dev/test/postgres-backups:/backups
    environment:
      - POSTGRES_USER=test

  django:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: python /app/manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=test
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres

I am newbie to docker. Can anyone help me to fix this problem?

**Comment by jayfk** [comment]
Your project directory is probably not visible to the virtual machine running your docker deamon, see #414
