### ISSUE TITLE
bootstrap .form-horizontal incompatible with v4 of bootstrap style sheet

### ISSUE THREAD

**Issue by clairedemars1** [pydanny/cookiecutter-django#514]
This relies on the development version of bootstrap's style sheet, v4-dev.
Evidence:  if I switch to version 3.3.6, the header in the base template messes up. 

However, v4-dev has a bug that makes it not work with bootstrap's form-horizontal class.
Evidence: I used form-horizontal in my code, and it works with version 3.3.6 of the style sheet, but not v4-dev.

There's probably nothing we can do now, except wait for the new release of v4, but I wanted to put this issue here as feedback that might make an impact on future decisions to use development versions of things (style sheets, etc).
Thanks

**Comment by pydanny** [comment]
Cookiecutter Django is partly about using bleeding edge tools. How Bootstrap works between versions is out of scope for Cookiecutter. Hence why I'm closing this issue.

However, if someone wants to create a Bootstrap 3 theme cookiecutter template that works as a direct replacement for Cookiecutter Django, I'm willing to link to it.
