### ISSUE TITLE
Using Django-Debug-Toolbar and ipdb in Docker (and with bootstrap 4)

### ISSUE THREAD

**Issue by mjsisley** [pydanny/cookiecutter-django#515]
I had issues running django-debug-toolbar and ipdb in docker out of the box.

In order to use django-debug-toolbar in Docker I needed to add code at https://gist.github.com/douglasmiranda/9de51aaba14543851ca3 to local.py. I did not have success adding to INTERNAL_IPS. There may be a better solution.

In order to have the django-debug-toobar display with bootstrap 4, I need to override the hidden property in css per django-debug-toolbar/django-debug-toolbar#798. 

In order to run ipdb with Docker, I needed to run `docker-compose run --service-ports django` to expose the necessary ports as per https://www.calazan.com/using-ipdb-docker-compose-interactive-debugging/. I could not get it to work with docker-compose up. (Maybe worth adding to the documentation, or maybe there is a better solution). 

Are these changes/ additions to documentation worth making?

**Comment by jayfk** [comment]
If you are running docker with docker-toolbox on a Mac/Windows machine, you need to set the virtual box bridge IP. By default that's `192.168.99.1`.

**Comment by trungdong** [comment]
Thanks, @jayfk. I added the IP to `INTERNAL_IPS` and the debug toolbar now shows up.
I didn't need to fix the CSS (I am using django-debug-toolbar 1.4).
