### ISSUE TITLE
Error when trying to create a Remote Python Interpreter in PyCharm 2016.1

### ISSUE THREAD

**Issue by phiberjenz** [pydanny/cookiecutter-django#523]
Hi,

Following docs/pycharm/configuration.rst i get an error message when trying to create a Remote Python Interpreter based on Docker Compose in PyCharm.

![skarmklipp 2016-04-16 12 27 52](https://cloud.githubusercontent.com/assets/4190625/14580487/b11cc896-03ce-11e6-8089-bea19a013545.png)
![skarmklipp 2016-04-16 12 27 45](https://cloud.githubusercontent.com/assets/4190625/14580488/b2969ecc-03ce-11e6-8972-d7860b51be56.png)

Anyone else with this problem?
@noisy Anything I can do in a different way?

**Comment by phiberjenz** [comment]
Did some digging. Apparently it seems that named volumes doesn't play well with PyCharm 2016.1. Removing them and going back to previous version of dev.yml fixes the problem.

**Comment by luzfcb** [comment]
@phiberjenz you try Pycharm 2016.1.2?

http://blog.jetbrains.com/pycharm/2016/04/announcing-pycharm-2016-1-2/

**Comment by phiberjenz** [comment]
I will try it tomorrow!

**Comment by bhops** [comment]
I'm experiencing the same issue on PyCharm 2016.1.2.

**Comment by luzfcb** [comment]
perhaps, Pycharm 2016.1.3 RC fix problems !?
http://blog.jetbrains.com/pycharm/2016/04/pycharm-2016-1-3-rc-is-available/

**Comment by bhops** [comment]
@luzfcb That worked. Thanks!

**Comment by phiberjenz** [comment]
Yes it's working on 2016.1.3!

**Comment by luzfcb** [comment]
:+1:
