### ISSUE TITLE
Validate all major features work everywhere

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#529]
Every major feature needs to work in the following areas:

*. Ubuntu Linux
*. OSX
*. Windows (Redis doesn't work perfectly in Windows, am looking into ramifications)

Every major feature needs to work with the following versions of Python:

* Python 2.7.x
* Python 3.5.x

Features to validate:

* [x] For Django 1.9
* [x] Renders Django projects with 100% starting test coverage
* [x] Twitter Bootstrap v4.0.0 - alpha
* [ ] End-to-end via Hitch
* [ ] AngularJS
* [x] 12-Factor based settings via django-environ
* [x] Optimized development and production settings
* [x] Registration via django-allauth
* [x] Comes with custom user model ready to go.
* [x] Grunt build for compass and livereload
* [ ] Basic e-mail configurations for sending emails via Mailgun
* [x] Media storage using Amazon S3
* [x] Docker support using docker-compose for development and production
* [x] Procfile for deploying to Heroku
* [x] Works with Python 2.7.x or 3.5.x
* [x] Run tests with unittest or py.test

What happens if something doesn't work in all these environments?

1. We'll provide a grace period of 30 (more? less?) days for the feature to be updated.
2. If the grace period ends, we'll look for a substitute or remove the feature altogether.

**Comment by pydanny** [comment]
If you can validate one or more of these items, please say so in the comments. I'll update the checklist.

**Comment by burhan** [comment]
Regarding Redis, it is stated plainly on `redis.com/download`:

> The Redis project does not officially support Windows.

I would like to recommend moving Redis to a container and exposing the port. If the user prefers not to use docker for development, redis would still be available at the normal redis port for them.

I see one major issue with this approach - it requires a hard dependency on docker being installed on the client machine.

**Comment by jayfk** [comment]
Redis isn't a hard requirement for the development environment. We are using `LocMemCache` as a cache there.

**Comment by mimischi** [comment]
Hitch does not work on Windows: https://hitchtest.readthedocs.org/en/latest/misc/tested_on.html#not-working-on

**Comment by crdoconnor** [comment]
+1 mimischi. Unfortunately there are many features it uses which aren't really possible to replicate on windows without a compatibility layer - for example, pyenv, libfaketime, along with a whole lot of code that would need to be heavily rewritten (unixpackage, the service handler).

It works inside docker (I've tested this on a debian image) and would probably work on the new 'bash for windows' thing. 

If you like I can pick and test one of these solutions and fix it up to make it easy to use hitch with it.

If neither one is an acceptable solution you should probably remove it.

**Comment by burhan** [comment]
I have the Linux runtime on my development machine; but even if it works
its not a solution until Microsoft rolls it out officially (right now, its
only available on the developer channel; which means you are dealing with
untested builds of Windows).

I'll give it a try this weekend and see what breaks.

**Comment by crdoconnor** [comment]
I have a dockerized version tested and running happily, although it requires an X server (e.g. cygwin/x). I can probably automate the set up of these things via powershell, though, so it's (relatively) seamless for a windows user.

**Comment by pydanny** [comment]
Removed Hitch in 5517bdd.

**Comment by audreyr** [comment]
Checked off django-environ, which works everywhere.

**Comment by burhan** [comment]
Is there a Hitch equivalent that we can evaluate?

**Comment by yunti** [comment]
I understand the reason to have all major features working on all platforms, which is a good idea, but it's definitely disappointing to see Hitch removed so quickly as it's definitely a very useful feature, which I would be keen to keep in if possible.  With Docker's new 'native' implementation on windows if hitch could work under that for now would that be sufficient until Microsoft rolls out the new Linux on Windows?

**Comment by pydanny** [comment]
@burhan @yunti The reason why I removed Hitch is because:

1. Doesn't work on Windows (https://hitchtest.readthedocs.org/en/latest/misc/tested_on.html#not-working-on)
2. Doesn't work on El Capitain (https://github.com/hitchtest/hitch/issues/28)
3. When I tried to get Hitch running on my Mac (`hitch init), it ran homebrew over my existing packages (took me a couple hours to fix, and I'm arguably a "power user"
4. I'm getting emails for help on both items

I think Hitch is great software, but here are my concerns:

1. The volume of fragile dependencies (.PyYAML for example) lends the project to being purely inside a docker container. As part of Cookiecutter Django it would have to be filtered from both Windows and OSX users.
2. For a complex project used by what appears to be serious companies, I can easily argue it's unfair that @crdoconnor is essentially working on it alone.

**Comment by pydanny** [comment]
In regards to Redis, I believe developers on Windows can use pure-memory options for those things when working locally.

**Comment by crdoconnor** [comment]
@pydanny:

2. It does work on El Capitan (I use it fairly regularly at work on El Capitan these days). @mimischi's issue appears to be a bug in virtualenv that appeared on which prevents non-broken python3 virtualenvs from being created. See the ticket for details.

3. I'm sorry for your poor experience. I honestly had no idea there were Mac users who explicitly wanted to keep specific packages from being installed via brew - or that it could overwrite (I thought it installed packages in a safe 'brew specific' location). Nonetheless, I'll accommodate this use case and make the installation of necessary packages an explicit step that the user has to perform. As I work on this I find that there are certain power user use cases which surprise me and trip me up (e.g. @Eraldo had PIP_REQUIRE_VIRTUALENV set to true in his environment) but I'm dealing with them as they arise (that issue I fixed).

4. I'd have been happy to field these emails and accommodate the design to deal with these issues had I known of their existence.

1. PyYAML hasn't caused any issues that I know of. Can you explain what you mean by this? There are a couple of other dependencies (e.g. pykwalify) which cause minor problems but I'm dealing with them as they arise. On the whole if a dependency causes major issues, I tend to toss it. Unfortunately, dependencies like virtualenv (above) that exhibit major problems I can't do a lot about.

2. I'm fairly responsive to the issues that are reported to me and I'm more than happy to field all support emails that come your way even tangentially related to this project.

**Comment by jayfk** [comment]
I can confirm docker on linux and Mac OS X. I haven't tried windows for a while, but thanks to @burhan this should work now, too.

**Comment by Eraldo** [comment]
I am happily using hitch on my system: OS X El Capitan Version 10.11.4.

I think hitch is a great project and I just set up a new project via cookiecutter and was shocked to see it has been removed.

After reading this thread I do understand why you chose to go down that path

I personally would love to see in integrated again. I gave another talk on it here in Berlin some time ago and it is gaining popularity. I hope we can get enough people on board to help solve the issues cookiecutter users face - so it can be rebundled. -- just my 50c.

@mcoconnor Please keep up the great work! :D
Same goes for the cookiecutter crew. ;)

**Comment by pydanny** [comment]
My problems with Hitch essentially boils down to: It's just @crdoconnor maintaining the project.

While @crdoconnor has done an amazing job, Hitch is a very sophisticated project with what appears to be a single maintainer. While it's becoming apparent that any number of companies and organizations use Hitch, no one AFAIK is supporting his development on the project. In addition to the bus factor, it also means that cross-compatability testing is extremely limiting.

While @crdoconnor is willing to answer questions and help on Hitch, he will need time off. He'll need breaks. That's just how these things go. I am also uncomfortable with large organizations (banks, et al) dumping unpaid support tasks on a single person this way.

To get Hitch back into this project, this is what we'll need:

1. Other regular committers to Hitch besides @crdoconnor. Hitch isn't simple, and deserves this kind of support. Perhaps @Eraldo or @burhan if they have time/desire/need? Or perhaps someone else. I just am uneasy dumping unpaid corporate support onto @crdoconnor.

2. Consideration for replacement of the unmaintained `PyYAML`. It got so bad (`Raumel.yaml` is a maintained fork that has problems of its own) with Cookiecutter installations that @hackebrot created a pure Python PyYAML replacement called Poyo. If Hitch could switch to that it would be nice, but I'll leave that up to @crdoconnor.

**Comment by jayfk** [comment]
I had the pleasure of setting up a cookiecutter-django project with docker on windows 10.

- [x] Docker
