### ISSUE TITLE
.idea directory missing with Pycharm enabled

### ISSUE THREAD

**Issue by Newton715** [pydanny/cookiecutter-django#535]
The pycharm .idea directory has gone missing with commit a783828 on April 25.

**Comment by benjaoming** [comment]
I still see it in current master, referred commit doesn't seem to affect it!?

**Comment by Newton715** [comment]
Maybe I'm missing something but between commits fee825e and a783828 I don't see /{{cookiecutter.project_slug}}/.idea

<img width="1020" alt="screen shot 2016-05-01 at 3 15 19 pm" src="https://cloud.githubusercontent.com/assets/3343995/14944692/4d33550a-0fb0-11e6-90ec-dfc481cefaec.png">

<img width="1027" alt="screen shot 2016-05-01 at 3 23 59 pm" src="https://cloud.githubusercontent.com/assets/3343995/14944728/10d09bee-0fb1-11e6-87a0-d6a7671a85d1.png">

I tried to start a project recently with the master and with Pycharm & docker support enabled, but the .idea directory was missing.  I downloaded fee825e and ran cookiecutter off of the directory and everything ran as expected.

**Comment by luzfcb** [comment]
@Newton715 after a short investigation, the settings were mistakenly removed in 15f350f0

**Comment by luzfcb** [comment]
@Newton715 please, test the branch "restore-idea-directory" and make sure everything works as expected.

first, make sure the cookiecutter version is >= 1.4

```
cookiecutter --version
```

after: 

```
git clone https://github.com/pydanny/cookiecutter-django --branch restore-idea-directory --single-branch
```
generate the project
```
cookiecutter cookiecutter-django/
```


pr: https://github.com/pydanny/cookiecutter-django/pull/537

**Comment by Newton715** [comment]
@luzfcb Tested it out.  .idea directory was created and docker tests ran in pycharm without an issue.

**Comment by benjaoming** [comment]
Disregard my comment then, I thought `.idea` folders were something *not* to have in a repo :)

**Comment by luzfcb** [comment]
fixed in https://github.com/pydanny/cookiecutter-django/pull/537

**Comment by luzfcb** [comment]
@Newton715 thanks.
