### ISSUE TITLE
Switch to django-anymail with mailgun as the default

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#539]
django-anymail led by @med is the ideal solution to our needs. Yes, it is bleeding edge, but we like that kind of thing. Especially as it is consistently maintained and has tests. 

As much as I would like to do the work for this enhancement, in this case deferring to those with more expertise is the right thing to do. To summarize, we're open for pull requests! 😄 

🔔  @medmunds @jayfk 

Reference ticket: #531

**Comment by jayfk** [comment]
:clap: @audreyr
