### ISSUE TITLE
Mail server

### ISSUE THREAD

**Issue by ArcaneWater** [pydanny/cookiecutter-django#542]
So i just installed this template and used mailhog, in readme it says just run npm install and grun serve, but i already fail at npm install as there is no package.json? Am i doing this wrong or whats recommended to get this local mail testing up?

**Comment by luzfcb** [comment]
`package.json` and `Gruntfile.js` only is shipped on generated project if you select `"use_grunt [n]: y"`

if `"use_grunt [n]: n"`, `package.json` and `Gruntfile.js` is removed by [cookiecutter post-generate hook](http://cookiecutter.readthedocs.io/en/latest/advanced_usage.html#using-pre-post-generate-hooks-0-7-0): 
https://github.com/pydanny/cookiecutter-django/blob/master/hooks/post_gen_project.py#L180-L181

**Comment by ArcaneWater** [comment]
Oh forgot about that i fixed now but it does not work "from the box"?

> Running "bgShell:runMailHog" (bgShell) task
> 
> Running "bgShell:runDjango" (bgShell) task
> 
> Running "watch" task
> Waiting...
> >> /bin/sh: ./mailhog: No such file or directory
> >> Error: Command failed: ./mailhog
> Running "sass:dev" (sass) task
> 
> Done, without errors.
