### ISSUE TITLE
django-secure still neccessary?

### ISSUE THREAD

**Issue by rdmurphy** [pydanny/cookiecutter-django#543]
Hello! Just came across this, and I thought of cookiecutter-django.

According to the `django-secure` docs, it was pulled into Django when it hit 1.8 and the [library is no longer maintained](https://django-secure.readthedocs.io/en/latest/index.html).

Unsure if the configuration changed in the process, but maybe the dependency could be dropped?

**Comment by pydanny** [comment]
We just need a pull request taking it out. Also see #280.

**Comment by pydanny** [comment]
Addred in #579 by @xpostudio4
