### ISSUE TITLE
Log Celery errors to Sentry

### ISSUE THREAD

**Issue by pckapps** [pydanny/cookiecutter-django#544]
Currently, errors that occur while a task is run in Celery is not reported to Sentry. I believe the default case should be that these tasks are also reported to Sentry. Some configuration is required to get that working as explained [here](https://docs.getsentry.com/hosted/clients/python/integrations/celery/)

**Comment by jayfk** [comment]
> Some configuration is required to get that working as explained here

That's set here https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/taskapp/celery.py#L27-L37

**Comment by pckapps** [comment]
Sorry, mine didn't generate it. Closing issue
