### ISSUE TITLE
Pulling the postgres backup

### ISSUE THREAD

**Issue by jangeador** [pydanny/cookiecutter-django#548]
What is the recommended way to get the docker-compose backup from the postgres. I backup using the command in the docs

`docker-compose run postgres backup`

I would like to know the best way to get those backup files from the docker container and to put them somewhere else.

**Comment by phiberjenz** [comment]
Had this exact problem yesterday.
`docker cp <containerId>:/file/path/within/container /host/path/target`

1. Get your Postgres container id by `docker ps`
2. `docker cp <containerId>:/backups ./backups`

**Comment by jayfk** [comment]
@phiberjenz if you have the time, would you add this to the docs and create a pull request?

**Comment by jangeador** [comment]
This works really well. Just one things that got me was the behavior of the ``docker cp`` command. If you want to keep using the same directory to keep backing up locally you need to suffix the source path with ``/.``. so the command that ended up working for me was:

`docker cp <containerId>:/backups/. ./backups`
