### ISSUE TITLE
py.test errors using travis

### ISSUE THREAD

**Issue by Eraldo** [pydanny/cookiecutter-django#550]
Since hitch has been removed, I am trying to run my tests with py.test for a new project.

The project uses travis for ci.

There is a default travis config file in the repo `.travis.yml` -- however I get an error telling me that it needs a script key. 
`Please override the script: key in your .travis.yml to run tests.`
After some research I found an article explaining that there is no sensible default for it so it has to be part of the file: https://github.com/travis-ci/travis-ci/issues/2870

What is the suggestion to put in the script part of the travis file when using `py.test`?

Another challenge I face with that is that I have a `test.txt` requirements file -- so travis needs to install these packages in order for the tests to work. Right now I get an error:

```
E   ImportError: No module named 'test_plus'
```

(since it uses the local settings by default which in my case do not have `django-test-plus` included -- in my case they are in `requirements/test.txt`)

Do you have any suggestions, hints or directions?
They are very welcome. :)

Best, Eraldo

**Comment by jeffshek** [comment]
@Eraldo  - To get around your second issue, what I changed on travis.yaml 
```yaml
install:
  - pip install -r requirements/test.txt
```
separating out configuration settings to its own file, ie. production, etc /config/production, config/staging config/testing.

and in app determining locations include
```python
import os
if 'TRAVIS' in os.environ:
     select testing configurations, etc.
````

**Comment by webyneter** [comment]
@Eraldo, have the issue been resolved?

**Comment by Eraldo** [comment]
Yes
I did not test the mentioned solution. However the issue is resolved.
