### ISSUE TITLE
git pre/post commit hooks

### ISSUE THREAD

**Issue by jeffshek** [pydanny/cookiecutter-django#556]
Thoughts on a pull request on a standard out of the box git pre-commit/post-commit hooks? I've used ones where we catch for any pdb in production / run pyflakes on code prior to commit, etc.

I'm looking at something similar below for inspiration
https://github.com/pre-commit/pre-commit-hooks

**Comment by pydanny** [comment]
Interesting idea!

:bell: @burhan @theskumar @luzfcb @audreyr @jayfk

**Comment by theskumar** [comment]
It's going to be a lovely edition.  It would be nice have some documentation on how to disable it temporarily.

**Comment by djch** [comment]
@theskumar From my experience you can just do add the `--no-verify` argument to your `git commit`

**Comment by jayfk** [comment]
Would love to have that as an optional thing :)

**Comment by luzfcb** [comment]
+1 to to have that as an optional thing.
flake8 pre-commit hook and isort pre-commit hook[1] with `--check-only` and/or `--diff`

[1] https://github.com/FalconSocial/pre-commit-python-sorter

**Comment by pydanny** [comment]
I think the consensus is that we would really like this feature. Please submit @jeffshek!

**Comment by audreyr** [comment]
Or if anyone wants to work on adding some of these during the PyCon sprints, go for it. 👍

**Comment by jeffshek** [comment]
@pydanny Sorry! Got a little caught up, but I'll make a PR for this tonight!
