### ISSUE TITLE
Example of celery use with Docker

### ISSUE THREAD

**Issue by jangeador** [pydanny/cookiecutter-django#558]
Does any user of this project have a working example of starting celery workers with Docker? Where will be the best place to start them from?

**Comment by jangeador** [comment]
I am closing the issue as I found the answer to my question. Here it is in case anyone else needs it. The docker containers already have 2 containers dedicated for these. They are called `celeryworker` and `celerybeat`. They will be running when the container is in production.

During development it is possible to see these in action by using the commands:

`celery -A [your_project].taskapp worker -l INFO` for the worker

and

`celery -A gesdnet.taskapp beat -l INFO` for the celerybeat.

**Comment by pydanny** [comment]
Is this in our documentation?

**Comment by jangeador** [comment]
No sir. I found it by looking at the docker-compose.yml file.

**Comment by jangeador** [comment]
I am still having problems with this. Can someone please provide me with a working example of a task using the configuration in the cookiecutter-django project. Also, it will be nice to have an example of a task using the celerybeat. Thanks in advance.
