### ISSUE TITLE
Logging celery errors with opbeat

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#559]
Currently, celery errors are not logged by opbeat.

Info: https://opbeat.com/docs/articles/get-started-with-django/#logging-celery-tasks

**Comment by pydanny** [comment]
Considering Sentry does such a great job at this kind of task, what's the purpose of having Opbeat do it as well?

**Comment by jayfk** [comment]
They are both optional. If someone uses Opbeat without Sentry, he/she won't get notifications.
