### ISSUE TITLE
Verify, revise, and improve docs/developing-locally-docker.rst

### ISSUE THREAD

**Issue by audreyr** [pydanny/cookiecutter-django#565]
- Make sure everything is up-to-date.
- If anything is unclear or incorrect, revise the text.
- Some parts are a bit longer than necessary and could be moved to a separate Docker Tips document.

**Comment by jayfk** [comment]
I'm happy to help if something is unclear.

**Comment by mjsisley** [comment]
Add items in #515 in Docker Tips section?

**Comment by jayfk** [comment]
@mjsisley 👍

**Comment by browniebroke** [comment]
@webyneter rewrote them a couple of months ago, I think we can close this?

**Comment by webyneter** [comment]
I guess so.
