### ISSUE TITLE
remove unused non-python dependencies from requirements.apt.xenial

### ISSUE THREAD

**Issue by luzfcb** [pydanny/cookiecutter-django#569]
https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/utility/requirements.apt.xenial

**Comment by browniebroke** [comment]
I can see this file has been renamed and simplified as part of https://github.com/pydanny/cookiecutter-django/commit/1812546e99890406b389eec1841ebd53ffd89a8b#diff-d06b6634c28ed5aea0da329995ab68c0 and it seems quite lean now:  

https://github.com/pydanny/cookiecutter-django/blob/60ebda8bf7b0cc0c752ff813a125316d3cb79ad3/%7B%7Bcookiecutter.project_slug%7D%7D/utility/requirements-xenial.apt#L1-L23

I'm closing this for now. If there is anything specific to clean up, please re-open.
