### ISSUE TITLE
Django Favicon Generation

### ISSUE THREAD

**Issue by mjsisley** [pydanny/cookiecutter-django#573]
These two packages exist:
- [django-favicon-plus](https://github.com/arteria/django-favicon-plus/)
- [django-super-favicon](https://github.com/ZuluPro/django-super-favicon)

The first is patterned after the helpful [favicon cheatsheet](https://github.com/audreyr/favicon-cheat-sheet) by @audreyr.

Thoughts on adding one of these, or something like it, into the project?

**Comment by pydanny** [comment]
I think this is a per-project kind of thing.

**Comment by mjsisley** [comment]
Makes sense. I think auto-favicon generation as an option is probably a nice-to-have, but not really needed.

It is likely that the gulp tasks could easily be pulled from here to add it as an option: https://github.com/este/este/tree/master/gulp, but I won't have the time, so +1 to closing.
