### ISSUE TITLE
Review and edit django-allauth templates

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#574]
The project comes with django-allauth templates by default. Most of the time they look somewhat *okay*, but are inconsistent. 

What to look for:

 * Margins: Is this correct accross all templates?
 * Widths: Some templates are half size, some are full size
 * Wording
   - Sign Up, Signup, Register, Log In, Login, e-Mail, Email, eMail-Address => Make one the default.
   - Check for spelling, grammar

**Comment by kappataumu** [comment]
I'm working on this, should the templates be brought in sync with upstream? There a couple of changes.

**Comment by pydanny** [comment]
@kappataumu Absolutely they should be made current with upstream, albeit formatted for Bootstrap 4. 

--@pydanny

**Comment by kappataumu** [comment]
Did this in a bit of a hurry, if there are any glaring omissions hit me up.
