### ISSUE TITLE
Link to the documentation from the README

### ISSUE THREAD

**Issue by kappataumu** [pydanny/cookiecutter-django#588]
When landing at the project's page, it's not immediately obvious where one should look for further info regarding configuration and setup. A prominent link pointing to [Read the Docs](http://cookiecutter-django.readthedocs.io/en/latest/index.html) should be placed in the README, near the top, as in [cookiecutter](https://github.com/audreyr/cookiecutter).

**Comment by pydanny** [comment]
Sounds like a great idea. Would you like to submit a pull request in order to get more credit? If not I can take care of it for you.

**Comment by audreyr** [comment]
Done in #597
