### ISSUE TITLE
Use the minified Bootstrap CSS and JS

### ISSUE THREAD

**Issue by kappataumu** [pydanny/cookiecutter-django#589]
I noticed that in [base.html](https://github.com/pydanny/cookiecutter-django/blob/bootstrap4-alfa2-cdn/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/templates/base.html), contrary to what the HTML comments suggest, the links are to the unminified CSS and JS for Bootstrap. In the [bootstrap4-alfa2-cdn](https://github.com/pydanny/cookiecutter-django/tree/bootstrap4-alfa2-cdn) branch by @luzfcb the links are correctly pointing to the minified versions (on MaxCDN), so it would be beneficial if that was merged. 

As a (welcome) side-effect, this also pins both files to [v4.0.0-alpha.2](https://github.com/twbs/bootstrap/releases/tag/v4.0.0-alpha.2) instead of the [v4-dev](https://github.com/twbs/bootstrap/tree/v4-dev) branch, which is a moving target.

**Comment by pydanny** [comment]
Good idea. Care to submit a pull request?
