### ISSUE TITLE
Write test that creates/checks a matrix of all y/n option combinations

### ISSUE THREAD

**Issue by audreyr** [pydanny/cookiecutter-django#591]
Ensure that the project generates without errors for every possible combination of:
- y/n values entered
- choices entered when selecting from a list, e.g. test all license choices

(Similarly filed in Cookiecutter PyPackage: https://github.com/audreyr/cookiecutter-pypackage/issues/184)

**Comment by jeffshek** [comment]
@audreyr i'll give this a shot, i'll start with the cc-django one and port it over if it's what we're going for

**Comment by jeffshek** [comment]
Sorry, it has been stupid busy, but I have this bookmarked and every few days I remind myself of the guilt that I didn't do this yet! I'm going to take a look into this week to give it a shot (if not already done)

**Comment by webyneter** [comment]
@jeffshek, any news on that?

**Comment by kenlavoie** [comment]
@browniebroke - is this still an open issue?
