### ISSUE TITLE
remove_file for deleting files in post_gen_project.py 

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#592]
This prevents hard-to-debug project generation failures that occur when a file that doesn't exist is attempted to be removed.

**Comment by webyneter** [comment]
Am I right to assume you were talking about refactoring `os.remove(file_name)` to `remove_file(file_name)`?

**Comment by serhii73** [comment]
Is no longer relevant?

**Comment by shywn-mrk** [comment]
Is this still relevant? If so, can you provide more information about what we are going to do about it?

**Comment by browniebroke** [comment]
Assuming it's no longer relevant, going to close this. If this is still relevant, we need to provide more actionable details when reopening.
