### ISSUE TITLE
dhparam.pem instructions need to come before docker-compose build

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#606]
If using Let's Encrypt and Certbot, this needs to be done before docker-compose. Otherwise the build fails and you have to start the build over again.

**Comment by jayfk** [comment]
It would be possible to autogenerate that file during container "boot". Is this something you would consider?

**Comment by mjsisley** [comment]
Unless there is a good reason not to, I'm going to submit a PR to use nginx-proxy and a companion container for Letsencrypt support (which handles dhparam.pem generation during build) instead per #596 when I have the chance.

**Comment by pydanny** [comment]
@mjsisley Automating the Letencrypt components would be awesome! As for the `nginx-proxy` item, in #596 we're waiting for a more knowledgable response.
