### ISSUE TITLE
Optionally generate a .gitlab-ci.yml

### ISSUE THREAD

**Issue by audreyr** [pydanny/cookiecutter-django#607]
- It should be optional. In `cookiecutter.json` we should have `"use_gitlab_ci": "n",`
- It should be pre-configured to run the test suite upon commit
- Document how it works in:
  - `docs/project-generation-options.rst` (broadly)
  - `docs/ci-gitlab.rst` (in detail)
- Continuous deployment might be nice as well, at least for one of the deployment options

**Comment by calculuscowboy** [comment]
I have a Cookiecutter Django project using GitLab CI and Docker with compose and machine for continuous deployment.  The basic pipeline is pushes to all branches run the tests (including flake8 and coverage), pushes to master and production branches also automatically deploy to beta.{{cookiecutter.domain_name}} and {{cookiecutter.domain_name}}, respectively.

The [.gitlab-ci.yml](https://github.com/pydanny/cookiecutter-django/files/307021/default.gitlab-ci.yml.txt) looks something like this.

I can put together a PR with documentation if there's interest, unless someone beats me to it. :)
