### ISSUE TITLE
Faster deployments

### ISSUE THREAD

**Issue by msamoylov** [pydanny/cookiecutter-django#623]
`./manage.py collectstatic` is pretty slow because us WhiteNoise. Is there any way to reduce downtime while deploying latest changes live?

**Comment by pydanny** [comment]
To which service are you deploying?

**Comment by msamoylov** [comment]
My bad. Deploying with Docker to Linode and Digital Ocean. It takes about a
minute to collect static files.

On Thu, Jun 16, 2016 at 7:50 PM, Daniel Roy Greenfeld <
notifications@github.com> wrote:

> To which service are you deploying?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pydanny/cookiecutter-django/issues/623#issuecomment-226544889>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAGhPY3OTkL9v9gZc9jkl9rD3dOSjoS7ks5qMX64gaJpZM4I2che>
> .
>



-- 
Michael Samoylov
michael.samoylov@gmail.com
LinkedIn: http://linkedin.com/in/msamoylov

**Comment by hasancansaral** [comment]
@pydanny I don't know if it is related to `./manage.py collectstatic` but in my case (AWS EC2 micro instance) `docker-compose build` takes around 30+ minutes.

After `Building django` is printed, it waits for that much until it proceeds to the Dockerfile's contents. Any thoughts?

**Comment by jayfk** [comment]
Sounds weird, but try a different AWS region.

**Comment by pydanny** [comment]
Considering this resolved via AWS region selection. If this is not the case, please re-open.

**Comment by hasancansaral** [comment]
@jayfk @pydanny No, it hasn't been resolved via AWS region change. I have tested this in more than one AWS regions, with different instance specs. Can we reopen?
