### ISSUE TITLE
Deploying with Fabric

### ISSUE THREAD

**Issue by msamoylov** [pydanny/cookiecutter-django#640]
Hi guys.

Will you consider a PR with Fabric? Right now there's no way to automate deployment if Docker is not selected.

**Comment by pydanny** [comment]
Three concerns, each of which prevents this from being an option:

1. Fabric is Python 2-only. PyInvoke or some other Python 3 friendly tool would have to be used instead.
2. Deploy to what? AWS? Digital Ocean? Rackspace? Something else? "fabric' is not specific enough.
3. I really, really prefer Docker over fabric/pyinvoke deployments. I don't want to assume the burden of responsibility for deploying via fabric/pyinvoke. We get lots questions on the Docker and Heroku deployments, adding in this option which suffers from problems #1 and #2 is too much work on the shoulders of the core maintainers.

**Comment by msamoylov** [comment]
1. I can argue that with https://pypi.python.org/pypi/Fabric3
2. Deploy to any Ubuntu server.
3. Makes sense. We've been using Fabric for ages and may be kinda out-of-date, so Docker is taking over the Django deployment market now? Just curious.

**Comment by pydanny** [comment]
> 3. Makes sense. We've been using Fabric for ages and may be kinda out-of-date, so Docker is taking over the Django deployment market now? Just curious.

I don't know for certain if Docker is the lead in the deployment market for Django. However, we do prefer it here in Cookiecutter Django.
