### ISSUE TITLE
timezone on containers

### ISSUE THREAD

**Issue by aleprovencio** [pydanny/cookiecutter-django#645]
Currently timezone is already set on django settings but not on containers :/

**Comment by webyneter** [comment]
@aleprovencio, could you please give more details on that?

**Comment by aleprovencio** [comment]
@webyneter , if I run 'date' commands on the containers they will not match the container set for django which has the timezone set. Thus, logs and other stuff gets messed up.

**Comment by webyneter** [comment]
@aleprovencio, it's been a while since you reported the bug; did you manage to resolve it?

**Comment by webyneter** [comment]
@aleprovencio, because if yes, your solution is very much welcome :)

**Comment by webyneter** [comment]
@aleprovencio, by the way, does this happen at development, or production, or both?

**Comment by aleprovencio** [comment]
Unfortunately I have not managed to fix it yet...
Yes, it happens on both environments :/

**Comment by webyneter** [comment]
@aleprovencio, gotta get take a look at this one soon.

**Comment by webyneter** [comment]
@aleprovencio, and thank you for reporting that subtle yet important issue.

**Comment by aleprovencio** [comment]
That's awesome, thanks for taking your time :)

**Comment by amcorreia** [comment]
@aleprovencio Try this, run container with

--env TZ=America/Sao_Paulo

**Comment by webyneter** [comment]
@aleprovencio, @amcorreia is right, did you try customizing the timezone?

**Comment by browniebroke** [comment]
I've tried to set my host timezone to something else, and the container seems to return UTC when nothing is set.

Since we use docker-compose to run several containers, the `--env` option isn't available, but we could add it in `local.yml` and in `.env`. The `date` command follows this setting.

The Django setting could then be changed to use the value from the environment variable `TZ`.

Am I missing anything?

**Comment by aleprovencio** [comment]
Sorry for missing last comment @webyneter and @amcorreia, but you are correct.
I also agree with @browniebroke , setting timezone like that is much more aligned with the project.
