### ISSUE TITLE
git clone suggestion for webpack

### ISSUE THREAD

**Issue by resakse** [pydanny/cookiecutter-django#647]
hi, thanks for making this..but can I suggest using https for git cloning webpack instead of ssh?
thanks!

**Comment by luzfcb** [comment]
@resakse Nice catch. 
Clone via ssh is a problem if you still know little git and / or have not set up your ssh keys to use git and github.

**Comment by luzfcb** [comment]
@resakse Thanks. fixed on https://github.com/pydanny/cookiecutter-django/commit/206fcc6d6dd34e87ec3ed2c0faeff3784a98a4e9
