### ISSUE TITLE
Fix SuspiciousOperation errors

### ISSUE THREAD

**Issue by aleprovencio** [pydanny/cookiecutter-django#670]
As @pydanny already predicted such problems here https://github.com/pydanny/cookiecutter-django/pull/319, i think we have to choose to silence these errors by configuring either the [logger](http://stackoverflow.com/questions/15238506/djangos-suspiciousoperation-invalid-http-host-header/17477436#17477436) or the [webserver](https://docs.djangoproject.com/en/1.9/topics/logging/) .

**Comment by pydanny** [comment]
Silencing errors is never a good idea. Perhaps you meant to turn my notes from #319 into an issue?

**Comment by aleprovencio** [comment]
I agree silencing them is not a good option, but then I think the suggested config for nginx is not about silencing, and seem viable; plus, I can't find a way to improve the logging for this case.
