### ISSUE TITLE
custom user model doesn't specify USERNAME_FIELD

### ISSUE THREAD

**Issue by yunti** [pydanny/cookiecutter-django#674]
The custom user model in user.models doesn't specify a USERNAME_FIELD, which from reading the django docs implies that this is required?

"your model must have a single unique field that can be used for identification purposes. This can be a username, an email address, or any other unique attribute." 
and make that the identifying field via `USERNAME_FIELD`

Should this be added to the custom user model in django cookiecutter or is there some use case where this doesn't fit?

**Comment by jayfk** [comment]
Could be wrong here, but I think allauth sets that up for us.

**Comment by yunti** [comment]
Ah see it now we're subclassing `AbstractUser` rather than `AbstractBaseUser` and it's set up in there.
