### ISSUE TITLE
Update to Django 1.10

### ISSUE THREAD

**Issue by luzfcb** [pydanny/cookiecutter-django#703]
Checklist:

- [x] Before update to Django 1.10, create a git tag to current version of cookiecuter-django
- [ ] Check if all dependencies officialy work with Django 1.10( if not, wait)
- [x] Check that the tests pass on Django 1.10
- [ ] Check that the tests pass on Django 1.10 with zero deprecation warnings messages: https://docs.djangoproject.com/en/1.10/howto/upgrade-version/#resolving-deprecation-warnings
- [ ] Update to Django 1.10 and update other dependencies and:
    - [x] Check if all possible generated project layout still works on deploy on Heroku.
    - [ ] Check if all possible generated project layout still works on deploy on Docker.
    - [ ] Check PyCharm 2016.2 compatibility, with and widout docker
    - [x] Update the README.rst
    - [x] Update [version on setup.py](https://github.com/pydanny/cookiecutter-django/blob/master/setup.py#L13)
    - [x] Update changelog.
    - [ ] after update, create a git tag

related: https://github.com/pydanny/cookiecutter-django/pull/702

**Comment by ssteinerx** [comment]
Generated layout works on Docker other than #704 opened 18 hours ago by ssteinerx

**Comment by ssteinerx** [comment]
Pycharm container also crashes.

**Comment by audreyr** [comment]
Verified that the tests pass on 1.10

**Comment by audreyr** [comment]
Dependencies that are Django version-dependent:

- [ ] django-environ
- [ ] whitenoise
- [ ] django-braces
- [ ] django-crispy-forms
- [ ] django-floppyforms
- [ ] django-model-utils
- [ ] django-allauth
- [ ] django-autoslug
- [ ] django-redis
- [ ] django-coverage-plugin
- [ ] django-extensions
- [ ] django-test-plus
- [ ] factory_boy
- [ ] django-debug-toolbar
- [ ] pytest-django

Check off each of the above when it officially works on 1.10.

**Comment by jayfk** [comment]
django-model-utils is not ready, see the latest change log in #709

**Comment by jayfk** [comment]
django-extensions is not ready, see https://github.com/django-extensions/django-extensions/pull/934

**Comment by jayfk** [comment]
django-test-plus is not ready, see https://github.com/revsys/django-test-plus/pull/45

**Comment by jayfk** [comment]
django-debug-toolbar is not ready, see https://github.com/jazzband/django-debug-toolbar/pull/864

**Comment by pydanny** [comment]
@jayfk, the following libraries are now ready and marked as such in the checklist:

* django-model-utils
* django-extensions
* django-test-plus
* django-debug-toolbar

**Comment by jayfk** [comment]
👍

**Comment by luzfcb** [comment]
django-braces test suit passes on Django 1.10
https://github.com/brack3t/django-braces/pull/212

**Comment by luzfcb** [comment]
django-floppyforms still require a lot of work to run with Django 1.10

See travis-ci tests of this pull-request https://github.com/gregmuellegger/django-floppyforms/pull/178

**Comment by pydanny** [comment]
@luzfcb Cookiecutter Django doesn't actually use django-floppyforms. We use it, sometimes. Perhaps it behooves us to remove it as a dependency?

**Comment by pydanny** [comment]
The following work with 1.10:

* factory-boy
* django-storages-redux

**Comment by pydanny** [comment]
Removed django-floppyforms in 28542a91a4a5f8f3ed121182c88269da19770e02

**Comment by ssteinerx** [comment]
@audreyr Django extensions was updated 5 days ago and now says: Django Extensions requires Django 1.8 or later and one of the recent commits says "Add Django 1.10 trove classifier" so I think that can be checked off.

**Comment by ssteinerx** [comment]
Django-redis is also passing this on all supported versions of Python:

```... env variables from .travis.yml $ export DJANGO="Django>=1.10,<1.11"
```

**Comment by ssteinerx** [comment]
IOW, cookiecutter-django for Django 1.10 is ready to rock vis-à-vis the dependency list!

**Comment by jayfk** [comment]
> IOW, cookiecutter-django for Django 1.10 is ready to rock vis-à-vis the dependency list!

Apparently, `django-coverage-plugin` is not ready: https://github.com/nedbat/django_coverage_plugin/issues/28

**Comment by ssteinerx** [comment]
@jayfk I actually spent a couple of hours today trying to figure out how to resolve 
https://github.com/nedbat/django_coverage_plugin/issues/28.

It's a very deep issue with the new template handlers and I've been away from Django long enough (last seriously involved circa 1.5ish) that while I understand the issue, I am completely unfamiliar with the changes that went in in 1.8 that completely break .django_coverage_plugin.

The long IRC discussion was interesting, enlightening in some ways, and left me completely clueless as to how to resolve the issue.

That it's been unresolved this long makes me think we should consider dropping the dependency and moving on.  It's a "nice to have" but not the end of the world if it's not there and I, for one, am not willing to hang back a version indefinitely for this one thing.

**Comment by jayfk** [comment]
Good call. If this is a deeper issue, I'm in favor of dropping it for now (and watch it closely thereafter) to get 1.10 out of the door.

**Comment by ssteinerx** [comment]
This is the killer issue: https://github.com/nedbat/django_coverage_plugin/issues/26

Read the IRC chat, this is going to be a bear to untangle if it even ever gets done.

**Comment by ssteinerx** [comment]
Is there a way to fake  pyup-bot  out into notifying us of a change on something we're not really depending on (so we don't have to remember to check, and will be notified as soon as django_coverage_plugin has a new release?)

If so, that makes it even easier to ditch it until it's resolved as we'll have a machine watching for changes and, if they never come, it'll consume zero human-cycles.

**Comment by jayfk** [comment]
We could pull it out of the main requirement files (so that it won't be installed) and place it in a separate file like `requirements_to_watch.txt` or something.

**Comment by ssteinerx** [comment]
@jayfk -- you have no idea how bad I just wanted to say "Make it So", tug on my shirt, and head back to my "Ready Room" to order some [Earl Grey, hot](https://www.youtube.com/watch?v=R2IJdfxWtPM) ;-).

**Comment by luzfcb** [comment]
> We could pull it out of the main requirement files (so that it won't be installed) and place it in a separate file like requirements_to_watch.txt or something.

good, simple and will work.

**Comment by ssteinerx** [comment]
@luzfcb What is pyup-bot's rule?  If it begins with 'requirements`, its contents are added to the list of things to watch?  If so, this'd be perfect!

**Comment by jayfk** [comment]
> If it begins with 'requirements`, its contents are added to the list of things to watch? If so, this'd be perfect!

Exactly, done in https://github.com/pydanny/cookiecutter-django/pull/783.

Looks like we're ready, right?

**Comment by ssteinerx** [comment]
Is the removal of React/WebPack merged into master yet?  I thought I saw @pydanny do that the other day, but I wasn't paying attention to where it got merged *to*.

**Comment by ssteinerx** [comment]
I think he merged master to the remove-react-for-now branch, but I don't think it was merged back the other way.

**Comment by luzfcb** [comment]
@ssteinerx 
> @luzfcb What is pyup-bot's rule? If it begins with 'requirements`, its contents are added to the list of things to watch? If so, this'd be perfect!

the rules are documented in: https://pyup.io/docs/configuration/#requirement-file-search

**Comment by ssteinerx** [comment]
@luzfcb Cool.  Wasn't being lazy, would have looked it up if necessary, just knew someone here would know to make sure we let the machines do the work.

**Comment by jayfk** [comment]
@luzfcb I should hire you :)

**Comment by ssteinerx** [comment]
I can help with this:  Check PyCharm 2016.2 compatibility, with and widout docker if we've got a release candidate branch going...

**Comment by jayfk** [comment]
maybe we should continue the discussion on gitter as it gets pretty noisy for everyone not involved in the release process if we continue with this passion.

**Comment by ssteinerx** [comment]
@jayfk agreed, I'll find the link and head there now.

**Comment by ssteinerx** [comment]
https://gitter.im/pydanny/cookiecutter-django

**Comment by ameistad** [comment]
I don't think raven (Sentry) is ready for 1.10 just yet.
https://github.com/getsentry/raven-python/issues/858 and https://github.com/getsentry/raven-python/pull/860

**Comment by jhancia** [comment]
I may be missing something, but it looks like django-storages-redux is "now released on PyPI as **django-storages"** as of 2-7-2016 (see  https://github.com/jschneier/django-storages/blob/master/CHANGELOG.rst).  So our requirements/production for this should now list  django-storages==1.5.1

**Comment by luzfcb** [comment]
@jhancia thank you, I really had not seen it.

**Comment by pydanny** [comment]
Closing as resolved
