### ISSUE TITLE
Command in Dockerfile-dev throws error and stops on startup

### ISSUE THREAD

**Issue by ssteinerx** [pydanny/cookiecutter-django#704]
manage.py runserver_plus: error: unrecognized arguments: 0.0.0.0:8000

Running:
```
./manage.py runserver_plus 0.0.0.0:8000
```
From the command line gives an identical error.

**Comment by ssteinerx** [comment]
Also reported here as their docs indicate that this should work:
[https://github.com/django-extensions/django-extensions/issues/935](https://github.com/django-extensions/django-extensions/issues/935)

**Comment by ssteinerx** [comment]
The command line help also no longer shows the parameter, only a bunch of flags.  I tried to work around using the `RUNSERVERPLUS_SERVER_ADDRESS_PORT`, but it is also ignored.

**Comment by ssteinerx** [comment]
This has been fixed in the master branch of django-extensions, but is broken in the released version rendering this inoperable in the current cookiecutter-django release which pulls in the borken django-extensions release.

**Comment by audreyr** [comment]
This is specific to Django 1.10, right (not 1.9)?

**Comment by ssteinerx** [comment]
No, the django-extension pulled in by the requirements file does not handle the ip:port parameter.  This has been fixed in the `master` branch of `django-extensions`, but is broken in the most recent release.

**Comment by jayfk** [comment]
Should be good now, see https://github.com/pydanny/cookiecutter-django/pull/725
