### ISSUE TITLE
Update docker docs

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#706]
Docker for Mac/Windows is the new thing. We should update the docs accordingly.

**Comment by ssteinerx** [comment]
I can help with this though the lack of good mapping between the OS X and Debian/Ubuntu makes it so you have to use weird paths with everything e.g. you can't use /var/... on OS X which is the 'normal' place for things on Deb/Ubuntu.

**Comment by jayfk** [comment]
@ssteinerx `dev.yml` and `docker-compose.yml` both use named volumes, so this shouldn't be a problem.

**Comment by ssteinerx** [comment]
Yes, but you have to either use non-standard locations or different files for OS X and e.g. Debian.
