### ISSUE TITLE
Docker pycharm container crashes immediately on startup with no output

### ISSUE THREAD

**Issue by ssteinerx** [pydanny/cookiecutter-django#707]
Just `exited with code 0`, not sure what it's supposed to be doing.

**Comment by luzfcb** [comment]
Whats is the Pycharm version

**Comment by ssteinerx** [comment]
2016.1.4, but I haven't done anything to attempt to integrate it with the Docker containers; not even sure what I'm supposed to do, if anything.  PyCharm is running, but that's all.

**Comment by aadimator** [comment]
I have exactly the same problem. No idea what to do

**Comment by zmrenwu** [comment]
Me too. And I have two problem.
1. _pycharm_1 exited with code 0
2. can't open file 'manage.py': [Errno 2] No such file or directory

With python3.5 django1.9.9 windows10 docker1.12.1 pycharm2016.2.2 cookiecutter1.4.0

**Comment by jayfk** [comment]
Any idea @noisy ?

**Comment by noisy** [comment]
@jayfk I will try to investigate that.

**Comment by zmrenwu** [comment]
Thank all of you! I give some detail about what I have do. First I follow the docs of cookiecutter to generate a project template with using docker and didn't change anything. Then I follow the docs of docker and install the lastest stable release version on windows10. Finally, with every thing setted, I run docker-compose -f dev.yml build to build the container,and run up command to start the container,and met the problems described above.

**Comment by banksee** [comment]
@noisy Any success on this? Same problem.

**Comment by zmrenwu** [comment]
@banksee If you use windows, make sure you allowed docker access you hard driver in docker settings (The default is not)

**Comment by jonesnc** [comment]
Also seeing this.

**Comment by webyneter** [comment]
It's been quite some time now since we dropped `pycharm` Docker Compose service.
