### ISSUE TITLE
Set CONN_MAX_AGE in DATABASE_URL

### ISSUE THREAD

**Issue by audreyr** [pydanny/cookiecutter-django#710]
[CONN_MAX_AGE](https://docs.djangoproject.com/en/1.9/ref/databases/#persistent-connections) defaults to 0. I think it would be nice for us to be more opinionated about it, setting it to a non-zero value by default.

[StackOverflow](http://stackoverflow.com/questions/19937257/what-is-a-good-value-for-conn-max-age-in-django) suggests 60, [RevSys](http://www.revsys.com/blog/2015/may/06/django-performance-simple-things/) suggests 600 (10 min). I lean toward 600 since we're using allauth and authenticated users tend to stick around a site longer.

**Comment by theskumar** [comment]
I would go with 1min, as 10mins way to much for default, having a larger value can have hard to debug issue, soaking up db connection limit. 

With 1min: 
1) we are providing a placeholder which people can see and update as needed (still better if configurable with env variable) 
2) 60sec is a decent for moderately crowded site.
