### ISSUE TITLE
Switch to a .dockerignore blacklist instead of whitelisting

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#713]
Currently, we use a whitelist to tell the docker deamon to ignore all `.*` files except:

```
.coveragerc
.env
.pylintrc
```

I think it's better to be explicit about what shouldn't be sent to the docker deamon and make a blacklist:

```
.editorconfig
.travis.yml
....
```

Why? Because it's super hard to debug. I was spending an hour figuring out why my node container was crashing. Hint: `.eslintrc` and `.eslintignore` were ignored :)

Thoughts?

**Comment by webyneter** [comment]
@jayfk, I agree, it's always better to be explicitly restrictive rather than implicitly permissive.
