### ISSUE TITLE
Cannot stop getting multiple emails on ERRORs

### ISSUE THREAD

**Issue by hasancansaral** [pydanny/cookiecutter-django#714]
Hi, as far as I can see the project is configured to send an email to the site admins on every HTTP 500 error when `DEBUG=False`. Additionally when I configure Sentry, I am also getting emails from Sentry. I am trying to stop emails I am getting from Django logger (at lease the `DisallowedHost` ones) by changing:

```
'django.security.DisallowedHost': {
            'level': 'ERROR',
            'handlers': ['console', 'mail_admins'],
            'propagate': True
}
```

to

```
'django.security.DisallowedHost': {
            'level': 'ERROR',
            'handlers': ['console'],
            'propagate': True
}
```

but to no use. What am I doing wrong? Would removing `mail_admins` handler altogether resolve the issue (and I am assuming that I would not get any email from Django logger in that case, which is more preferable)?

**Comment by pydanny** [comment]
`django.security.DisallowedHost` is not the same as a 500 error. I believe you'll need to add a logger to get that kind of control.

For what it's worth, I like getting two errors, one from the site and one from sentry. The reason is that Sentry can go down.If it's not working, then I still want to get notified.

**Comment by pydanny** [comment]
Closing this as I like getting the duplicate emails.

**Comment by jayfk** [comment]
> Closing this as I like getting the duplicate emails.

Quote of the day 👍

**Comment by tabebqena** [comment]
I suggest that the `propagate': True`, The logger propagate the record to its parent (may be 'django.security' or 'django') and that parent send the second email.
