### ISSUE TITLE
apps.UsersConfig prevents celery task autodiscovery

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#717]
Celery tasks that are created in `users/tasks.py` are not picked up automatically.

Probably because the `users` app is added to `INSTALLED_APPS` by pointing to the `UsersConfig` class instead of loading the module.

**Comment by pydanny** [comment]
You have to use explicit task discovery in the settings, specifically:

``` python
CELERY_IMPORTS = ("scoops.users.tasks", )
```

Adding that as a setting doesn't work, but perhaps we should document it.
