### ISSUE TITLE
Heroku 'Deploy Button' does not account for optional config variables.

### ISSUE THREAD

**Issue by mekhami** [pydanny/cookiecutter-django#729]
As the title says. I tried to deploy by clicking the Heroku Deploy button (which is just amazing btw, go heroku.) Through the process I was prompted to set several more config vars. Unfortunately, on the heroku page that opens up you can't add new config vars, you're restricted to the preset ones that are sent with the button. I don't know how you made all that magic work, but it prompted me for Opbeat and Sentry config variables.

**Comment by pydanny** [comment]
Sounds like you need to add your Opbeat and Sentry config variables on the command-line. That's done so after you install the Heroku toolbelt:

```
heroku config:set KEY=VALUE
```

@burhan might be able to answer more completely.

**Comment by mekhami** [comment]
Definitely, they have to be added, but it seemed like the point of the 'Deploy on Heroku' button was to streamline that process. Currently, if you use opbeat/sentry and click the Deploy on Heroku button, deployment will fail because of those config variables and you'll be forced to do the entire process on the command line anyway.

**Comment by guillaume-miara** [comment]
As I have just played around with this ( reallly awesome! ) project, with complete fresh eyes - and new to heroku! Please let me humbly give you a few things I had stumbled upon in the process ( see attachement) 

Currently the deploy on Heroku didn't run all the necessary cmds for me. I ended having to use a bash anyways.

Hope these few notes for newbes could be useful for you with the doc!

[NotesoncreatinganappwithDjango-CookieCutterforherokudeployment.pdf](https://github.com/pydanny/cookiecutter-django/files/453102/NotesoncreatinganappwithDjango-CookieCutterforherokudeployment.pdf)

**Comment by pydanny** [comment]
@guillaume-miara, do you want to submit that as a Pull Request in RestructuredText for our documentation? If not that, have you considered publishing your notes as a blog post?

**Comment by pydanny** [comment]
@mekhami , while we are going to continue supporting Heroku, I've decided that we're going to remove the Heroku Deploy Button (#779). There's too much going on with Cookiecutter Django, and the deploy button is better used on apps that are simpler in approach.
