### ISSUE TITLE
Gulpfile has some issues

### ISSUE THREAD

**Issue by Parbhat** [pydanny/cookiecutter-django#738]
There are some issues in Gulpfile

- The `runServer` task is not working properly because of this BrowserSync server goes to infinite loading. The problem is the runServer task is using `exec` from `gulp-exec` library. `gulp-exec` library is not required as mentioned in its [docs](https://github.com/robrich/gulp-exec) - "Note: If you just want to run a command, just run the command, don't use this plugin". The issue can be corrected with `exec = require('child_process').exec`.

- Live reloading with `gulp watch` is only working with Sass changes. To enable live reloading of templates, js `browserSync.reload` can be used as mentioned in the [docs](https://www.browsersync.io/docs/gulp).

I noticed these issues while working on my [fork](https://github.com/Parbhat/cookiecutter-django-foundation) of Cookiecutter Django. The corrected file - [link](https://github.com/Parbhat/cookiecutter-django-foundation/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/gulpfile.js).

If this seems ok, I can send a PR.

**Comment by audreyr** [comment]
Sorry for the delay @Parbhat. A PR for this would be really great.

**Comment by Parbhat** [comment]
@audreyr Great. Sending the PR..
