### ISSUE TITLE
rcssmin==1.0.6 --install-option="--without-c-extensions" Fails

### ISSUE THREAD

**Issue by spoetnik** [pydanny/cookiecutter-django#743]
Running "docker-compose -f dev.yml build" fails. 
     error: option --without-c-extensions not recognized

      Running setup.py install for django-appconf: started
        Running setup.py install for django-appconf: finished with status 'error'
        Complete output from command /usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o1djbqqe/django-appconf/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-u3om7rm6-record/install-record.txt --single-version-externally-managed --compile --without-c-extensions:
        usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
           or: -c --help [cmd1 cmd2 ...]
           or: -c --help-commands
           or: -c cmd --help
        
        error: option --without-c-extensions not recognized
        
        ----------------------------------------
    Command "/usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o1djbqqe/django-appconf/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-u3om7rm6-record/install-record.txt --single-version-externally-managed --compile --without-c-extensions" failed with error code 1 in /tmp/pip-build-o1djbqqe/django-appconf/
    ERROR: Service 'django' failed to build: The command '/bin/sh -c pip install -r /requirements/local.txt' returned a non-zero code: 1

**Comment by jayfk** [comment]
I'm able to reproduce this with `use_compressor` == `y`.

Also, prior to installing there's the warning:
```
/usr/local/lib/python3.5/site-packages/pip/req/req_file.py:150: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options, opts)
```

**Comment by pydanny** [comment]
I think this is resolved in d98bbcd70e926016bc526a2083d158440ac29de5. Please confirm.

**Comment by Parbhat** [comment]
@pydanny there is a small error in d98bbcd . `{% if cookiecutter.windows %}` should be `{% if cookiecutter.windows == "y" %}`.

**Comment by jayfk** [comment]
> @pydanny there is a small error in d98bbcd . {% if cookiecutter.windows %} should be {% if cookiecutter.windows == "y" %}.

fixed in https://github.com/pydanny/cookiecutter-django/commit/5dc41812d50d958a3df2ab0e8b919b95c6581501

**Comment by spoetnik** [comment]
Confirmed issue is resolved.
Thanks!
