### ISSUE TITLE
Add cookiecutter-django to up-for-grabs

### ISSUE THREAD

**Issue by mariusavram91** [pydanny/cookiecutter-django#750]
What do you think about adding the project to [up-for-grabs](http://up-for-grabs.net/#/tags/django)? I see a few low-hanging-fruit issues there.

**Comment by pydanny** [comment]
The problem Cookiecutter Django has is not with finding people to work on low hanging fruit, but with the core devs having the time to properly review and shepherd pull requests. In my opinion, putting this project on a pull request advertising site is arguably going to add to our workload. Therefore, at this time, I am opposed.

Any thoughts @jayfk @audreyr @burhan @theskumar @luzfcb?

**Comment by mariusavram91** [comment]
Understandable!

Sorry for putting this on both Cookiecutter projects.

**Comment by luzfcb** [comment]
@pydanny 
I agree, since in recent months, I have almost zero of free time to opensource

**Comment by burhan** [comment]
Regrettably I too have become busy with some work commitments and having
this would be a bit much. Agree with @pydanny

**Comment by theskumar** [comment]
Since most of the core-maintainers (including me) not in support, closing this ticket for now.
