### ISSUE TITLE
Customising authentication templates

### ISSUE THREAD

**Issue by yunti** [pydanny/cookiecutter-django#780]
Django cookie cutter looks to have customised the templates from django allauth (within templates/accounts) presumably to better use crispy forms?
I assume to more precisely customise the rendering of the authentication forms (signup etc) I would alter the included templates in /account as needed?

**Comment by jayfk** [comment]
That's correct.

**Comment by yunti** [comment]
Thanks - I trying to pricesely control the output of the django allauth forms, to get something like:

<input id="signup-password" type="password" class="form-control login-password" placeholder="Password">

However if I just output an individual field from the signup form, eg. 

{{ form.password1 }}

I dont' seem to be able to add attributes to the field without overriding the form.
How do you all tailor the rendering of the allauth forms exactly as you want them? In the cookiecutter templates you just use the crispy form filter:  {{ form|crispy }}
But I can't tailor this further unless I can amend the original form. Is it best to do something like?:

     class SignUpForm(allauthSignUpForm):
    message = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs):
        self.fields['password1'].label = "Add password"
        self.fields['password1'].help_text = "No less that 8 characters...."

**Comment by yunti** [comment]
Thanks
