### ISSUE TITLE
MAILGUN_SERVER_NAME unused?

### ISSUE THREAD

**Issue by phiberjenz** [pydanny/cookiecutter-django#788]
Where is the env MAILGUN_SERVER_NAME used?

I can only find it in the env.example file and also in the "Deploy to PythonAnywhere/Heroku" and "Settings" part of the documentation.

It seems that it's not used anywhere in the code.

Is there a reason for having this env?

**Comment by yunti** [comment]
It might be a hangover before things were switched to Django-anymail

**Comment by Afrowave** [comment]
It is the default mail engine that one can use. In the config/production.py, one would use Anymail with Mailgun like so:

    # Anymail
    ANYMAIL = {
        "MAILGUN_API_KEY": "env('DJANGO_MAILGUN_API_KEY')",
    }
    ANYMAIL["MAILGUN_API_KEY"] = env('DJANGO_MAILGUN_API_KEY')
    EMAIL_BACKEND = "anymail.backends.mailgun.MailgunBackend"

    DEFAULT_FROM_EMAIL = "postmaster@mg.mailgun.com"

The `DEFAULT_FROM_EMAIL` is for you to configure to the email you would want to use.
The other mail backends may be found at [django-anymail](https://github.com/anymail/django-anymail).

**Comment by ssteinerx** [comment]
> It might be a hangover before things were switched to Django-anymail

I don't have a solution to this ATM, but this project has a unique constraint in that it is tied to a particular Django release, so sticking with strict semver seems a bit counter-intuitive.

If there was a switched version of something leading to a backwards-incompatible change, semver rules should have forced a semver Major Version change:
 
>  Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

But how do you do that when:

**Comment by browniebroke** [comment]
Fixed in #1545
