### ISSUE TITLE
Can't access admin site after deploy production.

### ISSUE THREAD

**Issue by cunhuvan** [pydanny/cookiecutter-django#790]
When i deploy project in dev mode i can access admin site(127.0.0.0:8000/admin), but when I deploy project in production mode I can't access admin site(docker-machine-ip/admin). 
Note: other function still work fine,.env setting: DJANGO_ADMIN_URL=admin
Any idea to enable admin site on production mode.

**Comment by ameistad** [comment]
You could try linking to your admin in a template and see what url you get.
```
{% if request.user.is_superuser %}
  <a href="{% url 'admin:index' %}">Django Admin</a>
{% endif %}
```

**Comment by jangeador** [comment]
Your `.env` file should have this line: 
`DJANGO_ADMIN_URL=^admin/`

**Comment by cunhuvan** [comment]
@jangeador : I tried: DJANGO_ADMIN_URL=^admin/ still not work.

**Comment by jangeador** [comment]
Any errors? Can you log in to the regular site?

**Comment by cunhuvan** [comment]
on browser: Server Error (500)
on terminal: nginx_1         | 116.98.26.54 - - [14/Sep/2016:03:11:23 +0000] "GET /admin/login/?next=/admin/ HTTP/1.1" 500 38 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0" "-"

**Comment by jangeador** [comment]
That error 500 could be anything. Since you are running docker it would be really easy to see logs. Just docker-compose up on the docket-machine terminal and then look at the output. It should display the real error.

**Comment by cunhuvan** [comment]
nginx_1         | 116.98.26.54 - - [14/Sep/2016:03:11:23 +0000] "GET /admin/login/?next=/admin/ HTTP/1.1" 500 38 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0" "-"

Only this show on Docker-machine terminal

**Comment by jangeador** [comment]
I was hoping the django_1 machine would display the error. If you have your email configured you should be getting an email with the error. Please configure a real address as the admin in the config file and you should get an email with the error. One of the most common problems with this is the incorrect setting in allowed hosts. You might want to check that.

**Comment by cunhuvan** [comment]
in this site: https://cookiecutter-django.readthedocs.io/en/latest/settings.html
i saw DJANGO_ADMIN_URL in Production Default is: raises error.
anyidea?

**Comment by jangeador** [comment]
The documentation states that it raises error as a production default because it is not present and the configuration will look for it. You already define it in your `.env` file so it should not raise an error because it finds it there.

**Comment by cunhuvan** [comment]
I'm newbie and just finish config raven to see Error message. This is my problem: 
![error](https://cloud.githubusercontent.com/assets/11598929/18614902/35d29ef4-7dc2-11e6-9611-41cf6791a1a4.png)
please help me!

**Comment by pydanny** [comment]
If you have not defined `DJANGO_ADMIN_URL` in your .env file, then Django will crash. 

Fix this and then start looking into other things. Deployment, like debugging, is a process of elimination.

**Comment by jangeador** [comment]
That error is a dns problem, but since you are using docker, it's most likely a problem with docker and the way the containers are being built. Did you make any modifications to the docker files? What version of docker and docker-compose are you running? What is the OS of your production server? What command are you using to build and spin up your docker containers?

**Comment by cunhuvan** [comment]
@pydanny, @jangeador: Thanks for your support. That's postgres container problem. It was stop. Everything ok right now. Thanks all!

**Comment by Marpop** [comment]
@cunhuvan Can you provide solution? I have similar problem

**Comment by Micromegass** [comment]
@Marpop where are you deploying? I had to set my admin-url in the .env file `DJANGO_ADMIN_URL=hereyouradminlink/` and then specifically set it again in my Heroku settings: DJANGO_ADMIN_URL=heregoesyouradminlinkasspecifiedinyourenvfile/

Depending on where you are deploying this will differ

**Comment by Marpop** [comment]
@Micromegass I've solve it, but can't remember how. Sorry and thanks :)

**Comment by johnpaul89** [comment]
Who have a solution, I'm also getting the same error.
I can't be able to login into the admin after creating superuser.

**Comment by Afrowave** [comment]
@johnpaul89 Do you have https configured?

**Comment by johnpaul89** [comment]
No but Thank You.
I have figured out where the problem was.

**Comment by xiaoyualex** [comment]
> No but Thank You.
> I have figured out where the problem was.

how did you fix it? Thank you in advance.

**Comment by kakdeykaushik** [comment]
> No but Thank You.
> I have figured out where the problem was.

How did you fix it  ?

**Comment by kakdeykaushik** [comment]
> > No but Thank You.
> > I have figured out where the problem was.
> 
> how did you fix it? Thank you in advance.

Did you find the solution?

**Comment by cunhuvan** [comment]
Yes. But i forgot it. :)

Vào 0:04, Th 3, 16 thg 6, 2020 Kaushik Kakdey <notifications@github.com> đã
viết:

**Comment by freakspace** [comment]
For any future people. I got this error because i forgot to do the initial migration. So just run python manage.py migrate.

**Comment by edivaldolluisb** [comment]
> @Marpop where are you deploying? I had to set my admin-url in the .env file `DJANGO_ADMIN_URL=hereyouradminlink/` and then specifically set it again in my Heroku settings: `DJANGO_ADMIN_URL=heregoesyouradminlinkasspecifiedinyourenvfile/`
> 
> Depending on where you are deploying this will differ

in which file should I make this change?

**Comment by edivaldolluisb** [comment]
> If you have not defined `DJANGO_ADMIN_URL` in your .env file, then Django will crash.
> 
> Fix this and then start looking into other things. Deployment, like debugging, is a process of elimination.

in which file should I make this change?

**Comment by browniebroke** [comment]
It's here: 

https://github.com/cookiecutter/cookiecutter-django/blob/4c9d7c663bb4dbaec42000b6c740e8974bf7ea4e/%7B%7Bcookiecutter.project_slug%7D%7D/.envs/.production/.django#L6

So in your generated project, it would be under `.envs/.production/.django`
