### ISSUE TITLE
add LocaleMiddleware

### ISSUE THREAD

**Issue by willemarcel** [pydanny/cookiecutter-django#792]
The settings comes with `USE_I18N` and `USE_L10N` set as `True`, but we need to add `'django.middleware.locale.LocaleMiddleware'` to make the localization and internationalization work.

Is there any reason why the `LocaleMiddleware` isn't in the `MIDDLEWARE_CLASSES` by default?

**Comment by jayfk** [comment]
Thanks for the heads up, it's coming with 1.10: #793.
