### ISSUE TITLE
Pycharm run configurations all start with "Docker" but none of them actually use it

### ISSUE THREAD

**Issue by ssteinerx** [pydanny/cookiecutter-django#794]
I get this when trying the "run" button from the Docker tab:

```
5:44 AM Error running Docker: runserver_plus: Cannot run program "docker-compose:///Users/ssteiner/.../devdir/dev.yml:django/python" (in directory "/Users/ssteiner/.../devdir"): error=2, No such file or directory
```

When I run/debug from the top bar (where you can select the configuration to run), it just runs the regular local `manage.py runserver` command.

I've never used Docker from within PyCharm, so I'm not clear on how this is supposed to work, but the configurations do not seem properly named at least.

**Comment by jayfk** [comment]
Have you checked out https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/docs/pycharm/configuration.rst?

**Comment by HintikkaKimmo** [comment]
@jayfk Thanks for that got me connected to the Docker VM, now this is more of a Pycharm thing but I still have issues. I can see .idea/RunConfigurations on my project, but none of the run actions is available. In fact, Pycharm does not seem to recognise any run actions from cookiecutter generated docker project.

**Comment by HintikkaKimmo** [comment]
Ah, this once was easy. Cookiecutter made a second .idea folder within the idea folder as I already had this location open in Pycharm. Just moving the files fixed this.
