### ISSUE TITLE
Start using GitHub's new "Projects" interface for e.g. Django 1.10 upgrade

### ISSUE THREAD

**Issue by ssteinerx** [pydanny/cookiecutter-django#797]
@pydanny, @audreyr, @luzfcb, @jayfk 

The new GitHub "Projects" interface incorporates many great workflow improvements like Trello-like drag'n'drop backlog etc. type boards.  In a traditional "Agile" type workflow, bugs to be worked on in a "Sprint" go into a "backlog", get assigned, flagged as "Passes Tests", "100% Coverage", "Ready for code review", "Ready to merge",  "Done" type workflow and it makes it very clear what needs to happen next.

I do not have access to create one here, but I think that, in addition to the 'wip-migrate-to-django-1.10' type branches, it would be great to start using projects to make sure we all know what remains to be done to get to a particular goal.

In my opinion, that (combined with making some future assignable milestones like "Integrate Channels", with sub-projects therein) would be a huge step toward making it really easy for new (or old) contributors to know "what's next" to move the project forward to specific goals.  

If we were to make sure that "low hanging fruit" was always in the "next milestone" then onboarding new contributors would be that much easier and, if nobody grabs it, would ensure that _someone_ cleans up some of the little dangling nits to work toward getting "Issues" and "Pull Requests" cleared up and/or closed just before each new release.

**Comment by jayfk** [comment]
I've created one here: https://github.com/pydanny/cookiecutter-django/projects/1

It's just horrible.

**Comment by ssteinerx** [comment]
@jayfk Glad to hear you like it! ;-).  

I think "Project" means something like "Update to Django 1.10", then you put tickets into the backlog that need to be done to get to "done" in that project.

Can't say I've used it a whole lot, I've actually been using the ZenHub for GitHub Chrome extension which has a whole bunch of extra improvements and is free for open source repos.
