### ISSUE TITLE
Please make a new tag for "Project Organization" or somesuch for discussion tickets

### ISSUE THREAD

**Issue by ssteinerx** [pydanny/cookiecutter-django#800]
There have been several tickets lately discussing "Project Organization" or "best practices" etc.

Specifically, #800, #797, #784, #782.

In my opinion they need to be pulled out or tagged somehow.  They're not really "issues", more along the line of discussions about how to better organize the project.

Either a tag, or moving them to the wiki would be helpful, methinks.

Once there's agreement on a particular thing (like not checking changes into master), then there can be a real "Issue" for documenting the procedure as part of an upcoming release, it can be assigned as a Project or added to a Milestone, and they're not cluttering up the Issues in the meantime.

**Comment by audreyr** [comment]
Good idea, tagging them now.
