### ISSUE TITLE
Multiple apps per host

### ISSUE THREAD

**Issue by microspace** [pydanny/cookiecutter-django#802]
I want to reopen #500 issue. How to lauch multiple apps?
I have nginx-proxy and a django site running. I want to add this cookiecutter-django site to the host

**Comment by ssteinerx** [comment]
@pydanny This has come up a couple of times in the last couple of days.

Nginx setup is a whole 'nuther kettle of fish.  

I think we need to think seriously about pulling deployment under various scenarios out of "things that we can support within the scope of cookiecutter-django itself" as the non-Django aspects of the project consume *way* more bandwidth than anything actually related to Django or the project set up by running this cookiecutter.

That said, obviously this is meant to be an all-in-one setup, but it should be "all-in-one,  one way", not all-in-one with every possible variation of deployment tool, wsgi/asgi front end, possible load balancer/proxy, multi-site deployment, cacheing, optimization, CSS framework, javascript library, and so forth ad nauseum.

A "This is what we support as part of this project" document/disclaimer might go a long way towards cutting down the enormous backlog of out-of-scope "support requests" aka "how do I set up my project in a way that meets my specific requirements once I've got it working as designed?"

@pydanny Let's chat about this offline, I've got an idea.

S

**Comment by microspace** [comment]
I agree with you. Please, consider my words as shouts of despair. I'm happy that you answered at all.

Concerning the issue: I've deleted your nginx.conf, and put projects config into `sites-enabled` directory.

**Comment by microspace** [comment]
Is it true that when I use nginx-proxy with django cookiecutter, I have nginx behind nginx?

**Comment by ssteinerx** [comment]
@microspace Using nginx as a proxy means that requests that should be handled by e.g. Gunicorn are sent to Gunicorn on the port on which it's listening. 

So, for example, a request for "http://mydomain.com/home" on the usual port 80 ashould be handled by the Django app using Guinicorn running on port 8000, so nginix sends the request to port 8000, then returns the response from Gunicorn as if Gunicorn had handled the request on port 80.  The browser doesn't care, it just gets the correct response without having to worry about the back-end details.

A request for "http://mydomain.com/static/app.css" is a request for a static file which nginx handles much more efficiently, so nginx just handles it.  Again, the browser is none the wiser, it just gets what it asked for.

Nginx is just used to delegate all requests coming in on "http://mydomain.com" to the correct handler and sends back the appropriate response in a completely transparent way.

**Comment by jayfk** [comment]
> Is it true that when I use nginx-proxy with django cookiecutter, I have nginx behind nginx?

Yeah, you can configure it this way. 

But honestly, as @ssteinerx says, this is way out of scope for Cookiecutter Django. There are much better ways to find people to chat about deploying and running Django apps. Check out the #django IRC channel on freenode, or stackoverflow (there's even a `cookiecutter-django` tag).

**Comment by microspace** [comment]
Thank you for your responses! 
Docker gave me layer of complexity in deploying apps. I've reconfigured my server without docker already.
