### ISSUE TITLE
Using wizard for multiple form signup

### ISSUE THREAD

**Issue by yunti** [pydanny/cookiecutter-django#806]
It's not clear from the docs and the user app what's the best approach to integrate using django wizard with a multi form signup is? I've created a separate view inheriting from `SessionWizardView`, but how should this be integrated with cookiecutter and django allauth without losing their existing setup (eg redirecting via RedirectAuthenticatedUserMixin etc..)

**Comment by pydanny** [comment]
There are so many variations of how signup could work that we can't possibly address this in Cookiecutter Django. My apologies, it's out of scope. 

That said, if you figure out your preferred way of doing things, and write an article about it, we would be honored to have a link to it.

**Comment by yunti** [comment]
thanks I understand there has to be a line drawn somewhere. Got a solution mainly using the wizard to replace the signup view, with some slight alterations to keep the benefit of allauth.  Article is a good idea, I'll certainly do a link when it's done. 
Thanks
