### ISSUE TITLE
Fix indentation in nginx.conf

### ISSUE THREAD

**Issue by audreyr** [pydanny/cookiecutter-django#807]
https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/nginx/nginx.conf contains a mix of tabs and spaces, I think. Or maybe they're tabs, just misaligned.

Either way, it would be good for them to be consistently aligned.

**Comment by luzfcb** [comment]
fixed in https://github.com/pydanny/cookiecutter-django/commit/a4884bb5d76f49f823361eac12cd905d82ea2313
