### ISSUE TITLE
Local media storage for production with docker and lets encrypt

### ISSUE THREAD

**Issue by Egregors** [pydanny/cookiecutter-django#809]
Hi! This project is absolutely amazing! I have a working service based this project (docker, py3, lets-encrypt). But I have an issue with S3 media storage (specific for region). 

Can you help me please, How can I configure nginx-secure.conf, urls.py, production.py (something else?) for storing media files locally in a docker volume, and serve it by Nginx over https?

**Comment by pydanny** [comment]
Apologies @Egregors, but providing instructions for file hosting in a docker volume is out of scope for this project. We insist on hosting media on third-party CDNs, or via Whitenoise (for simple efforts). If s3 isn't an option, then there are any number of alternatives (Azure, Libcloud, etc) supported by [django-storages](https://django-storages.readthedocs.io/en/latest/).
