### ISSUE TITLE
Provide default password validators

### ISSUE THREAD

**Issue by cdvv7788** [pydanny/cookiecutter-django#811]
By default we can set about any password on our projects. This can be restricted with [password validation](https://docs.djangoproject.com/en/1.10/topics/auth/passwords/#module-django.contrib.auth.password_validation). I don't think that it is a bad idea to add a couple of these validators by default, at least in config.settings.production.

**Comment by jayfk** [comment]
That's coming with the 1.10 release, see https://github.com/pydanny/cookiecutter-django/pull/793.
