### ISSUE TITLE
Update to new anymail 0.5 and document the usage of MAILGUN_SENDER_DOMAIN

### ISSUE THREAD

**Issue by jangeador** [pydanny/cookiecutter-django#815]
With the old anymail there isn't a way to send emails from other domains other than those specified in mailgun. The new `MAILGUN_SENDER_DOMAIN` setting allows users to have a domain configured in mailgun such as `mg.example.com`, and then use other domains to send mail from such as `example.com` or even `othermail.example.com`. 

Update to the new release of anymail 0.5 and document the new setting in example.env file.

**Comment by luzfcb** [comment]
fixed in https://github.com/pydanny/cookiecutter-django/commit/3d25befb3f43d8965816376a4e64b868e0db6f6d
