### ISSUE TITLE
Add django-autoslug (removed for 1.10) to requirements_to_watch.txt

### ISSUE THREAD

**Issue by ssteinerx** [pydanny/cookiecutter-django#818]
Add to requirements_to_watch.txt to ensure that pyup-bot notifies us of 1.10 compatible update.

Also, any other removed not-ready-for-1.10 plugins.

**Comment by luzfcb** [comment]
fixed in https://github.com/pydanny/cookiecutter-django/commit/5815865703a8e2062d262989083f211e278e8231
