### ISSUE TITLE
Zurb Foundation

### ISSUE THREAD

**Issue by nueverest** [pydanny/cookiecutter-django#837]
It would be nice to be able to choose between Zurb Foundation http://foundation.zurb.com and Bootstrap.

**Comment by Parbhat** [comment]
You can try [Cookiecutter Django Foundation](https://github.com/Parbhat/cookiecutter-django-foundation), which combines Cookiecutter Django with Zurb Foundation 6 framework.

**Comment by pydanny** [comment]
@parbhat, Looks awesome. I'm going to link to that from our README :smile:
