### ISSUE TITLE
Keep automatically generated static files in version control?

### ISSUE THREAD

**Issue by valerymelou** [pydanny/cookiecutter-django#847]
I noticed that automatically generated static files of the generated project are tracked by Git. Is this intended? If not I think we should keep them out of the version control system. If yes, please I would like to know why.

**Comment by luzfcb** [comment]
@valerymelou thanks to report.

fixed in https://github.com/pydanny/cookiecutter-django/commit/3b3e53b57bfb4b1fe2e7a7b1c3b0cf7865354bd7

**Comment by valerymelou** [comment]
Cool. What about files generated in the static folder by Grunt or Gulp? They are also tracked by the version control even though they can be automatically generated from Sass and JavaScript sources.

**Comment by jangeador** [comment]
We need those there for deployment branches, at least in my case. I make all the development changes in the dev machine and I commit the generated files to my production branch. I really don't want to have this project depend on having node installed on the production server.

**Comment by valerymelou** [comment]
It's true that I have been dealing with that in a different way. So I guess it's just me noticing this. Closing the issue. Thanks guys.
