### ISSUE TITLE
Use Argon2 Password Hasher?

### ISSUE THREAD

**Issue by jhancia** [pydanny/cookiecutter-django#850]
Hello, noticed that the Django 1.10 docs recommend to use the Argon2 password hasher rather than the defaults.  Any thoughts on using this?  Apparently it requires an additional 3rd party library.  See [here](https://docs.djangoproject.com/en/1.10/releases/1.10/#django-contrib-auth) and [here](https://docs.djangoproject.com/en/1.10/topics/auth/passwords/#argon2-usage)

**Comment by pydanny** [comment]
I'm very excited to include Argon2, but the [installation path is a bit worrisome](https://argon2-cffi.readthedocs.io/en/stable/installation.html#installation). According to the docs (linked above), recent `pip` and `setuptools` should account for any problems. That's wonderful, and I really respect the maintainer's efforts, but sometimes things can go haywire (especially when dealing with closed-source vendors like Microsoft and Apple). Considering the size and dynamism of our community, I don't want to dump a ton of work on the maintainer of argon2-cffi unless they are certain their package is ready.

Therefore, I'm going to ask the maintainer of argon2-cffi, @hynek, the following question: Considering that we have a LOT of Windows users for Cookiecutter Django, are you okay with us using your argon2-cffi library for password hashing?

**Comment by hynek** [comment]
I think that ship has sailed once Django added and endorsed it. :)  As with Python 3, once Django encourage something, things tend to start moving.

FWIW, Windows is least of my concerns since it‘s shipping wheels from day 1 (for exactly those reasons; I knew I could rather work out building wheels than supporting people building a C extension).

So sure, go for it.

**Comment by pydanny** [comment]
Thanks for the response @hynek. 😄 

@jhancia, did you want to put together a pull request?

**Comment by jhancia** [comment]
Sure, I can give it a go.

**Comment by pydanny** [comment]
Closed by #1079
