### ISSUE TITLE
link to html5shiv in base.html no longer exists

### ISSUE THREAD

**Issue by shireenrao** [pydanny/cookiecutter-django#852]
In the file https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/templates/base.html the link pointing to html5shiv no longer exists -

**Comment by pydanny** [comment]
Want to submit a pull request removing it?

**Comment by shireenrao** [comment]
My only concern is for code in the project which maybe referencing it. I don't know the library. The reason I found this issue was because for local development, I was changing the reference for any external css or javascript to local files. I will submit a pull request removing the link.

**Comment by luzfcb** [comment]
Please, change to
https://cdnjs.com/libraries/html5shiv

html5shiv.min.js


-- 

Fábio C. Barrionuevo da Luz
Palmas - Tocantins - Brasil - América do Sul

http://pythonclub.com.br/

Blog colaborativo sobre Python e tecnologias Relacionadas, mantido
totalmente no https://github.com/pythonclub/pythonclub.github.io .

Todos são livres para publicar. É só fazer fork, escrever sua postagem e
mandar o pull-request. Leia mais sobre como publicar em README.md e
contributing.md.

Regra básica de postagem:

"Você" acha interessante? É útil para "você"? Pode ser utilizado com Python
ou é útil para quem usa Python? Está esperando o que? Publica logo, que
estou louco para ler...



Em 17/10/2016 18:21, "shireenrao" <notifications@github.com> escreveu:

**Comment by shireenrao** [comment]
Oops.. Sorry.. Will fix the pull request.

**Comment by pydanny** [comment]
Merged.
