### ISSUE TITLE
OSX PyCharm integration issue with API URL

### ISSUE THREAD

**Issue by sanderl-mediamonks** [pydanny/cookiecutter-django#870]
I'm following the instructions in docs/pycharm/configuration.rst, but I'm stuck at the API URL part.

OSX can't connect to a socket so I need a TCP url.

By default there's no docker-machine running. So I tried creating a machine first using docker-machine. Then there is an API available at https://192.168.99.100:2376.

But then I somehow need to setup port forwarding as this machine is not available at http://localhost:8000/.

Is there an out of the box solution here that I'm missing?

**Comment by jayfk** [comment]
For the time being, you have to launch a Docker TCP proxy for this to work with Docker for Mac.

See Alexander Koshevoy's response here: https://youtrack.jetbrains.com/issue/IDEA-159223

**Comment by sfdye** [comment]
This should have been fixed in newer version of PyCharm I guess @sanderl-mediamonks
