### ISSUE TITLE
Best way to update site domain and name

### ISSUE THREAD

**Issue by yunti** [pydanny/cookiecutter-django#878]
I didn't know the project site domain when first starting the project, which has now changed from that initially specified.   These seem to be set within contrib-site migration.   What's the best way to update these? Manually with a new migration?

**Comment by jayfk** [comment]
Exactly. Or you revert the first migration, edit it manually, and then run the migration again.

**Comment by yunti** [comment]
Perfect thanks.

**Comment by art3mHQ** [comment]
can you please share how to do it exactly?

**Comment by Yusuf-shaik** [comment]
> can you please share how to do it exactly?
I know this is from a year ago but i'll answer it for anyone else that comes across this in the future. So migration 0003 is what sets your domain name, you need to revert to an older migration, make the code changes, then run the migrations again.
- On your server, run `docker-compose -f production.yml run --rm django python manage.py migrate sites 0002` which will revert your migration status to 0002
- Run `run docker-compose -f production.yml run --rm django python manage.py showmigrations sites` to confirm that only the first 2 migrations are set, you will see checkboxes
- Then make the code changes in the migration file and anywhere else you need to, and run `docker-compose -f production.yml build && docker-compose -f production.yml run --rm django python manage.py migrate && docker-compose -f production.yml up` which will build, migrate the changes with your new domain name, and run your site
