### ISSUE TITLE
 Invalid HTTP_HOST header in Docker Local

### ISSUE THREAD

**Issue by pilgrim2go** [pydanny/cookiecutter-django#879]
I tried deploying cookie cutter app using Docker locally.

At this step of running
```
docker-compose -f dev.yml

```
Everything is fine, but when accessing http://dockerbox:8000, I got following error
```
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dockerdev:8000'. You may need to add 'dockerdev' to ALLOWED_HOSTS.
```
I already set dockerdev in local.py
ALLOWED_HOSTS='.dockerdev'
*dockerdev: is my docker machine box set in /etc/hosts

Any help?

**Comment by Afrowave** [comment]
If I may, is it 'dockerdev' or 'dockerbox'?

**Comment by HintikkaKimmo** [comment]
I am getting same/similar error when using this project with Docker build locally. My Docker Machine is called Default 

```
django.core.exceptions.DisallowedHost
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.99.100:8000'. You may need to add '192.168.99.100' to ALLOWED_HOSTS.
```
I tried to create` .env` with `DJANGO_ALLOWED_HOSTS=192.168.99.100` which did not work.

Next I tried to add > 

`ALLOWED_HOSTS = '192.168.99.100'` which also does not seem to work. 

Still bit new with Django&Docker so might be something easy I am doing wrong.

**Comment by jayfk** [comment]
It's probably related to https://github.com/pydanny/cookiecutter-django/pull/863/. If you remove `env.read_env()` from `settings/common.py` this should work again.

**Comment by HintikkaKimmo** [comment]
Did not seem to work I get the same error. I try undo what I did first and they try again. 

I also noticed something else environ package is not listed as project requirements? Should I have environ somewhere outside?

**Comment by HintikkaKimmo** [comment]
So I did this at local.py to fix it but security team might now agree that for production. 

`ALLOWED_HOSTS = ['*']`

For whatever reason it cleared the error but giving exact IP or hostname did not.

**Comment by pydanny** [comment]
Closing as resolved.

**Comment by daniel374** [comment]
Inside the settings.py file:
ALLOWED_HOSTS = ['192.168.99.100']

**Comment by webyneter** [comment]
@daniel374 it doesn't make any sense.

**Comment by Afrowave** [comment]
@daniel374 is referring to the  docker machine that one starts up as`default`. It would be started up as on the CLI:

```
docker-machine start default
```

**Comment by justdan23** [comment]
> So I fixed this by adding line below to `local.py` , and commenting out `env.read_env()` but security team might now agree that for production.
> 
> `ALLOWED_HOSTS = ['*']`
> 
> For whatever reason it cleared the error but giving exact IP or hostname did not.
> 
> EDIT!!! After clearing the browser history and rebuilding containers, adding IP does actually work so to fix just delete `env.read_env()` and add `ALLOWED_HOSTS = ['YOUR DOMAIN or IP']`
> 
> Thanks @jayfk

I would not hard code this into the python generated code.  If you generated the template code using `django-admin start project testapp` for example, then within the "testapp" folder is a settings.py which has `ALLOWED_HOSTS=[ ]`

I use:
```
import os
...
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(" ")
```

They in your .env file add:
```
DJANGO_ALLOWED_HOSTS="dockerbox 192.168.99.100"
```

Then docker compose and it works as designed.
