### ISSUE TITLE
Update bootstrap to 4.0.0-alpha.6

### ISSUE THREAD

**Issue by ssteinerx** [pydanny/cookiecutter-django#892]
Alpha 5 released Wednesday, October 19, 2016.

**Comment by lanshark** [comment]
I am working on this, slowly.  One thing that changes is pull-xs-right becomes float-xs-right.  Still working on the rest of the changes.

**Comment by dmarcelino** [comment]
Alpha 6 is out and it sounds like a big change: https://blog.getbootstrap.com/2017/01/06/bootstrap-4-alpha-6/

**Comment by polinom** [comment]
Are we waiting for a beta here?

**Comment by luzfcb** [comment]
I would be happy to review a pull-request that include all the necessary modifications (including all changes in current html code)

**Comment by pydanny** [comment]
Started on this in 19924fecf4444c31ef527bc0ffdbcd29a9055c95.

**Comment by pydanny** [comment]
I just bumped the resources to Bootstrap 4.0.0-alpha.6 in 19924fecf4444c31ef527bc0ffdbcd29a9055c95. I'll work on this daily to stamp out issues. If someone wants to submit a PR that completes all the work, that would be appreciated! 😄

**Comment by pydanny** [comment]
Marking this as closed. As bugs get filed, we'll address them as they come.
