### ISSUE TITLE
python: can't open file 'manage.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by foxmask** [pydanny/cookiecutter-django#895]
Hi, 
I follow the doc and this [article](https://realpython.com/blog/python/development-and-deployment-of-cookiecutter-django-via-docker/)

But I unable to do this 

```
$ docker-compose -f dev.yml run django python manage.py migrate
Postgres is up - continuing...
python: can't open file 'manage.py': [Errno 2] No such file or directory
```
I redo the job 3 times to be sure I didnt miss something.

Do you have any idea ?
Regards

**Comment by mimischi** [comment]
Did you use ``docker-compose -f dev.yml build`` to build the whole system? Could you please post the output of ``docker ps`` and ``docker-compose -f dev.yml run django ls -la``.

Furthermore this tutorial does not seem up to date anymore, as the current Dockerfile should create a data partition by itself and the whole ``$ echo 'ln -sfn /mnt/sda1/data /data' >> /var/lib/boot2docker/bootlocal.sh`` command is obsolete.

What version of Docker are you using and on which operating system? Windows, macOS, Linux?

**Comment by foxmask** [comment]
i'm going to retry and will skip the step with the symbolic link.

I use Debian 8.6 and docker 1.12.3
```
docker --version
Docker version 1.12.3, build 6b644ec
```

**Comment by foxmask** [comment]
[so here I am](https://gist.github.com/foxmask/84dfe256bb4d8b45011c159816ea85d8), you have everything from the creation of the vm (except cookiecutter https://github.com/pydanny/cookiecutter-django.git I didnt restart from scratch)

**Comment by jayfk** [comment]
If you're running Debian, you should use native Docker instead of using Docker Machine. 

Docker Machine on Debian is probably not correctly mapping your project directory into the virtual machine you are running, that's why you get the error.

**Comment by foxmask** [comment]
ok so I skipped the docker-machine part and now it's running. 
But ! If I say I use Postgresql 9.6, docker-compose -f dev.yml up never found the database at all

**Comment by Devansh3790** [comment]
Facing the same issue within a different scenario:
Added cookiecutter-django project under `backend` folder.
`docker-compose -f local.yml run django ls -la`

`
...
drwxrwxr-x    5 1000     1000          4096 May 17 21:01 backend
-rw-rw-r--    1 1000     1000          1534 May 17 21:06 local.yml
...
`

Why it is copying the files in backend instead of django folder.

Thanks in advance.

**Comment by browniebroke** [comment]
@Devansh3790 the project has changed a lot since this issue was opened, if you need help, please file a new issue the options you've selected, some details about your machine (Linux, Windows, Mac) and what command is failing.

Thanks
