### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#899]
The current travis build is broken, because our base image is failing to install docker properly.

While this might be temporary (until the keyservers are up again), this should be more robust and have no single point of failure.

**Comment by browniebroke** [comment]
Is this still a decent problem? Looking at the build history, it doesn't look like it happened recently? 

As a side note, I think it looks a bit too unspecified for being a 'low-hanging fruit', at least if you want to direct new contributors with this label. Would be good to give a couple of pointers, like:
- Example of logs of the error we are looking at
- Ideas to be explored to reach a 'no single point of failure'.

I'm happy to give this a try if that's still an issue?
