### ISSUE TITLE
Redundant file encoding lines

### ISSUE THREAD

**Issue by Sgiath** [pydanny/cookiecutter-django#909]
There is in every python file this line:
```
# -*- coding: utf-8 -*-
```
but according to the PEP8
> Files using ASCII (in Python 2) or UTF-8 (in Python 3) should not have an encoding declaration.

it is described on [pep8.org](http://pep8.org/#source-file-encoding).

So I think it should be removed from every file. Am I right?

P.S.: I can do that once it will be approved as the right move.

**Comment by webyneter** [comment]
Done as of #1130.
