### ISSUE TITLE
Some environ path problem?

### ISSUE THREAD

**Issue by piyushmaurya23** [pydanny/cookiecutter-django#910]
In settings/common/.py
`ROOT_DIR = environ.Path(__file__) - 3  # ({{app_name}}/config/settings/common.py - 3 = {{app_name}}/)`

I am getting following error:
`/app/config/settings/.env doesn't exist`

My .env file is in root directory.

**Comment by luzfcb** [comment]
@piyushmaurya23 

on `config/settings/common.py`, try replace 

form
```python
env.read_env()

```
to
```python
env.read_env(str(ROOT_DIR.path('.env')))
```

**Comment by piyushmaurya23** [comment]
thank you @luzfcb it solved my problem.
