### ISSUE TITLE
Migration issue on first run

### ISSUE THREAD

**Issue by mrahma01** [pydanny/cookiecutter-django#911]
Hi, 

After setup, when I run the migration, I see the following error. I am scratching my head to find out the reason. Please help.

> ./manage.py migrate
> /home/muhammad/.venvs/schecurring/dev/lib/python3.5/site-packages/environ/environ.py:608: UserWarning: /home/muhammad/projects/schecurring/config/settings/.env doesn't exist - if you're not configuring your environment separately, create one.
>   "environment separately, create one." % env_file)
> Traceback (most recent call last):
>   File "./manage.py", line 23, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/muhammad/.venvs/schecurring/dev/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
>     utility.execute()
>   File "/home/muhammad/.venvs/schecurring/dev/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/muhammad/.venvs/schecurring/dev/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/muhammad/.venvs/schecurring/dev/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
>     output = self.handle(*args, **options)
>   File "/home/muhammad/.venvs/schecurring/dev/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 86, in handle
>     executor.loader.check_consistent_history(connection)
>   File "/home/muhammad/.venvs/schecurring/dev/lib/python3.5/site-packages/django/db/migrations/loader.py", line 292, in check_consistent_history
>     connection.alias,
> django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency users.0001_initial on database 'default'.

`

**Comment by luzfcb** [comment]
@mrahma01 
this is the relevant line of the error
```
/home/muhammad/.venvs/schecurring/dev/lib/python3.5/site-packages/environ/environ.py:608: 
UserWarning: /home/muhammad/projects/schecurring/config/settings/.env doesn't exist 
```

Please try a solution proposed in: https://github.com/pydanny/cookiecutter-django/issues/910

**Comment by Sgiath** [comment]
@luzfcb I don't think this is the problem. It's just a warning and it is related to the *environ* package.

The exception is `InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency users.0001_initial on database 'default'.`
The problem is that "admin migrations" are applied before "users migrations" and this is odd. If it is a just blank app and you didn't code anything yet I would suggest just generate the new app with cookiecutter and run:
```
docker-compose -y dev.yml build
docker-compose -y dev.yml run django python manage.py makemigrations
docker-compose -y dev.yml run django python manage.py migrate
docker-compose -y dev.yml run django python manage.py createsuperuser
docker-compose -y dev.yml up
```
and see if it is working (I assume you are using Docker if not use similar commands for your platform).

**Comment by mrahma01** [comment]
Thanks that helps.
