### ISSUE TITLE
Can not dev with docker

### ISSUE THREAD

**Issue by mrahma01** [pydanny/cookiecutter-django#921]
Hi,

When I try to build with docker, it fails when start installing pip requirements.
Here is my docker version:

> $ docker version 
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

> Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Here is my docker-composer version:

> $ docker-compose version
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

Here is my docker info:

> $ docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 11
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 36
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-51-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.688 GiB
Name: Latitude-E7450
ID: JJK2:EOEC:JXB2:SLFK:5UMN:H43J:Q7PY:3OST:4OUZ:4XSL:C5ZJ:4ZBX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

And this is where it fails when I run, 
    docker-compose -f dev.yml build

>  ---> Running in 0eac9a6fadb7
Collecting wheel==0.29.0 (from -r /requirements/base.txt (line 5))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7ed70320b8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/wheel/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7ed7b28a90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/wheel/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7ed7b28048>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/wheel/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7ed7b28c50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/wheel/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7ed7b40898>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/wheel/
  Could not find a version that satisfies the requirement wheel==0.29.0 (from -r /requirements/base.txt (line 5)) (from versions: )
No matching distribution found for wheel==0.29.0 (from -r /requirements/base.txt (line 5))
ERROR: Service 'django' failed to build: The command '/bin/sh -c pip install -r /requirements/local.txt' returned a non-zero code: 1

Does it mean, it cannot connect to outside world from inside the docker? 
Hope I have described it all?

**Comment by mrahma01** [comment]
I don't know what causes it. But I restarted everything and it seems working now.

Really enjoying your book.

**Comment by rwillmer** [comment]
If it's working ok, should you close this issue?

**Comment by truncj** [comment]
@mrahma01 restarting docker just fixed this for me. thanks!
