### ISSUE TITLE
Use list [] in settings consistently

### ISSUE THREAD

**Issue by schacki** [pydanny/cookiecutter-django#927]
Currently in settings files, list [] and tuple () are used both; and at least for me without following a specific structure or logic.
I would like to make this list only, because
- this would make it more consistent
- this would make operations like INSTALLED_APPS.insert(0, 'my.great.app.that.needs.to.come.first') much easier.
I am happy to provide a PR.

**Comment by Sgiath** [comment]
I would also like to see the unification between `'` and `"` characters. The simple quote seems to be preferred and more common in the project however sometimes the `"` character can be found. For example [here](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/common.py#L264).

**Comment by pydanny** [comment]
Heh. I mix `'` and `"` without thinking about it.

In any case, these problems I believe have been addressed.
