### ISSUE TITLE
Logging improvements

### ISSUE THREAD

**Issue by schacki** [pydanny/cookiecutter-django#928]
Currently, if you do not opt for the Sentry Logging, the logging ist very basic and not production ready. Morever, this basic logging is only enabled for production, but not for dev. The the log file destination should also be controllable via environment variable-

**Comment by browniebroke** [comment]
Agreed, I'd like to see that. a better logging setup would have helped with #1705, where the logs were not saying much.

**Comment by browniebroke** [comment]
I've opened #2040 which should improve the situation. Also, I found this post which explains things in details:

https://lincolnloop.com/blog/disabling-error-emails-django/
