### ISSUE TITLE
cookiecutter-django version

### ISSUE THREAD

**Issue by ibnbay99** [pydanny/cookiecutter-django#937]
I want to know what cookiecutter-django version i download from below command (default)?
cookiecutter https://github.com/pydanny/cookiecutter-django

It's from stable release? 1.9.9-05?

If i want to download latest commit from https://github.com/pydanny/cookiecutter-django,
how to do it?

Thanks

**Comment by webyneter** [comment]
In terms of the underlying cookiecutter implementation, you can checkout a particular commit (say, tagged 1.9.9-05) of a particular template (say, pydanny/cookiecutter-django) this way:

`cookiecutter -c 1.9.9-05 https://github.com/pydanny/cookiecutter-django`

For more info, run cookiecutter -h`.

**Comment by webyneter** [comment]
@ibnbay99, has your problem been solved?

**Comment by pydanny** [comment]
Marking this as closed, as @webyneter answered the question.
