### ISSUE TITLE
Gulp watch task doesn't output to console

### ISSUE THREAD

**Issue by hetsch** [pydanny/cookiecutter-django#939]
It might be a configuration problem of mine, but if using `gulp watch`, no messages are printed from the devserver to the bash console, at least my OSX (10.11). Running the app by issuing `manage.py runserver`, all messages are printed as expected. For example: in `config.settings.local.py` the DJANGO_EMAIL_BACKEND is set to `django.core.mail.backends.console.EmailBackend` which nicely outputs the text of the emails to the console - if using `manage.py runserver`. If using `gulp watch`, nothing is printed to stdout.

Don't know what's going on, because in `gulpfile.js line 76` this seems to be handled properly:

    // Run django server
    gulp.task('runServer', function() {
        exec('python manage.py runserver', function (err, stdout, stderr) {
             console.log(stdout);
             console.log(stderr);
       });
    });

**Comment by hetsch** [comment]
It might have to do with https://docs.djangoproject.com/en/1.10/releases/1.10/#runserver-output-goes-through-logging.

**Comment by johnfraney** [comment]
I was able to get arond this by using `spawn = require('child_process').spawn` instead of `exec`:

```
 gulp.task('runServer', function(cb) {
   var cmd = spawn('python', ['manage.py', 'runserver'], {stdio: 'inherit'});
   cmd.on('close', function(code) {
     console.log('runServer exited with code ' + code);
     cb(code);
   });
 });
```
I'll open a PR for this.

**Comment by webyneter** [comment]
@hetsch, I'm about to merge #1128, and I wonder does your workflow still requires `migrate` and `runServer` Gulp tasks? If not, I will get rid of them ones-and-for-all; otherwise, I will leave them out, and we can workout the best way to support them.
