### ISSUE TITLE
env.example and .env

### ISSUE THREAD

**Issue by schacki** [pydanny/cookiecutter-django#944]
Currently, I manually need to copy env.example to .env after each project creation. Would it make sense to add that step to the post_gen_project hook?

Furthermore, django_environ complains about the .env file not existing. This could be resolved by:
a) also copying env.example to config/settings/.env
or 
b) pointing to the .env file in the project root by saying: env.read_env(os.path.join(PROJECT_ROOT, '.env')
I would prefer option b.

**Comment by TidyData** [comment]
I like @schacki 's idea and generated a pull request to implement it assuming maintainers agree.

**Comment by TidyData** [comment]
I can't figure out how to deconflict it though, I don't understand because I literally just forked it from this repo....

**Comment by webyneter** [comment]
No longer an issue since #1295.
