### ISSUE TITLE
Stopping docker containers when running from Pycharm

### ISSUE THREAD

**Issue by fayimora** [pydanny/cookiecutter-django#964]
I have been using the docker-compose command from the terminal but I decided to try out PyCharm. Everything runs fine but it seems the containers run in the background as there is no way to stop them from PyCharm. Also, this means I can't monitor the logs as I do when running from the terminal. 

Am I missing a configuration somewhere or is this setup intentional?

**Comment by banksee** [comment]
Don't you have a "Docker" tab in your PyCharm?
Enable it and you will be able to monitor logs and control the services.
![screenshot from 2017-01-07 21-42-06](https://cloud.githubusercontent.com/assets/4748206/21744623/33a571f8-d522-11e6-9360-32a57407795b.png)

**Comment by fayimora** [comment]
Thanks @banksee !
