### ISSUE TITLE
New project generation options not reflected in documentation

### ISSUE THREAD

**Issue by kerstin** [pydanny/cookiecutter-django#975]
Hiya, I noticed that some of the options given during project generation are not (yet) included in the [documentation](https://github.com/pydanny/cookiecutter-django/blob/master/docs/project-generation-options.rst), e.g. the PostgreSQL selection option or "use_elasticbeanstalk_experimental".

**Comment by kerstin** [comment]
I could add a sentence about Postgres myself and send a PR (later or tomorrow), but I have no clue about Elastic Beanstalk. (:

**Comment by webyneter** [comment]
Experimental support for Elastic Beanstalk is no longer a part of Cookiecutter Django.
