### ISSUE TITLE
Should not import the package to get the version in setup.py

### ISSUE THREAD

**Issue by audreyr** [pydanny/cookiecutter-django#98]
As per discussion in https://github.com/audreyr/cookiecutter-pypackage/issues/1

**Comment by theskumar** [comment]
I'm in favour of using initially generated version number from the cookiecutter in setup.py. If duplication is a concern, I think using tools like https://github.com/peritus/bumpversion by @peritus makes the life quite easier in that case. 

There are two places where version number is being used `project/__init__.py` and `packages.json` and probably someone would like to have it inside `docs/` and `REAMDE`, so having it duplicated in `setup.py` shouldn't be an issue.

PS: re-open, this issue with valid reasons if you need a change.
