### ISSUE TITLE
Test in Python 3.2 fails in Travis

### ISSUE THREAD

**Issue by PetrDlouhy** [pydanny/cookiecutter-django#982]
It seems, that Python 3.2 is not supported by `PIP` anymore (https://pip.pypa.io/en/stable/installing/). This causes Travis tests to fail in default configuration with:
```
 File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/models.py", line 856
    http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
                                                      ^
SyntaxError: invalid syntax
```

**Comment by ssteinerx** [comment]
Regardless of pip's own support, Python 3.2 support was officially dropped by Django at the end of 2016.

The tests on 3.2 should be removed.

https://docs.djangoproject.com/en/1.10/faq/install/

What Python version can I use with Django?

Django version	Python versions
1.8	2.7, 3.2 __(until the end of 2016)__, 3.3, 3.4, 3.5
1.9, 1.10	2.7, 3.4, 3.5
1.11	2.7, 3.4, 3.5, 3.6
2.0	3.5+

**Comment by PetrDlouhy** [comment]
This issue was meant for cookiecutter-djangopackage. I did mistakenly posted it here. Sorry for that, I am closing this and posting it there.
