### ISSUE TITLE
Creating an API based project structure

### ISSUE THREAD

**Issue by bluesurfer** [pydanny/cookiecutter-django#987]
It would be really great if we could have a good structure for an API based project where the backend (a DRF application) is completely separated from the frontend (a Vue or React or Angular application).

**Comment by pydanny** [comment]
DRF is pretty straightforward to set up, but I've thought of adding a basic structure for reference. We would try to get @tomchristie involved in that kind of effort.

As for tying this project to a particular frontend setup (Vie, React, Angular, Riot, or any other framework-of-the-month), that's unfortunately not going to happen (again). We tried it with React and Angular, but the maintenance burden is too much for an unpaid, volunteer project.

**Comment by aniketmaithani** [comment]
@bluesurfer I think you can check out `django-init` . @theskumar is the core contributor of the package and is build on the lines of @pydanny 's Cookiecutter-Django. 

ref : https://github.com/Fueled/django-init

It is specifically designed for API related project with minimal front-end dependencies :)

**Comment by pydanny** [comment]
@theskumar is also a core contributor of Cookiecutter Django, a reviewer of Two Scoops of Django, and an all around awesome guy. Trust his work, it is good stuff. 👍

**Comment by bluesurfer** [comment]
But is it possible to have a seperated pure DRF and a pure JavaScript framework projects and make them communicate one another through API?

**Comment by tomchristie** [comment]
Perfectly happy to review any cookiecutter for REST framework if needed, yup.

**Comment by pydanny** [comment]
@tomchristie, Thanks! I hope to take you up on that soon. 😄 

@bluesurfer You have two options:

1. In your own Cookiecutter Django-rendered project, add a directory and setup that adheres to whatever JavaScript framework you are using. Tie to DRF and enjoy. 
2. Use a different Django-themed Cookiecutter template that has your preferred JavaScript framework and DRF setup already set up as you like. You can find them by using the GitHub search feature.

**Comment by theskumar** [comment]
> But is it possible to have a seperated pure DRF and a pure JavaScript framework projects and make them communicate one another through API?

Yes. You can also checkout https://github.com/Fueled/cookiecutter-angular, apart from what's suggested above, it plays nicely with DRF. There are some boilerplate for authentication state management, and a suggested layout and rest is upto you.

**Comment by bluesurfer** [comment]
@pydanny 

Ok, I think I'll go with (1). We have a relatively robust Django project (originally created with this cookiecutter) and it would be perfect if the new fully dynamic application would grow in parallel with the new API we are going to implement in the native Django app. However, I would like to know if there exist a recognized best practice for this kind of situation.

P.S: I hate all those freaking Javascript frameworks but apparently the end user of 2017 need everything to be dynamic :(
