### ISSUE TITLE
Can't make mailhog send email in local environment

### ISSUE THREAD

**Issue by jorgeas80** [pydanny/cookiecutter-django#989]
Can't make mailhog work by following [these instructions](http://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html?highlight=MailHog#setup-your-email-backend).

The mail works in console, by using

`EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'`

But if I just run mailhog from the root folder, no mail is generated. No errors in console.

My environment

**OS (Ubuntu 17.04**, living on the edge...). Output of lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Zesty Zapus (development branch)
Release:	17.04
Codename:	zesty

**Python 3.5.2**
**MailHog 0.2.1**

Running ./mailhog I just get this:

```
2017/01/11 00:26:51 Using in-memory storage
2017/01/11 00:26:51 [SMTP] Binding to address: 0.0.0.0:1025
[HTTP] Binding to address: 0.0.0.0:8025
2017/01/11 00:26:51 Serving under http://0.0.0.0:8025/
Creating API v1 with WebPath: 
Creating API v2 with WebPath: 
```

No output mail generated when registering new users, for example.

**Comment by jorgeas80** [comment]
I guess I just should define EMAIL_BACKEND with a specific value to make it work with Mailhog, but can't find it in the docs.

**Comment by testbucket** [comment]
in your .env file put this setting 

EMAIL_HOST=localhost
