### ISSUE TITLE
AUTOSLUG_SLUGIFY_FUNCTION setting appears to be unused

### ISSUE THREAD

**Issue by kevinmanncito** [pydanny/cookiecutter-django#992]
The settings file has this setting `AUTOSLUG_SLUGIFY_FUNCTION` but this library https://github.com/neithere/django-autoslug or any other library that I can tell isn't in the requirements that would use the setting. Do we just need to add it into base.txt? Or am I missing something and there is a reason for the setting being there?

**Comment by pydanny** [comment]
I beg to disagree on the use of `AUTOSLUG_SLUGIFY_FUNCTION` in django-autoslug. It's the first item in https://github.com/neithere/django-autoslug/blob/a16fd5e83063e533e709238522fe1321e24349e1/autoslug/settings.py

Please reopen if I am incorrect.

**Comment by kevinmanncito** [comment]
Welp it looks like I opened this issue while having a brain fart. Thanks for all the work you've done with this project and other projects in the Django community.
