### ISSUE TITLE
Documentation may not address the handling of new Django version releases.

### ISSUE THREAD

**Issue by justinmnoor** [pydanny/cookiecutter-django#996]
Hi new user here. I want to make my own cookiecutter. I've taken the tutorials on @audreyr's page and I think I see how this works. I am however confused as to how I would handle new releases of Django. Would I have to manually update files if their module import locations change? Sorry in advance if I've missed anything in the docs.

**Comment by luzfcb** [comment]
How to update the django version is outside the scope of this project.

Probably the documentation you are looking for is this: https://docs.djangoproject.com/en/1.10/howto/upgrade-version/


Additionally, here are some good tips:

https://torchbox.com/blog/django-guide-upgrading-your-application/

**Comment by justinmnoor** [comment]
I was referring to the cookiecutter, not the Django application. For example in the users app there is a preexisting urls.py, models.py, etc., before Django is installed by the requirements files. If a module import location on any of these files changes under a new version of Django would I need to modify these files manually? Thanks.

**Comment by luzfcb** [comment]
If I understand the question, modifications will be only be necessary if these modifications are described in the Django release notes of the version of Django that you updated.

**Comment by luzfcb** [comment]
cookiecutter-django was planned only to start a project, and not upgrade an existing project.
