### ISSUE TITLE
Modify 'django-storages-redux' to 'django-storages', and 'boto' to 'boto3', in production.txt requirements file.

### ISSUE THREAD

**Issue by justinmnoor** [pydanny/cookiecutter-django#998]
Correct me if I'm wrong but I believe the 'https://github.com/jschneier/django-storages' repo is the official successor of the django-storages-redux project as of February 2016 per its documentation. It recommends using the boto3 backend instead of the older boto backend https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html.

Sorry in advance if I've missed anything. Thanks.

**Comment by abirafdirp** [comment]
This might resolve #1050 

After I upgraded to storages and boto3, changing all imports from *boto* to *boto3* and changed the settings to follow the new storages settings I'm finally no longer getting ImportError boto again.

**Comment by justinmnoor** [comment]
Thanks. Yes [django-storages](https://github.com/jschneier/django-storages) is awesome.
